//! O3 ASJ GENETIC-CORE funnel: the reproducible 54-call strand-bias-clean transversion
//! non-LOC* allele-specific-junction core — the O3 DELIVERABLE that replaces the retracted
//! "~77" headline (whose only backing, `bench/P1_P4_RESULTS.md`, is absent on disk; adversarial
//! review #4).
//!
//! Faithful Rust port of `bench/asj_genetic_core.py`. This is a PURE-TSV join — NO BAM, NO
//! floats recomputed. It stacks the outputs of the two upstream O3 analysis layers row-for-row
//! over the SAME 475 ASJ calls:
//!  * [`super::asj_verify`] → `bench/asj_calls_verified.tsv` (carries `high_confidence`, the
//!    transversion-anchor flag), and
//!  * [`super::asj_strand_bias`] → `bench/asj_calls_strandbias.tsv` (carries `sor` / `sor_pass`,
//!    the longcallR-style StrandOddsRatio filter),
//! and applies a three-filter funnel, each filter removing a distinct confound
//! (`bench/asj_genetic_core.py:7-17`):
//!  1. TRANSVERSION   `high_confidence == "1"`  — an A↔C/A↔T/C↔G/G↔T anchor cannot be an A→I
//!     RNA-edit site, so the allele-specificity is GENETIC not editing.        475 → 120
//!  2. NON-LOC*       `!gene.starts_with("LOC")` — `LOC*` loci are unannotated paralog families
//!     where a "SNP" may distinguish two COPIES masquerading as two alleles.   120 → 76
//!  3. STRAND-BIAS    `sor_pass == "1"`          — removes mapping/strand artifacts; the old
//!     "mechanistically airtight" flagships PSMD2 & DAXX FAIL this gate.         76 → 54
//! The genetic core is the 54 rows passing all three filters, in 29 genes.
//!
//! ## What is ported (Python = ground truth)
//!  * [`parse_verified`] / [`parse_strandbias`] (`bench/asj_genetic_core.py:27-33`) — the two
//!    `csv.DictReader(..., delimiter="\t")` loads, resolving columns BY NAME.
//!  * [`GeneticCore::build`] (`main`, `:34-52`) — the two structural asserts
//!    (`len(ver) == len(sb)` AND every row's 7-tuple key `(gene, chrom, anchor, alleleX, alleleY,
//!    donor, acceptor)` matches between the tables; reproduced here as `Err`s so a de-aligned
//!    input STOPS instead of silently mis-joining), the per-row funnel, and the funnel tallies
//!    `n_all` / `n_transversion` / `n_nonloc` / `n_core` / sorted `core_genes`.
//!  * [`GeneticCoreRow::line`] + [`render_tsv`] (`:54-61`) — the exact `csv.DictWriter`
//!    output: the 14 columns in [`CORE_HEADER`] order (`extrasaction="ignore"` ⇒ only these,
//!    in this order), each value its RAW input string except the three computed `0`/`1` flag
//!    ints, joined by `\t` and terminated by `\r\n` (csv's default `lineterminator`, INCLUDING a
//!    trailing `\r\n` after the last row). Field values here never contain a delimiter/quote/
//!    newline, so `QUOTE_MINIMAL` never quotes — the plain `\t` join is byte-identical (the
//!    parity test asserts the whole-file bytes against the shipped `asj_genetic_core.tsv`).
//!
//! ## TSV-write byte fidelity
//! [`render_tsv`] reproduces `csv.DictWriter`'s `\r\n` line terminator EXACTLY, so the emitted
//! bytes equal the shipped `bench/asj_genetic_core.tsv` (md5 `770ad35e2963a5bbb6e5f1282615b0d7`)
//! byte-for-byte. Byte-parity is enforced against `testdata/asj_genetic_core_fixture.json`
//! (generated by `bench/gen_asj_genetic_core_fixture.py`, PYTHONHASHSEED=0): the self-contained
//! `#[test]` rebuilds the funnel from the fixture's embedded input tables and asserts the 14-col
//! output rows, the funnel counts (`in_genetic_core` sum == 54), the retired-flagship behavior
//! (PSMD2 & DAXX first `high_confidence` row EXCLUDED), and the full `\r\n` output bytes ==
//! Python. A second test runs the port on the shipped input TSVs and asserts the rendered bytes
//! == the shipped `asj_genetic_core.tsv`.
//!
//! **STATUS:** TEST-ONLY  (docs/MODULE_STATUS.md; assigned by reachability, not by this header)

use std::path::Path;

use anyhow::{Context, Result, bail, ensure};

/// Input basename: the verified-calls TSV (from [`super::asj_verify`]); carries `high_confidence`.
/// Python `bench/asj_genetic_core.py:32  ver = load("asj_calls_verified.tsv")`.
pub const IN_VERIFIED_BASENAME: &str = "asj_calls_verified.tsv";

/// Input basename: the strand-bias TSV (from [`super::asj_strand_bias`]); carries `sor`/`sor_pass`.
/// Python `bench/asj_genetic_core.py:33  sb = load("asj_calls_strandbias.tsv")`.
pub const IN_STRANDBIAS_BASENAME: &str = "asj_calls_strandbias.tsv";

/// Output basename: the per-call genetic-core audit TSV. Python
/// `bench/asj_genetic_core.py:54  out = .../asj_genetic_core.tsv`.
pub const OUT_TSV_BASENAME: &str = "asj_genetic_core.tsv";

/// The 14 output columns, in `csv.DictWriter` order (`bench/asj_genetic_core.py:55-56`).
/// `extrasaction="ignore"` ⇒ EXACTLY these, in this order.
pub const CORE_COLS: [&str; 14] = [
    "gene",
    "chrom",
    "anchor",
    "alleleX",
    "alleleY",
    "donor",
    "acceptor",
    "dPSI",
    "q",
    "high_confidence",
    "non_loc_copy_confound_clean",
    "sor",
    "sor_pass",
    "in_genetic_core",
];

/// The output header line (`CORE_COLS` joined by `\t`).
pub const CORE_HEADER: &str =
    "gene\tchrom\tanchor\talleleX\talleleY\tdonor\tacceptor\tdPSI\tq\thigh_confidence\tnon_loc_copy_confound_clean\tsor\tsor_pass\tin_genetic_core";

/// `csv.DictWriter`'s default line terminator (dialect "excel"). Reproduced verbatim so the
/// rendered bytes equal the shipped `asj_genetic_core.tsv`.
pub const LINE_TERMINATOR: &str = "\r\n";

// ===========================================================================
// Column-by-name helpers  (csv.DictReader)
// ===========================================================================

/// Resolve a header column to its index, erroring (like `csv.DictReader`'s later `KeyError`)
/// when the column is absent.
fn col_index(header: &[&str], name: &str) -> Result<usize> {
    header
        .iter()
        .position(|&c| c == name)
        .with_context(|| format!("TSV header missing required column {name:?}"))
}

/// The 7-tuple row-alignment key `(gene, chrom, anchor, alleleX, alleleY, donor, acceptor)`.
/// Python `bench/asj_genetic_core.py:36`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RowKey {
    pub gene: String,
    pub chrom: String,
    pub anchor: String,
    pub allele_x: String,
    pub allele_y: String,
    pub donor: String,
    pub acceptor: String,
}

// ===========================================================================
// parse_verified  (bench/asj_genetic_core.py:32)
// ===========================================================================

/// One `asj_calls_verified.tsv` row, reduced to the columns the funnel + output need: the 7-tuple
/// key plus `dPSI`, `q`, and `high_confidence` (all echoed to the output as RAW strings).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct VerifiedRow {
    pub gene: String,
    pub chrom: String,
    pub anchor: String,
    pub allele_x: String,
    pub allele_y: String,
    pub donor: String,
    pub acceptor: String,
    pub d_psi: String,
    pub q: String,
    /// The transversion-anchor flag ("0"/"1"); filter 1 is `== "1"`.
    pub high_confidence: String,
}

impl VerifiedRow {
    /// The 7-tuple row-alignment key.
    pub fn key(&self) -> RowKey {
        RowKey {
            gene: self.gene.clone(),
            chrom: self.chrom.clone(),
            anchor: self.anchor.clone(),
            allele_x: self.allele_x.clone(),
            allele_y: self.allele_y.clone(),
            donor: self.donor.clone(),
            acceptor: self.acceptor.clone(),
        }
    }
}

/// Parse `asj_calls_verified.tsv` text (columns located BY NAME, like `csv.DictReader`).
/// The first line is the header; every subsequent line is a data row (no blank-line skip,
/// matching `csv.DictReader` over the shipped input, which has none).
pub fn parse_verified(text: &str) -> Result<Vec<VerifiedRow>> {
    let mut lines = text.lines();
    let header_line = lines.next().context("empty asj_calls_verified.tsv (no header)")?;
    let header: Vec<&str> = header_line.split('\t').collect();
    let (ci_gene, ci_chrom, ci_anchor, ci_ax, ci_ay, ci_donor, ci_acceptor, ci_dpsi, ci_q, ci_hc) = (
        col_index(&header, "gene")?,
        col_index(&header, "chrom")?,
        col_index(&header, "anchor")?,
        col_index(&header, "alleleX")?,
        col_index(&header, "alleleY")?,
        col_index(&header, "donor")?,
        col_index(&header, "acceptor")?,
        col_index(&header, "dPSI")?,
        col_index(&header, "q")?,
        col_index(&header, "high_confidence")?,
    );
    let mut out = Vec::new();
    for line in lines {
        let f: Vec<&str> = line.split('\t').collect();
        let get = |i: usize| -> String { f.get(i).copied().unwrap_or("").to_string() };
        out.push(VerifiedRow {
            gene: get(ci_gene),
            chrom: get(ci_chrom),
            anchor: get(ci_anchor),
            allele_x: get(ci_ax),
            allele_y: get(ci_ay),
            donor: get(ci_donor),
            acceptor: get(ci_acceptor),
            d_psi: get(ci_dpsi),
            q: get(ci_q),
            high_confidence: get(ci_hc),
        });
    }
    Ok(out)
}

// ===========================================================================
// parse_strandbias  (bench/asj_genetic_core.py:33)
// ===========================================================================

/// One `asj_calls_strandbias.tsv` row, reduced to the 7-tuple key plus `sor` (echoed as RAW
/// string) and `sor_pass` ("0"/"1"; filter 3 is `== "1"`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StrandBiasRow {
    pub gene: String,
    pub chrom: String,
    pub anchor: String,
    pub allele_x: String,
    pub allele_y: String,
    pub donor: String,
    pub acceptor: String,
    /// The StrandOddsRatio value (echoed to the output verbatim as `sor`).
    pub sor: String,
    /// The SOR-clean flag ("0"/"1").
    pub sor_pass: String,
}

impl StrandBiasRow {
    /// The 7-tuple row-alignment key.
    pub fn key(&self) -> RowKey {
        RowKey {
            gene: self.gene.clone(),
            chrom: self.chrom.clone(),
            anchor: self.anchor.clone(),
            allele_x: self.allele_x.clone(),
            allele_y: self.allele_y.clone(),
            donor: self.donor.clone(),
            acceptor: self.acceptor.clone(),
        }
    }
}

/// Parse `asj_calls_strandbias.tsv` text (columns located BY NAME, like `csv.DictReader`).
pub fn parse_strandbias(text: &str) -> Result<Vec<StrandBiasRow>> {
    let mut lines = text.lines();
    let header_line = lines.next().context("empty asj_calls_strandbias.tsv (no header)")?;
    let header: Vec<&str> = header_line.split('\t').collect();
    let (ci_gene, ci_chrom, ci_anchor, ci_ax, ci_ay, ci_donor, ci_acceptor, ci_sor, ci_sp) = (
        col_index(&header, "gene")?,
        col_index(&header, "chrom")?,
        col_index(&header, "anchor")?,
        col_index(&header, "alleleX")?,
        col_index(&header, "alleleY")?,
        col_index(&header, "donor")?,
        col_index(&header, "acceptor")?,
        col_index(&header, "sor")?,
        col_index(&header, "sor_pass")?,
    );
    let mut out = Vec::new();
    for line in lines {
        let f: Vec<&str> = line.split('\t').collect();
        let get = |i: usize| -> String { f.get(i).copied().unwrap_or("").to_string() };
        out.push(StrandBiasRow {
            gene: get(ci_gene),
            chrom: get(ci_chrom),
            anchor: get(ci_anchor),
            allele_x: get(ci_ax),
            allele_y: get(ci_ay),
            donor: get(ci_donor),
            acceptor: get(ci_acceptor),
            sor: get(ci_sor),
            sor_pass: get(ci_sp),
        });
    }
    Ok(out)
}

// ===========================================================================
// GeneticCoreRow + funnel  (bench/asj_genetic_core.py:39-52)
// ===========================================================================

/// One joined output row: the 14 columns of [`CORE_COLS`]. The first 10 are echoed RAW strings
/// from the verified table (`{**v}` restricted by `extrasaction="ignore"`), then the three
/// computed flags, with `sor` spliced in from the strand-bias table.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneticCoreRow {
    pub gene: String,
    pub chrom: String,
    pub anchor: String,
    pub allele_x: String,
    pub allele_y: String,
    pub donor: String,
    pub acceptor: String,
    pub d_psi: String,
    pub q: String,
    /// `high_confidence` echoed from the verified row ("0"/"1").
    pub high_confidence: String,
    /// `int(non_loc)` — 1 iff `!gene.starts_with("LOC")`.
    pub non_loc_copy_confound_clean: u8,
    /// `sor` echoed from the strand-bias row (RAW string).
    pub sor: String,
    /// `int(sor_pass)` — 1 iff the strand-bias `sor_pass == "1"`.
    pub sor_pass: u8,
    /// `int(in_core)` — 1 iff transversion AND non-LOC AND sor_pass (the genetic core).
    pub in_genetic_core: u8,
}

impl GeneticCoreRow {
    /// The exact `csv.DictWriter` data line: the 14 columns joined by `\t`, ints as `0`/`1`,
    /// everything else its RAW string. No trailing terminator (added by [`render_tsv`]).
    pub fn line(&self) -> String {
        format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}",
            self.gene,
            self.chrom,
            self.anchor,
            self.allele_x,
            self.allele_y,
            self.donor,
            self.acceptor,
            self.d_psi,
            self.q,
            self.high_confidence,
            self.non_loc_copy_confound_clean,
            self.sor,
            self.sor_pass,
            self.in_genetic_core,
        )
    }

    /// The 14 values as an ordered vector of strings (ints stringified), for row-level parity
    /// checks against the fixture's captured `out_rows`.
    pub fn values(&self) -> Vec<String> {
        vec![
            self.gene.clone(),
            self.chrom.clone(),
            self.anchor.clone(),
            self.allele_x.clone(),
            self.allele_y.clone(),
            self.donor.clone(),
            self.acceptor.clone(),
            self.d_psi.clone(),
            self.q.clone(),
            self.high_confidence.clone(),
            self.non_loc_copy_confound_clean.to_string(),
            self.sor.clone(),
            self.sor_pass.to_string(),
            self.in_genetic_core.to_string(),
        ]
    }
}

/// The complete funnel result: every joined row plus the four funnel tallies and the sorted
/// core-gene list. `bench/asj_genetic_core.py:48-52`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneticCore {
    /// Every joined output row (all 475), in input order.
    pub rows: Vec<GeneticCoreRow>,
    /// `n_all` — total candidate ASJ calls.
    pub n_all: usize,
    /// `n_transversion` — rows with `high_confidence == "1"`.
    pub n_transversion: usize,
    /// `n_nonloc` — rows with `high_confidence == "1"` AND non-LOC.
    pub n_nonloc: usize,
    /// `n_core` — rows in the genetic core (all three filters pass).
    pub n_core: usize,
    /// The sorted, unique set of genes among the core rows.
    pub core_genes: Vec<String>,
}

impl GeneticCore {
    /// Build the funnel by row-aligned join of the verified + strand-bias tables.
    ///
    /// Reproduces `main`'s two asserts as errors: the tables must be the SAME length and
    /// row-aligned by the 7-tuple key (`bench/asj_genetic_core.py:34,37`). A de-aligned input
    /// therefore STOPS (does not silently mis-join).
    pub fn build(ver: &[VerifiedRow], sb: &[StrandBiasRow]) -> Result<Self> {
        ensure!(
            ver.len() == sb.len(),
            "call tables differ in length (verified={}, strandbias={})",
            ver.len(),
            sb.len()
        );
        let mut rows = Vec::with_capacity(ver.len());
        for (i, (v, s)) in ver.iter().zip(sb.iter()).enumerate() {
            if v.key() != s.key() {
                bail!(
                    "call tables are not row-aligned at row {i}: verified key {:?} != strandbias key {:?}",
                    v.key(),
                    s.key()
                );
            }
            let transversion = v.high_confidence == "1";
            let non_loc = !v.gene.starts_with("LOC");
            let sor_pass = s.sor_pass == "1";
            let in_core = transversion && non_loc && sor_pass;
            rows.push(GeneticCoreRow {
                gene: v.gene.clone(),
                chrom: v.chrom.clone(),
                anchor: v.anchor.clone(),
                allele_x: v.allele_x.clone(),
                allele_y: v.allele_y.clone(),
                donor: v.donor.clone(),
                acceptor: v.acceptor.clone(),
                d_psi: v.d_psi.clone(),
                q: v.q.clone(),
                high_confidence: v.high_confidence.clone(),
                non_loc_copy_confound_clean: non_loc as u8,
                sor: s.sor.clone(),
                sor_pass: sor_pass as u8,
                in_genetic_core: in_core as u8,
            });
        }

        let n_all = rows.len();
        // n_transversion: high_confidence == "1".
        let n_transversion = rows.iter().filter(|r| r.high_confidence == "1").count();
        // n_nonloc: high_confidence == "1" AND non_loc (Python's `and r["non_loc_..."]` truthy).
        let n_nonloc = rows
            .iter()
            .filter(|r| r.high_confidence == "1" && r.non_loc_copy_confound_clean == 1)
            .count();
        // core rows + sorted unique gene set (Python `sorted({r["gene"] for r in core})`).
        let mut core_gene_set: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
        let mut n_core = 0usize;
        for r in &rows {
            if r.in_genetic_core == 1 {
                n_core += 1;
                core_gene_set.insert(r.gene.clone());
            }
        }
        let core_genes: Vec<String> = core_gene_set.into_iter().collect();

        Ok(Self { rows, n_all, n_transversion, n_nonloc, n_core, core_genes })
    }

    /// The genetic-core rows only (`in_genetic_core == 1`) — the 54-call deliverable.
    pub fn core_rows(&self) -> impl Iterator<Item = &GeneticCoreRow> {
        self.rows.iter().filter(|r| r.in_genetic_core == 1)
    }
}

// ===========================================================================
// render_tsv / run driver  (bench/asj_genetic_core.py:54-61)
// ===========================================================================

/// Render the full `asj_genetic_core.tsv` bytes: [`CORE_HEADER`] then every row's [`line`], each
/// terminated by `\r\n` (INCLUDING a trailing `\r\n` after the last row, matching
/// `csv.DictWriter`). Byte-identical to the shipped file.
///
/// [`line`]: GeneticCoreRow::line
pub fn render_tsv(core: &GeneticCore) -> String {
    let mut out = String::with_capacity((core.rows.len() + 1) * 64);
    out.push_str(CORE_HEADER);
    out.push_str(LINE_TERMINATOR);
    for r in &core.rows {
        out.push_str(&r.line());
        out.push_str(LINE_TERMINATOR);
    }
    out
}

/// Build the funnel from the two input TSV files (`ver_path` / `sb_path`). Files default to
/// `{bench}/asj_calls_verified.tsv` and `{bench}/asj_calls_strandbias.tsv` when the caller
/// passes those basenames under a bench directory.
pub fn run_from_paths(ver_path: &Path, sb_path: &Path) -> Result<GeneticCore> {
    let ver_text = std::fs::read_to_string(ver_path)
        .with_context(|| format!("read verified TSV {}", ver_path.display()))?;
    let sb_text = std::fs::read_to_string(sb_path)
        .with_context(|| format!("read strand-bias TSV {}", sb_path.display()))?;
    let ver = parse_verified(&ver_text)?;
    let sb = parse_strandbias(&sb_text)?;
    GeneticCore::build(&ver, &sb)
}

/// Build the funnel from a bench directory (joins the two default input basenames) and write
/// `asj_genetic_core.tsv` into it, byte-identical to the Python output. Returns the funnel so the
/// caller can print the summary. `bench/asj_genetic_core.py::main`.
pub fn run_and_write(bench_dir: &Path) -> Result<GeneticCore> {
    let ver_path = bench_dir.join(IN_VERIFIED_BASENAME);
    let sb_path = bench_dir.join(IN_STRANDBIAS_BASENAME);
    let core = run_from_paths(&ver_path, &sb_path)?;
    let out_path = bench_dir.join(OUT_TSV_BASENAME);
    std::fs::write(&out_path, render_tsv(&core))
        .with_context(|| format!("write {}", out_path.display()))?;
    Ok(core)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;
    use std::path::PathBuf;

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/asj_genetic_core_fixture.json");
        serde_json::from_str(raw).expect("parse asj_genetic_core fixture json")
    }

    /// Rebuild the two input tables from the fixture's embedded rows (so the test is
    /// self-contained — no shipped-file dependency).
    fn tables_from_fixture(fx: &Value) -> (Vec<VerifiedRow>, Vec<StrandBiasRow>) {
        let ver = fx["ver_rows"]
            .as_array()
            .expect("ver_rows array")
            .iter()
            .map(|r| VerifiedRow {
                gene: r["gene"].as_str().unwrap().to_string(),
                chrom: r["chrom"].as_str().unwrap().to_string(),
                anchor: r["anchor"].as_str().unwrap().to_string(),
                allele_x: r["alleleX"].as_str().unwrap().to_string(),
                allele_y: r["alleleY"].as_str().unwrap().to_string(),
                donor: r["donor"].as_str().unwrap().to_string(),
                acceptor: r["acceptor"].as_str().unwrap().to_string(),
                d_psi: r["dPSI"].as_str().unwrap().to_string(),
                q: r["q"].as_str().unwrap().to_string(),
                high_confidence: r["high_confidence"].as_str().unwrap().to_string(),
            })
            .collect();
        let sb = fx["sb_rows"]
            .as_array()
            .expect("sb_rows array")
            .iter()
            .map(|r| StrandBiasRow {
                gene: r["gene"].as_str().unwrap().to_string(),
                chrom: r["chrom"].as_str().unwrap().to_string(),
                anchor: r["anchor"].as_str().unwrap().to_string(),
                allele_x: r["alleleX"].as_str().unwrap().to_string(),
                allele_y: r["alleleY"].as_str().unwrap().to_string(),
                donor: r["donor"].as_str().unwrap().to_string(),
                acceptor: r["acceptor"].as_str().unwrap().to_string(),
                sor: r["sor"].as_str().unwrap().to_string(),
                sor_pass: r["sor_pass"].as_str().unwrap().to_string(),
            })
            .collect();
        (ver, sb)
    }

    /// SELF-CONTAINED byte-parity: rebuild the funnel from the fixture's embedded input tables
    /// and assert (a) every 14-col output row == Python, (b) the funnel counts
    /// (475 → 120 → 76 → 54, `in_genetic_core` sum == 54), (c) the sorted core-gene list, (d) the
    /// retired-flagship behavior (PSMD2 & DAXX first `high_confidence` row EXCLUDED), and (e) the
    /// full `\r\n` output bytes == the shipped `asj_genetic_core.tsv`.
    #[test]
    fn asj_genetic_core_parity() {
        let fx = load_fixture();
        // Header / constant parity.
        assert_eq!(CORE_HEADER, fx["header"].as_str().unwrap(), "output header");
        assert_eq!(LINE_TERMINATOR, fx["line_terminator"].as_str().unwrap(), "line terminator");
        assert_eq!(
            CORE_COLS.to_vec(),
            fx["cols"].as_array().unwrap().iter().map(|c| c.as_str().unwrap()).collect::<Vec<_>>(),
            "output column order"
        );

        let (ver, sb) = tables_from_fixture(&fx);
        let core = GeneticCore::build(&ver, &sb).expect("build funnel");

        // (b) funnel counts.
        assert_eq!(core.n_all, fx["n_all"].as_u64().unwrap() as usize, "n_all");
        assert_eq!(core.n_transversion, fx["n_transversion"].as_u64().unwrap() as usize, "n_transversion");
        assert_eq!(core.n_nonloc, fx["n_nonloc"].as_u64().unwrap() as usize, "n_nonloc");
        assert_eq!(core.n_core, fx["n_core"].as_u64().unwrap() as usize, "n_core");
        // The pinned funnel: 475 -> 120 -> 76 -> 54.
        assert_eq!(core.n_all, 475, "funnel: 475 candidates");
        assert_eq!(core.n_transversion, 120, "funnel: 120 transversion");
        assert_eq!(core.n_nonloc, 76, "funnel: 76 non-LOC");
        assert_eq!(core.n_core, 54, "funnel: 54 genetic core");
        // in_genetic_core column sums to 54.
        let core_sum: u64 = core.rows.iter().map(|r| r.in_genetic_core as u64).sum();
        assert_eq!(core_sum, 54, "in_genetic_core column sum == 54");
        assert_eq!(core.core_rows().count(), 54, "core_rows() count == 54");

        // (c) sorted core-gene list.
        let want_genes: Vec<String> = fx["core_genes"]
            .as_array()
            .unwrap()
            .iter()
            .map(|g| g.as_str().unwrap().to_string())
            .collect();
        assert_eq!(core.core_genes, want_genes, "sorted core-gene list");

        // (a) every 14-col output row == Python.
        let want_rows = fx["out_rows"].as_array().unwrap();
        assert_eq!(core.rows.len(), want_rows.len(), "output row count");
        for (i, (r, want)) in core.rows.iter().zip(want_rows).enumerate() {
            let want_vals: Vec<String> =
                want.as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();
            assert_eq!(r.values(), want_vals, "output row {i} values");
        }

        // (d) retired-flagship behavior: the FIRST high_confidence PSMD2 & DAXX rows are
        // transversion=1 but EXCLUDED from the core (sor_pass gate). Reproduces Python's
        // `next((r for r in rows if r.gene==g and high_confidence=="1"), None)`.
        for g in ["PSMD2", "DAXX"] {
            let hit = core
                .rows
                .iter()
                .find(|r| r.gene == g && r.high_confidence == "1")
                .unwrap_or_else(|| panic!("expected a high_confidence {g} row"));
            assert_eq!(hit.high_confidence, "1", "{g} flagship is transversion");
            assert_eq!(hit.sor_pass, 0, "{g} flagship fails SOR strand-bias gate");
            assert_eq!(hit.in_genetic_core, 0, "{g} flagship EXCLUDED from genetic core");
        }
        // Cross-check against the fixture's captured flagship rows.
        for f in fx["flagships"].as_array().unwrap() {
            let g = f["gene"].as_str().unwrap();
            let hit = core.rows.iter().find(|r| r.gene == g && r.high_confidence == "1").unwrap();
            assert_eq!(hit.sor, f["sor"].as_str().unwrap(), "{g} flagship sor");
            assert_eq!(hit.sor_pass, f["sor_pass"].as_u64().unwrap() as u8, "{g} flagship sor_pass");
            assert_eq!(
                hit.in_genetic_core,
                f["in_genetic_core"].as_u64().unwrap() as u8,
                "{g} flagship in_genetic_core"
            );
        }
        // PSMD2 still APPEARS in the core-gene list (two LATER PSMD2 rows are SOR-clean), even
        // though its flagship junction is excluded; DAXX does not.
        assert!(core.core_genes.iter().any(|g| g == "PSMD2"), "PSMD2 in core genes (via later rows)");
        assert!(!core.core_genes.iter().any(|g| g == "DAXX"), "DAXX excluded from core genes");

        // (e) full \r\n output bytes == the shipped file bytes.
        let rendered = render_tsv(&core);
        assert_eq!(rendered, fx["out_tsv_bytes"].as_str().unwrap(), "full \\r\\n output bytes");
        // Structural byte facts: 476 CRLF-terminated lines, trailing CRLF.
        assert_eq!(rendered.matches("\r\n").count(), 476, "476 CRLF terminators (header + 475 rows)");
        assert!(rendered.ends_with("\r\n"), "file ends with trailing CRLF");

        eprintln!(
            "asj_genetic_core parity: funnel {}→{}→{}→{} (in_genetic_core sum={core_sum}); \
             {} core genes; PSMD2/DAXX flagships EXCLUDED; {} output rows + full CRLF bytes == Python",
            core.n_all, core.n_transversion, core.n_nonloc, core.n_core, core.core_genes.len(), core.rows.len(),
        );
    }

    /// Live byte-parity over the SHIPPED input TSVs: parse `bench/asj_calls_verified.tsv` +
    /// `asj_calls_strandbias.tsv` (via the port's own parsers), run the funnel, and assert the
    /// rendered bytes == the shipped `bench/asj_genetic_core.tsv`. Skips-with-message (does NOT
    /// fail) if any of the three files is absent, so CI without them is green; all three ARE
    /// committed. Fast (pure TSV, no BAM) → always-on.
    #[test]
    fn asj_genetic_core_shipped_files_byte_parity() {
        let bench = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bench");
        let ver_path = bench.join(IN_VERIFIED_BASENAME);
        let sb_path = bench.join(IN_STRANDBIAS_BASENAME);
        let out_path = bench.join(OUT_TSV_BASENAME);
        if !ver_path.exists() || !sb_path.exists() || !out_path.exists() {
            eprintln!(
                "asj_genetic_core shipped-file parity SKIPPED: input/output TSV absent ({} / {} / {}). \
                 Committed in dev; run there to exercise this test.",
                ver_path.display(),
                sb_path.display(),
                out_path.display()
            );
            return;
        }
        let core = run_from_paths(&ver_path, &sb_path).expect("run funnel on shipped inputs");
        assert_eq!(core.n_core, 54, "shipped inputs → 54-call genetic core");

        let rendered = render_tsv(&core);
        let shipped = std::fs::read(&out_path).expect("read shipped asj_genetic_core.tsv");
        assert_eq!(
            rendered.as_bytes(),
            shipped.as_slice(),
            "rendered bytes != shipped asj_genetic_core.tsv (byte-parity)"
        );
        eprintln!(
            "asj_genetic_core shipped-file parity: rendered {} bytes == bench/asj_genetic_core.tsv EXACTLY; \
             54-call core reproduced",
            rendered.len()
        );
    }
}
