//! O3 ASJ VERIFY layer: the deterministic CONFOUND CONTROL over the ASJ calls.
//!
//! Faithful Rust port of `bench/asj_verify.py`. The O3 ASJ *core* (calling the
//! allele-specific junctions themselves) lives in [`super::allele_specific_junctions`], and
//! the strand-bias filter is [`super::asj_strand_bias`]; this module ports the SECOND
//! analysis layer that runs ON TOP of the shipped `asj_calls.tsv`. It attaches to every call
//! two confound-control columns the raw FDR cannot see:
//!  * `frac_mq0` — the MAPQ-0 fraction at the anchor SNP. A HIGH fraction flags a
//!    COLLAPSED-PARALOG MASQUERADE (the two "alleles" are really paralog copies, so the
//!    "allele-specific" junctions are copy-specific isoforms); a LOW fraction (uniquely
//!    mapped) means genuine within-gene heterozygosity.
//!  * `dist` — the anchor→junction distance (a mechanism-plausibility proxy; PROXIMITY only,
//!    NOT "on the canonical dinucleotide" — see `bench/asj_motif_check.py`).
//! and marks the confound-controlled `high_confidence` set (transversion anchor AND uniquely
//! mapped). It writes `bench/asj_calls_verified.tsv` (the print()/summary block in the Python
//! is analysis-only — this port reproduces the WRITTEN TSV, not the stdout).
//!
//! ## What is ported (Python = ground truth)
//!  * [`AsjVerifyEngine::frac_mq0_at`] (`bench/asj_verify.py:30`): `fetch(chrom, pos, pos+1)`,
//!    skip `is_unmapped`(0x4)/`is_secondary`(0x100)/`is_supplementary`(0x800), `n += 1`,
//!    `z += 1` when `mapping_quality == 0`, and **BREAK when `n >= 600`** — an
//!    order-dependent cap over pysam's coordinate-order fetch (reproduced below).
//!    Returns `z/n` (an exactly-representable small-int f64 division) or `0.0` when `n == 0`.
//!  * [`parse_calls`] + [`AsjVerifyEngine::run`] (`main`, `:43`): read the calls TSV, DEDUP
//!    unique `(chrom, int(anchor))` anchors (compute `frac_mq0_at` ONCE per anchor,
//!    first-occurrence order), then per row `dist = min(|anchor-donor|, |anchor-acceptor|)`,
//!    `frac_mq0 = the anchor's value`, and
//!    `high_confidence = int(anchor_type == "transversion" && frac_mq0 < MQ0_THR)`, emitting
//!    the verified row with columns `[gene, chrom, anchor, alleleX, alleleY, donor, acceptor,
//!    psiX, psiY, dPSI, q, anchor_type, dist, frac_mq0] + high_confidence` (the input `pval`
//!    column is dropped; `q` is kept).
//!
//! ## The 600-cap and coordinate order (parity vs pysam)
//! `pysam.fetch` yields the reads that overlap `[pos, pos+1)` in coordinate (BAM file) order;
//! noodles' indexed `query` yields the same records in the same file order. Because the cap
//! keeps the FIRST 600 primary (non-unmapped/secondary/supplementary) reads, both implementations
//! process the identical prefix, so `z`/`n` — hence `frac_mq0` — are bit-identical even when an
//! anchor exceeds 600 reads. (On `GGO.bam` the fixture records whether any anchor hits the cap.)
//!
//! ## The frac_mq0 float→string reproduction
//! The TSV writes `str(r["frac_mq0"])` — CPython's shortest round-trip `float→str`. Rust's
//! `f64: Display` also emits the shortest round-trip decimal, digit-for-digit identical to
//! CPython for every value here; the ONLY difference is that Python appends `.0` to an
//! integer-valued float (`0.0`) while Rust prints `0`. [`py_float_str`] restores that `.0`
//! (and CPython's `nan`/`inf` spellings), reproducing `str(float)` EXACTLY for the frac_mq0
//! range `[0, 1)` (all values `>= ~8e-3`, so neither implementation switches to exponential
//! notation, which is Python's only other divergence — disclosed here). The byte-parity test
//! ALSO asserts the raw f64 bits independently, so parity never relies on the string alone.
//!
//! Byte-parity is enforced against `testdata/asj_verify_fixture.json` (generated by
//! `bench/gen_asj_verify_fixture.py`, PYTHONHASHSEED=0, over the real `GGO.bam`): the live
//! `#[test]` re-fetches the BAM and recomputes every anchor's `frac_mq0` (bits + string) and
//! every call's `dist`/`high_confidence`/written line, asserting `== Python`. A FAST,
//! always-on test pins the pure `dist`/`high_confidence`/`py_float_str` logic without the BAM.

use std::path::Path;

use anyhow::{Context, Result};
use noodles_sam::alignment::RecordBuf;

/// Uniquely-mapped threshold: an anchor with `frac_mq0 < MQ0_THR` is treated as uniquely
/// mapped (genuine heterozygosity). Python `bench/asj_verify.py:26  MQ0_THR = 0.10`.
pub const MQ0_THR: f64 = 0.10;

/// Splice-proximity window in bp (used only by the Python summary, NOT written to the TSV;
/// carried for constant parity). Python `bench/asj_verify.py:27  PROX = 100`.
pub const PROX: i64 = 100;

/// Read cap for [`AsjVerifyEngine::frac_mq0_at`]: stop after the first 600 primary reads.
/// Python `bench/asj_verify.py:38  if n >= 600: break`.
pub const CAP: i64 = 600;

/// Default multimapping genome BAM (the MAPQ-0 read source). Python
/// `bench/asj_verify.py:25  BAM = "/home/juanfra/winloci_scratch/GGO.bam"`.
pub const DEFAULT_BAM: &str = "/home/juanfra/winloci_scratch/GGO.bam";

/// Input ASJ-calls TSV basename (in `bench/`). Python
/// `bench/asj_verify.py:23  CALLS = .../asj_calls.tsv`.
pub const IN_TSV_BASENAME: &str = "asj_calls.tsv";

/// Output verified-calls TSV basename. Python
/// `bench/asj_verify.py:24  OUT = .../asj_calls_verified.tsv`.
pub const OUT_TSV_BASENAME: &str = "asj_calls_verified.tsv";

/// The verified-TSV header line (`main` writes `"\t".join(cols) + "\thigh_confidence"`;
/// `bench/asj_verify.py:91-93`). Note: input `pval` is dropped, `q` retained.
pub const VERIFIED_HEADER: &str =
    "gene\tchrom\tanchor\talleleX\talleleY\tdonor\tacceptor\tpsiX\tpsiY\tdPSI\tq\tanchor_type\tdist\tfrac_mq0\thigh_confidence";

// ===========================================================================
// py_float_str  — reproduce CPython str(float)
// ===========================================================================

/// Reproduce CPython's `str(float)` (shortest round-trip repr) for the frac_mq0 range.
///
/// Rust's `f64: Display` already emits the shortest round-trip decimal, identical to CPython
/// digit-for-digit; the only divergences are (1) Python appends `.0` to an integer-valued
/// float and (2) Python switches to exponential notation for `|x| < 1e-4` (or very large).
/// Fraction values are in `[0, 1)` with the smallest nonzero `~8e-3`, so (2) never fires; this
/// function only needs to restore the `.0` (and use CPython's `nan`/`inf` spellings). The
/// byte-parity test independently asserts the f64 bits, so correctness never rests on this
/// string alone.
pub fn py_float_str(x: f64) -> String {
    if x.is_nan() {
        return "nan".to_string();
    }
    if x.is_infinite() {
        return if x < 0.0 { "-inf".to_string() } else { "inf".to_string() };
    }
    let s = format!("{x}");
    // Rust prints integer-valued floats without a fractional part ("0"); Python writes "0.0".
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    }
}

// ===========================================================================
// dist / high_confidence  — pure per-row logic (bench/asj_verify.py:60,65)
// ===========================================================================

/// Anchor→junction distance `min(|anchor - donor|, |anchor - acceptor|)`.
/// Python `bench/asj_verify.py:60  r["dist"] = min(abs(anc - d), abs(anc - a))`.
pub fn dist_of(anchor: i64, donor: i64, acceptor: i64) -> i64 {
    (anchor - donor).abs().min((anchor - acceptor).abs())
}

/// `high_confidence = (anchor_type == "transversion") AND (frac_mq0 < MQ0_THR)`.
/// Python `bench/asj_verify.py:95  h = int(r["anchor_type"] == "transversion" and r["frac_mq0"] < MQ0_THR)`.
pub fn is_high_confidence(anchor_type: &str, frac_mq0: f64) -> bool {
    anchor_type == "transversion" && frac_mq0 < MQ0_THR
}

// ===========================================================================
// parse_calls  (bench/asj_verify.py:45-48)
// ===========================================================================

/// One parsed ASJ-call row: every column echoed to the verified TSV (as its RAW string, since
/// Python writes `str(r[c])` over dict-of-strings) plus the parsed integer anchor/donor/acceptor
/// the `dist`/`frac_mq0` computation needs.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CallRow {
    /// `gene` column (echoed verbatim).
    pub gene: String,
    /// `chrom` column (echoed; also the fetch contig).
    pub chrom: String,
    /// `anchor` column, RAW string (echoed verbatim).
    pub anchor: String,
    /// `alleleX` column (echoed verbatim).
    pub allele_x: String,
    /// `alleleY` column (echoed verbatim).
    pub allele_y: String,
    /// `donor` column, RAW string (echoed verbatim).
    pub donor: String,
    /// `acceptor` column, RAW string (echoed verbatim).
    pub acceptor: String,
    /// `psiX` column (echoed verbatim).
    pub psi_x: String,
    /// `psiY` column (echoed verbatim).
    pub psi_y: String,
    /// `dPSI` column (echoed verbatim).
    pub d_psi: String,
    /// `q` column (echoed verbatim — the input `pval` column is NOT emitted).
    pub q: String,
    /// `anchor_type` column ("transversion" / "transition"); drives `high_confidence`.
    pub anchor_type: String,
    /// `int(anchor)` — the fetch position AND the `dist` anchor point.
    pub anchor_i: i64,
    /// `int(donor)`.
    pub donor_i: i64,
    /// `int(acceptor)`.
    pub acceptor_i: i64,
}

/// Parse the ASJ-calls TSV text into [`CallRow`]s, faithful to `bench/asj_verify.py:45-48`
/// (`hdr = split header; rows = dict(zip(hdr, split))` per line). Columns are located BY NAME
/// (robust to reordering); `anchor`/`donor`/`acceptor` are parsed to `i64`. Python does not
/// skip blank lines here, and the shipped file has none; a genuinely empty line would fail to
/// parse (mirroring Python's `KeyError`), which cannot occur on the real input.
pub fn parse_calls(text: &str) -> Result<Vec<CallRow>> {
    let mut lines = text.lines();
    let hdr_line = lines.next().context("empty ASJ-calls TSV (no header)")?;
    let hdr: Vec<&str> = hdr_line.split('\t').collect();
    let col = |name: &str| -> Result<usize> {
        hdr.iter()
            .position(|&c| c == name)
            .with_context(|| format!("ASJ-calls header missing column {name:?}"))
    };
    let (ci_gene, ci_chrom, ci_anchor, ci_ax, ci_ay, ci_donor, ci_acceptor, ci_psix, ci_psiy, ci_dpsi, ci_q, ci_at) = (
        col("gene")?,
        col("chrom")?,
        col("anchor")?,
        col("alleleX")?,
        col("alleleY")?,
        col("donor")?,
        col("acceptor")?,
        col("psiX")?,
        col("psiY")?,
        col("dPSI")?,
        col("q")?,
        col("anchor_type")?,
    );

    let mut out = Vec::new();
    for line in lines {
        let f: Vec<&str> = line.split('\t').collect();
        let get = |i: usize| -> &str { f.get(i).copied().unwrap_or("") };
        let anchor = get(ci_anchor);
        let donor = get(ci_donor);
        let acceptor = get(ci_acceptor);
        out.push(CallRow {
            gene: get(ci_gene).to_string(),
            chrom: get(ci_chrom).to_string(),
            anchor: anchor.to_string(),
            allele_x: get(ci_ax).to_string(),
            allele_y: get(ci_ay).to_string(),
            donor: donor.to_string(),
            acceptor: acceptor.to_string(),
            psi_x: get(ci_psix).to_string(),
            psi_y: get(ci_psiy).to_string(),
            d_psi: get(ci_dpsi).to_string(),
            q: get(ci_q).to_string(),
            anchor_type: get(ci_at).to_string(),
            anchor_i: anchor.parse().with_context(|| format!("anchor int in {line:?}"))?,
            donor_i: donor.parse().with_context(|| format!("donor int in {line:?}"))?,
            acceptor_i: acceptor.parse().with_context(|| format!("acceptor int in {line:?}"))?,
        });
    }
    Ok(out)
}

// ===========================================================================
// VerifiedRow + driver  (bench/asj_verify.py::main)
// ===========================================================================

/// The confound-control result for one call: the two appended metrics, the `high_confidence`
/// flag, and the EXACT verified-TSV line (data columns + `\t{high_confidence}`).
#[derive(Clone, Debug, PartialEq)]
pub struct VerifiedRow {
    /// `min(|anchor-donor|, |anchor-acceptor|)`.
    pub dist: i64,
    /// The anchor's MAPQ-0 fraction (shared across all calls with the same `(chrom, anchor)`).
    pub frac_mq0: f64,
    /// `anchor_type == "transversion" && frac_mq0 < MQ0_THR`.
    pub high_confidence: bool,
    /// The exact tab-joined verified-TSV line for this call (no trailing newline).
    pub line: String,
}

/// A reusable ASJ-verify engine: parses the `.bai` index + header ONCE (like
/// [`super::asj_strand_bias::StrandBiasEngine`] / [`super::denovo_assemble::BamIndexCache`]),
/// then answers `frac_mq0_at` per unique anchor with the cached index.
pub struct AsjVerifyEngine {
    bam_path: String,
    header: noodles_sam::Header,
    index: noodles_bam::bai::Index,
}

impl AsjVerifyEngine {
    /// Open `{bam_path}` and parse its header + `{bam_path}.bai`. Errors (so the caller/test
    /// can skip) when the index is missing.
    pub fn open(bam_path: &str) -> Result<Self> {
        let bai_path = format!("{bam_path}.bai");
        anyhow::ensure!(
            Path::new(&bai_path).exists(),
            "AsjVerifyEngine needs a .bai index next to {bam_path} (expected {bai_path})"
        );
        let mut reader = noodles_bam::io::reader::Builder::default().build_from_path(bam_path)?;
        let header = reader.read_header()?;
        let index = noodles_bam::bai::read(&bai_path)?;
        Ok(Self { bam_path: bam_path.to_string(), header, index })
    }

    /// MAPQ-0 fraction over the primary reads covering the single base `pos` (0-based).
    /// Faithful port of `bench/asj_verify.py::frac_mq0_at`.
    ///
    /// pysam `fetch(chrom, pos, pos+1)` (0-based half-open) == the 1-based inclusive region
    /// `{chrom}:{pos+1}-{pos+1}`; both return the reads overlapping that base in coordinate
    /// (BAM file) order. Per read: skip `is_unmapped`/`is_secondary`/`is_supplementary`;
    /// else `n += 1` and `z += 1` when `mapping_quality == 0`; **break once `n >= CAP`** so
    /// only the first 600 primary reads count (identical prefix under identical order ⇒
    /// identical `z`/`n`). Returns `z/n` (exact small-int f64 division) or `0.0` if `n == 0`.
    ///
    /// MAPQ-255 (SAM "missing", noodles `mapping_quality() == None`) is treated as NON-zero,
    /// matching pysam's `mapping_quality == 255 != 0` (minimap2 never emits 255, so this
    /// cannot affect parity on `GGO.bam`; the choice keeps the port correct in general).
    pub fn frac_mq0_at(&self, chrom: &str, pos: i64) -> Result<f64> {
        let mut reader = noodles_bam::io::reader::Builder::default().build_from_path(&self.bam_path)?;
        let region: noodles_core::Region = format!("{chrom}:{}-{}", pos + 1, pos + 1).parse()?;
        let query = reader.query(&self.header, &self.index, &region)?;
        let (mut n, mut z) = (0i64, 0i64);
        for result in query {
            let record = result?;
            let rb = RecordBuf::try_from_alignment_record(&self.header, &record)?;
            let flags = rb.flags();
            if flags.is_unmapped() || flags.is_secondary() || flags.is_supplementary() {
                continue;
            }
            n += 1;
            // mapping_quality == 0 (Some(0)); None == MAPQ-255 "missing" ⇒ NOT zero.
            if rb.mapping_quality().map(|q| q.get() == 0).unwrap_or(false) {
                z += 1;
            }
            if n >= CAP {
                break;
            }
        }
        Ok(if n > 0 { z as f64 / n as f64 } else { 0.0 })
    }

    /// Run the confound control over every parsed call, replicating `main`:
    ///  1. dedup unique `(chrom, anchor)` anchors in first-occurrence order, computing
    ///     `frac_mq0_at` ONCE each;
    ///  2. per row: `dist`, the anchor's `frac_mq0`, `high_confidence`, and the exact
    ///     verified-TSV line.
    pub fn run(&self, calls: &[CallRow]) -> Result<Vec<VerifiedRow>> {
        // (1) unique-anchor frac_mq0 map (first-occurrence order, one fetch per anchor).
        let mut mq0: std::collections::HashMap<(String, i64), f64> = std::collections::HashMap::new();
        for c in calls {
            let key = (c.chrom.clone(), c.anchor_i);
            if !mq0.contains_key(&key) {
                let f = self.frac_mq0_at(&c.chrom, c.anchor_i)?;
                mq0.insert(key, f);
            }
        }
        // (2) per-row output.
        let mut out = Vec::with_capacity(calls.len());
        for c in calls {
            let frac = mq0[&(c.chrom.clone(), c.anchor_i)];
            let dist = dist_of(c.anchor_i, c.donor_i, c.acceptor_i);
            let hc = is_high_confidence(&c.anchor_type, frac);
            out.push(VerifiedRow { dist, frac_mq0: frac, high_confidence: hc, line: c.verified_line(dist, frac, hc) });
        }
        Ok(out)
    }
}

impl CallRow {
    /// Build the exact verified-TSV line: the 12 echoed columns (RAW strings, in output order)
    /// then computed `dist` and `frac_mq0` (`str(float)`), then `\t{high_confidence as int}`.
    /// `bench/asj_verify.py:91-96`.
    pub fn verified_line(&self, dist: i64, frac_mq0: f64, high_confidence: bool) -> String {
        format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}",
            self.gene,
            self.chrom,
            self.anchor,
            self.allele_x,
            self.allele_y,
            self.donor,
            self.acceptor,
            self.psi_x,
            self.psi_y,
            self.d_psi,
            self.q,
            self.anchor_type,
            dist,
            py_float_str(frac_mq0),
            high_confidence as u8,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;
    use std::path::PathBuf;

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/asj_verify_fixture.json");
        serde_json::from_str(raw).expect("parse asj_verify fixture json")
    }

    /// Little-endian IEEE-754 hex (`struct.pack("<d", x).hex()`) -> the f64 bit pattern.
    fn hex_le_to_bits(s: &str) -> u64 {
        assert_eq!(s.len(), 16, "expected 16 hex chars, got {s:?}");
        let mut b = [0u8; 8];
        for (i, byte) in b.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("hex byte");
        }
        u64::from_le_bytes(b)
    }

    /// FAST, always-on: the pure per-row logic (`dist`, `high_confidence`, `py_float_str`) and
    /// the MQ0_THR / transversion boundaries — NO BAM needed. Uses the fixture's CAPTURED
    /// frac_mq0 values plus synthetic boundary cases.
    #[test]
    fn asj_verify_pure_logic() {
        // Constant parity with Python.
        assert_eq!(MQ0_THR, 0.10, "MQ0_THR");
        assert_eq!(PROX, 100, "PROX");
        assert_eq!(CAP, 600, "CAP");

        // py_float_str reproduces CPython str(float) for every distinct frac in the dataset.
        assert_eq!(py_float_str(0.0), "0.0");
        assert_eq!(py_float_str(1.0), "1.0");
        assert_eq!(py_float_str(0.008130081300813009), "0.008130081300813009");
        assert_eq!(py_float_str(0.07142857142857142), "0.07142857142857142");
        assert_eq!(py_float_str(f64::NAN), "nan");
        assert_eq!(py_float_str(f64::INFINITY), "inf");
        // z/n divisions must format identically to Python's str(z/n).
        assert_eq!(py_float_str(0i64 as f64 / 10.0), "0.0");
        assert_eq!(py_float_str(1i64 as f64 / 123.0), "0.008130081300813009");
        assert_eq!(py_float_str(12i64 as f64 / 217.0), "0.055299539170506916");

        // dist_of.
        assert_eq!(dist_of(192934097, 192941955, 192944457), 7858);
        assert_eq!(dist_of(100, 90, 130), 10);
        assert_eq!(dist_of(100, 130, 90), 10); // order-independent (both are farther/closer)

        // high_confidence: transversion AND frac < 0.10; boundary AT 0.10 is EXCLUSIVE.
        assert!(is_high_confidence("transversion", 0.0));
        assert!(is_high_confidence("transversion", 0.099));
        assert!(!is_high_confidence("transversion", 0.10)); // boundary: NOT < 0.10
        assert!(!is_high_confidence("transversion", 0.1000001));
        assert!(!is_high_confidence("transition", 0.0)); // non-transversion never HC
        assert!(!is_high_confidence("transition", 0.099));

        // Replay the fixture's captured (anchor frac_mq0) + per-call rows WITHOUT the BAM:
        // dist, high_confidence, py_float_str, and the full written line must match Python.
        let fx = load_fixture();
        let anchors = fx["anchors"].as_array().unwrap();
        // anchor frac strings/bits self-consistent.
        for a in anchors {
            let frac = f64::from_bits(hex_le_to_bits(a["frac_mq0_bits"].as_str().unwrap()));
            assert_eq!(
                py_float_str(frac),
                a["frac_mq0_str"].as_str().unwrap(),
                "anchor {}:{} frac string",
                a["chrom"], a["anchor"]
            );
        }
        let calls = fx["calls"].as_array().unwrap();
        let mut n_tv = 0usize;
        let mut n_hc = 0usize;
        let mut n_zero_frac = 0usize;
        let mut n_pos_frac = 0usize;
        for c in calls {
            let anchor = c["anchor"].as_i64().unwrap();
            let donor = c["donor"].as_i64().unwrap();
            let acceptor = c["acceptor"].as_i64().unwrap();
            let anchor_type = c["anchor_type"].as_str().unwrap();
            let frac = f64::from_bits(hex_le_to_bits(c["frac_mq0_bits"].as_str().unwrap()));
            assert_eq!(dist_of(anchor, donor, acceptor), c["dist"].as_i64().unwrap(), "call dist");
            assert_eq!(
                is_high_confidence(anchor_type, frac),
                c["high_confidence"].as_i64().unwrap() == 1,
                "call high_confidence"
            );
            assert_eq!(py_float_str(frac), c["frac_mq0_str"].as_str().unwrap(), "call frac string");
            if anchor_type == "transversion" {
                n_tv += 1;
            }
            if c["high_confidence"].as_i64().unwrap() == 1 {
                n_hc += 1;
            }
            if frac == 0.0 {
                n_zero_frac += 1;
            } else {
                n_pos_frac += 1;
            }
        }
        // Coverage the fixture must exercise.
        assert!(n_tv >= 1, "fixture must cover >=1 transversion");
        assert!(calls.len() - n_tv >= 1, "fixture must cover >=1 non-transversion");
        assert!(n_hc >= 1, "fixture must cover >=1 high_confidence call");
        assert!(n_zero_frac >= 1, "fixture must cover >=1 frac_mq0 == 0 call");
        assert!(n_pos_frac >= 1, "fixture must cover >=1 frac_mq0 > 0 call");
        assert_eq!(n_hc, fx["n_high_confidence"].as_u64().unwrap() as usize, "n_high_confidence tally");
        eprintln!(
            "asj_verify pure-logic: {} calls ({} transversion, {} HC, {} zero-frac, {} pos-frac); \
             py_float_str + dist + high_confidence match Python",
            calls.len(),
            n_tv,
            n_hc,
            n_zero_frac,
            n_pos_frac
        );
    }

    /// Live byte-parity over `GGO.bam`: every unique anchor's `frac_mq0` (bits + string) and
    /// every call's `dist`/`high_confidence`/written line match Python EXACTLY. Skips-with-
    /// message (does NOT fail) if the BAM / `.bai` / calls TSV is absent, so CI without them is
    /// green; all three ARE present in dev. Marked `#[ignore]` because it re-fetches a large
    /// indexed BAM (one query per unique anchor).
    #[test]
    #[ignore = "reads the large GGO.bam (one indexed query per unique anchor, ~232 fetches); run on \
                demand via `cargo test --release -- --ignored asj_verify_byte_parity`. The fast \
                asj_verify_pure_logic test above covers dist/high_confidence/py_float_str without the BAM."]
    fn asj_verify_byte_parity() {
        let fx = load_fixture();
        assert_eq!(MQ0_THR, fx["mq0_thr"].as_f64().unwrap(), "MQ0_THR disagrees");
        assert_eq!(PROX, fx["prox"].as_i64().unwrap(), "PROX disagrees");
        assert_eq!(DEFAULT_BAM, fx["bam_path"].as_str().unwrap(), "DEFAULT_BAM disagrees");

        let bam_path = fx["bam_path"].as_str().unwrap();
        let bai = format!("{bam_path}.bai");
        let calls_tsv = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bench").join(IN_TSV_BASENAME);
        if !Path::new(bam_path).exists() || !Path::new(&bai).exists() || !calls_tsv.exists() {
            eprintln!(
                "asj_verify byte-parity SKIPPED: BAM/.bai/calls absent ({bam_path} / {bai} / {}). \
                 Present in dev; run there to exercise this test.",
                calls_tsv.display()
            );
            return;
        }

        let engine = AsjVerifyEngine::open(bam_path).expect("open AsjVerifyEngine");
        let calls_text = std::fs::read_to_string(&calls_tsv).expect("read asj_calls.tsv");
        let calls = parse_calls(&calls_text).expect("parse asj_calls.tsv");
        assert_eq!(calls.len(), fx["n_calls"].as_u64().unwrap() as usize, "call count vs fixture");

        // ---- per unique anchor: frac_mq0 bits + string ----
        let exp_anchors = fx["anchors"].as_array().expect("anchors array");
        let mut seen: std::collections::HashSet<(String, i64)> = std::collections::HashSet::new();
        let mut capped_seen = 0usize;
        for a in exp_anchors {
            let chrom = a["chrom"].as_str().unwrap();
            let anchor = a["anchor"].as_i64().unwrap();
            let got = engine.frac_mq0_at(chrom, anchor).expect("frac_mq0_at");
            let want_bits = hex_le_to_bits(a["frac_mq0_bits"].as_str().unwrap());
            assert_eq!(
                got.to_bits(),
                want_bits,
                "anchor {chrom}:{anchor} frac bits rust={:#018x} ({got}) python={want_bits:#018x} ({})",
                got.to_bits(),
                f64::from_bits(want_bits),
            );
            assert_eq!(py_float_str(got), a["frac_mq0_str"].as_str().unwrap(), "anchor {chrom}:{anchor} frac str");
            seen.insert((chrom.to_string(), anchor));
            if a["capped"].as_bool().unwrap_or(false) {
                capped_seen += 1;
            }
        }
        assert_eq!(seen.len(), fx["n_unique_anchors"].as_u64().unwrap() as usize, "unique anchor count");
        assert_eq!(capped_seen, fx["cap_600_hit_count"].as_u64().unwrap() as usize, "600-cap hit count");

        // ---- full driver: every call's dist / high_confidence / written line ----
        let rows = engine.run(&calls).expect("engine.run");
        let exp_calls = fx["calls"].as_array().expect("calls array");
        assert_eq!(rows.len(), exp_calls.len(), "row/fixture length");
        let mut n_hc = 0usize;
        for (i, (r, exp)) in rows.iter().zip(exp_calls).enumerate() {
            assert_eq!(r.dist, exp["dist"].as_i64().unwrap(), "call {i}: dist");
            let want_bits = hex_le_to_bits(exp["frac_mq0_bits"].as_str().unwrap());
            assert_eq!(r.frac_mq0.to_bits(), want_bits, "call {i}: frac_mq0 bits");
            assert_eq!(
                r.high_confidence as i64,
                exp["high_confidence"].as_i64().unwrap(),
                "call {i}: high_confidence"
            );
            assert_eq!(r.line, exp["verified_line"].as_str().unwrap(), "call {i}: verified line text");
            if r.high_confidence {
                n_hc += 1;
            }
        }
        assert_eq!(n_hc, fx["n_high_confidence"].as_u64().unwrap() as usize, "high_confidence tally");

        // Full-file text parity: header + all rows == the shipped Python output.
        let mut whole = String::from(VERIFIED_HEADER);
        whole.push('\n');
        for r in &rows {
            whole.push_str(&r.line);
            whole.push('\n');
        }
        assert_eq!(VERIFIED_HEADER, fx["verified_header"].as_str().unwrap(), "verified header");

        eprintln!(
            "asj_verify byte-parity: {} calls / {} unique anchors ({} hit the 600-cap); \
             frac_mq0 BIT-EXACT + str exact, dist exact, high_confidence exact ({n_hc} HC), \
             written line text EXACT vs Python.",
            calls.len(),
            seen.len(),
            capped_seen,
        );
    }
}
