//! O3 ASJ ANALYSIS layer: the StrandOddsRatio (SOR) strand-bias filter.
//!
//! Faithful Rust port of `bench/asj_strand_bias.py`. The O3 ASJ *core* (calling the
//! allele-specific junctions themselves) already lives in
//! [`super::allele_specific_junctions`]; this module ports the analysis layer that runs
//! ON TOP of the shipped `asj_calls.tsv`: for every ASJ call it re-fetches the reads that
//! SPAN the junction, splits them by (junction-usage x strand) into a 2x2 table, and
//! computes the GATK StrandOddsRatio. A junction "used" only by reads from one strand is a
//! hallmark of an alignment artifact rather than a true splice choice (longcallR, Nat
//! Methods 2026, rejects allele-specific junctions with `SOR >= 2`).
//!
//! ## What is ported (Python = ground truth)
//!  * [`introns`] (`bench/asj_strand_bias.py:58`): CIGAR-derived intron chain — one
//!    `(rpos, rpos+len)` per `N` op, with `M/D/=/X` consuming reference and `I/S/H/P` not.
//!  * [`strand_table`] (`:70`): fetch every read spanning `(donor, acceptor)`, skip
//!    unmapped/secondary/supplementary/no-CIGAR, require SPAN
//!    (`reference_start <= donor && reference_end >= acceptor`), and tally
//!    `(r_fwd, r_rev, a_fwd, a_rev) = (used+, used-, notused+, notused-)` RAW.
//!  * [`sor`] (`:98`): GATK SOR with a `+1` pseudocount — a PURE float function, ported
//!    bit-for-bit (`f64::ln == math.log` on Linux libm, verified in prior ports).
//!  * [`fisher_strand_p`] (`:111`): the Fisher-exact strand-bias p (a NON-gate cross-check
//!    column), computed by REUSING [`super::allele_specific_junctions::fisher_exact_2x2`]
//!    (scipy two-sided convention; matches scipy to ~4e-13 — see the byte-parity test).
//!  * [`StrandBiasEngine::run`] / [`compute_row`](StrandBiasEngine::compute_row)
//!    (`main`, `:120`): per-row donor/acceptor normalisation (swap if `donor > acceptor`),
//!    the chrom-not-in-refs -> `NaN` branch, and `sor_pass = !sor.is_nan() && sor < SOR_KEEP`.
//!
//! ## The gate is exact; fisher is a tolerance-matched cross-check
//! `sor` / `sor_pass` are the ACTUAL gate and are asserted BIT-EXACT against the shipped
//! Python build. `fisher_strand_p` is an advisory cross-check only; the reused
//! `fisher_exact_2x2` uses a Lanczos `ln Γ` approximation (not libm), so it agrees with
//! scipy to ~1e-12 rather than bit-for-bit. This is disclosed and the parity test asserts
//! the tolerance relationship (never the raw bits) for fisher.
//!
//! Byte-parity is enforced against `testdata/asj_strand_bias_fixture.json` (generated by
//! `bench/gen_asj_strand_bias_fixture.py`, PYTHONHASHSEED=0, over the real `GGO_mm.bam`)
//! by the `#[test]` below, which re-fetches the live BAM and recomputes every column.

use std::collections::HashSet;
use std::path::Path;

use anyhow::{Context, Result};
use noodles_sam::alignment::record::cigar::op::Kind;
use noodles_sam::alignment::record::Cigar as _;
use noodles_sam::alignment::RecordBuf;

/// GATK SNV hard-filter cutoff: KEEP if `SOR < 3.0`. Python
/// `bench/asj_strand_bias.py:53  SOR_KEEP = 3.0`.
pub const SOR_KEEP: f64 = 3.0;

/// longcallR junction REJECT threshold (stricter cross-check): KEEP if `SOR < 2.0`.
/// Python `bench/asj_strand_bias.py:54  SOR_STRICT = 2.0`.
pub const SOR_STRICT: f64 = 2.0;

/// Default multimapping genome BAM (the strand-table read source). Python
/// `bench/asj_strand_bias.py:52
/// DEFAULT_BAM = "/home/juanfra/winloci_scratch/GGO_mm.bam"`.
pub const DEFAULT_BAM: &str = "/home/juanfra/winloci_scratch/GGO_mm.bam";

/// Input ASJ-calls TSV basename (in `bench/`). Python
/// `bench/asj_strand_bias.py:50  IN_TSV = os.path.join(HERE, "asj_calls.tsv")`.
pub const IN_TSV_BASENAME: &str = "asj_calls.tsv";

/// Output augmented-calls TSV basename. Python
/// `bench/asj_strand_bias.py:51  OUT_TSV = os.path.join(HERE, "asj_calls_strandbias.tsv")`.
pub const OUT_TSV_BASENAME: &str = "asj_calls_strandbias.tsv";

// ===========================================================================
// introns  (bench/asj_strand_bias.py:58)
// ===========================================================================

/// CIGAR-derived intron chain (0-based reference coords of each `N` block) for an aligned
/// read. Faithful port of `bench/asj_strand_bias.py::introns`.
///
/// `rpos` starts at `reference_start` (0-based = `alignment_start - 1`). For each op:
/// `N`(Skip) appends `(rpos, rpos+len)` then advances `rpos`; `M/D/=/X`
/// (Match/Deletion/SequenceMatch/SequenceMismatch) advance `rpos`; `I/S/H/P`
/// (Insertion/SoftClip/HardClip/Pad) do NOT consume reference. A record with no
/// alignment start yields an empty chain (never reached for the mapped reads this scans).
pub fn introns(rb: &RecordBuf) -> Vec<(i64, i64)> {
    let ref_start = match rb.alignment_start() {
        Some(s) => s.get() as i64 - 1,
        None => return Vec::new(),
    };
    let mut out: Vec<(i64, i64)> = Vec::new();
    let mut rpos = ref_start;
    for op in rb.cigar().as_ref().iter() {
        let len = op.len() as i64;
        match op.kind() {
            Kind::Skip => {
                out.push((rpos, rpos + len)); // N: intron
                rpos += len;
            }
            Kind::Match | Kind::Deletion | Kind::SequenceMatch | Kind::SequenceMismatch => {
                rpos += len; // M/D/=/X consume reference
            }
            // I(Insertion) / S(SoftClip) / H(HardClip) / P(Pad): no reference consumed.
            Kind::Insertion | Kind::SoftClip | Kind::HardClip | Kind::Pad => {}
        }
    }
    out
}

// ===========================================================================
// strand_table  (bench/asj_strand_bias.py:70)
// ===========================================================================

/// 2x2 strand-by-junction-usage counts over reads spanning `(donor, acceptor)`.
/// Returns `(r_fwd, r_rev, a_fwd, a_rev) = (used+, used-, notused+, notused-)` RAW (no
/// pseudocount). Faithful port of `bench/asj_strand_bias.py::strand_table`.
///
/// `donor`/`acceptor` must already be NORMALISED (`donor <= acceptor`; the caller swaps).
/// The read set is the indexed query over `[donor, acceptor+1)` — pysam
/// `fetch(chrom, donor, acceptor + 1)` (0-based half-open) == the 1-based inclusive region
/// `{chrom}:{donor+1}-{acceptor+1}`. Both return exactly the reads whose alignment overlaps
/// that interval, so re-applying the identical Python post-filter yields identical counts.
///
/// Per read (Python lines 79-94):
///  1. skip `is_unmapped` (0x4) / `is_secondary` (0x100) / `is_supplementary` (0x800) /
///     no-CIGAR (`cigartuples is None`);
///  2. require SPAN: `reference_start <= donor && reference_end >= acceptor`, where
///     `reference_end = reference_start + cigar reference-span` (sum of `M/D/N/=/X`),
///     exactly pysam's `reference_end`;
///  3. `used = (donor, acceptor) in introns(read)`; `rev = is_reverse` (flag 0x10 =
///     noodles `is_reverse_complemented`);
///  4. tally into `(used, rev)` -> one of `r_fwd/r_rev/a_fwd/a_rev`.
///
/// Opens a fresh reader per call (cheap) and uses the caller-cached `header`/`index`
/// (parsing the multi-MB `.bai` once), matching [`super::denovo_assemble::BamIndexCache`].
pub fn strand_table(
    bam_path: &str,
    header: &noodles_sam::Header,
    index: &noodles_bam::bai::Index,
    chrom: &str,
    donor: i64,
    acceptor: i64,
) -> Result<(i64, i64, i64, i64)> {
    let mut reader = noodles_bam::io::reader::Builder::default().build_from_path(bam_path)?;
    // pysam fetch(chrom, donor, acceptor+1) 0-based half-open == 1-based inclusive [donor+1, acceptor+1].
    let region: noodles_core::Region =
        format!("{chrom}:{}-{}", donor + 1, acceptor + 1).parse()?;
    let query = reader.query(header, index, &region)?;

    let (mut r_fwd, mut r_rev, mut a_fwd, mut a_rev) = (0i64, 0i64, 0i64, 0i64);
    for result in query {
        let record = result?;
        let rb = RecordBuf::try_from_alignment_record(header, &record)?;

        let flags = rb.flags();
        if flags.is_unmapped() || flags.is_secondary() || flags.is_supplementary() {
            continue;
        }
        // cigartuples is None -> skip (an empty CIGAR record).
        let cigar = rb.cigar();
        if cigar.as_ref().is_empty() {
            continue;
        }
        let Some(start) = rb.alignment_start() else {
            continue;
        };
        let ref_start = start.get() as i64 - 1;
        let span = cigar.alignment_span() as i64;
        if span == 0 {
            // pysam reference_end is None here; such a read is never returned by fetch
            // (it has no reference overlap) -> skip defensively (cannot affect parity).
            continue;
        }
        let ref_end = ref_start + span;
        // SPAN the junction: reference_start <= donor AND reference_end >= acceptor.
        if ref_start > donor || ref_end < acceptor {
            continue;
        }
        let used = introns(&rb).iter().any(|&(s, e)| s == donor && e == acceptor);
        let rev = flags.is_reverse_complemented(); // flag 0x10 == pysam is_reverse
        match (used, rev) {
            (true, false) => r_fwd += 1,
            (true, true) => r_rev += 1,
            (false, false) => a_fwd += 1,
            (false, true) => a_rev += 1,
        }
    }
    Ok((r_fwd, r_rev, a_fwd, a_rev))
}

// ===========================================================================
// sor  (bench/asj_strand_bias.py:98) — PURE float, bit-exact
// ===========================================================================

/// GATK StrandOddsRatio with a `+1` pseudocount on every cell. Faithful, bit-exact port of
/// `bench/asj_strand_bias.py::sor`:
/// ```text
/// rp,rm,ap,am = r_fwd+1, r_rev+1, a_fwd+1, a_rev+1
/// ratio     = (rp*am) / (ap*rm)
/// sym       = ratio + 1/ratio
/// ref_ratio = min(rp,rm) / max(rp,rm)
/// alt_ratio = min(ap,am) / max(ap,am)
/// SOR       = ln(sym) + ln(ref_ratio) - ln(alt_ratio)
/// ```
/// Every operation (`+`, `*`, `/`, `min`, `max`, `ln`) is a bit-exact IEEE-754 f64 op with
/// identical evaluation order to CPython, so the returned `f64` matches `math.log`-based
/// Python bit-for-bit (the gate depends on this).
pub fn sor(r_fwd: i64, r_rev: i64, a_fwd: i64, a_rev: i64) -> f64 {
    let rp = r_fwd as f64 + 1.0;
    let rm = r_rev as f64 + 1.0;
    let ap = a_fwd as f64 + 1.0;
    let am = a_rev as f64 + 1.0;
    let ratio = (rp * am) / (ap * rm);
    let sym = ratio + 1.0 / ratio;
    let ref_ratio = rp.min(rm) / rp.max(rm);
    let alt_ratio = ap.min(am) / ap.max(am);
    sym.ln() + ref_ratio.ln() - alt_ratio.ln()
}

// ===========================================================================
// fisher_strand_p  (bench/asj_strand_bias.py:111) — NON-gate cross-check
// ===========================================================================

/// Fisher-exact strand-bias p over the raw 2x2 `[[r_fwd, r_rev], [a_fwd, a_rev]]` — a
/// cross-check column, NOT the gate. Port of `bench/asj_strand_bias.py::fisher_strand_p`.
///
/// REUSES [`super::allele_specific_junctions::fisher_exact_2x2`], which implements scipy's
/// two-sided convention (sum the hypergeometric probabilities of all same-margin tables no
/// more likely than observed). It matches `scipy.stats.fisher_exact` to ~4e-13 across the
/// real calls (measured; see the fixture's `max_fisher_div_vs_rust_replica`), NOT
/// bit-for-bit — it uses a Lanczos `ln Γ` rather than libm. scipy never raises for these
/// non-negative tables (degenerate/all-zero margins -> `1.0`), so this never returns `NaN`;
/// the only `NaN` fisher arises in the chrom-not-in-refs branch handled by the driver.
pub fn fisher_strand_p(r_fwd: i64, r_rev: i64, a_fwd: i64, a_rev: i64) -> f64 {
    super::allele_specific_junctions::fisher_exact_2x2(
        r_fwd as u32,
        r_rev as u32,
        a_fwd as u32,
        a_rev as u32,
    )
}

// ===========================================================================
// driver  (bench/asj_strand_bias.py::main, :120)
// ===========================================================================

/// One parsed ASJ-call row (only the columns the SOR filter needs). The full input header
/// is preserved verbatim by the TSV writer in Python; this port carries only what the
/// per-row computation reads (`chrom`, `donor`, `acceptor`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CallRow {
    /// Chromosome / contig name.
    pub chrom: String,
    /// RAW donor coordinate as written in the TSV (may be `> acceptor`; normalised later).
    pub donor: i64,
    /// RAW acceptor coordinate as written in the TSV.
    pub acceptor: i64,
}

/// The strand-bias result for one call: the augmented columns Python appends
/// (`R_fwd,R_rev,A_fwd,A_rev,sor,fisher_strand_p,sor_pass`) plus the NORMALISED junction.
#[derive(Clone, Debug)]
pub struct StrandBiasRow {
    /// Chromosome / contig name (echoed from the input).
    pub chrom: String,
    /// Normalised donor (`min(raw_donor, raw_acceptor)`).
    pub donor: i64,
    /// Normalised acceptor (`max(raw_donor, raw_acceptor)`).
    pub acceptor: i64,
    /// `R_fwd = used & forward` count.
    pub r_fwd: i64,
    /// `R_rev = used & reverse` count.
    pub r_rev: i64,
    /// `A_fwd = notused & forward` count.
    pub a_fwd: i64,
    /// `A_rev = notused & reverse` count.
    pub a_rev: i64,
    /// StrandOddsRatio; `NaN` when `chrom` is not in the BAM references.
    pub sor: f64,
    /// Fisher strand-bias p (cross-check); `NaN` when `chrom` is not in the BAM references.
    pub fisher_strand_p: f64,
    /// `!sor.is_nan() && sor < SOR_KEEP` — the actual keep decision.
    pub sor_pass: bool,
}

/// Parse the ASJ-calls TSV text into [`CallRow`]s. Faithful to
/// `bench/asj_strand_bias.py::main` (`hdr = split header; rows = dict(zip(hdr, split))`
/// for each non-blank line): the header names the columns, and only `chrom`/`donor`/
/// `acceptor` are read. Blank lines are skipped (Python `if line.strip()`).
pub fn parse_calls(text: &str) -> Result<Vec<CallRow>> {
    let mut lines = text.lines();
    let hdr_line = lines.next().context("empty ASJ-calls TSV (no header)")?;
    let hdr: Vec<&str> = hdr_line.split('\t').collect();
    let col = |name: &str| -> Result<usize> {
        hdr.iter()
            .position(|&c| c == name)
            .with_context(|| format!("ASJ-calls header missing column {name:?}"))
    };
    let (c_chrom, c_donor, c_acceptor) = (col("chrom")?, col("donor")?, col("acceptor")?);

    let mut out = Vec::new();
    for line in lines {
        if line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        out.push(CallRow {
            chrom: f[c_chrom].to_string(),
            donor: f[c_donor].parse().with_context(|| format!("donor int in {line:?}"))?,
            acceptor: f[c_acceptor]
                .parse()
                .with_context(|| format!("acceptor int in {line:?}"))?,
        });
    }
    Ok(out)
}

/// A reusable strand-bias engine: parses the `.bai` index + header ONCE (like
/// [`super::denovo_assemble::BamIndexCache`]) and caches the BAM reference-name set for the
/// chrom-not-in-refs test, so a whole calls file is processed with one index parse.
pub struct StrandBiasEngine {
    bam_path: String,
    header: noodles_sam::Header,
    index: noodles_bam::bai::Index,
    refs: HashSet<String>,
}

impl StrandBiasEngine {
    /// Open `{bam_path}` and parse its header + `{bam_path}.bai`. Errors (so the caller /
    /// test can skip) when the index is missing.
    pub fn open(bam_path: &str) -> Result<Self> {
        let bai_path = format!("{bam_path}.bai");
        anyhow::ensure!(
            Path::new(&bai_path).exists(),
            "StrandBiasEngine needs a .bai index next to {bam_path} (expected {bai_path})"
        );
        let mut reader = noodles_bam::io::reader::Builder::default().build_from_path(bam_path)?;
        let header = reader.read_header()?;
        let index = noodles_bam::bai::read(&bai_path)?;
        let refs: HashSet<String> = header
            .reference_sequences()
            .iter()
            .map(|(name, _)| format!("{name}"))
            .collect();
        Ok(Self { bam_path: bam_path.to_string(), header, index, refs })
    }

    /// Compute the strand-bias columns for ONE call from its RAW (pre-normalise) coords,
    /// replicating `main`'s per-row body: normalise (swap if `donor > acceptor`), take the
    /// chrom-not-in-refs -> all-zero + `NaN` branch, else `strand_table` + `sor` + fisher,
    /// then `sor_pass = !sor.is_nan() && sor < SOR_KEEP`.
    pub fn compute_row(&self, chrom: &str, donor_raw: i64, acceptor_raw: i64) -> Result<StrandBiasRow> {
        let (donor, acceptor) = if donor_raw > acceptor_raw {
            (acceptor_raw, donor_raw)
        } else {
            (donor_raw, acceptor_raw)
        };
        let (r_fwd, r_rev, a_fwd, a_rev, sor_v, fisher);
        if !self.refs.contains(chrom) {
            r_fwd = 0;
            r_rev = 0;
            a_fwd = 0;
            a_rev = 0;
            sor_v = f64::NAN;
            fisher = f64::NAN;
        } else {
            let (rf, rr, af, ar) =
                strand_table(&self.bam_path, &self.header, &self.index, chrom, donor, acceptor)?;
            r_fwd = rf;
            r_rev = rr;
            a_fwd = af;
            a_rev = ar;
            sor_v = sor(rf, rr, af, ar);
            fisher = fisher_strand_p(rf, rr, af, ar);
        }
        let sor_pass = !sor_v.is_nan() && sor_v < SOR_KEEP;
        Ok(StrandBiasRow {
            chrom: chrom.to_string(),
            donor,
            acceptor,
            r_fwd,
            r_rev,
            a_fwd,
            a_rev,
            sor: sor_v,
            fisher_strand_p: fisher,
            sor_pass,
        })
    }

    /// Run the filter over every parsed call, in file order (Python's row loop).
    pub fn run(&self, calls: &[CallRow]) -> Result<Vec<StrandBiasRow>> {
        calls
            .iter()
            .map(|c| self.compute_row(&c.chrom, c.donor, c.acceptor))
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;
    use std::path::PathBuf;

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/asj_strand_bias_fixture.json");
        serde_json::from_str(raw).expect("parse asj_strand_bias fixture json")
    }

    /// Little-endian IEEE-754 hex (`struct.pack("<d", x).hex()`) -> the f64 bit pattern.
    fn hex_le_to_bits(s: &str) -> u64 {
        assert_eq!(s.len(), 16, "expected 16 hex chars, got {s:?}");
        let mut b = [0u8; 8];
        for (i, byte) in b.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("hex byte");
        }
        u64::from_le_bytes(b)
    }

    /// Fisher is a NON-gate cross-check: the reused `fisher_exact_2x2` uses a Lanczos
    /// `ln Γ`, agreeing with scipy to ~4e-13 (fixture `max_fisher_div_vs_rust_replica`).
    /// Assert the tolerance relationship, never the raw bits.
    const FISHER_TOL: f64 = 1e-9;

    fn assert_row_matches(got: &StrandBiasRow, exp: &Value, label: &str) {
        // ---- normalised junction ----
        assert_eq!(got.donor, exp["donor"].as_i64().unwrap(), "{label}: donor");
        assert_eq!(got.acceptor, exp["acceptor"].as_i64().unwrap(), "{label}: acceptor");
        // ---- raw R/A integer counts (exact) ----
        assert_eq!(got.r_fwd, exp["R_fwd"].as_i64().unwrap(), "{label}: R_fwd");
        assert_eq!(got.r_rev, exp["R_rev"].as_i64().unwrap(), "{label}: R_rev");
        assert_eq!(got.a_fwd, exp["A_fwd"].as_i64().unwrap(), "{label}: A_fwd");
        assert_eq!(got.a_rev, exp["A_rev"].as_i64().unwrap(), "{label}: A_rev");
        // ---- sor: BIT-EXACT (the gate) ----
        if exp["sor_is_nan"].as_bool().unwrap() {
            assert!(got.sor.is_nan(), "{label}: sor expected NaN, got {}", got.sor);
        } else {
            let want = hex_le_to_bits(exp["sor_bits"].as_str().unwrap());
            assert_eq!(
                got.sor.to_bits(),
                want,
                "{label}: sor bits rust={:#018x} ({}) python={want:#018x} ({})",
                got.sor.to_bits(),
                got.sor,
                f64::from_bits(want),
            );
        }
        // ---- fisher: NON-gate cross-check, tolerance match ----
        if exp["fisher_is_nan"].as_bool().unwrap() {
            assert!(got.fisher_strand_p.is_nan(), "{label}: fisher expected NaN");
        } else {
            let want = f64::from_bits(hex_le_to_bits(exp["fisher_bits"].as_str().unwrap()));
            assert!(
                (got.fisher_strand_p - want).abs() < FISHER_TOL,
                "{label}: fisher rust={} scipy={} |diff|={:.3e} >= {FISHER_TOL:.0e}",
                got.fisher_strand_p,
                want,
                (got.fisher_strand_p - want).abs()
            );
        }
        // ---- sor_pass: EXACT ----
        assert_eq!(got.sor_pass, exp["sor_pass"].as_bool().unwrap(), "{label}: sor_pass");
    }

    /// Live byte-parity over GGO_mm.bam: constants agree; every real + synthetic call's
    /// R/A ints + sor bits + sor_pass match Python EXACTLY, fisher within tolerance.
    /// Skips-with-message (does NOT fail) if the multi-GB BAM / its `.bai` / the calls TSV
    /// is absent, so CI without them is green; all three ARE present in dev.
    #[test]
    #[ignore = "reads the 11 GB GGO_mm.bam (opens a fresh reader per call, ~460s); run on demand via \
                `cargo test --release -- --ignored asj_strand_bias_byte_parity`. The fast, always-on \
                sor_pure_bit_exact_spot below covers the SOR math (475/475 bit-exact) without the BAM."]
    fn asj_strand_bias_byte_parity() {
        let fx = load_fixture();

        // Constant agreement with the Python.
        assert_eq!(SOR_KEEP, fx["sor_keep"].as_f64().unwrap(), "SOR_KEEP disagrees");
        assert_eq!(SOR_STRICT, fx["sor_strict"].as_f64().unwrap(), "SOR_STRICT disagrees");
        assert_eq!(
            DEFAULT_BAM,
            fx["bam_path"].as_str().unwrap(),
            "DEFAULT_BAM disagrees with Python"
        );

        let bam_path = fx["bam_path"].as_str().unwrap();
        let bai = format!("{bam_path}.bai");
        let calls_tsv = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bench").join(IN_TSV_BASENAME);
        if !Path::new(bam_path).exists() || !Path::new(&bai).exists() || !calls_tsv.exists() {
            eprintln!(
                "asj_strand_bias byte-parity SKIPPED: BAM/.bai/calls absent \
                 ({bam_path} / {bai} / {}). Present in dev; run there to exercise this test.",
                calls_tsv.display()
            );
            return;
        }

        // Reused fisher_exact_2x2 really tracks scipy (fixture-measured divergence tiny).
        let measured_div = fx["max_fisher_div_vs_rust_replica"].as_f64().unwrap();
        assert!(
            measured_div < FISHER_TOL,
            "measured scipy-vs-Rust fisher divergence {measured_div:.3e} exceeds tolerance"
        );

        let engine = StrandBiasEngine::open(bam_path).expect("open StrandBiasEngine");
        let calls_text = std::fs::read_to_string(&calls_tsv).expect("read asj_calls.tsv");
        let calls = parse_calls(&calls_text).expect("parse asj_calls.tsv");

        let exp_calls = fx["calls"].as_array().expect("calls array");
        assert_eq!(
            calls.len(),
            fx["n_calls"].as_u64().unwrap() as usize,
            "parsed call count disagrees with fixture"
        );
        assert_eq!(calls.len(), exp_calls.len(), "call/fixture length mismatch");

        // ---- every real call ----
        let mut n_zero_used = 0usize;
        let mut n_high_sor = 0usize;
        let mut n_pass3 = 0usize;
        for (i, (c, exp)) in calls.iter().zip(exp_calls).enumerate() {
            // input coords must match the fixture's recorded raw coords (same TSV).
            assert_eq!(c.donor, exp["donor_raw"].as_i64().unwrap(), "call {i}: donor_raw");
            assert_eq!(c.acceptor, exp["acceptor_raw"].as_i64().unwrap(), "call {i}: acceptor_raw");
            assert_eq!(c.chrom, exp["chrom"].as_str().unwrap(), "call {i}: chrom");

            let got = engine.compute_row(&c.chrom, c.donor, c.acceptor).expect("compute_row");
            assert_row_matches(&got, exp, &format!("call {i} ({})", c.chrom));

            if (got.r_fwd + got.r_rev) == 0 {
                n_zero_used += 1;
            }
            if !got.sor.is_nan() && got.sor >= SOR_KEEP {
                n_high_sor += 1;
            }
            if got.sor_pass {
                n_pass3 += 1;
            }
        }

        // Tally agreement with the Python driver (n_keep_3 / n_zero_used / n_high_sor).
        let stats = &fx["stats"];
        assert_eq!(n_pass3, stats["n_keep_3"].as_u64().unwrap() as usize, "n_keep_3");
        assert_eq!(n_zero_used, stats["n_zero_used"].as_u64().unwrap() as usize, "n_zero_used");
        assert_eq!(n_high_sor, stats["n_high_sor"].as_u64().unwrap() as usize, "n_high_sor");
        // Coverage the fixture must exercise.
        assert!(n_zero_used >= 1, "fixture should cover >=1 zero-used call");
        assert!(n_high_sor >= 1, "fixture should cover >=1 high-SOR (fail) call");

        // ---- synthetic edge cases (NaN branch + donor/acceptor swap) ----
        let synth = fx["synthetic"].as_array().expect("synthetic array");
        assert!(synth.len() >= 2, "expected >=2 synthetic edge rows");
        let mut saw_nan = false;
        let mut saw_swap = false;
        for exp in synth {
            let chrom = exp["chrom"].as_str().unwrap();
            let dr = exp["donor_raw"].as_i64().unwrap();
            let ar = exp["acceptor_raw"].as_i64().unwrap();
            let note = exp["note"].as_str().unwrap_or("");
            let got = engine.compute_row(chrom, dr, ar).expect("compute_row synthetic");
            assert_row_matches(&got, exp, &format!("synthetic[{note}]"));
            if exp["sor_is_nan"].as_bool().unwrap() {
                assert!(got.sor.is_nan() && got.fisher_strand_p.is_nan(), "NaN synthetic");
                saw_nan = true;
            }
            if note == "swapped_donor_acceptor" {
                // donor_raw > acceptor_raw must normalise to donor < acceptor.
                assert!(dr > ar, "swap fixture must have donor_raw > acceptor_raw");
                assert!(got.donor < got.acceptor, "normalise must order donor < acceptor");
                saw_swap = true;
            }
        }
        assert!(saw_nan, "synthetic must cover the chrom-not-in-refs NaN branch");
        assert!(saw_swap, "synthetic must cover the donor/acceptor swap branch");

        eprintln!(
            "asj_strand_bias byte-parity: {} real + {} synthetic calls; \
             sor BIT-EXACT, sor_pass EXACT, fisher within {:.0e} (measured {:.1e}); \
             n_keep3={n_pass3} n_zero_used={n_zero_used} n_high_sor={n_high_sor}",
            calls.len(),
            synth.len(),
            FISHER_TOL,
            measured_div,
        );
    }

    /// `sor` is a pure float: spot-check a few tables against the fixture bits WITHOUT the
    /// BAM (always runs, even in CI), pinning the bit-exactness of the gate arithmetic.
    #[test]
    fn sor_pure_bit_exact_spot() {
        let fx = load_fixture();
        let calls = fx["calls"].as_array().unwrap();
        let mut checked = 0usize;
        for exp in calls {
            if exp["sor_is_nan"].as_bool().unwrap() {
                continue;
            }
            let s = sor(
                exp["R_fwd"].as_i64().unwrap(),
                exp["R_rev"].as_i64().unwrap(),
                exp["A_fwd"].as_i64().unwrap(),
                exp["A_rev"].as_i64().unwrap(),
            );
            let want = hex_le_to_bits(exp["sor_bits"].as_str().unwrap());
            assert_eq!(
                s.to_bits(),
                want,
                "sor({},{},{},{}) bits rust={:#018x} python={want:#018x}",
                exp["R_fwd"], exp["R_rev"], exp["A_fwd"], exp["A_rev"],
                s.to_bits(),
            );
            checked += 1;
        }
        assert!(checked >= 400, "expected >=400 pure-sor checks, got {checked}");
        eprintln!("sor pure bit-exact: {checked} tables match Python math.log SOR bit-for-bit");
    }
}
