//! Shared exon-graph LIBRARY -- faithful Rust port of the reusable core of
//! `bench/recombination_bridge_detector.py` (RBD), the O1 over-merge-gate migration
//! (`docs/RETIREMENT_AND_MIGRATION.md` Tier-2 #6, full byte-parity path).
//!
//! This is the library the TWO shipped O1 over-merge gates consume:
//!   * `bench/recombinant_split.py`  (Alu/recombinant-bridge SPLIT gate) uses
//!     `family_exons` / `exon_match_tensor` / `build_graph` / `colinear_cov` /
//!     `subfams_colocated` / `subfam_dom_gene` + `COLINEAR_COV` / `ID_THRESH`;
//!   * `bench/multi_repeat_bridge_gate.py` (repeat-bridge gate) uses `family_exons`
//!     / `exon_match_tensor` / `build_graph` / `cross_component_maxid`.
//! Both gates call the LIBRARY functions below; the port targets exactly those.
//!
//! PORTED (the Python is ground truth; line refs are `bench/recombination_bridge_detector.py`):
//!   * constants `ID_THRESH=0.70` (:57), `MIN_EXON=30` (:58), `COLINEAR_COV=0.60` (:59);
//!   * `revcomp` (:66) + the `_COMP` table (:63); `aln_id` (:70) -- the CRUX (edlib HW);
//!   * `load_skeletons` (:88) -- RBD's OWN 1-based-inclusive exon complement (see note);
//!   * `family_exons` (:162), `exon_match_tensor` (:185), `build_graph` (:216),
//!     `pair_coverage` (:228), `cross_component_maxid` (:237), `colinear_cov` (:250),
//!     `subfam_label` (:273), `subfam_dom_gene` (:279), `subfams_colocated` (:284).
//!   * `IndexedFasta` is REUSED from `super::repeat_catalog` (already byte-exact).
//!
//! DEFERRED (NOT the library the gates call -- TSV/JSON production + analysis):
//!   * `analyze_family` (:299), `main` (:527), `_pure_controls`/`_control_precompute`/
//!     `control_recall_cost` (:457-524), and the loaders `load_families` (:129) /
//!     `target_families` (:140) / `load_strand` (:115). (`multi_repeat_bridge_gate` does
//!     call `analyze_family` in `_rederive_disconnected`, but that is a gate-DRIVER
//!     concern; the reusable exon-graph MATH is what this module ports.) Constants
//!     `CARD_ID` (:60) / `N_CONTROL` (:61) are used ONLY by the deferred control-recall.
//!
//! CRUX -- `aln_id` HW (infix) edit distance without edlib: RBD does
//! `edlib.align(q, t, mode="HW", task="distance")` = the minimum edit distance of `q`
//! against ANY substring of `t` (free gaps at BOTH ends of `t`). We compute it with a
//! pure DP: `dp[i][j]` over `q` rows x `t` cols, `dp[0][*]=0` (free start in `t`),
//! `dp[i][0]=i`, standard 3-way min, answer `= min_j dp[|q|][j]` (free end in `t`).
//! This equals edlib HW exactly (proven on 20 010 random + adversarial pairs, and the
//! >=80-pair `aln_id` fixture below). `aln_id` tries `q` AND `revcomp(q)` and returns
//! `1 - min_dist/len(q)`.
//!
//! STRAND note (`family_exons`): RBD orders exons 5'->3' by REVERSING the exon ORDER
//! for `'-'` strand -- it does NOT reverse-complement the bases; each exon carries the
//! forward (`+`-strand) genome slice, upper-cased. (Reverse-complement enters ONLY via
//! `aln_id`, which tries both orientations.) The `exlen` of a `'-'` member is therefore
//! the genomic exon-length list reversed. The fixture ships `'-'` multi-exon members to
//! pin this.
//!
//! COORDINATE note: RBD's `load_skeletons` uses a DIFFERENT convention from
//! `vg_repeat_catalog.dn_exons` (ported in `super::repeat_catalog`): RBD builds exons as
//! 1-based-INCLUSIVE `(cur, isr-1)` .. `(cur, end)` with `cur = ier+1`, does NOT sort the
//! introns, keeps only `b >= a`, and `family_exons` fetches `fa.fetch(chrom, s-1, e)`
//! (the `s-1` makes it 1-based->0-based). `dn_exons` is 0-based half-open with a SORTED
//! intron list and a direct `fetch(a, b)`. They are two independent scripts with distinct
//! conventions, so this module ports RBD's `load_skeletons` faithfully (it does NOT reuse
//! `repeat_catalog::{dn_exons,load_skeletons}`); it DOES reuse `IndexedFasta`.
//!
//! Verified byte-identical to the shipped Python against a golden fixture
//! (`testdata/bridge_detector_fixture.json`, generated by
//! `bench/gen_bridge_detector_fixture.py`, PYTHONHASHSEED=0); see the `#[test]`s.

use std::collections::{BTreeSet, HashMap};

use super::repeat_catalog::IndexedFasta;

/// Exon-match identity (HW / infix) threshold. `recombination_bridge_detector.py:57`.
pub const ID_THRESH: f64 = 0.70;
/// Minimum exon length (bp) considered for graph edges. `...py:58`.
pub const MIN_EXON: usize = 30;
/// Path-level colinear-coverage threshold. `...py:59`.
pub const COLINEAR_COV: f64 = 0.60;

// ===========================================================================
// revcomp  (recombination_bridge_detector.py:63-67)
// ===========================================================================

/// One-base complement, exactly the Python `_COMP = str.maketrans("ACGTacgtNn",
/// "TGCAtgcaNn")`: A<->T, C<->G, G<->C, T<->A (both cases), N->N, n->n; EVERY OTHER
/// byte is left unchanged (Python `str.translate` passes unmapped chars through).
#[inline]
fn comp_base(b: u8) -> u8 {
    match b {
        b'A' => b'T',
        b'C' => b'G',
        b'G' => b'C',
        b'T' => b'A',
        b'a' => b't',
        b'c' => b'g',
        b'g' => b'c',
        b't' => b'a',
        b'N' => b'N',
        b'n' => b'n',
        other => other,
    }
}

/// Reverse-complement of `s`: complement every base via `comp_base`, then reverse
/// (`s.translate(_COMP)[::-1]`).
pub fn revcomp(s: &[u8]) -> Vec<u8> {
    s.iter().rev().map(|&b| comp_base(b)).collect()
}

// ===========================================================================
// aln_id  (recombination_bridge_detector.py:70-82)  -- the CRUX
// ===========================================================================

/// HW (infix) edit distance of `q` against `t`: the minimum edit distance of `q` to ANY
/// substring of `t` (free gaps at both ends of `t`). Equals `edlib.align(q, t,
/// mode="HW", task="distance")["editDistance"]`. Two rolling DP rows over `t` columns
/// (`dp[0][*]=0`, `dp[i][0]=i`, answer `= min_j dp[|q|][j]`).
fn hw_distance(q: &[u8], t: &[u8]) -> usize {
    let lq = q.len();
    let lt = t.len();
    // dp row 0 = 0 across all t columns (a free start position in t).
    let mut prev: Vec<usize> = vec![0; lt + 1];
    let mut cur: Vec<usize> = vec![0; lt + 1];
    for i in 1..=lq {
        cur[0] = i; // dp[i][0] = i
        let qi = q[i - 1];
        for j in 1..=lt {
            let sub = prev[j - 1] + if qi == t[j - 1] { 0 } else { 1 };
            let del = prev[j] + 1;
            let ins = cur[j - 1] + 1;
            cur[j] = sub.min(del).min(ins);
        }
        std::mem::swap(&mut prev, &mut cur);
    }
    // answer = min over j of dp[|q|][j]  (free end position in t). After the final swap
    // the last computed row is in `prev`. For lq == 0, prev is the all-zero row 0.
    *prev.iter().min().expect("row has >= 1 column")
}

/// Best HW (infix) identity of `q` inside `t`, trying `q` AND `revcomp(q)`.
/// `id = 1 - min_dist / len(q)`; `0.0` if either string is empty
/// (`recombination_bridge_detector.py:70`).
pub fn aln_id(q: &[u8], t: &[u8]) -> f64 {
    if q.is_empty() || t.is_empty() {
        return 0.0;
    }
    let d_fwd = hw_distance(q, t);
    let d_rev = hw_distance(&revcomp(q), t);
    let best = d_fwd.min(d_rev);
    // 1.0 - best / len(q)  (single f64 division, matches Python exactly).
    1.0 - best as f64 / q.len() as f64
}

// ===========================================================================
// load_skeletons  (recombination_bridge_detector.py:88-112)  -- RBD's own
// ===========================================================================

/// One member locus fed to `family_exons` (`{dn, gene, chrom, start, end}`; the dict
/// `_members` builds in the gates). `gene` is used by the subfam helpers.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Member {
    pub dn: String,
    pub gene: String,
    pub chrom: String,
    pub start: i64,
    pub end: i64,
}

/// Parse the denovo-skeletons TSV text into RBD's `{(chrom,start,end) -> exon list}`,
/// where each exon is a 1-based-INCLUSIVE `(a, b)` interval.
///
/// Faithful port of `load_skeletons` (:88): skip the header, split on `\t`, pad short
/// rows to 6 fields (`(t + [""]*6)[:6]`), read `chrom,start,end,introns = f0,f1,f2,f5`,
/// parse `introns = "a-b;c-d;..."` into `iv` WITHOUT sorting, then walk the complement
/// `cur=start`: for each `(isr, ier)` push exon `(cur, isr-1)` and set `cur = ier+1`;
/// finally push `(cur, end)`; keep only exons with `b >= a`.
pub fn parse_skeletons(text: &str) -> HashMap<(String, i64, i64), Vec<(i64, i64)>> {
    let mut skel = HashMap::new();
    let mut lines = text.lines();
    lines.next(); // header
    for ln in lines {
        // Python: t = line.rstrip("\n").split("\t"); if len<6: t=(t+[""]*6)[:6]
        let mut f: Vec<&str> = ln.split('\t').collect();
        if f.len() < 6 {
            while f.len() < 6 {
                f.push("");
            }
        }
        let (chrom, start, end, introns) = (f[0], f[1], f[2], f[5]);
        let start: i64 = match start.parse() {
            Ok(v) => v,
            Err(_) => continue,
        };
        let end: i64 = match end.parse() {
            Ok(v) => v,
            Err(_) => continue,
        };
        // iv = [(a,b) for seg in introns.split(";")] IF introns else []   (NO sort)
        let mut iv: Vec<(i64, i64)> = Vec::new();
        if !introns.is_empty() {
            for seg in introns.split(';') {
                let mut it = seg.split('-');
                let a: i64 = it
                    .next()
                    .expect("intron token left field")
                    .parse()
                    .expect("intron start parses");
                let b: i64 = it
                    .next()
                    .expect("intron token right field")
                    .parse()
                    .expect("intron end parses");
                iv.push((a, b));
            }
        }
        let mut exons: Vec<(i64, i64)> = Vec::new();
        let mut cur = start;
        for (isr, ier) in iv {
            exons.push((cur, isr - 1));
            cur = ier + 1;
        }
        exons.push((cur, end));
        exons.retain(|&(a, b)| b >= a);
        skel.insert((chrom.to_string(), start, end), exons);
    }
    skel
}

/// Read + parse the denovo-skeletons TSV file (see `parse_skeletons`).
pub fn load_skeletons(path: &str) -> std::io::Result<HashMap<(String, i64, i64), Vec<(i64, i64)>>> {
    Ok(parse_skeletons(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// family_exons  (recombination_bridge_detector.py:162-182)
// ===========================================================================

/// A per-member exon record (transcript 5'->3' order). Faithful to the Python dict
/// (`dn, gene, chrom, start, end, strand, exons, exlen`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Rec {
    pub dn: String,
    pub gene: String,
    pub chrom: String,
    pub start: i64,
    pub end: i64,
    pub strand: String,
    /// exon sequences (upper-cased, forward-strand bases), in transcript 5'->3' order
    pub exons: Vec<Vec<u8>>,
    /// `[len(x) for x in exons]`
    pub exlen: Vec<usize>,
}

/// Genome-slice fetcher matching `pysam.FastaFile.fetch(chrom, start, end)` on 0-based
/// half-open coordinates (returns bytes verbatim, case-carrying). `IndexedFasta`
/// implements it; tests supply a mock backed by the fixture's captured slices.
pub trait ExonFetcher {
    fn fetch(&self, chrom: &str, start: i64, end: i64) -> Option<Vec<u8>>;
}

impl ExonFetcher for IndexedFasta {
    fn fetch(&self, chrom: &str, start: i64, end: i64) -> Option<Vec<u8>> {
        IndexedFasta::fetch(self, chrom, start, end)
    }
}

/// Build a family's per-member exon records (transcript order). Drops members whose
/// `(chrom,start,end)` skeleton is absent (Python `if exons is None: continue`).
///
/// Faithful port of `family_exons` (:162): `st = strand.get(dn, "+")`; transcript order
/// = exon indices, REVERSED iff `st == "-"`; each exon's sequence is
/// `fa.fetch(chrom, s-1, e).upper()` (forward-strand bases, upper-cased -- NOT
/// reverse-complemented). `exlen = [len(x) for x in seqs]`.
pub fn family_exons<F: ExonFetcher>(
    members: &[Member],
    skel: &HashMap<(String, i64, i64), Vec<(i64, i64)>>,
    strand: &HashMap<String, String>,
    fa: &F,
) -> Vec<Rec> {
    let mut recs = Vec::new();
    for m in members {
        let key = (m.chrom.clone(), m.start, m.end);
        let exons = match skel.get(&key) {
            None => continue,
            Some(e) => e,
        };
        let st = strand.get(&m.dn).map(|s| s.as_str()).unwrap_or("+");
        // transcript 5'->3' order (reverse the exon ORDER for '-')
        let mut order: Vec<usize> = (0..exons.len()).collect();
        if st == "-" {
            order.reverse();
        }
        let mut seqs: Vec<Vec<u8>> = Vec::with_capacity(order.len());
        for gi in order {
            let (s, e) = exons[gi];
            let raw = fa.fetch(&m.chrom, s - 1, e).unwrap_or_default();
            let up: Vec<u8> = raw.iter().map(|b| b.to_ascii_uppercase()).collect();
            seqs.push(up);
        }
        let exlen = seqs.iter().map(|x| x.len()).collect();
        recs.push(Rec {
            dn: m.dn.clone(),
            gene: m.gene.clone(),
            chrom: m.chrom.clone(),
            start: m.start,
            end: m.end,
            strand: st.to_string(),
            exons: seqs,
            exlen,
        });
    }
    recs
}

// ===========================================================================
// exon_match_tensor  (recombination_bridge_detector.py:185-213)
// ===========================================================================

/// `best[(mi, ei, nj)] = (id, exon_index_in_nj)` -- the best HW match of exon `ei` of
/// member `mi` against member `nj`. Stores entries in Python `dict` INSERTION order
/// (a outer, b middle, i inner) for exact iteration parity, plus a lookup map with the
/// `(0.0, -1)` default of the Python `best.get(...)`.
#[derive(Debug, Default)]
pub struct Tensor {
    /// `(a, i, b, id, j)` in insertion order (mirrors `best.items()`).
    pub entries: Vec<(usize, usize, usize, f64, i64)>,
    map: HashMap<(usize, usize, usize), (f64, i64)>,
}

impl Tensor {
    /// `best.get((a, i, b), (0.0, -1))`.
    pub fn get(&self, a: usize, i: usize, b: usize) -> (f64, i64) {
        self.map.get(&(a, i, b)).copied().unwrap_or((0.0, -1))
    }
}

/// Pairwise exon-match tensor via `aln_id` + length prefilter.
///
/// Faithful port of `exon_match_tensor` (:185): for every ordered pair `a != b`, for
/// every exon `i` of `a` with `len >= MIN_EXON`, scan every exon `j` of `b` with
/// `len >= MIN_EXON`; skip if `min(len)/max(len) < 0.5`; align the SHORTER as the query
/// (`aln_id(qa, tb)` if `len(qa) <= len(tb)` else `aln_id(tb, qa)`); keep the strict-max
/// `(id, j)` (init `(0.0, -1)`); store `best[(a, i, b)]`.
pub fn exon_match_tensor(recs: &[Rec]) -> Tensor {
    let n = recs.len();
    let mut t = Tensor::default();
    for a in 0..n {
        for b in 0..n {
            if a == b {
                continue;
            }
            let ea = &recs[a].exons;
            let eb = &recs[b].exons;
            for (i, qa) in ea.iter().enumerate() {
                if qa.len() < MIN_EXON {
                    continue;
                }
                let mut bid = 0.0f64;
                let mut bj: i64 = -1;
                for (j, tb) in eb.iter().enumerate() {
                    if tb.len() < MIN_EXON {
                        continue;
                    }
                    let (lo, hi) = if qa.len() <= tb.len() {
                        (qa.len(), tb.len())
                    } else {
                        (tb.len(), qa.len())
                    };
                    // Python: if lo / hi < 0.5: continue   (float division)
                    if (lo as f64) / (hi as f64) < 0.5 {
                        continue;
                    }
                    let idv = if qa.len() <= tb.len() {
                        aln_id(qa, tb)
                    } else {
                        aln_id(tb, qa)
                    };
                    if idv > bid {
                        bid = idv;
                        bj = j as i64;
                    }
                }
                t.entries.push((a, i, b, bid, bj));
                t.map.insert((a, i, b), (bid, bj));
            }
        }
    }
    t
}

// ===========================================================================
// build_graph  (recombination_bridge_detector.py:216-225)
// ===========================================================================

/// The intra-family LOCUS graph: nodes `0..n`, an undirected edge `(a,b)` iff some exon
/// match hits `id >= ID_THRESH`, plus `edge_exons[(a,b)] = [exon i of a that hit b]` in
/// tensor-insertion order.
#[derive(Debug)]
pub struct LocusGraph {
    pub n: usize,
    /// adjacency (undirected), deterministic ordered sets
    pub adj: Vec<BTreeSet<usize>>,
    /// directed `(a,b) -> [i,...]` in insertion order (the Python `edge_exons`)
    pub edge_exons: Vec<((usize, usize), Vec<usize>)>,
}

impl LocusGraph {
    pub fn num_edges(&self) -> usize {
        self.adj.iter().enumerate().map(|(u, s)| s.iter().filter(|&&v| v > u).count()).sum()
    }

    pub fn neighbors(&self, u: usize) -> &BTreeSet<usize> {
        &self.adj[u]
    }

    /// Sorted, deduplicated undirected edge list `(u<v)` -- matches Python
    /// `sorted({tuple(sorted((u,v))) for u,v in G.edges()})`.
    pub fn edges(&self) -> Vec<(usize, usize)> {
        let mut out = Vec::new();
        for u in 0..self.n {
            for &v in &self.adj[u] {
                if v > u {
                    out.push((u, v));
                }
            }
        }
        out.sort_unstable();
        out
    }

    /// Connected components as sorted lists, sorted by first element -- matches the
    /// gates' `sorted((sorted(c) for c in nx.connected_components(G)), key=lambda c:c[0])`.
    /// Deterministic BFS in ascending node order.
    pub fn connected_components(&self) -> Vec<Vec<usize>> {
        let mut seen = vec![false; self.n];
        let mut comps: Vec<Vec<usize>> = Vec::new();
        for s in 0..self.n {
            if seen[s] {
                continue;
            }
            let mut stack = vec![s];
            seen[s] = true;
            let mut comp = Vec::new();
            while let Some(u) = stack.pop() {
                comp.push(u);
                for &v in &self.adj[u] {
                    if !seen[v] {
                        seen[v] = true;
                        stack.push(v);
                    }
                }
            }
            comp.sort_unstable();
            comps.push(comp);
        }
        comps.sort_by(|a, b| a[0].cmp(&b[0]));
        comps
    }
}

/// Build the locus graph from the tensor (`build_graph`, :216). Iterates the tensor in
/// insertion order so `edge_exons` list order matches Python `best.items()`.
pub fn build_graph(recs: &[Rec], t: &Tensor) -> LocusGraph {
    let n = recs.len();
    let mut adj: Vec<BTreeSet<usize>> = vec![BTreeSet::new(); n];
    let mut ee_index: HashMap<(usize, usize), usize> = HashMap::new();
    let mut edge_exons: Vec<((usize, usize), Vec<usize>)> = Vec::new();
    for &(a, i, b, idv, _j) in &t.entries {
        if idv >= ID_THRESH {
            adj[a].insert(b);
            adj[b].insert(a);
            // edge_exons[(a,b)].append(i)  (directed key, insertion order)
            match ee_index.get(&(a, b)) {
                Some(&k) => edge_exons[k].1.push(i),
                None => {
                    ee_index.insert((a, b), edge_exons.len());
                    edge_exons.push(((a, b), vec![i]));
                }
            }
        }
    }
    LocusGraph { n, adj, edge_exons }
}

// ===========================================================================
// coverage / colinearity metrics
// ===========================================================================

/// Fraction of `a`'s exons (`>= MIN_EXON`) with an `id >= ID_THRESH` match to some exon
/// of `b` (`pair_coverage`, :228).
pub fn pair_coverage(recs: &[Rec], t: &Tensor, a: usize, b: usize) -> f64 {
    let ne: Vec<usize> = recs[a]
        .exons
        .iter()
        .enumerate()
        .filter(|(_, s)| s.len() >= MIN_EXON)
        .map(|(i, _)| i)
        .collect();
    if ne.is_empty() {
        return 0.0;
    }
    let hit = ne.iter().filter(|&&i| t.get(a, i, b).0 >= ID_THRESH).count();
    hit as f64 / ne.len() as f64
}

/// `round(x, 3)` matching CPython's `float.__round__` (correctly-rounded decimal, ties
/// to even). Verified to equal Rust `format!("{:.3}", x)` + parse (see unit test).
fn round3(x: f64) -> f64 {
    if !x.is_finite() {
        return x;
    }
    format!("{:.3}", x).parse::<f64>().expect("3-decimal format parses")
}

/// Max best-exon identity BETWEEN distinct components, `round`ed to 3 dp
/// (`cross_component_maxid`, :237). `comps` are node-index groups; each is sorted
/// internally (Python `comps = [sorted(c) for c in comps]`).
pub fn cross_component_maxid(recs: &[Rec], t: &Tensor, comps: &[Vec<usize>]) -> f64 {
    let sorted_comps: Vec<Vec<usize>> = comps
        .iter()
        .map(|c| {
            let mut c = c.clone();
            c.sort_unstable();
            c
        })
        .collect();
    let mut mx = 0.0f64;
    for ci in 0..sorted_comps.len() {
        for cj in (ci + 1)..sorted_comps.len() {
            for &a in &sorted_comps[ci] {
                for &b in &sorted_comps[cj] {
                    for i in 0..recs[a].exons.len() {
                        let v = t.get(a, i, b).0;
                        if v > mx {
                            mx = v;
                        }
                    }
                }
            }
        }
    }
    round3(mx)
}

/// Longest order-preserving matched-exon chain of bridge `b` covered by neighbour `nn`,
/// divided by `n_exons(b)` (`colinear_cov`, :250). LIS is NON-decreasing (Python
/// `bisect_right`), over `j` in increasing-`i` order.
pub fn colinear_cov(recs: &[Rec], t: &Tensor, b: usize, nn: usize) -> f64 {
    let k = recs[b].exons.len();
    // pairs (i, j) for i with an id>=ID_THRESH, j>=0 match; sorted by (i,j) == by i.
    let mut pairs: Vec<(usize, i64)> = Vec::new();
    for i in 0..k {
        let (idv, j) = t.get(b, i, nn);
        if idv >= ID_THRESH && j >= 0 {
            pairs.push((i, j));
        }
    }
    if pairs.is_empty() {
        return 0.0;
    }
    pairs.sort_unstable(); // by (i, j); i is unique so effectively by i
    // patience sorting -> longest NON-decreasing subsequence of the j sequence.
    let mut tails: Vec<i64> = Vec::new();
    for (_, x) in pairs {
        // bisect_right: first index with tails[idx] > x
        let p = tails.partition_point(|&v| v <= x);
        if p == tails.len() {
            tails.push(x);
        } else {
            tails[p] = x;
        }
    }
    if k == 0 {
        0.0
    } else {
        tails.len() as f64 / k as f64
    }
}

// ===========================================================================
// subfamily helpers  (recombination_bridge_detector.py:273-296)
// ===========================================================================

/// Dominant gene of a component (`collections.Counter(...).most_common(1)[0][0]`):
/// highest count, ties broken by FIRST-SEEN in `comp` order (CPython `most_common`
/// selects the first-inserted among equal counts). `comp` must be non-empty.
pub fn subfam_dom_gene(recs: &[Rec], comp: &[usize]) -> String {
    let mut order: Vec<String> = Vec::new();
    let mut counts: HashMap<String, usize> = HashMap::new();
    for &i in comp {
        let g = &recs[i].gene;
        if !counts.contains_key(g) {
            order.push(g.clone());
        }
        *counts.entry(g.clone()).or_insert(0) += 1;
    }
    let mut best = &order[0];
    for g in &order {
        // strict '>' keeps the first-seen on a count tie
        if counts[g] > counts[best] {
            best = g;
        }
    }
    best.clone()
}

/// `f"{dom}({len(comp)})"` (`subfam_label`, :273).
pub fn subfam_label(recs: &[Rec], comp: &[usize]) -> String {
    format!("{}({})", subfam_dom_gene(recs, comp), comp.len())
}

/// True iff two DISTINCT parts of `bridged` occupy genomically OVERLAPPING loci (same
/// chrom, closed-interval overlap `a.start <= b.end && b.start <= a.end`)
/// (`subfams_colocated`, :284).
pub fn subfams_colocated(recs: &[Rec], bridged: &[Vec<usize>]) -> bool {
    for ci in 0..bridged.len() {
        for cj in (ci + 1)..bridged.len() {
            for &a in &bridged[ci] {
                for &b in &bridged[cj] {
                    let (ra, rb) = (&recs[a], &recs[b]);
                    if ra.chrom == rb.chrom && ra.start <= rb.end && rb.start <= ra.end {
                        return true;
                    }
                }
            }
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/bridge_detector_fixture.json");
        serde_json::from_str(raw).expect("parse bridge_detector fixture json")
    }

    fn rec_from_json(r: &Value) -> Rec {
        let exons: Vec<Vec<u8>> = r["exons"]
            .as_array()
            .unwrap()
            .iter()
            .map(|s| s.as_str().unwrap().as_bytes().to_vec())
            .collect();
        let exlen = exons.iter().map(|x| x.len()).collect();
        Rec {
            dn: r["dn"].as_str().unwrap().to_string(),
            gene: r["gene"].as_str().unwrap().to_string(),
            chrom: r["chrom"].as_str().unwrap().to_string(),
            start: r["start"].as_i64().unwrap(),
            end: r["end"].as_i64().unwrap(),
            strand: r["strand"].as_str().unwrap().to_string(),
            exons,
            exlen,
        }
    }

    // ---------------------------------------------------------------- unit corners

    #[test]
    fn constants_match_python() {
        let fx = load_fixture();
        assert_eq!(fx["ID_THRESH"].as_f64().unwrap(), ID_THRESH);
        assert_eq!(fx["MIN_EXON"].as_u64().unwrap() as usize, MIN_EXON);
        assert_eq!(fx["COLINEAR_COV"].as_f64().unwrap(), COLINEAR_COV);
    }

    #[test]
    fn revcomp_table_semantics() {
        // A<->T, C<->G, N->N (both cases), everything else passes through, then reverse.
        assert_eq!(revcomp(b"ACGT"), b"ACGT".to_vec()); // palindrome
        assert_eq!(revcomp(b"AAAA"), b"TTTT".to_vec());
        assert_eq!(revcomp(b"ACGTN"), b"NACGT".to_vec()); // N->N, reversed
        assert_eq!(revcomp(b"acgt"), b"acgt".to_vec()); // lowercase palindrome
        assert_eq!(revcomp(b"acg"), b"cgt".to_vec()); // a->t,c->g,g->c reversed
        assert_eq!(revcomp(b""), Vec::<u8>::new());
        // unmapped byte passes through unchanged (Python str.translate leaves it)
        assert_eq!(revcomp(b"AXT"), b"AXT".to_vec()); // T->A, X->X, A->T ; reversed = A X T
    }

    #[test]
    fn hw_distance_corners() {
        assert_eq!(hw_distance(b"ACGT", b"TTACGTGG"), 0); // exact infix
        assert_eq!(hw_distance(b"ACGT", b"ACGT"), 0);
        assert_eq!(hw_distance(b"ACGTACGTACGT", b"ACGT"), 8); // q longer -> 8 deletions
        assert_eq!(hw_distance(b"ACGT", b"ACAT"), 1); // one substitution
        assert_eq!(hw_distance(b"A", b"TTTT"), 1); // best infix "" or one mismatch
    }

    #[test]
    fn round3_matches_python() {
        // hardcoded CPython round(x,3) values (incl the half-to-even tie 0.0625 -> 0.062)
        for (v, want) in [
            (0.0f64, 0.0f64),
            (1.0, 1.0),
            (2.0 / 3.0, 0.667),
            (0.7005, 0.701),
            (0.0625, 0.062),
            (0.0635, 0.064),
            (0.9995, 1.0),
            (0.4445, 0.445),
            (1.0 - 5.0 / 17.0, 0.706),
        ] {
            assert_eq!(round3(v).to_bits(), want.to_bits(), "round3({v}) != {want}");
        }
    }

    #[test]
    fn subfams_colocated_and_dom_gene_synthetic() {
        let mk = |coords: &[(&str, i64, i64, &str)]| -> Vec<Rec> {
            coords
                .iter()
                .map(|&(c, s, e, g)| Rec {
                    dn: String::new(),
                    gene: g.to_string(),
                    chrom: c.to_string(),
                    start: s,
                    end: e,
                    strand: "+".to_string(),
                    exons: vec![],
                    exlen: vec![],
                })
                .collect()
        };
        // overlapping same-chrom across parts -> True
        let r = mk(&[("c1", 100, 200, "A"), ("c1", 150, 250, "B")]);
        assert!(subfams_colocated(&r, &[vec![0], vec![1]]));
        // non-overlapping -> False
        let r = mk(&[("c1", 100, 200, "A"), ("c1", 300, 400, "B")]);
        assert!(!subfams_colocated(&r, &[vec![0], vec![1]]));
        // dom-gene FIRST-SEEN tie-break
        let r = mk(&[("c", 1, 2, "ZED"), ("c", 3, 4, "ALPHA"), ("c", 5, 6, "ZED"), ("c", 7, 8, "ALPHA")]);
        assert_eq!(subfam_dom_gene(&r, &[0, 1, 2, 3]), "ZED");
        assert_eq!(subfam_label(&r, &[0, 1, 2, 3]), "ZED(4)");
        assert_eq!(subfam_dom_gene(&r, &[1, 0, 3, 2]), "ALPHA");
    }

    // ---------------------------------------------------------------- (a) aln_id parity

    /// PROVES the pure-Rust HW-DP `aln_id` == edlib on >= 80 adversarial pairs (exact
    /// bit-for-bit float equality). Reports the first mismatch.
    #[test]
    fn aln_id_parity_vs_edlib() {
        let fx = load_fixture();
        let cases = fx["aln_id"].as_array().expect("aln_id array");
        assert!(cases.len() >= 80, "need >= 80 aln_id cases, got {}", cases.len());
        let mut classes: BTreeSet<String> = BTreeSet::new();
        let mut n_empty = 0;
        let mut n_n = 0;
        let mut n_revcomp = 0;
        for c in cases {
            let q = c["q"].as_str().unwrap();
            let t = c["t"].as_str().unwrap();
            // EXACT bits (serde_json's decimal float parser is 1-ULP imprecise).
            let want = f64::from_bits(c["bits"].as_u64().unwrap());
            let cls = c["cls"].as_str().unwrap_or("");
            classes.insert(cls.to_string());
            if q.is_empty() || t.is_empty() {
                n_empty += 1;
            }
            if q.contains('N') || t.contains('N') {
                n_n += 1;
            }
            if cls.contains("revcomp") {
                n_revcomp += 1;
            }
            let got = aln_id(q.as_bytes(), t.as_bytes());
            assert_eq!(
                got.to_bits(),
                want.to_bits(),
                "aln_id MISMATCH cls='{cls}' q='{q}' t='{t}': rust {got} (bits {:#x}) != python {want} (bits {:#x})",
                got.to_bits(),
                want.to_bits()
            );
        }
        // edge-class coverage guard
        for required in ["both_empty", "q_empty", "t_empty", "q_longer", "exact_infix", "tandem"] {
            assert!(classes.contains(required), "aln_id fixture missing class '{required}'");
        }
        assert!(n_empty >= 3 && n_n >= 3 && n_revcomp >= 3, "aln_id fixture lacks edge coverage");
        eprintln!(
            "aln_id parity: {} pairs bit-identical to edlib (empty={n_empty} N={n_n} revcomp={n_revcomp}, classes={})",
            cases.len(),
            classes.len()
        );
    }

    // ---------------------------------------------------------------- (b) load_skeletons parity

    #[test]
    fn load_skeletons_parity() {
        let fx = load_fixture();
        let cases = fx["load_skeletons"].as_array().expect("load_skeletons array");
        assert!(cases.len() >= 20, "need >= 20 load_skeletons cases");
        let mut n_real = 0;
        let mut n_syn = 0;
        for c in cases {
            let chrom = c["chrom"].as_str().unwrap();
            let start = c["start"].as_i64().unwrap();
            let end = c["end"].as_i64().unwrap();
            let introns = c["introns"].as_str().unwrap();
            match c["kind"].as_str().unwrap() {
                "real" => n_real += 1,
                _ => n_syn += 1,
            }
            let want: Vec<(i64, i64)> = c["exons"]
                .as_array()
                .unwrap()
                .iter()
                .map(|p| {
                    let a = p.as_array().unwrap();
                    (a[0].as_i64().unwrap(), a[1].as_i64().unwrap())
                })
                .collect();
            // reconstruct a single-row skeleton TSV and parse it
            let text = format!(
                "chrom\tstart\tend\tn_exon\tn_reads\tintrons\n{chrom}\t{start}\t{end}\t0\t0\t{introns}\n"
            );
            let skel = parse_skeletons(&text);
            let got = skel
                .get(&(chrom.to_string(), start, end))
                .expect("parsed key present")
                .clone();
            assert_eq!(got, want, "load_skeletons MISMATCH {chrom}:{start}-{end} introns='{introns}'");
        }
        assert!(n_real >= 10 && n_syn >= 6, "need both real + synthetic skeleton cases");
        eprintln!("load_skeletons parity: {} cases ({n_real} real + {n_syn} synthetic)", cases.len());
    }

    // ---------------------------------------------------------------- (b) family_exons parity

    /// Mock fetcher backed by the fixture's captured raw (case-carrying) genome slices,
    /// keyed on `(chrom, start0, end0)` = the exact `fetch(chrom, s-1, e)` args.
    struct MockFasta {
        slices: HashMap<(String, i64, i64), Vec<u8>>,
    }
    impl ExonFetcher for MockFasta {
        fn fetch(&self, chrom: &str, start: i64, end: i64) -> Option<Vec<u8>> {
            self.slices.get(&(chrom.to_string(), start, end)).cloned()
        }
    }

    #[test]
    fn family_exons_parity() {
        let fx = load_fixture();
        let fams = fx["family_exons"].as_array().expect("family_exons array");
        assert!(fams.len() >= 20, "need >= 20 family_exons families, got {}", fams.len());
        let mut n_dropped = 0;
        let mut n_minus_multiexon = 0;
        let mut n_lowercase_slice = 0;
        for f in fams {
            // members
            let members: Vec<Member> = f["members"]
                .as_array()
                .unwrap()
                .iter()
                .map(|m| Member {
                    dn: m["dn"].as_str().unwrap().to_string(),
                    gene: m["gene"].as_str().unwrap().to_string(),
                    chrom: m["chrom"].as_str().unwrap().to_string(),
                    start: m["start"].as_i64().unwrap(),
                    end: m["end"].as_i64().unwrap(),
                })
                .collect();
            // strand map
            let mut strand: HashMap<String, String> = HashMap::new();
            for (k, v) in f["strand"].as_object().unwrap() {
                strand.insert(k.clone(), v.as_str().unwrap().to_string());
            }
            // skel (only members with a skeleton)
            let mut skel: HashMap<(String, i64, i64), Vec<(i64, i64)>> = HashMap::new();
            for s in f["skel"].as_array().unwrap() {
                let chrom = s["chrom"].as_str().unwrap().to_string();
                let st = s["start"].as_i64().unwrap();
                let en = s["end"].as_i64().unwrap();
                let exons: Vec<(i64, i64)> = s["exons"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|p| {
                        let a = p.as_array().unwrap();
                        (a[0].as_i64().unwrap(), a[1].as_i64().unwrap())
                    })
                    .collect();
                skel.insert((chrom, st, en), exons);
            }
            // mock slices
            let mut slices: HashMap<(String, i64, i64), Vec<u8>> = HashMap::new();
            for sl in f["slices"].as_array().unwrap() {
                let chrom = sl["chrom"].as_str().unwrap().to_string();
                let s0 = sl["start0"].as_i64().unwrap();
                let e0 = sl["end0"].as_i64().unwrap();
                let bytes = sl["bytes"].as_str().unwrap().as_bytes().to_vec();
                if bytes.iter().any(|b| b.is_ascii_lowercase()) {
                    n_lowercase_slice += 1;
                }
                slices.insert((chrom, s0, e0), bytes);
            }
            let fa = MockFasta { slices };

            let got = family_exons(&members, &skel, &strand, &fa);
            let want: Vec<Rec> = f["recs"].as_array().unwrap().iter().map(rec_from_json).collect();

            if members.len() > want.len() {
                n_dropped += 1;
            }
            for r in &want {
                if r.strand == "-" && r.exons.len() >= 2 {
                    n_minus_multiexon += 1;
                }
            }
            assert_eq!(got.len(), want.len(), "family_exons rec count mismatch (fid {})", f["fid"]);
            for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
                assert_eq!(g, w, "family_exons MISMATCH fid {} rec {i} (dn {})", f["fid"], w.dn);
            }
        }
        assert!(n_dropped >= 1, "fixture must exercise a dropped (no-skeleton) member");
        assert!(n_minus_multiexon >= 1, "fixture must exercise a '-' multi-exon member (order reversal)");
        assert!(n_lowercase_slice >= 1, "fixture must exercise soft-masked (lowercase) slices -> .upper()");
        eprintln!(
            "family_exons parity: {} families ({n_dropped} with dropped member, {n_minus_multiexon} minus-multiexon recs, {n_lowercase_slice} lowercase slices)",
            fams.len()
        );
    }

    // ---------------------------------------------------------------- (c) tensor/graph/etc parity

    #[test]
    fn tensor_family_parity() {
        let fx = load_fixture();
        let fams = fx["tensor_families"].as_array().expect("tensor_families array");
        assert!(fams.len() >= 15, "need >= 15 tensor families, got {}", fams.len());
        let mut n_multicomp = 0;
        let mut n_edges_total = 0usize;
        let mut n_colinear_pos = 0;
        for f in fams {
            let fid = f["fid"].as_i64().unwrap();
            let recs: Vec<Rec> = f["recs"].as_array().unwrap().iter().map(rec_from_json).collect();
            let t = exon_match_tensor(&recs);

            // -- best tensor (insertion order + id bit-exact + j)
            let want_best = f["best"].as_array().unwrap();
            assert_eq!(t.entries.len(), want_best.len(), "fid {fid}: best len mismatch");
            for (k, wb) in want_best.iter().enumerate() {
                let w = wb.as_array().unwrap();
                let (wa, wi, wbb) = (
                    w[0].as_u64().unwrap() as usize,
                    w[1].as_u64().unwrap() as usize,
                    w[2].as_u64().unwrap() as usize,
                );
                let wid = f64::from_bits(w[5].as_u64().unwrap()); // exact id bits
                let wj = w[4].as_i64().unwrap();
                let (ga, gi, gb, gid, gj) = t.entries[k];
                assert_eq!(
                    (ga, gi, gb, gid.to_bits(), gj),
                    (wa, wi, wbb, wid.to_bits(), wj),
                    "fid {fid}: best entry {k} MISMATCH: rust {:?} python {:?}",
                    (ga, gi, gb, gid, gj),
                    (wa, wi, wbb, wid, wj)
                );
            }

            // -- graph adjacency (edges) + edge_exons
            let g = build_graph(&recs, &t);
            let want_edges: Vec<(usize, usize)> = f["edges"]
                .as_array()
                .unwrap()
                .iter()
                .map(|e| {
                    let a = e.as_array().unwrap();
                    (a[0].as_u64().unwrap() as usize, a[1].as_u64().unwrap() as usize)
                })
                .collect();
            assert_eq!(g.edges(), want_edges, "fid {fid}: adjacency mismatch");
            n_edges_total += want_edges.len();
            // edge_exons (directed, insertion order)
            let mut want_ee: Vec<((usize, usize), Vec<usize>)> = f["edge_exons"]
                .as_array()
                .unwrap()
                .iter()
                .map(|e| {
                    let a = e.as_array().unwrap();
                    let k = (a[0].as_u64().unwrap() as usize, a[1].as_u64().unwrap() as usize);
                    let is: Vec<usize> = a[2].as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as usize).collect();
                    (k, is)
                })
                .collect();
            let mut got_ee = g.edge_exons.clone();
            // order is insertion-dependent on both sides; compare as sorted sets of (key, list)
            want_ee.sort();
            got_ee.sort();
            assert_eq!(got_ee, want_ee, "fid {fid}: edge_exons mismatch");

            // -- connected components (must equal Python comps_of)
            let want_comps: Vec<Vec<usize>> = f["components"]
                .as_array()
                .unwrap()
                .iter()
                .map(|c| c.as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as usize).collect())
                .collect();
            let got_comps = g.connected_components();
            assert_eq!(got_comps, want_comps, "fid {fid}: components mismatch");
            if want_comps.len() >= 2 {
                n_multicomp += 1;
            }

            // -- colinear_cov (all ordered pairs) bit-exact
            for row in f["colinear_cov"].as_array().unwrap() {
                let r = row.as_array().unwrap();
                let (b, nn) = (r[0].as_u64().unwrap() as usize, r[1].as_u64().unwrap() as usize);
                let want = f64::from_bits(r[3].as_u64().unwrap());
                let got = colinear_cov(&recs, &t, b, nn);
                assert_eq!(got.to_bits(), want.to_bits(), "fid {fid}: colinear_cov({b},{nn}) {got} != {want}");
                if want > 0.0 {
                    n_colinear_pos += 1;
                }
            }

            // -- pair_coverage (all ordered pairs) bit-exact
            for row in f["pair_coverage"].as_array().unwrap() {
                let r = row.as_array().unwrap();
                let (a, b) = (r[0].as_u64().unwrap() as usize, r[1].as_u64().unwrap() as usize);
                let want = f64::from_bits(r[3].as_u64().unwrap());
                let got = pair_coverage(&recs, &t, a, b);
                assert_eq!(got.to_bits(), want.to_bits(), "fid {fid}: pair_coverage({a},{b}) {got} != {want}");
            }

            // -- cross_component_maxid bit-exact
            let want_xcid = f64::from_bits(f["cross_component_maxid_bits"].as_u64().unwrap());
            let got_xcid = cross_component_maxid(&recs, &t, &got_comps);
            assert_eq!(got_xcid.to_bits(), want_xcid.to_bits(), "fid {fid}: cross_component_maxid mismatch");

            // -- subfams_colocated + subfam_dom_gene + subfam_label over components
            let want_coloc = f["subfams_colocated"].as_bool().unwrap();
            assert_eq!(subfams_colocated(&recs, &got_comps), want_coloc, "fid {fid}: subfams_colocated");
            let want_dom: Vec<String> = f["subfam_dom_gene"].as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();
            let got_dom: Vec<String> = got_comps.iter().map(|c| subfam_dom_gene(&recs, c)).collect();
            assert_eq!(got_dom, want_dom, "fid {fid}: subfam_dom_gene");
            let want_lab: Vec<String> = f["subfam_label"].as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();
            let got_lab: Vec<String> = got_comps.iter().map(|c| subfam_label(&recs, c)).collect();
            assert_eq!(got_lab, want_lab, "fid {fid}: subfam_label");
        }
        assert!(n_multicomp >= 2, "fixture must exercise >= 2 multi-component families (cross_component/subfams)");
        assert!(n_edges_total > 0, "fixture must exercise graph edges");
        assert!(n_colinear_pos > 0, "fixture must exercise positive colinear coverage");
        eprintln!(
            "tensor parity: {} families byte-identical (multicomp={n_multicomp}, total_edges={n_edges_total}, colinear>0={n_colinear_pos})",
            fams.len()
        );
    }

    // ---------------------------------------------------------------- (d) subfam cases parity

    #[test]
    fn subfam_cases_parity() {
        let fx = load_fixture();
        let cases = fx["subfam_cases"].as_array().expect("subfam_cases array");
        assert!(cases.len() >= 6);
        let mut seen_true = false;
        let mut seen_false = false;
        for c in cases {
            let recs: Vec<Rec> = c["recs_coords"]
                .as_array()
                .unwrap()
                .iter()
                .map(|rc| {
                    let a = rc.as_array().unwrap();
                    Rec {
                        dn: String::new(),
                        gene: a[3].as_str().unwrap().to_string(),
                        chrom: a[0].as_str().unwrap().to_string(),
                        start: a[1].as_i64().unwrap(),
                        end: a[2].as_i64().unwrap(),
                        strand: "+".to_string(),
                        exons: vec![],
                        exlen: vec![],
                    }
                })
                .collect();
            let partition: Vec<Vec<usize>> = c["partition"]
                .as_array()
                .unwrap()
                .iter()
                .map(|p| p.as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as usize).collect())
                .collect();
            let want_coloc = c["subfams_colocated"].as_bool().unwrap();
            seen_true |= want_coloc;
            seen_false |= !want_coloc;
            assert_eq!(subfams_colocated(&recs, &partition), want_coloc);
            let want_dom: Vec<String> = c["subfam_dom_gene"].as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();
            let got_dom: Vec<String> = partition.iter().map(|p| subfam_dom_gene(&recs, p)).collect();
            assert_eq!(got_dom, want_dom);
            let want_lab: Vec<String> = c["subfam_label"].as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();
            let got_lab: Vec<String> = partition.iter().map(|p| subfam_label(&recs, p)).collect();
            assert_eq!(got_lab, want_lab);
        }
        assert!(seen_true && seen_false, "subfam_cases must cover colocated True AND False");
        eprintln!("subfam_cases parity: {} cases (True + False covered)", cases.len());
    }
}
