//! O1 RNA-only EDGE-ORACLE loaders + the allele-demote decision (Rust port).
//!
//! Faithful Rust port of the pieces of the `E_r` RNA-homology edge oracle that
//! the family-definition DRIVER consumes, the next increment of the Python->Rust
//! migration (`docs/RETIREMENT_AND_MIGRATION.md` Tier-1 #4). Sits on top of the
//! already-ported loaders (`family_loaders.rs`, which supplies `gene_of_dn` via
//! `build_genes_dict`) and the `distinct_loci`/`refine_families` operators in
//! `family_definition.rs`.
//!
//! Ported functions (the Python source is the SPEC; line refs are the shipped
//! file `bench/rna_only_edge_oracle.py`):
//!   * `load_pair_core`     (:103)  -- EDGES_TSV -> gene-pair -> MAX `core_recip`
//!     over the DN-graph edges of that pair (the whole-transcript reciprocal
//!     homology weight the gamma operator sees). Preserves EXACTLY the max-
//!     aggregation, the `ga != gb` skip, and the `gene_of_dn`-missing skip.
//!   * `load_universal_aln` (:548)  -- SHAREDLEN_UNIV_TSV -> gene-pair ->
//!     `aln_frac` (`""` -> `None`), the leakage-free universal shared-exon cache.
//!   * `load_allele`        (:182)  -- A1_TSV -> gene -> the family-level RNA
//!     allele signal (`balanced_frac` / `het_risk` / `copy_like` / `med_maf`).
//!   * `demote_gene`        (:1235) -- the copy-vs-allele DEMOTE DECISION: a gene
//!     whose every variant position is a balanced ~50/50 het (`balanced_frac >=
//!     0.90` AND `copy_like <= 0.10`) is declared ALLELIC, not multi-copy. It
//!     pulls in ONLY the `load_allele` dict + the two scalar thresholds (nothing
//!     from the catalog / DNA), so the port is self-contained.
//!
//! FILE-PATH CONSTANTS (Python `rna_only_edge_oracle.py`, joined onto `BENCH =`
//! the `bench/` dir):
//!   * EDGES_TSV          = `bench/denovo_family_edges.tsv`   (:81)
//!   * SHAREDLEN_UNIV_TSV = `bench/ri_sharedlen_universal.tsv` (:540)
//!   * A1_TSV             = `bench/a1_read_consensus_o1.tsv`  (:86)
//!
//! Verified byte-identical to the shipped Python loaders + `demote_gene` against
//! a golden fixture (`testdata/edge_oracle_fixture.json`, generated by
//! `bench/gen_edge_oracle_fixture.py`); see the `#[test]`s at the bottom.

use std::collections::HashMap;

/// `balanced_frac >= DEMOTE_BAL_MIN` is one of the two DEMOTE conjuncts: a minor-
/// allele fraction ~0.5 (balanced) is a diploid het, i.e. an allele-as-copy risk.
/// Hard-coded from `rna_only_edge_oracle.py:1237` (`a["balanced_frac"] >= 0.90`);
/// the same constant is mirrored at `family_rna_refine.py:181  DEMOTE_BAL_MIN`.
pub const DEMOTE_BAL_MIN: f64 = 0.90;

/// `copy_like <= DEMOTE_COPY_MAX` is the second DEMOTE conjunct: a `copy_like`
/// near 0 means NOT a ~1/K real copy. Hard-coded from
/// `rna_only_edge_oracle.py:1237` (`a["copy_like"] <= 0.10`); mirrored at
/// `family_rna_refine.py:182  DEMOTE_COPY_MAX`.
pub const DEMOTE_COPY_MAX: f64 = 0.10;

/// Canonical UNORDERED gene-pair key = the Python `frozenset((a, b))`.
///
/// A sorted `(String, String)` tuple: `frozenset({a, b})` is order-independent,
/// and the loaders only ever build/look up a key with this same function, so the
/// sorted tuple is a faithful stand-in. (Python `frozenset((a, a)) == {a}` has a
/// single element; the sorted tuple `(a, a)` is a distinct-but-consistent
/// representation. `load_pair_core` never emits a self-pair (its `ga != gb`
/// guard); `load_universal_aln` has no such guard, but the shipped
/// `ri_sharedlen_universal.tsv` carries no same-gene rows, and a `(a, a)` key can
/// never collide with a cross-pair `(min, max)` where the two genes differ.)
pub fn gene_pair_key(a: &str, b: &str) -> (String, String) {
    if a <= b {
        (a.to_string(), b.to_string())
    } else {
        (b.to_string(), a.to_string())
    }
}

// ===========================================================================
// load_pair_core  (bench/rna_only_edge_oracle.py:103)
// ===========================================================================

/// gene-pair -> MAX `core_recip` over the DN-graph edges of that pair.
///
/// Faithful port of `load_pair_core` operating on the raw EDGES_TSV text (the
/// file version reads the file and delegates here). The header line is skipped;
/// every subsequent line is `a\tb\tcore_recip` (POSITIONAL 3-column split, as in
/// the Python `a, b, c = ln.rstrip("\n").split("\t")`). For each edge:
///   * `ga = gene_of_dn.get(a)`, `gb = gene_of_dn.get(b)`;
///   * SKIP unless BOTH are present AND `ga != gb` (the Python
///     `if ga and gb and ga != gb`);
///   * keep the STRICTLY-greatest `float(c)` per gene-pair, exactly as the Python
///     `if cv > pc.get(k, -1.0): pc[k] = cv` (default -1.0; order-invariant MAX).
pub fn load_pair_core_str(
    gene_of_dn: &HashMap<String, String>,
    text: &str,
) -> HashMap<(String, String), f64> {
    let mut pc: HashMap<(String, String), f64> = HashMap::new();
    for line in text.lines().skip(1) {
        // Python: a, b, c = ln.rstrip("\n").split("\t")  (exactly 3 columns)
        let f: Vec<&str> = line.split('\t').collect();
        let (a, b, c) = (f[0], f[1], f[2]);
        if let (Some(ga), Some(gb)) = (gene_of_dn.get(a), gene_of_dn.get(b)) {
            if ga != gb {
                let cv: f64 = c.parse().expect("core_recip float");
                let k = gene_pair_key(ga, gb);
                // Python: if cv > pc.get(k, -1.0): pc[k] = cv
                let cur = pc.get(&k).copied().unwrap_or(-1.0);
                if cv > cur {
                    pc.insert(k, cv);
                }
            }
        }
    }
    pc
}

/// Read the EDGES_TSV file and parse it (see `load_pair_core_str`).
pub fn load_pair_core(
    gene_of_dn: &HashMap<String, String>,
    path: &str,
) -> std::io::Result<HashMap<(String, String), f64>> {
    Ok(load_pair_core_str(gene_of_dn, &std::fs::read_to_string(path)?))
}

// ===========================================================================
// load_universal_aln  (bench/rna_only_edge_oracle.py:548)
// ===========================================================================

/// gene-pair -> `aln_frac` from the UNIVERSAL (leakage-free) cache; `""` -> `None`.
///
/// Faithful port of `load_universal_aln`: the header line builds the column-index
/// map (`I = {c: i for i, c in enumerate(h)}`); columns `gene_a`, `gene_b`,
/// `aln_frac`. An empty `aln_frac` string maps to `None`, otherwise `float(af)`.
/// (Last-write-wins on a duplicate gene-pair, matching the Python dict
/// assignment; the shipped cache carries no duplicates.)
pub fn load_universal_aln_str(text: &str) -> HashMap<(String, String), Option<f64>> {
    let mut lines = text.lines();
    let header: Vec<&str> = lines.next().expect("universal header").split('\t').collect();
    let idx: HashMap<&str, usize> = header.iter().enumerate().map(|(i, &c)| (c, i)).collect();
    let (ia, ib, iaf) = (idx["gene_a"], idx["gene_b"], idx["aln_frac"]);
    let mut d: HashMap<(String, String), Option<f64>> = HashMap::new();
    for line in lines {
        let f: Vec<&str> = line.split('\t').collect();
        let k = gene_pair_key(f[ia], f[ib]);
        let af = f[iaf];
        let v = if af.is_empty() {
            None
        } else {
            Some(af.parse::<f64>().expect("aln_frac float"))
        };
        d.insert(k, v);
    }
    d
}

/// Read the SHAREDLEN_UNIV_TSV file and parse it (see `load_universal_aln_str`).
pub fn load_universal_aln(path: &str) -> std::io::Result<HashMap<(String, String), Option<f64>>> {
    Ok(load_universal_aln_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// load_allele  (bench/rna_only_edge_oracle.py:182)
// ===========================================================================

/// The family-level RNA allele signal for one gene (`load_allele` value dict).
/// Minor-allele-fraction ~0.5 => diploid het (allele-as-copy risk); ~1/K => real
/// copy. Consumed by `demote_gene`.
#[derive(Clone, Debug, PartialEq)]
pub struct AlleleSignal {
    pub balanced_frac: f64,
    pub het_risk: f64,
    pub copy_like: f64,
    pub med_maf: f64,
}

/// gene -> `AlleleSignal`. Faithful port of `load_allele`: the header builds the
/// column-index map; columns `gene`, `balanced_frac`, `het_risk`, `copy_like`,
/// `med_maf` (all parsed as `f64`). Last-write-wins per gene (Python dict).
pub fn load_allele_str(text: &str) -> HashMap<String, AlleleSignal> {
    let mut lines = text.lines();
    let header: Vec<&str> = lines.next().expect("allele header").split('\t').collect();
    let idx: HashMap<&str, usize> = header.iter().enumerate().map(|(i, &c)| (c, i)).collect();
    let (ig, ibal, ihet, icop, imaf) = (
        idx["gene"],
        idx["balanced_frac"],
        idx["het_risk"],
        idx["copy_like"],
        idx["med_maf"],
    );
    let mut d: HashMap<String, AlleleSignal> = HashMap::new();
    for line in lines {
        let f: Vec<&str> = line.split('\t').collect();
        d.insert(
            f[ig].to_string(),
            AlleleSignal {
                balanced_frac: f[ibal].parse().expect("balanced_frac float"),
                het_risk: f[ihet].parse().expect("het_risk float"),
                copy_like: f[icop].parse().expect("copy_like float"),
                med_maf: f[imaf].parse().expect("med_maf float"),
            },
        );
    }
    d
}

/// Read the A1_TSV file and parse it (see `load_allele_str`).
pub fn load_allele(path: &str) -> std::io::Result<HashMap<String, AlleleSignal>> {
    Ok(load_allele_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// demote_gene  (bench/rna_only_edge_oracle.py:1235)
// ===========================================================================

/// The copy-vs-allele DEMOTE DECISION for a single gene.
///
/// Faithful port of the nested `demote_gene` in the APPLY stage:
/// ```python
/// def demote_gene(g):
///     a = allele.get(g)
///     return a is not None and a["balanced_frac"] >= 0.90 and a["copy_like"] <= 0.10
/// ```
/// A gene absent from `allele` returns `false` (Python `a is None`). The
/// comparison operators are load-bearing and preserved EXACTLY: `balanced_frac`
/// is `>=` (inclusive) `DEMOTE_BAL_MIN`, `copy_like` is `<=` (inclusive)
/// `DEMOTE_COPY_MAX`. It closes over ONLY the `load_allele` dict + the two scalar
/// thresholds -- no catalog / DNA / genome input -- so the port is self-contained.
pub fn demote_gene(allele: &HashMap<String, AlleleSignal>, gene: &str) -> bool {
    match allele.get(gene) {
        Some(a) => a.balanced_frac >= DEMOTE_BAL_MIN && a.copy_like <= DEMOTE_COPY_MAX,
        None => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---------------------------------------------------------------- unit tests

    fn sig(bal: f64, het: f64, cop: f64, maf: f64) -> AlleleSignal {
        AlleleSignal { balanced_frac: bal, het_risk: het, copy_like: cop, med_maf: maf }
    }

    #[test]
    fn demote_gene_boundaries_and_missing() {
        let mut a: HashMap<String, AlleleSignal> = HashMap::new();
        a.insert("HIT".into(), sig(0.95, 1.0, 0.05, 0.46)); // clear demote
        a.insert("EXACT".into(), sig(0.90, 1.0, 0.10, 0.5)); // both boundaries inclusive
        a.insert("BAL_LOW".into(), sig(0.8999, 1.0, 0.05, 0.5)); // bal just below
        a.insert("COPY_HIGH".into(), sig(0.95, 1.0, 0.1001, 0.5)); // copy just above
        assert!(demote_gene(&a, "HIT"));
        assert!(demote_gene(&a, "EXACT")); // >= and <= are inclusive
        assert!(!demote_gene(&a, "BAL_LOW"));
        assert!(!demote_gene(&a, "COPY_HIGH"));
        assert!(!demote_gene(&a, "ABSENT")); // a is None -> false
    }

    #[test]
    fn pair_core_max_aggregation_and_skips() {
        // gene map: two genes A/B via DN1/DN2; DN3 same-gene as DN1 (A); DN9 unmapped.
        let mut god: HashMap<String, String> = HashMap::new();
        god.insert("DN1".into(), "A".into());
        god.insert("DN2".into(), "B".into());
        god.insert("DN3".into(), "A".into()); // A--A (ga==gb) skip
        // DN9 deliberately absent -> missing skip
        let text = "\
a\tb\tcore_recip
DN1\tDN2\t0.20
DN2\tDN1\t0.50
DN1\tDN2\t0.31
DN1\tDN3\t0.99
DN1\tDN9\t0.77";
        let pc = load_pair_core_str(&god, text);
        // A/B present with MAX = 0.50 (order-invariant); A/A and A/<missing> absent.
        assert_eq!(pc.len(), 1);
        let k = gene_pair_key("A", "B");
        assert!((pc[&k] - 0.50).abs() < 1e-12);
        assert!(!pc.contains_key(&gene_pair_key("A", "A")));
    }

    #[test]
    fn universal_aln_empty_is_none() {
        let text = "\
gene_a\tgene_b\tdn_a\tdn_b\tcls\tin_ep\tcore\taln_len\taln_frac
GB\tGA\tx\ty\ttruthbar\t1\t0.3\t0\t0.1234
GC\tGD\tx\ty\ttruthbar\t0\t0.2\t0\t";
        let d = load_universal_aln_str(text);
        assert_eq!(d[&gene_pair_key("GA", "GB")], Some(0.1234)); // key is sorted
        assert_eq!(d[&gene_pair_key("GC", "GD")], None); // empty -> None
    }

    // ---------------------------------------------------------------- parity test

    /// Byte-parity against the golden fixture emitted by
    /// `bench/gen_edge_oracle_fixture.py` from the shipped Python loaders +
    /// `demote_gene`. Reports the first mismatch it finds.
    #[test]
    fn edge_oracle_parity() {
        let raw = include_str!("testdata/edge_oracle_fixture.json");
        let fx: serde_json::Value = serde_json::from_str(raw).expect("parse fixture json");

        // thresholds must match the Python constants.
        let th = &fx["thresholds"];
        assert!(
            (th["demote_bal_min"].as_f64().unwrap() - DEMOTE_BAL_MIN).abs() < 1e-12,
            "DEMOTE_BAL_MIN drift"
        );
        assert!(
            (th["demote_copy_max"].as_f64().unwrap() - DEMOTE_COPY_MAX).abs() < 1e-12,
            "DEMOTE_COPY_MAX drift"
        );

        // ---- (a) load_pair_core parity (incl. MAX-aggregation + both skip paths) ----
        let pcx = &fx["pair_core"];
        let god: HashMap<String, String> = pcx["gene_of_dn"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(k, v)| (k.clone(), v.as_str().unwrap().to_string()))
            .collect();
        let pc = load_pair_core_str(&god, pcx["edges_tsv"].as_str().unwrap());
        let golden_pc: HashMap<(String, String), f64> = pcx["golden"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| {
                let a = e.as_array().unwrap();
                (
                    (a[0].as_str().unwrap().to_string(), a[1].as_str().unwrap().to_string()),
                    a[2].as_f64().unwrap(),
                )
            })
            .collect();
        assert_eq!(
            pc.len(),
            golden_pc.len(),
            "PAIR_CORE size mismatch: rust {} vs python {}",
            pc.len(),
            golden_pc.len()
        );
        for (k, gv) in &golden_pc {
            let got = pc.get(k).unwrap_or_else(|| {
                panic!("PAIR_CORE missing pair {k:?} (python core {gv})")
            });
            assert!(
                (got - gv).abs() <= 1e-12,
                "PAIR_CORE MISMATCH {k:?}: rust {got} != python {gv}"
            );
        }
        // diversity guards (fixture stays representative of the aggregation/skip paths)
        let div = &pcx["diversity"];
        assert!(div["n_pairs"].as_u64().unwrap() >= 8, "too few pair_core pairs");
        assert!(div["multi_edge_pairs"].as_u64().unwrap() >= 3, "too few multi-edge (MAX) pairs");
        assert!(div["max_not_first"].as_u64().unwrap() >= 1, "no order-sensitive MAX pair");
        assert!(div["skipped_missing"].as_u64().unwrap() >= 1, "no gene_of_dn-missing skip");
        assert!(div["skipped_same_gene"].as_u64().unwrap() >= 1, "no ga==gb skip");

        // ---- (b) load_universal_aln parity (incl. empty -> None) ----
        let ux = &fx["universal_aln"];
        let ua = load_universal_aln_str(ux["tsv"].as_str().unwrap());
        let mut n_empty = 0usize;
        let mut golden_ua: HashMap<(String, String), Option<f64>> = HashMap::new();
        for e in ux["golden"].as_array().unwrap() {
            let a = e.as_array().unwrap();
            let k = (a[0].as_str().unwrap().to_string(), a[1].as_str().unwrap().to_string());
            let v = if a[2].is_null() {
                n_empty += 1;
                None
            } else {
                Some(a[2].as_f64().unwrap())
            };
            golden_ua.insert(k, v);
        }
        assert_eq!(ua.len(), golden_ua.len(), "UNIVERSAL_ALN size mismatch");
        for (k, gv) in &golden_ua {
            let got = ua
                .get(k)
                .unwrap_or_else(|| panic!("UNIVERSAL_ALN missing pair {k:?}"));
            match (got, gv) {
                (None, None) => {}
                (Some(x), Some(y)) => assert!(
                    (x - y).abs() <= 1e-12,
                    "UNIVERSAL_ALN MISMATCH {k:?}: rust {x} != python {y}"
                ),
                _ => panic!("UNIVERSAL_ALN None/Some MISMATCH {k:?}: rust {got:?} != python {gv:?}"),
            }
        }
        assert!(n_empty >= 1, "fixture has no empty(None) universal_aln row");

        // ---- (c) load_allele parity (per-field) ----
        let ax = &fx["allele"];
        let al = load_allele_str(ax["tsv"].as_str().unwrap());
        let golden_al = ax["golden"].as_object().unwrap();
        assert_eq!(al.len(), golden_al.len(), "ALLELE size mismatch");
        for (g, gv) in golden_al {
            let got = al.get(g).unwrap_or_else(|| panic!("ALLELE missing gene {g}"));
            let want = AlleleSignal {
                balanced_frac: gv["balanced_frac"].as_f64().unwrap(),
                het_risk: gv["het_risk"].as_f64().unwrap(),
                copy_like: gv["copy_like"].as_f64().unwrap(),
                med_maf: gv["med_maf"].as_f64().unwrap(),
            };
            assert!(
                (got.balanced_frac - want.balanced_frac).abs() <= 1e-12
                    && (got.het_risk - want.het_risk).abs() <= 1e-12
                    && (got.copy_like - want.copy_like).abs() <= 1e-12
                    && (got.med_maf - want.med_maf).abs() <= 1e-12,
                "ALLELE MISMATCH {g}: rust {got:?} != python {want:?}"
            );
        }

        // ---- (d) demote_gene parity (diverse; boundary cases at each threshold) ----
        let dx = &fx["demote"];
        let allele: HashMap<String, AlleleSignal> = dx["allele"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(g, v)| {
                (
                    g.clone(),
                    AlleleSignal {
                        balanced_frac: v["balanced_frac"].as_f64().unwrap(),
                        het_risk: v["het_risk"].as_f64().unwrap(),
                        copy_like: v["copy_like"].as_f64().unwrap(),
                        med_maf: v["med_maf"].as_f64().unwrap(),
                    },
                )
            })
            .collect();
        let mut n_demote = 0usize;
        let mut n_true = 0usize;
        for case in dx["cases"].as_array().unwrap() {
            let gene = case["gene"].as_str().unwrap();
            let expect = case["expect"].as_bool().unwrap();
            let got = demote_gene(&allele, gene);
            assert_eq!(
                got, expect,
                "DEMOTE MISMATCH gene '{gene}': rust {got} != python {expect}"
            );
            n_demote += 1;
            if expect {
                n_true += 1;
            }
        }
        assert!(n_demote >= 8, "too few demote cases: {n_demote}");
        assert!(n_true >= 1, "no positive demote case");
        assert!(n_demote - n_true >= 1, "no negative demote case");

        eprintln!(
            "edge_oracle parity: pair_core {} pairs OK (multi-edge {}, max-not-first {}, skip-missing {}, skip-same {}); \
             universal_aln {} rows OK ({} None); allele {} genes OK; demote {} cases OK ({} demoted)",
            golden_pc.len(),
            div["multi_edge_pairs"], div["max_not_first"], div["skipped_missing"], div["skipped_same_gene"],
            golden_ua.len(), n_empty, golden_al.len(), n_demote, n_true
        );
    }
}
