//! O1 family-definition LOADERS (Rust port of the Python reference).
//!
//! Faithful Rust port of the input loaders + DN-locus->gene projection that feed
//! the already-ported `distinct_loci` / `refine_families` operators in
//! `family_definition.rs`. This is the next increment of the Python->Rust
//! family-definition migration (`docs/RETIREMENT_AND_MIGRATION.md` Tier-1 #2).
//!
//! Ported functions (Python source is the SPEC; line refs are the shipped file):
//!   * `components_from_edges` (bench/graph_def_refine_sweep.py:180)  -- partition
//!     nodes into connected components using ONLY the kept edges;
//!   * `load_meta`   (bench/family_er_pr.py:83)   -- META TSV  -> {DN -> (chrom,start,end)};
//!   * `load_annot`  (bench/family_er_pr.py:94)   -- ANNOT TSV -> per-contig sorted
//!     intervals + maxlen;
//!   * `gene_of`     (bench/family_er_pr.py:111)  -- max-overlap annotation interval
//!     for a DN locus (the SUBTLE one: strict `>` tie-break + descending-scan order
//!     are load-bearing; see `Annot::gene_of`);
//!   * `load_raw_families` (bench/family_er_pr.py:148) -- DENOVO_FAMS TSV -> families;
//!   * `load_edges`  (bench/family_er_pr.py:158)  -- DENOVO_EDGES TSV -> (a,b) pairs;
//!   * `build_genes_dict` (bench/family_er_pr.py:284) -- assemble the per-DN gene
//!     metadata (chrom/start/end/biotype/name/ov) + the floored/unfloored gene maps,
//!     with the missing-meta fallback parse and the OV_FLOOR floor.
//!
//! Verified byte-identical to the shipped Python build against a golden fixture
//! (`testdata/loaders_fixture.json`, generated by `bench/gen_loaders_fixture.py`);
//! see the `#[test]`s at the bottom.

use std::collections::{BTreeSet, HashMap, HashSet};

use super::family_definition::Gene;

/// Minimum overlap fraction for the DN-locus -> gene projection to be KEPT.
///
/// A projection is kept iff its overlap covers `>= OV_FLOOR` of the DN span OR
/// `>= OV_FLOOR` of the gene span. Below the floor the locus name/biotype default
/// to the DN id / `"NA"` (a spurious `<20%` clip must not seed a block name or
/// inflate the over-merge count). Hard-coded from the Python constant
/// `bench/family_er_pr.py:69  OV_FLOOR = 0.20`.
pub const OV_FLOOR: f64 = 0.20;

// ===========================================================================
// components_from_edges  (bench/graph_def_refine_sweep.py:180)
// ===========================================================================

/// Partition `all_nodes` into connected components using ONLY `kept_edges`.
///
/// Faithful port of the Python `components_from_edges`: it builds a graph over
/// `all_nodes` PLUS every endpoint appearing in `kept_edges` (networkx
/// `add_edge` implicitly adds unseen endpoints), then returns the connected
/// components. Each `kept_edges` entry is an unordered pair `(u, v)` (the Python
/// `frozenset` pair). The component ORDER is irrelevant to the caller (the
/// Python result is a `[set(...)]`); the returned `Vec<BTreeSet>` is nonetheless
/// deterministic (union-find over the sorted node universe).
pub fn components_from_edges(
    all_nodes: &[String],
    kept_edges: &[(String, String)],
) -> Vec<BTreeSet<String>> {
    // Node universe = all_nodes UNION every edge endpoint (networkx semantics).
    let mut universe: BTreeSet<&str> = BTreeSet::new();
    for n in all_nodes {
        universe.insert(n.as_str());
    }
    for (u, v) in kept_edges {
        universe.insert(u.as_str());
        universe.insert(v.as_str());
    }
    // Stable index assignment in sorted node order -> deterministic output.
    let verts: Vec<&str> = universe.iter().copied().collect();
    let idx: HashMap<&str, usize> = verts.iter().enumerate().map(|(i, &v)| (v, i)).collect();

    let mut parent: Vec<usize> = (0..verts.len()).collect();
    fn find(parent: &mut [usize], x: usize) -> usize {
        let mut root = x;
        while parent[root] != root {
            root = parent[root];
        }
        let mut cur = x;
        while parent[cur] != root {
            let next = parent[cur];
            parent[cur] = root;
            cur = next;
        }
        root
    }
    for (u, v) in kept_edges {
        let (ru, rv) = (find(&mut parent, idx[u.as_str()]), find(&mut parent, idx[v.as_str()]));
        if ru != rv {
            parent[ru] = rv;
        }
    }

    // Group nodes by root; each group is one connected component.
    let mut groups: HashMap<usize, BTreeSet<String>> = HashMap::new();
    for (i, &v) in verts.iter().enumerate() {
        let r = find(&mut parent, i);
        groups.entry(r).or_default().insert(v.to_string());
    }
    let mut comps: Vec<BTreeSet<String>> = groups.into_values().collect();
    // Deterministic order (by smallest member) -- cosmetic; callers compare as a set.
    comps.sort_by(|a, b| a.iter().next().cmp(&b.iter().next()));
    comps
}

// ===========================================================================
// load_meta  (bench/family_er_pr.py:83)
// ===========================================================================

/// DN id -> `(chrom, start, end)`, skipping the header line. Faithful port of
/// `load_meta` operating on the raw TSV text (`load_meta` reads the file and
/// delegates here). Columns: `f[0]=id  f[1]=chrom  f[2]=start  f[3]=end`.
pub fn load_meta_str(text: &str) -> HashMap<String, (String, i64, i64)> {
    let mut m = HashMap::new();
    for line in text.lines().skip(1) {
        // Python: f = ln.rstrip("\n").split("\t")
        let f: Vec<&str> = line.split('\t').collect();
        let start: i64 = f[2].parse().expect("meta start int");
        let end: i64 = f[3].parse().expect("meta end int");
        m.insert(f[0].to_string(), (f[1].to_string(), start, end));
    }
    m
}

/// Read the META TSV file and parse it (see `load_meta_str`).
pub fn load_meta(path: &str) -> std::io::Result<HashMap<String, (String, i64, i64)>> {
    Ok(load_meta_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// load_annot / gene_of  (bench/family_er_pr.py:94 / :111)
// ===========================================================================

/// One annotation interval `(start, end, biotype, gene)` on a contig.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AnnotInterval {
    pub start: i64,
    pub end: i64,
    pub biotype: String,
    pub gene: String,
}

/// Per-contig annotation index: intervals sorted by the FULL tuple
/// `(start, end, biotype, gene)` (matching Python's `ivals.sort()`), the parallel
/// `starts` vector for binary search, and the max interval length on the contig.
#[derive(Clone, Debug)]
pub struct ContigAnnot {
    pub starts: Vec<i64>,
    pub ivals: Vec<AnnotInterval>,
    pub maxlen: i64,
}

/// The whole annotation: `contig -> ContigAnnot`. Faithful port of `load_annot`.
#[derive(Clone, Debug, Default)]
pub struct Annot {
    pub by_contig: HashMap<String, ContigAnnot>,
}

impl Annot {
    /// Build from `contig -> unsorted intervals` (the `by_c` dict in `load_annot`).
    /// Sorts each contig's intervals by `(start, end, biotype, gene)` and records
    /// `starts` + `maxlen` exactly as the Python does.
    pub fn build(by_contig: HashMap<String, Vec<AnnotInterval>>) -> Annot {
        let mut out: HashMap<String, ContigAnnot> = HashMap::new();
        for (c, mut ivals) in by_contig {
            // Python `ivals.sort()` on (int,int,str,str) tuples -> lexicographic.
            ivals.sort_by(|a, b| {
                (a.start, a.end, &a.biotype, &a.gene).cmp(&(b.start, b.end, &b.biotype, &b.gene))
            });
            let starts: Vec<i64> = ivals.iter().map(|iv| iv.start).collect();
            // Python: maxlen = max(e - s for ...). Non-empty by construction.
            let maxlen = ivals.iter().map(|iv| iv.end - iv.start).max().unwrap_or(0);
            out.insert(c, ContigAnnot { starts, ivals, maxlen });
        }
        Annot { by_contig: out }
    }

    /// Parse the ANNOT TSV text into an `Annot` (see `load_annot`). Columns:
    /// `f[0]=contig f[1]=start f[2]=end f[3]=biotype f[4]=gene`; skips the header.
    pub fn from_str(text: &str) -> Annot {
        let mut by_c: HashMap<String, Vec<AnnotInterval>> = HashMap::new();
        for line in text.lines().skip(1) {
            let f: Vec<&str> = line.split('\t').collect();
            by_c.entry(f[0].to_string()).or_default().push(AnnotInterval {
                start: f[1].parse().expect("annot start int"),
                end: f[2].parse().expect("annot end int"),
                biotype: f[3].to_string(),
                gene: f[4].to_string(),
            });
        }
        Annot::build(by_c)
    }

    /// Max-overlap annotation interval for a DN locus `[qs, qe)`, plus the overlap
    /// fraction `ovf = max(overlap/DN_span, overlap/gene_span)`. Returns
    /// `(gene, biotype, ovf)`, or `(None, None, 0.0)` when the locus overlaps no
    /// interval. FAITHFUL port of the Python `gene_of` -- the load-bearing details:
    ///
    ///   * scan intervals with `start <= qe` DOWNWARD from `bisect_right`;
    ///   * BREAK when `start < qs - maxlen` (a valid prune: any real overlapper has
    ///     span `<= maxlen`, so its start `> qs - maxlen`);
    ///   * count overlap `ov = min(e,qe) - max(s,qs)` only when `e > qs`;
    ///   * keep the STRICTLY-greatest `ov` (`if ov > best_ov`) -- ties keep the
    ///     FIRST-scanned interval = the highest `start` (with the `(start,end,bt,
    ///     gene)` tuple order as the sub-tie-break). This scan order + strict `>`
    ///     are preserved EXACTLY.
    pub fn gene_of(&self, chrom: &str, qs: i64, qe: i64) -> (Option<String>, Option<String>, f64) {
        let rec = match self.by_contig.get(chrom) {
            Some(r) => r,
            None => return (None, None, 0.0),
        };
        // hi = bisect_right(starts, qe) == number of starts <= qe.
        let hi = rec.starts.partition_point(|&s| s <= qe);
        let mut best_ov: i64 = 0;
        let mut best_gene: Option<&str> = None;
        let mut best_bt: Option<&str> = None;
        let mut best_span: i64 = 0;
        let lo_bound = qs - rec.maxlen;
        let mut i = hi as isize - 1;
        while i >= 0 {
            let iv = &rec.ivals[i as usize];
            if iv.start < lo_bound {
                break;
            }
            if iv.end > qs {
                let ov = iv.end.min(qe) - iv.start.max(qs);
                if ov > best_ov {
                    best_ov = ov;
                    best_gene = Some(&iv.gene);
                    best_bt = Some(&iv.biotype);
                    best_span = iv.end - iv.start;
                }
            }
            i -= 1;
        }
        match best_gene {
            None => (None, None, 0.0),
            Some(g) => {
                let dn_span = qe - qs;
                let frac_dn = if dn_span > 0 {
                    best_ov as f64 / dn_span as f64
                } else {
                    0.0
                };
                let frac_gene = if best_span > 0 {
                    best_ov as f64 / best_span as f64
                } else {
                    0.0
                };
                (
                    Some(g.to_string()),
                    best_bt.map(|s| s.to_string()),
                    frac_dn.max(frac_gene),
                )
            }
        }
    }
}

/// Read the ANNOT TSV file and parse it (see `Annot::from_str`).
pub fn load_annot(path: &str) -> std::io::Result<Annot> {
    Ok(Annot::from_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// load_raw_families / load_edges  (bench/family_er_pr.py:148 / :158)
// ===========================================================================

/// DENOVO_FAMS TSV -> list of families, each a `Vec<DN id>` (the `f[2]` comma
/// list). Skips the header. Faithful port of `load_raw_families`.
pub fn load_raw_families_str(text: &str) -> Vec<Vec<String>> {
    let mut fams = Vec::new();
    for line in text.lines().skip(1) {
        let f: Vec<&str> = line.split('\t').collect();
        fams.push(f[2].split(',').map(|s| s.to_string()).collect());
    }
    fams
}

/// Read the DENOVO_FAMS TSV file and parse it (see `load_raw_families_str`).
pub fn load_raw_families(path: &str) -> std::io::Result<Vec<Vec<String>>> {
    Ok(load_raw_families_str(&std::fs::read_to_string(path)?))
}

/// DENOVO_EDGES TSV -> list of `(a, b)` pairs (`f[0]`, `f[1]`). Skips the header.
/// Faithful port of `load_edges` (no dedup; order preserved).
pub fn load_edges_str(text: &str) -> Vec<(String, String)> {
    let mut edges = Vec::new();
    for line in text.lines().skip(1) {
        let f: Vec<&str> = line.split('\t').collect();
        edges.push((f[0].to_string(), f[1].to_string()));
    }
    edges
}

/// Read the DENOVO_EDGES TSV file and parse it (see `load_edges_str`).
pub fn load_edges(path: &str) -> std::io::Result<Vec<(String, String)>> {
    Ok(load_edges_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// build_genes_dict  (bench/family_er_pr.py:284)
// ===========================================================================

/// Per-DN gene metadata (one entry of the Python `genes` dict): the DN locus
/// coords plus the floored gene projection. `biotype`/`name` default to `"NA"` /
/// the DN id when the projection is dropped by `OV_FLOOR`; `ov` is the UNFLOORED
/// overlap fraction (kept for the sensitivity report).
#[derive(Clone, Debug, PartialEq)]
pub struct GeneMeta {
    pub chrom: String,
    pub start: i64,
    pub end: i64,
    pub biotype: String,
    pub name: String,
    pub ov: f64,
}

impl GeneMeta {
    /// Project to the `Gene` shape consumed by `refine_families` / `distinct_loci`
    /// (drops the `ov` field). Lets the ported loaders feed the ported refiner.
    pub fn to_gene(&self) -> Gene {
        Gene {
            chrom: self.chrom.clone(),
            start: self.start,
            end: self.end,
            name: self.name.clone(),
            biotype: self.biotype.clone(),
        }
    }
}

/// Overlap-fraction contamination counts (the Python `ovstats` dict).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct OvStats {
    pub mapped_raw: usize,
    pub mapped_floored: usize,
    pub dropped_by_floor: usize,
    pub lt20_overlap: usize,
    pub lt50_overlap: usize,
}

/// Result of `build_genes_dict`: the `genes` metadata map plus the floored /
/// unfloored gene projections and the diagnostic counters.
#[derive(Clone, Debug)]
pub struct BuildGenes {
    /// DN id -> gene metadata (the Python `genes` dict).
    pub genes: HashMap<String, GeneMeta>,
    /// DN id -> gene, FLOORED (`ovf >= OV_FLOOR`) -- the headline projection.
    pub gene_of_dn: HashMap<String, String>,
    /// DN id -> gene, UNFLOORED max-overlap map (any truthy gene).
    pub gene_of_dn_raw: HashMap<String, String>,
    /// Count of DN ids absent from `meta` (resolved by the fallback id parse).
    pub miss_meta: usize,
    pub ovstats: OvStats,
}

/// Assemble the per-DN `genes` metadata for every member of every raw family.
///
/// Faithful port of `build_genes_dict`. For each DN member (FIRST occurrence
/// wins across the flattened `raw_fams`):
///   1. look up `meta`; if missing, count it and parse `DN_<contig>_<start>_<nreads>`
///      -> `chrom = "_".join(parts[1:-2])`, `start = int(parts[-2])`, `end = start`
///      (the contig may itself contain underscores);
///   2. project to a gene via `annot.gene_of` -> `(g, bt, ovf)`;
///   3. `keep = g.is_some() && ovf >= OV_FLOOR`;
///   4. `genes[dn] = {chrom,start,end, biotype: keep?bt:"NA", name: keep?g:dn, ov: ovf}`;
///   5. `gene_of_dn[dn] = g` iff `keep`; `gene_of_dn_raw[dn] = g` iff `g` is truthy.
///
/// All of the fallback parse, the floor, the `"NA"`/self-name defaults, and the
/// `ovstats` counters are preserved exactly.
pub fn build_genes_dict(
    raw_fams: &[Vec<String>],
    meta: &HashMap<String, (String, i64, i64)>,
    annot: &Annot,
) -> BuildGenes {
    let mut genes: HashMap<String, GeneMeta> = HashMap::new();
    let mut gene_of_dn: HashMap<String, String> = HashMap::new();
    let mut gene_of_dn_raw: HashMap<String, String> = HashMap::new();
    let mut seen: HashSet<String> = HashSet::new();
    let mut miss_meta = 0usize;
    let mut lt20 = 0usize;
    let mut lt50 = 0usize;
    let mut mapped_raw = 0usize;

    for fam in raw_fams {
        for dn in fam {
            // Python: `if dn in genes: continue` -- first occurrence wins.
            if !seen.insert(dn.clone()) {
                continue;
            }
            let (chrom, start, end) = match meta.get(dn) {
                Some((c, s, e)) => (c.clone(), *s, *e),
                None => {
                    miss_meta += 1;
                    // DN_<contig...>_<start>_<nreads>; contig may contain underscores.
                    let parts: Vec<&str> = dn.split('_').collect();
                    let n = parts.len();
                    let start: i64 = parts[n - 2].parse().expect("fallback start int");
                    let chrom = parts[1..n - 2].join("_");
                    (chrom, start, start)
                }
            };
            let (g, bt, ovf) = annot.gene_of(&chrom, start, end);
            let keep = g.is_some() && ovf >= OV_FLOOR;
            genes.insert(
                dn.clone(),
                GeneMeta {
                    chrom,
                    start,
                    end,
                    biotype: if keep {
                        bt.clone().unwrap()
                    } else {
                        "NA".to_string()
                    },
                    name: if keep {
                        g.clone().unwrap()
                    } else {
                        dn.clone()
                    },
                    ov: ovf,
                },
            );
            if let Some(gname) = &g {
                gene_of_dn_raw.insert(dn.clone(), gname.clone());
                mapped_raw += 1;
                if ovf < 0.20 {
                    lt20 += 1;
                }
                if ovf < 0.50 {
                    lt50 += 1;
                }
            }
            if keep {
                gene_of_dn.insert(dn.clone(), g.unwrap());
            }
        }
    }

    let ovstats = OvStats {
        mapped_raw,
        mapped_floored: gene_of_dn.len(),
        dropped_by_floor: mapped_raw - gene_of_dn.len(),
        lt20_overlap: lt20,
        lt50_overlap: lt50,
    };
    BuildGenes {
        genes,
        gene_of_dn,
        gene_of_dn_raw,
        miss_meta,
        ovstats,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---------------------------------------------------------------- unit tests

    fn iv(start: i64, end: i64, bt: &str, gene: &str) -> AnnotInterval {
        AnnotInterval {
            start,
            end,
            biotype: bt.to_string(),
            gene: gene.to_string(),
        }
    }

    #[test]
    fn gene_of_tie_break_keeps_first_scanned_highest_start() {
        // Two intervals give the SAME overlap (500) to query [1000,2000):
        //   LOW : [500,1500)  ov = 500, span 1000
        //   HIGH: [1500,3000) ov = 500, span 1500
        // Descending scan hits HIGH first; strict `>` keeps it (LOW does not replace).
        let mut by = HashMap::new();
        by.insert(
            "c".to_string(),
            vec![iv(500, 1500, "bt_low", "GENE_LOW"), iv(1500, 3000, "bt_high", "GENE_HIGH")],
        );
        let annot = Annot::build(by);
        let (g, bt, ovf) = annot.gene_of("c", 1000, 2000);
        assert_eq!(g.as_deref(), Some("GENE_HIGH"));
        assert_eq!(bt.as_deref(), Some("bt_high"));
        assert!((ovf - 0.5).abs() < 1e-12, "ovf = {ovf}"); // max(500/1000, 500/1500)
    }

    #[test]
    fn gene_of_no_overlap_and_missing_contig() {
        let mut by = HashMap::new();
        by.insert("c".to_string(), vec![iv(0, 100, "b", "G")]);
        let annot = Annot::build(by);
        assert_eq!(annot.gene_of("c", 500, 600), (None, None, 0.0));
        assert_eq!(annot.gene_of("absent", 0, 100), (None, None, 0.0));
        // zero-length query inside an interval -> ov == 0 -> no gene
        assert_eq!(annot.gene_of("c", 50, 50), (None, None, 0.0));
    }

    #[test]
    fn components_from_edges_basics() {
        let nodes: Vec<String> = ["a", "b", "c", "d", "e"].iter().map(|s| s.to_string()).collect();
        let edges = vec![("a".to_string(), "b".to_string()), ("b".to_string(), "c".to_string())];
        let comps = components_from_edges(&nodes, &edges);
        let set: HashSet<BTreeSet<String>> = comps.into_iter().collect();
        let abc: BTreeSet<String> = ["a", "b", "c"].iter().map(|s| s.to_string()).collect();
        let d: BTreeSet<String> = ["d"].iter().map(|s| s.to_string()).collect();
        let e: BTreeSet<String> = ["e"].iter().map(|s| s.to_string()).collect();
        assert_eq!(set, [abc, d, e].into_iter().collect());
        // an edge endpoint not in all_nodes is still added (networkx semantics)
        let comps2 = components_from_edges(&[], &[("x".to_string(), "y".to_string())]);
        assert_eq!(comps2.len(), 1);
        assert_eq!(comps2[0], ["x", "y"].iter().map(|s| s.to_string()).collect());
    }

    #[test]
    fn build_genes_dict_fallback_parse_multi_underscore() {
        // DN absent from meta -> fallback parse; contig retains its underscores.
        let raw = vec![vec!["DN_SYN_ctg_x_5000_3".to_string()]];
        let meta: HashMap<String, (String, i64, i64)> = HashMap::new();
        let annot = Annot::build(HashMap::new());
        let out = build_genes_dict(&raw, &meta, &annot);
        assert_eq!(out.miss_meta, 1);
        let gm = &out.genes["DN_SYN_ctg_x_5000_3"];
        assert_eq!(gm.chrom, "SYN_ctg_x");
        assert_eq!(gm.start, 5000);
        assert_eq!(gm.end, 5000);
        assert_eq!(gm.name, "DN_SYN_ctg_x_5000_3"); // no gene -> self name
        assert_eq!(gm.biotype, "NA");
        assert!(!out.gene_of_dn.contains_key("DN_SYN_ctg_x_5000_3"));
        assert!(!out.gene_of_dn_raw.contains_key("DN_SYN_ctg_x_5000_3"));
    }

    // ---------------------------------------------------------------- parity tests

    /// Byte-parity against the golden fixture emitted by
    /// `bench/gen_loaders_fixture.py` from the shipped Python build.
    #[test]
    fn loaders_parity() {
        let raw = include_str!("testdata/loaders_fixture.json");
        let fx: serde_json::Value = serde_json::from_str(raw).expect("parse fixture json");

        // OV_FLOOR must match the Python constant.
        let ov_floor = fx["ov_floor"].as_f64().expect("ov_floor");
        assert!(
            (ov_floor - OV_FLOOR).abs() < 1e-12,
            "fixture ov_floor {ov_floor} != OV_FLOOR {OV_FLOOR}"
        );

        // ---- (0) raw TSV parsers (load_meta / load_annot / load_raw_families / load_edges) ----
        let rp = &fx["raw_parsers"];
        // load_meta
        let meta = load_meta_str(rp["meta_tsv"].as_str().unwrap());
        for (dn, v) in rp["meta_golden"].as_object().unwrap() {
            let a = v.as_array().unwrap();
            let want = (
                a[0].as_str().unwrap().to_string(),
                a[1].as_i64().unwrap(),
                a[2].as_i64().unwrap(),
            );
            assert_eq!(meta.get(dn), Some(&want), "load_meta mismatch for {dn}");
        }
        assert_eq!(meta.len(), rp["meta_golden"].as_object().unwrap().len());
        // load_raw_families
        let fams = load_raw_families_str(rp["raw_fams_tsv"].as_str().unwrap());
        let fams_want: Vec<Vec<String>> = rp["raw_fams_golden"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| f.as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect())
            .collect();
        assert_eq!(fams, fams_want, "load_raw_families mismatch");
        // load_edges
        let edges = load_edges_str(rp["edges_tsv"].as_str().unwrap());
        let edges_want: Vec<(String, String)> = rp["edges_golden"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| {
                let p = e.as_array().unwrap();
                (p[0].as_str().unwrap().to_string(), p[1].as_str().unwrap().to_string())
            })
            .collect();
        assert_eq!(edges, edges_want, "load_edges mismatch");
        // load_annot (compare per-contig starts / maxlen / ivals)
        let annot_p = Annot::from_str(rp["annot_tsv"].as_str().unwrap());
        for (c, cg) in rp["annot_golden"].as_object().unwrap() {
            let rec = annot_p.by_contig.get(c).unwrap_or_else(|| panic!("annot contig {c} missing"));
            let starts_want: Vec<i64> =
                cg["starts"].as_array().unwrap().iter().map(|x| x.as_i64().unwrap()).collect();
            assert_eq!(rec.starts, starts_want, "annot starts mismatch {c}");
            assert_eq!(rec.maxlen, cg["maxlen"].as_i64().unwrap(), "annot maxlen mismatch {c}");
            let ivals_want: Vec<AnnotInterval> = cg["ivals"]
                .as_array()
                .unwrap()
                .iter()
                .map(|iv| {
                    let a = iv.as_array().unwrap();
                    AnnotInterval {
                        start: a[0].as_i64().unwrap(),
                        end: a[1].as_i64().unwrap(),
                        biotype: a[2].as_str().unwrap().to_string(),
                        gene: a[3].as_str().unwrap().to_string(),
                    }
                })
                .collect();
            assert_eq!(rec.ivals, ivals_want, "annot ivals mismatch {c}");
        }

        // ---- (a) build_genes_dict parity (gene_of + fallback + floor + dedup + ovstats) ----
        let bg = &fx["build_genes"];
        let raw_fams: Vec<Vec<String>> = bg["raw_fams"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| f.as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect())
            .collect();
        let meta: HashMap<String, (String, i64, i64)> = bg["meta"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(k, v)| {
                let a = v.as_array().unwrap();
                (
                    k.clone(),
                    (a[0].as_str().unwrap().to_string(), a[1].as_i64().unwrap(), a[2].as_i64().unwrap()),
                )
            })
            .collect();
        let mut by_c: HashMap<String, Vec<AnnotInterval>> = HashMap::new();
        for (c, arr) in bg["annot"].as_object().unwrap() {
            let list = arr
                .as_array()
                .unwrap()
                .iter()
                .map(|iv| {
                    let a = iv.as_array().unwrap();
                    AnnotInterval {
                        start: a[0].as_i64().unwrap(),
                        end: a[1].as_i64().unwrap(),
                        biotype: a[2].as_str().unwrap().to_string(),
                        gene: a[3].as_str().unwrap().to_string(),
                    }
                })
                .collect();
            by_c.insert(c.clone(), list);
        }
        let annot = Annot::build(by_c);

        let out = build_genes_dict(&raw_fams, &meta, &annot);
        let golden = &bg["golden"];

        // genes dict: per-DN, per-field
        let genes_g = golden["genes"].as_object().unwrap();
        assert_eq!(out.genes.len(), genes_g.len(), "genes dict size mismatch");
        let mut n_loci = 0usize;
        for (dn, gv) in genes_g {
            let got = out.genes.get(dn).unwrap_or_else(|| panic!("genes missing DN {dn}"));
            assert_eq!(got.chrom, gv["chrom"].as_str().unwrap(), "chrom {dn}");
            assert_eq!(got.start, gv["start"].as_i64().unwrap(), "start {dn}");
            assert_eq!(got.end, gv["end"].as_i64().unwrap(), "end {dn}");
            assert_eq!(got.biotype, gv["biotype"].as_str().unwrap(), "biotype {dn}");
            assert_eq!(got.name, gv["name"].as_str().unwrap(), "name {dn}");
            let ov_g = gv["ov"].as_f64().unwrap();
            assert!(
                (got.ov - ov_g).abs() <= 1e-12,
                "ov mismatch {dn}: rust {} != python {ov_g}",
                got.ov
            );
            n_loci += 1;
        }

        // gene_of_dn / gene_of_dn_raw membership + values
        let god_g: HashMap<String, String> = golden["gene_of_dn"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(k, v)| (k.clone(), v.as_str().unwrap().to_string()))
            .collect();
        assert_eq!(out.gene_of_dn, god_g, "gene_of_dn mismatch");
        let godr_g: HashMap<String, String> = golden["gene_of_dn_raw"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(k, v)| (k.clone(), v.as_str().unwrap().to_string()))
            .collect();
        assert_eq!(out.gene_of_dn_raw, godr_g, "gene_of_dn_raw mismatch");

        // miss_meta + ovstats
        assert_eq!(out.miss_meta, golden["miss_meta"].as_u64().unwrap() as usize, "miss_meta");
        let ov_g = &golden["ovstats"];
        assert_eq!(out.ovstats.mapped_raw, ov_g["mapped_raw"].as_u64().unwrap() as usize);
        assert_eq!(out.ovstats.mapped_floored, ov_g["mapped_floored"].as_u64().unwrap() as usize);
        assert_eq!(out.ovstats.dropped_by_floor, ov_g["dropped_by_floor"].as_u64().unwrap() as usize);
        assert_eq!(out.ovstats.lt20_overlap, ov_g["lt20_overlap"].as_u64().unwrap() as usize);
        assert_eq!(out.ovstats.lt50_overlap, ov_g["lt50_overlap"].as_u64().unwrap() as usize);

        // diversity guards (fixture stays representative)
        let div = &golden["diversity"];
        assert!(n_loci >= 300, "fixture too small: {n_loci} loci (< 300)");
        assert!(div["mapped_above_floor"].as_u64().unwrap() >= 100, "too few above-floor loci");
        assert!(div["mapped_below_floor_na"].as_u64().unwrap() >= 10, "too few below-floor (NA) loci");
        assert!(div["no_overlap"].as_u64().unwrap() >= 20, "too few no-overlap loci");
        assert!(div["missing_meta"].as_u64().unwrap() >= 5, "too few missing-meta loci");
        assert!(div["ties"].as_u64().unwrap() >= 2, "too few gene_of tie loci");

        // ---- (b) components_from_edges parity (set of node-sets) ----
        let mut n_comp_cases = 0usize;
        for case in fx["components"].as_array().unwrap() {
            let label = case["label"].as_str().unwrap();
            let all_nodes: Vec<String> =
                case["all_nodes"].as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect();
            let kept_edges: Vec<(String, String)> = case["kept_edges"]
                .as_array()
                .unwrap()
                .iter()
                .map(|e| {
                    let p = e.as_array().unwrap();
                    (p[0].as_str().unwrap().to_string(), p[1].as_str().unwrap().to_string())
                })
                .collect();
            let golden_set: HashSet<BTreeSet<String>> = case["golden"]
                .as_array()
                .unwrap()
                .iter()
                .map(|c| c.as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect())
                .collect();
            let got_set: HashSet<BTreeSet<String>> =
                components_from_edges(&all_nodes, &kept_edges).into_iter().collect();
            assert_eq!(
                got_set, golden_set,
                "COMPONENTS PARITY MISMATCH case '{label}': rust {} comps vs python {}",
                got_set.len(),
                golden_set.len()
            );
            n_comp_cases += 1;
        }
        assert!(n_comp_cases >= 5, "too few component cases: {n_comp_cases}");

        eprintln!(
            "loaders parity: build_genes_dict {n_loci} loci OK (above={} below-NA={} no-ov={} miss-meta={} ties={}); \
             {n_comp_cases} component cases OK; TSV parsers OK",
            div["mapped_above_floor"], div["mapped_below_floor_na"], div["no_overlap"],
            div["missing_meta"], div["ties"]
        );
    }
}
