//! Canonical (k, w)-minimizers -- faithful Rust port of `bench/vg_repeat_catalog.py`.
//!
//! This is the FOUNDATION + byte-parity crux of the O1 over-merge-gate migration
//! (`docs/RETIREMENT_AND_MIGRATION.md` Tier-2 #7: the `vg_repeat_catalog.py` /
//! `multi_repeat_bridge_gate.py` repeat-bridge gate, full-port path). Every gate
//! that rests on the repeat catalog -- `recombination_bridge_detector`,
//! `vg_repeat_catalog`, `recombinant_split`, `multi_repeat_bridge_gate` -- consumes
//! the output of this ONE function, so once it is byte-exact the remaining gate
//! port is mechanical.
//!
//! SPEC (the Python is the ground truth; line refs are `bench/vg_repeat_catalog.py`):
//!   * constants K=15, W=10 (:69-70); `_B` 2-bit base map (:76).
//!   * `def minimizers(seq, k=K, w=W) -> list[(canon_value:int, masked_bool)]` (:115).
//!   * Returns collapsed RUNS of selected canonical minimizers (consecutive identical
//!     `canon` selections merged into one emitted `(canon, masked)`).
//!
//! DETERMINISTIC: pure 2-bit canonical encoding (no hashing / RNG), leftmost-tie
//! minimizers (strict `>` deque eviction), N resets the k-mer window.
//!
//! Verified byte-identical to the shipped Python `minimizers` against a golden
//! fixture (`testdata/minimizers_fixture.json`, generated by
//! `bench/gen_minimizers_fixture.py`); see the `#[test]`s at the bottom.
//!
//! NOTE on input bytes: the Python does `b = seq.encode("ascii", "replace")` and
//! then indexes `b[i]`, so any non-ASCII CHARACTER is first collapsed to a single
//! `?` (0x3F) byte. This port takes `&[u8]` directly (the callers pass genome/exon
//! bytes, which are ASCII). For ASCII input the two are identical; a stray byte
//! >= 128 takes the same `code < 0` RESET path here as the `?` does in Python
//! (`is_lc` is only consulted when `code >= 0`), so the reset behaviour matches --
//! only the (never-exercised, non-ASCII) byte-vs-character length would differ.
//!
//! **STATUS:** INFRASTRUCTURE  (docs/MODULE_STATUS.md; assigned by reachability, not by this header)

use std::collections::VecDeque;

/// Minimizer k (k-mer length). `bench/vg_repeat_catalog.py:69  K = 15`.
pub const MINIMIZER_K: usize = 15;
/// Minimizer window w (w consecutive k-mers). `bench/vg_repeat_catalog.py:70  W = 10`.
pub const MINIMIZER_W: usize = 10;

/// 2-bit base code, exactly the Python `_B` map
/// (`vg_repeat_catalog.py:76  _B = {65:0,67:1,71:2,84:3, 97:0,99:1,103:2,116:3}`):
/// A/a -> 0, C/c -> 1, G/g -> 2, T/t -> 3; every other byte -> -1 (the Python
/// `_B.get(c, -1)`), which RESETS the rolling k-mer window (N, gap, ambiguity code).
#[inline]
fn base_code(byte: u8) -> i32 {
    match byte {
        b'A' | b'a' => 0,
        b'C' | b'c' => 1,
        b'G' | b'g' => 2,
        b'T' | b't' => 3,
        _ => -1,
    }
}

/// Collapsed runs of selected canonical (k, w)-minimizers over `seq`.
///
/// Returns `Vec<(canon_value, masked)>`; consecutive identical `canon` selections
/// are merged into a single run (the Python `last_val` collapse). `canon` is the
/// strand-agnostic `min(forward_code, revcomp_code)` of the k-mer (so an inverted
/// paralog yields the same node); `masked` is `true` iff the k-mer's `k`-base window
/// is majority-lowercase (soft-masked). An `N`/ambiguous base RESETS the window.
///
/// Faithful port of `minimizers` (`bench/vg_repeat_catalog.py:115-175`). The value
/// type is `u64` for headroom; k=15 => 30 bits, which also fits `u32`.
pub fn minimizers(seq: &[u8], k: usize, w: usize) -> Vec<(u64, bool)> {
    let n = seq.len();
    // Python: if n < k: return []
    if n < k {
        return Vec::new();
    }
    // kmask = (1 << (2*k)) - 1 ; shift = 2*(k-1)  (vg_repeat_catalog.py:122-123)
    let kmask: u64 = (1u64 << (2 * k)) - 1;
    let shift: u32 = (2 * (k - 1)) as u32;

    // ------------------------------------------------------------------ rolling pass
    // Per k-mer END position: canon value (None while the window is invalid) + the
    // majority-lowercase flag. Mirrors the Python `canon` / `masked` lists exactly.
    let mut canon: Vec<Option<u64>> = Vec::with_capacity(n);
    let mut masked: Vec<bool> = Vec::with_capacity(n);
    let mut f: u64 = 0; // forward rolling 2-bit code
    let mut r: u64 = 0; // reverse-complement rolling 2-bit code
    let mut valid: usize = 0; // length of the current uninterrupted (non-N) run
    let mut lc: VecDeque<u8> = VecDeque::new(); // lowercase flags of the current k-window
    let mut lc_sum: usize = 0; // popcount of `lc`

    for &c in seq.iter() {
        let code = base_code(c);
        // Python: is_lc = 1 if 97 <= c <= 122 else 0  (only consulted when code >= 0)
        let is_lc: u8 = if (97..=122).contains(&c) { 1 } else { 0 };
        if code < 0 {
            // N / other -> RESET the window and clear the lowercase deque.
            f = 0;
            r = 0;
            valid = 0;
            lc.clear();
            lc_sum = 0;
            canon.push(None);
            masked.push(false);
            continue;
        }
        let code = code as u64;
        // f = ((f << 2) | code) & kmask ; r = (r >> 2) | ((3 - code) << shift)
        f = ((f << 2) | code) & kmask;
        r = (r >> 2) | ((3 - code) << shift);
        // push lowercase flag; trim the window to the last k bases (lc_sum tracks it)
        lc.push_back(is_lc);
        lc_sum += is_lc as usize;
        if lc.len() > k {
            lc_sum -= lc.pop_front().unwrap() as usize;
        }
        valid += 1;
        if valid >= k {
            // canon = f if f < r else r ; masked = 1 if lc_sum*2 > k else 0
            canon.push(Some(if f < r { f } else { r }));
            masked.push(lc_sum * 2 > k);
        } else {
            canon.push(None);
            masked.push(false);
        }
    }

    // ------------------------------------------------- window-min (monotonic deque)
    // `dq` holds indices into `canon` in strictly-increasing VALUE order; the strict
    // `>` eviction keeps the LEFTMOST index on value ties. `positions` = the indices
    // where a valid k-mer ended (canon is Some); windows are over w CONSECUTIVE valid
    // k-mers, so a window may straddle an N-gap exactly as in Python.
    let mut out: Vec<(u64, bool)> = Vec::new();
    let mut dq: VecDeque<usize> = VecDeque::new();
    let mut last_val: Option<u64> = None;
    let positions: Vec<usize> = (0..canon.len()).filter(|&i| canon[i].is_some()).collect();

    for (idx, &p) in positions.iter().enumerate() {
        let v = canon[p].expect("positions only holds Some canon indices");
        // while dq and canon[dq[-1]] > v: dq.pop()   (STRICT > => leftmost tie kept)
        while let Some(&back) = dq.back() {
            if canon[back].expect("dq holds valid positions") > v {
                dq.pop_back();
            } else {
                break;
            }
        }
        dq.push_back(p);
        // Python: if idx >= w - 1   (guard usize underflow as idx + 1 >= w)
        if idx + 1 >= w {
            // window of the last w k-mers => positions[idx-w+1 .. idx]
            let left_p = positions[idx + 1 - w];
            // while dq[0] < left_p: dq.popleft()   (evict out-of-window-left)
            while let Some(&front) = dq.front() {
                if front < left_p {
                    dq.pop_front();
                } else {
                    break;
                }
            }
            let sel = *dq.front().expect("window is non-empty");
            let val = canon[sel].expect("sel is a valid position");
            // collapse consecutive identical selections into runs (Python `last_val`)
            if last_val != Some(val) {
                out.push((val, masked[sel]));
                last_val = Some(val);
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---------------------------------------------------------------- unit corners

    #[test]
    fn empty_and_below_k_return_empty() {
        assert!(minimizers(b"", MINIMIZER_K, MINIMIZER_W).is_empty());
        // len < k -> [] (14 < 15)
        assert!(minimizers(b"ACGTACGTACGTAC", MINIMIZER_K, MINIMIZER_W).is_empty());
        assert!(minimizers(&vec![b'A'; MINIMIZER_K - 1], MINIMIZER_K, MINIMIZER_W).is_empty());
        // exactly k bases = a SINGLE k-mer -> still [] : the first run is only emitted
        // once a full window of w k-mers exists (Python guard `idx >= w - 1`), which
        // needs k + w - 1 bases. So exactly k and any length < k+w-1 emit nothing.
        assert!(minimizers(&vec![b'A'; MINIMIZER_K], MINIMIZER_K, MINIMIZER_W).is_empty());
        assert!(
            minimizers(&vec![b'A'; MINIMIZER_K + MINIMIZER_W - 2], MINIMIZER_K, MINIMIZER_W)
                .is_empty(),
            "k+w-2 bases = w-1 k-mers -> no full window yet"
        );
        // k + w - 1 bases = exactly w k-mers -> the first (single collapsed) run.
        assert_eq!(
            minimizers(&vec![b'A'; MINIMIZER_K + MINIMIZER_W - 1], MINIMIZER_K, MINIMIZER_W).len(),
            1
        );
    }

    #[test]
    fn homopolymer_collapses_to_one_run() {
        // A homopolymer -> every k-mer has the same canonical value -> the window-min
        // is constant -> the run-collapse yields exactly ONE emitted tuple.
        let a = minimizers(&vec![b'A'; 200], MINIMIZER_K, MINIMIZER_W);
        assert_eq!(a.len(), 1, "homopolymer should collapse to a single run");
        // poly-A: canon(AAAA...) forward=0, so min(f,r)=0.
        assert_eq!(a[0].0, 0);
        assert!(!a[0].1); // uppercase -> not masked
    }

    #[test]
    fn single_n_resets_the_window() {
        // An interior N clears the rolling window: the k-mers spanning the N are
        // dropped (canon=None), so a single N in an otherwise-uniform run cannot
        // increase the count of DISTINCT emitted values beyond the homopolymer's one.
        let mut s = vec![b'A'; 100];
        s[50] = b'N';
        let out = minimizers(&s, MINIMIZER_K, MINIMIZER_W);
        // still all A on both sides -> single collapsed value 0
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].0, 0);
        // a leading N-run then k A's still yields the poly-A minimizer
        let mut s2 = vec![b'N'; 20];
        s2.extend(std::iter::repeat(b'A').take(30));
        assert_eq!(minimizers(&s2, MINIMIZER_K, MINIMIZER_W), vec![(0u64, false)]);
    }

    #[test]
    fn lowercase_majority_masks() {
        // A fully-lowercase homopolymer: lc_sum = k = 15, 15*2=30 > 15 -> masked.
        let out = minimizers(&vec![b'a'; 200], MINIMIZER_K, MINIMIZER_W);
        assert_eq!(out.len(), 1);
        assert!(out[0].1, "all-lowercase k-window is majority-lowercase -> masked");
        assert_eq!(out[0].0, 0); // canon of poly-A(lower) == poly-A == 0
    }

    // ---------------------------------------------------------------- parity test

    /// Byte-parity against the golden fixture emitted by
    /// `bench/gen_minimizers_fixture.py` from the shipped Python `minimizers`.
    /// Reports the first differing sequence + position.
    #[test]
    fn minimizers_parity() {
        let raw = include_str!("testdata/minimizers_fixture.json");
        let fx: serde_json::Value = serde_json::from_str(raw).expect("parse fixture json");

        // constants must match the Python K / W
        assert_eq!(fx["k"].as_u64().unwrap() as usize, MINIMIZER_K, "K drift");
        assert_eq!(fx["w"].as_u64().unwrap() as usize, MINIMIZER_W, "W drift");

        let cases = fx["cases"].as_array().expect("cases array");
        assert!(cases.len() >= 60, "fixture too small: {} cases (need >= 60)", cases.len());

        let mut n_checked = 0usize;
        let mut classes: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
        for case in cases {
            let name = case["name"].as_str().unwrap_or("<unnamed>");
            let class = case["class"].as_str().unwrap_or("<none>");
            classes.insert(class.to_string());
            let seq = case["seq"].as_str().expect("seq string");

            // golden Python output: list of [canon:int, masked:0|1]
            let golden: Vec<(u64, bool)> = case["out"]
                .as_array()
                .unwrap()
                .iter()
                .map(|e| {
                    let a = e.as_array().unwrap();
                    (a[0].as_u64().unwrap(), a[1].as_u64().unwrap() != 0)
                })
                .collect();

            let got = minimizers(seq.as_bytes(), MINIMIZER_K, MINIMIZER_W);

            assert_eq!(
                got.len(),
                golden.len(),
                "LENGTH MISMATCH case '{name}' (class {class}): rust {} runs != python {} runs\n  seq = {seq}",
                got.len(),
                golden.len()
            );
            for (i, (g, e)) in got.iter().zip(golden.iter()).enumerate() {
                assert_eq!(
                    g, e,
                    "MISMATCH case '{name}' (class {class}) at run {i}: rust {g:?} != python {e:?}\n  seq = {seq}"
                );
            }
            n_checked += 1;
        }

        // edge-class coverage guard (the fixture must exercise every class)
        for required in [
            "empty",
            "below_k",
            "exactly_k",
            "homopolymer",
            "random_acgt",
            "with_n",
            "mixed_case",
            "revcomp",
            "tandem",
        ] {
            assert!(
                classes.contains(required),
                "fixture missing edge class '{required}' (have: {classes:?})"
            );
        }

        eprintln!(
            "minimizers parity: {n_checked} sequences byte-identical to Python; classes = {classes:?}"
        );
    }
}
