//! O1 multi-repeat-bridge gate -- faithful Rust port of the WIRED path of
//! `bench/multi_repeat_bridge_gate.py` (MRB) (the O1 over-merge-gate migration,
//! `docs/RETIREMENT_AND_MIGRATION.md` Tier-2 #7, full byte-parity path).
//!
//! WHAT THIS GATE DOES.  It removes the DISCONNECTED repeat-bridge RNA-level over-merge
//! class: families whose pairwise `E_r` oracle glued loci that share NO FULL EXON at
//! `id >= 0.70` (a sub-exonic Alu/repeat bridge, not real transcript homology) yet
//! survive the single-extreme-edge repeat-hub gate.  The recall-safe distinguisher is
//! the CONJUNCTION: (>=2 full-exon components AND cross-component best-exon-id < 0.70 =
//! NO full shared exon) AND (>= `several` DISTINCT cross-component shared VG minimizer
//! nodes each with global multiplicity >= `t`) AND the same-gene guard (never separate
//! same-gene loci).  GSTM2 (domain-share) + MAGE (cardinality) share a full exon => the
//! family is a SINGLE full-exon component => the gate STRUCTURALLY cannot fire (spared
//! at every threshold), which is the load-bearing "no-full-shared-exon" conjunct.
//!
//! WIRED PATH ONLY.  The DRIVER (`family_rna_refine.build_catalog`) calls exactly
//! `MRB.split_families_repeat_bridge(refined, genes, gene_of_dn, t=8, several=2)`; its
//! reachable code is `split_families_repeat_bridge` [:664] -> `split_family_repeat_bridge`
//! [:638] -> `characterize` [:122] + `gate_cut` [:229] (+ `_block_members` [:624],
//! `locus_node_set` [:103], `load_node_mult` [:86], `_stage_loaders` [:605]).  Ported here.
//!
//! DEFERRED (NOT wired-runtime -- analysis / gate-stage / sweeps; see the report):
//!   * `main` [:258], `gate_stage` [:773], `_rederive_disconnected` [:242],
//!     `analyze_family` (in RBD), `apply_gate`/`run_scope`, the MULT_GRID/SEVERAL_GRID
//!     sweeps, `_verdict`/`_gate_verdict`/`_metrics`/`_oracle_recall`/
//!     `real_loss_provenance`/`_cut_truth_classes`.
//!
//! REUSES the already-ported libraries -- nothing re-derived:
//!   * `super::bridge_detector`: `family_exons` / `exon_match_tensor` / `build_graph` /
//!     `connected_components` / `cross_component_maxid` + `ID_THRESH` (RBD exon graph),
//!     and `load_strand` (RBD's `_stage_loaders` strand map);
//!   * `super::repeat_catalog::dn_exons` (`vg_repeat_catalog.dn_exons`, introns-string
//!     convention) + `super::minimizers::{minimizers, MINIMIZER_K, MINIMIZER_W}` for the
//!     canonical-minimizer `locus_node_set`;
//!   * `super::family_loaders::GeneMeta` for the `genes` dict shape.
//!
//! fa_up vs fa_mask.  MRB opens TWO handles: `fa_up = FastaFile(R.GENOME)` and
//! `fa_mask = FastaFile(V.GENOME)`.  In the shipped build R.GENOME == V.GENOME ==
//! `GGO.fasta` (the SAME soft-masked file); `family_exons` reads via `fa_up` and
//! `.upper()`s every exon (exon IDENTITY is case-insensitive), while `locus_node_set`
//! reads via `fa_mask` and feeds the case-carrying bytes to `minimizers`.  BUT
//! `locus_node_set` returns `set(val for val, _ in minimizers(s))` -- it DISCARDS the
//! per-minimizer `masked` bool, and the canonical 2-bit `val` is itself case-insensitive
//! (`base_code` maps A/a,C/c,... identically).  So the node VALUES are independent of the
//! genome's soft-mask; `fa_up` and `fa_mask` are the same bytes here and the port takes a
//! single `ExonFetcher` for both.  (`family_exons` still upper-cases; `minimizers` still
//! reads the raw bytes -- both are honoured exactly.)
//!
//! Verified byte-identical to the shipped Python build against a golden fixture
//! (`testdata/multi_repeat_bridge_fixture.json`, generated by
//! `bench/gen_multi_repeat_bridge_fixture.py`, PYTHONHASHSEED=0); see the `#[test]`s.
//!
//! **STATUS:** OTHER-BINARY — family_define; default-ON there (driver.rs:143 `repeat_bridge_gate: true`), opt-OUT via --no-repeat-bridge-gate or RUSTLE_NO_REPEAT_BRIDGE_GATE=1 (src  (docs/MODULE_STATUS.md; assigned by reachability, not by this header)

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};

use super::bridge_detector::{
    build_graph, cross_component_maxid, exon_match_tensor, family_exons, ExonFetcher, Member,
    ID_THRESH,
};
use super::family_loaders::GeneMeta;
use super::minimizers::{minimizers, MINIMIZER_K, MINIMIZER_W};
use super::repeat_catalog::dn_exons;

/// T: per-node canonical-minimizer multiplicity operating point.
/// `bench/multi_repeat_bridge_gate.py:599  WIRED_MULT_MIN = 8`.
pub const WIRED_MULT_MIN: usize = 8;
/// C: >= C distinct cross-component shared VG nodes at mult >= T.
/// `bench/multi_repeat_bridge_gate.py:600  WIRED_COUNT_MIN = 2`.
pub const WIRED_COUNT_MIN: usize = 2;
/// Cap family size for the O(n^2 exon) tensor (families with `> MAX_MEMBERS` recs are
/// reported skipped, never cut). `bench/multi_repeat_bridge_gate.py:66  MAX_MEMBERS = 30`.
pub const MAX_MEMBERS: usize = 30;
/// The swept multiplicity thresholds `characterize` precomputes `rep_bridges` over.
/// `bench/multi_repeat_bridge_gate.py:63  MULT_GRID = [5, 8, 12, 20]`. The wired
/// `gate_cut(pl, 8, 2)` reads `rep_bridges[8]`; a `t` outside this grid reads 0
/// (Python `row["rep_bridges"].get(t, 0)`), reproduced exactly by `gate_cut`.
pub const MULT_GRID: [usize; 4] = [5, 8, 12, 20];

// ===========================================================================
// load_node_mult  (multi_repeat_bridge_gate.py:86)
// ===========================================================================

/// The global per-node `(multiplicity, cyclic)` maps, parsed from the "# SECTION
/// nodes (mult>=2)" block of the shipped `bench/vg_repeat_catalog.tsv`.
///
/// Faithful port of `load_node_mult` (:86): drop the first two lines (the section
/// banner + the column header), then for each subsequent line STOP at the
/// "# SECTION edges" banner, split on `\t`, and record `mult[f0] = int(f1)` and
/// `cyclic[f0] = int(f3)`. Nodes ABSENT from this section default to `mult 1` /
/// `cyclic 0` at every lookup (they are the unique/low-mult minimizers not written
/// to the table). Returns `(mult, cyclic)`.
pub fn parse_node_mult(text: &str) -> (HashMap<u64, usize>, HashMap<u64, usize>) {
    let mut mult = HashMap::new();
    let mut cyclic = HashMap::new();
    let mut lines = text.lines();
    lines.next(); // "# SECTION nodes (mult>=2)"
    lines.next(); // header
    for ln in lines {
        if ln.starts_with("# SECTION edges") {
            break;
        }
        let f: Vec<&str> = ln.split('\t').collect();
        // Python: code = int(f[0]); mult[code]=int(f[1]); cyclic[code]=int(f[3])
        let code: u64 = match f[0].parse() {
            Ok(v) => v,
            Err(_) => continue,
        };
        mult.insert(code, f[1].parse().expect("node multiplicity parses"));
        cyclic.insert(code, f[3].parse().expect("node cyclic flag parses"));
    }
    (mult, cyclic)
}

/// Read + parse the `vg_repeat_catalog.tsv` node section (see `parse_node_mult`).
pub fn load_node_mult(path: &str) -> std::io::Result<(HashMap<u64, usize>, HashMap<u64, usize>)> {
    Ok(parse_node_mult(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// locus_node_set  (multi_repeat_bridge_gate.py:103)
// ===========================================================================

/// The canonical-minimizer NODE SET of a locus = EXACTLY `vg_repeat_catalog`'s
/// construction: the spliced exonic sequence (`dn_exons` complement of the introns +
/// per-exon genome fetch, case-carrying) run through `minimizers`, keeping the
/// canonical VALUES (the per-minimizer `masked` bool is DISCARDED).
///
/// Faithful port of `locus_node_set` (:103):
///   * `meta.get(dn)` miss  -> `None` (Python returns `None`; `characterize` maps it to
///     an empty set);
///   * `V.dn_exons(dn, meta, vskel)` -> `(chrom, exons)` (never `None` here since meta
///     hit); an empty exon list => empty spliced sequence;
///   * the fetch join is wrapped in `try/except` -> any failed fetch yields the empty
///     set (here: a `None` from `fa.fetch` on any exon -> `Some(empty)`);
///   * `if len(s) < K: return set()`;
///   * else `set(val for val, _ in minimizers(s))`.
pub fn locus_node_set<F: ExonFetcher>(
    dn: &str,
    meta: &HashMap<String, (String, i64, i64)>,
    vskel: &HashMap<(String, i64, i64), String>,
    fa: &F,
) -> Option<HashSet<u64>> {
    // mm = meta.get(dn); if mm is None: return None
    meta.get(dn)?;
    // chrom, exons = V.dn_exons(dn, meta, vskel)   (Some, since meta hit)
    let (chrom, exons) = match dn_exons(dn, meta, vskel) {
        Some(x) => x,
        None => return Some(HashSet::new()), // defensive; unreachable on a meta hit
    };
    // s = "".join(fa.fetch(chrom, a, b) for a, b in exons)   (try/except -> empty set)
    let mut s: Vec<u8> = Vec::new();
    for (a, b) in exons {
        match fa.fetch(&chrom, a, b) {
            Some(part) => s.extend_from_slice(&part),
            None => return Some(HashSet::new()), // Python `except -> set()`
        }
    }
    if s.len() < MINIMIZER_K {
        return Some(HashSet::new());
    }
    Some(
        minimizers(&s, MINIMIZER_K, MINIMIZER_W)
            .into_iter()
            .map(|(val, _)| val)
            .collect(),
    )
}

// ===========================================================================
// _block_members  (multi_repeat_bridge_gate.py:624)
// ===========================================================================

/// Member dicts `(dn, gene, chrom, start, end)` for a block of DN loci. Faithful port
/// of `_block_members` (:624): iterate `sorted(block)`, drop any `dn` absent from
/// `genes`, else build a member with `gene = gene_of_dn.get(dn, "NA")` and
/// `chrom/start/end` from `genes[dn]`.
pub fn block_members(
    block: &[String],
    genes: &HashMap<String, GeneMeta>,
    gene_of_dn: &HashMap<String, String>,
) -> Vec<Member> {
    let mut sb: Vec<String> = block.to_vec();
    sb.sort();
    let mut ms = Vec::new();
    for dn in &sb {
        let g = match genes.get(dn) {
            None => continue,
            Some(g) => g,
        };
        ms.push(Member {
            dn: dn.clone(),
            gene: gene_of_dn.get(dn).cloned().unwrap_or_else(|| "NA".to_string()),
            chrom: g.chrom.clone(),
            start: g.start,
            end: g.end,
        });
    }
    ms
}

// ===========================================================================
// characterize  (multi_repeat_bridge_gate.py:122)  -- THE CORE
// ===========================================================================

/// The per-family CHARACTERIZE "plan": the full-exon component split + the fields the
/// gate reads. Mirrors the Python `dict` returned by `characterize`.
///
/// `characterize` returns `None` (Python) iff `n < 2` (fewer than 2 skeleton'd recs);
/// otherwise a `Plan` with `skipped == true` iff `n > MAX_MEMBERS` (in which case only
/// `n_members` / `n_distinct_genes` / `same_gene_family` are meaningful and `comps_dn`
/// / `all_dn` are empty, mirroring the Python `comps_dn=None, all_dn=None`).
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Plan {
    pub n_members: usize,
    pub n_distinct_genes: usize,
    pub same_gene_family: bool,
    pub skipped: bool,
    // -- below only meaningful when `!skipped` --
    pub n_comp: usize,
    pub connected: bool,
    pub shares_full_exon: bool,
    /// `None` iff `n_comp <= 1` (Python `xcomp_id = ... if n_comp > 1 else None`).
    pub xcomp_best_exon_id: Option<f64>,
    pub no_full_shared_exon: bool,
    pub n_cross_pairs: usize,
    pub n_cross_pairs_with_node: usize,
    pub n_cross_shared_nodes: usize,
    pub max_cross_mult: usize,
    pub med_cross_mult: usize,
    pub n_cross_cyclic: usize,
    /// `t -> #distinct cross-component shared nodes with multiplicity >= t`, over MULT_GRID.
    pub rep_bridges: BTreeMap<usize, usize>,
    pub n_internal_shared_nodes: usize,
    pub max_internal_mult: usize,
    pub n_internal_repeat_m8: usize,
    pub min_comp_size: usize,
    pub separates_same_gene: bool,
    pub guard_ok: bool,
    /// full-exon components as sorted DN lists (Python `comps_dn`, frozensets -> sorted).
    pub comps_dn: Vec<Vec<String>>,
    /// every DN kept by `family_exons`, in rec order (Python `all_dn`).
    pub all_dn: Vec<String>,
}

/// `_distinct_genes(members)` (:254): sorted set of member genes excluding `"NA"`/`""`.
fn distinct_genes(members: &[Member]) -> Vec<String> {
    let mut s: BTreeSet<String> = BTreeSet::new();
    for m in members {
        if m.gene != "NA" && !m.gene.is_empty() {
            s.insert(m.gene.clone());
        }
    }
    s.into_iter().collect()
}

/// Build the CHARACTERIZE plan for a family. Faithful port of `characterize` (:122);
/// see the field-by-field comments. Returns `None` iff `n < 2`.
///
/// `fa_up` feeds `family_exons` (`.upper()`ed exon identity); `fa_mask` feeds
/// `locus_node_set` (case-carrying minimizers). In the shipped build these are the SAME
/// genome; the two parameters are kept distinct to mirror `characterize`'s signature.
#[allow(clippy::too_many_arguments)]
pub fn characterize<F: ExonFetcher, G: ExonFetcher>(
    members: &[Member],
    r_skel: &HashMap<(String, i64, i64), Vec<(i64, i64)>>,
    strand: &HashMap<String, String>,
    fa_up: &F,
    meta: &HashMap<String, (String, i64, i64)>,
    vskel: &HashMap<(String, i64, i64), String>,
    fa_mask: &G,
    mult: &HashMap<u64, usize>,
    cyclic: &HashMap<u64, usize>,
) -> Option<Plan> {
    let recs = family_exons(members, r_skel, strand, fa_up);
    let n = recs.len();
    if n < 2 {
        return None;
    }
    let dg = distinct_genes(members);
    let n_distinct_genes = dg.len();
    let same_gene_family = n_distinct_genes <= 1;

    if n > MAX_MEMBERS {
        // skip dict: only n_members / n_distinct_genes / same_gene_family meaningful.
        return Some(Plan {
            n_members: n,
            n_distinct_genes,
            same_gene_family,
            skipped: true,
            ..Default::default()
        });
    }

    // ---- full-exon locus graph (REUSE the recombination detector) ----
    let best = exon_match_tensor(&recs);
    let graph = build_graph(&recs, &best);
    let comps = graph.connected_components(); // sorted comps, sorted by first element
    let n_comp = comps.len();
    let comps_dn: Vec<Vec<String>> = comps
        .iter()
        .map(|comp| {
            // frozenset(recs[i]["dn"] for i in comp) -> sorted DN list
            let mut s: BTreeSet<String> = BTreeSet::new();
            for &i in comp {
                s.insert(recs[i].dn.clone());
            }
            s.into_iter().collect()
        })
        .collect();
    let all_dn: Vec<String> = recs.iter().map(|r| r.dn.clone()).collect();
    let connected = n_comp == 1;
    let shares_full_exon = connected;
    let xcomp_id = if n_comp > 1 {
        Some(cross_component_maxid(&recs, &best, &comps))
    } else {
        None
    };
    let no_full_shared_exon = n_comp >= 2 && xcomp_id.map(|x| x < ID_THRESH).unwrap_or(false);

    // comp_of[i]
    let mut comp_of: Vec<usize> = vec![0; n];
    for (ci, comp) in comps.iter().enumerate() {
        for &m in comp {
            comp_of[m] = ci;
        }
    }

    // ---- per-locus node sets ----
    let nodesets: Vec<HashSet<u64>> = recs
        .iter()
        .map(|r| locus_node_set(&r.dn, meta, vskel, fa_mask).unwrap_or_default())
        .collect();

    // ---- cross-component (bridge) shared nodes vs all-pairs internal shared nodes ----
    let mut cross_shared: HashMap<u64, usize> = HashMap::new();
    let mut cross_codes: Vec<u64> = Vec::new(); // distinct keys (order irrelevant to outputs)
    let mut internal_shared: HashSet<u64> = HashSet::new();
    let mut n_cross_pairs = 0usize;
    let mut n_cross_pairs_with_node = 0usize;
    for a in 0..n {
        for b in (a + 1)..n {
            let sh: Vec<u64> = nodesets[a].intersection(&nodesets[b]).copied().collect();
            for &c in &sh {
                internal_shared.insert(c);
            }
            if comp_of[a] != comp_of[b] {
                n_cross_pairs += 1;
                if !sh.is_empty() {
                    n_cross_pairs_with_node += 1;
                }
                for &c in &sh {
                    let e = cross_shared.entry(c).or_insert(0);
                    if *e == 0 {
                        cross_codes.push(c);
                    }
                    *e += 1;
                }
            }
        }
    }

    let mut cross_mults: Vec<usize> = cross_codes.iter().map(|&c| mult_of(mult, c)).collect();
    cross_mults.sort_unstable();
    let mut rep_bridges: BTreeMap<usize, usize> = BTreeMap::new();
    for &t in MULT_GRID.iter() {
        let nb = cross_codes.iter().filter(|&&c| mult_of(mult, c) >= t).count();
        rep_bridges.insert(t, nb);
    }
    let n_cross_cyclic = cross_codes
        .iter()
        .filter(|&&c| cyclic.get(&c).copied().unwrap_or(0) != 0)
        .count();
    let max_cross_mult = cross_mults.last().copied().unwrap_or(0);
    let med_cross_mult = if cross_mults.is_empty() {
        0
    } else {
        cross_mults[cross_mults.len() / 2]
    };

    let internal_mults: Vec<usize> = internal_shared.iter().map(|&c| mult_of(mult, c)).collect();
    let max_internal_mult = internal_mults.iter().copied().max().unwrap_or(0);
    let n_internal_repeat_m8 = internal_mults.iter().filter(|&&v| v >= 8).count();

    // ---- recall-safety guard (never separate same-gene loci) ----
    let min_comp_size = comps.iter().map(|c| c.len()).min().unwrap_or(n);
    let mut gene_comps: HashMap<String, BTreeSet<usize>> = HashMap::new();
    for (i, r) in recs.iter().enumerate() {
        if r.gene != "NA" && !r.gene.is_empty() {
            gene_comps.entry(r.gene.clone()).or_default().insert(comp_of[i]);
        }
    }
    let separates_same_gene = gene_comps.values().any(|cs| cs.len() >= 2);
    let guard_ok = n_comp >= 2 && !separates_same_gene;

    Some(Plan {
        n_members: n,
        n_distinct_genes,
        same_gene_family,
        skipped: false,
        n_comp,
        connected,
        shares_full_exon,
        xcomp_best_exon_id: xcomp_id,
        no_full_shared_exon,
        n_cross_pairs,
        n_cross_pairs_with_node,
        n_cross_shared_nodes: cross_codes.len(),
        max_cross_mult,
        med_cross_mult,
        n_cross_cyclic,
        rep_bridges,
        n_internal_shared_nodes: internal_shared.len(),
        max_internal_mult,
        n_internal_repeat_m8,
        min_comp_size,
        separates_same_gene,
        guard_ok,
        comps_dn,
        all_dn,
    })
}

/// `mult.get(c, 1)` -- absent nodes default to multiplicity 1 (Python).
#[inline]
fn mult_of(mult: &HashMap<u64, usize>, c: u64) -> usize {
    mult.get(&c).copied().unwrap_or(1)
}

// ===========================================================================
// gate_cut  (multi_repeat_bridge_gate.py:229)
// ===========================================================================

/// The CONJUNCTION gate decision. Faithful port of `gate_cut` (:229): CUT iff
/// (NOT skipped) AND (`no_full_shared_exon`) AND (`rep_bridges[t] >= several`) AND
/// (`guard_ok`). A `t` outside MULT_GRID reads `rep_bridges.get(t) -> 0` (Python
/// `.get(t, 0)`), so the gate does not fire for it.
pub fn gate_cut(plan: &Plan, t: usize, several: usize) -> bool {
    if plan.skipped {
        return false;
    }
    if !plan.no_full_shared_exon {
        return false;
    }
    if plan.rep_bridges.get(&t).copied().unwrap_or(0) < several {
        return false;
    }
    if !plan.guard_ok {
        return false;
    }
    true
}

// ===========================================================================
// split_family_repeat_bridge  (multi_repeat_bridge_gate.py:638)
// ===========================================================================

/// A cached loader bundle for the gate (`_stage_loaders`, :605) -- the RNA
/// exon-structure + genome + VG-multiplicity inputs `characterize` needs. `fa_up` /
/// `fa_mask` are separate handles in Python; here a single `ExonFetcher` backs both.
pub struct StageLoaders<'a, F: ExonFetcher> {
    pub r_skel: &'a HashMap<(String, i64, i64), Vec<(i64, i64)>>,
    pub strand: &'a HashMap<String, String>,
    pub vskel: &'a HashMap<(String, i64, i64), String>,
    pub meta: &'a HashMap<String, (String, i64, i64)>,
    pub fa: &'a F,
    pub mult: &'a HashMap<u64, usize>,
    pub cyclic: &'a HashMap<u64, usize>,
}

/// Return a PARTITION of `block` (list of sorted DN-lists) plus the plan. Faithful port
/// of `split_family_repeat_bridge` (:638): build members; if `< 2`, no split; else
/// `characterize`; if the plan is skipped or `gate_cut` does not fire, no split; else
/// replace the block by its full-exon components (`comps_dn`) plus leftover
/// no-skeleton singletons (`sorted(set(block) - covered)`), then sort the parts by first
/// element. Returns `(parts, Some(plan))` on a cut, `([sorted(block)], plan_or_none)`
/// otherwise (the plan is returned only when the gate FIRES, else `None`, matching
/// Python which returns `pl` only on the cut path).
pub fn split_family_repeat_bridge<F: ExonFetcher>(
    block: &[String],
    genes: &HashMap<String, GeneMeta>,
    gene_of_dn: &HashMap<String, String>,
    t: usize,
    several: usize,
    res: &StageLoaders<F>,
) -> (Vec<Vec<String>>, Option<Plan>) {
    let members = block_members(block, genes, gene_of_dn);
    if members.len() < 2 {
        return (vec![sorted_block(block)], None);
    }
    let pl = characterize(
        &members, res.r_skel, res.strand, res.fa, res.meta, res.vskel, res.fa, res.mult, res.cyclic,
    );
    let plan = match pl {
        None => return (vec![sorted_block(block)], None),
        Some(p) => p,
    };
    if plan.skipped || !gate_cut(&plan, t, several) {
        return (vec![sorted_block(block)], None);
    }
    let mut covered: BTreeSet<String> = BTreeSet::new();
    let mut parts: Vec<Vec<String>> = Vec::new();
    for comp in &plan.comps_dn {
        let mut p = comp.clone();
        p.sort(); // sorted(comp) (already sorted, but faithful)
        for dn in &p {
            covered.insert(dn.clone());
        }
        parts.push(p);
    }
    // leftover no-skeleton members -> singletons: sorted(set(block) - covered)
    let bset: BTreeSet<String> = block.iter().cloned().collect();
    for dn in bset.difference(&covered) {
        parts.push(vec![dn.clone()]);
    }
    // sorted((p for p in parts if p), key=lambda c: c[0])
    let mut result: Vec<Vec<String>> = parts.into_iter().filter(|p| !p.is_empty()).collect();
    result.sort_by(|a, b| a[0].cmp(&b[0]));
    (result, Some(plan))
}

/// `sorted(block)` (lexicographic on the ASCII DN ids).
fn sorted_block(block: &[String]) -> Vec<String> {
    let mut b: Vec<String> = block.to_vec();
    b.sort();
    b
}

// ===========================================================================
// split_families_repeat_bridge  (multi_repeat_bridge_gate.py:664)
// ===========================================================================

/// One entry of the split bookkeeping (Python `split_info` dict).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SplitInfo {
    pub dominant: String,
    pub genes: Vec<String>,
    pub name: String,
    pub n_loci: usize,
    pub n_parts: usize,
    pub subfam_genes: Vec<String>,
}

/// Apply the gate to a list of refined blocks. Faithful port of
/// `split_families_repeat_bridge` (:664): for each block, `split_family_repeat_bridge`;
/// if it produced `> 1` parts, record a `SplitInfo` (pre-split gene set + dominant +
/// per-part dominants); extend `new_refined` by the parts. Returns
/// `(new_refined, split_info)`.
///
/// ORDER CONTRACT: `dominant` is `Counter(gene_of_dn[dn] for dn in b ...).most_common(1)`,
/// whose tie-break is the FIRST gene seen while iterating `b`; so the port iterates each
/// block in the EXACT element order given (the driver feeds sorted DN lists). `genes`
/// (`pre_genes`) is a sorted set and `subfam_genes` iterate sorted parts, so those are
/// order-independent.
pub fn split_families_repeat_bridge<F: ExonFetcher>(
    refined: &[Vec<String>],
    genes: &HashMap<String, GeneMeta>,
    gene_of_dn: &HashMap<String, String>,
    t: usize,
    several: usize,
    res: &StageLoaders<F>,
) -> (Vec<Vec<String>>, Vec<SplitInfo>) {
    let mut new_refined: Vec<Vec<String>> = Vec::new();
    let mut split_info: Vec<SplitInfo> = Vec::new();
    for b in refined {
        let (parts, _) = split_family_repeat_bridge(b, genes, gene_of_dn, t, several, res);
        if parts.len() > 1 {
            // pre_genes = sorted({gene_of_dn[dn] for dn in b if not None/NA})
            let mut pre_set: BTreeSet<String> = BTreeSet::new();
            for dn in b {
                if let Some(g) = gene_of_dn.get(dn) {
                    if g != "NA" {
                        pre_set.insert(g.clone());
                    }
                }
            }
            let pre_genes: Vec<String> = pre_set.into_iter().collect();
            // dom = Counter(gene_of_dn[dn] for dn in b if not None/NA).most_common(1)
            let dom_seq: Vec<String> = b
                .iter()
                .filter_map(|dn| gene_of_dn.get(dn))
                .filter(|g| g.as_str() != "NA")
                .cloned()
                .collect();
            let dominant = most_common_gene(&dom_seq).unwrap_or_else(|| "NA".to_string());
            // per-part dominants
            let mut subfam_genes: Vec<String> = Vec::new();
            for p in &parts {
                let gs: Vec<String> = p
                    .iter()
                    .filter_map(|dn| gene_of_dn.get(dn))
                    .filter(|g| g.as_str() != "NA")
                    .cloned()
                    .collect();
                subfam_genes.push(most_common_gene(&gs).unwrap_or_else(|| "NA".to_string()));
            }
            let name = if pre_genes.is_empty() {
                "NA".to_string()
            } else {
                pre_genes.join("+")
            };
            split_info.push(SplitInfo {
                dominant,
                genes: pre_genes,
                name,
                n_loci: parts.iter().map(|p| p.len()).sum(),
                n_parts: parts.len(),
                subfam_genes,
            });
        }
        new_refined.extend(parts);
    }
    (new_refined, split_info)
}

/// `collections.Counter(seq).most_common(1)[0][0]` -- the highest-count element, ties
/// broken by FIRST-SEEN in iteration order (CPython `most_common` is stable on equal
/// counts). `None` iff `seq` is empty.
fn most_common_gene(seq: &[String]) -> Option<String> {
    let mut order: Vec<&String> = Vec::new();
    let mut counts: HashMap<&String, usize> = HashMap::new();
    for g in seq {
        if !counts.contains_key(g) {
            order.push(g);
        }
        *counts.entry(g).or_insert(0) += 1;
    }
    let mut best: Option<&String> = None;
    for g in order {
        match best {
            None => best = Some(g),
            Some(b) => {
                if counts[g] > counts[b] {
                    best = Some(g);
                }
            }
        }
    }
    best.cloned()
}

#[cfg(test)]
#[path = "multi_repeat_bridge_tests.rs"]
mod tests;
