//! Byte-parity tests for `super` (`multi_repeat_bridge`) against the golden fixture
//! `testdata/multi_repeat_bridge_fixture.json` (generated by
//! `bench/gen_multi_repeat_bridge_fixture.py`, PYTHONHASHSEED=0).
//!
//! Structure:
//!   * `parity_default` (DEFAULT `cargo test`): a COST-BUDGETED subset (`default==true`)
//!     covering every required behaviour -- named PDIA3/PRKAB2 cut, GSTM2/MAGE spared,
//!     the >MAX_MEMBERS skip, same-gene-guard-blocked, non-cut -- with FULL recompute:
//!     per-block `characterize` plan fields + `gate_cut` + `split_family_repeat_bridge`
//!     parts, plus the aggregate `split_families_repeat_bridge` (new_refined+split_info).
//!   * `gstm2_mage_spared_and_cut_count` (DEFAULT): the dedicated assertions -- the
//!     GSTM2 + MAGE domain-share families are NOT cut, and the default cut count matches.
//!   * `parity_full_61` (`#[ignore]`, RELEASE-run): the SAME parity over ALL selected
//!     blocks incl. the expensive families, asserting exactly 61 cut families reproduced
//!     and the big mult-426 GSTM2 + MAGEA cardinality families spared. Heavy HW-DP
//!     (~27 G cell-ops); run with `cargo test --release -- --ignored`.

use super::*;
use serde_json::Value;
use std::collections::HashMap;

fn load_fixture() -> Value {
    let raw = include_str!("testdata/multi_repeat_bridge_fixture.json");
    serde_json::from_str(raw).expect("parse multi_repeat_bridge fixture json")
}

/// Mock genome fetcher backed by the fixture's captured raw (case-carrying) slices,
/// keyed on `(chrom, start0, end0)` = the exact `fa.fetch(chrom, start0, end0)` args of
/// BOTH the `family_exons` (`s-1..e`) and `locus_node_set` (`a..b`) fetch loops.
struct MockFasta {
    slices: HashMap<(String, i64, i64), Vec<u8>>,
}
impl ExonFetcher for MockFasta {
    fn fetch(&self, chrom: &str, start: i64, end: i64) -> Option<Vec<u8>> {
        self.slices.get(&(chrom.to_string(), start, end)).cloned()
    }
}

/// All loader maps + slices, accumulated from one or many fixture records (blocks are
/// DN-disjoint, so merging is safe; shared VG-node multiplicities are globally consistent).
#[derive(Default)]
struct Loaders {
    genes: HashMap<String, GeneMeta>,
    gene_of_dn: HashMap<String, String>,
    strand: HashMap<String, String>,
    r_skel: HashMap<(String, i64, i64), Vec<(i64, i64)>>,
    vskel: HashMap<(String, i64, i64), String>,
    meta: HashMap<String, (String, i64, i64)>,
    mult: HashMap<u64, usize>,
    cyclic: HashMap<u64, usize>,
    slices: HashMap<(String, i64, i64), Vec<u8>>,
}

impl Loaders {
    fn add(&mut self, rec: &Value) {
        for (dn, v) in rec["genes"].as_object().unwrap() {
            let a = v.as_array().unwrap();
            self.genes.insert(
                dn.clone(),
                GeneMeta {
                    chrom: a[0].as_str().unwrap().to_string(),
                    start: a[1].as_i64().unwrap(),
                    end: a[2].as_i64().unwrap(),
                    name: dn.clone(),
                    biotype: "NA".to_string(),
                    ov: 0.0,
                },
            );
        }
        for (dn, v) in rec["gene_of_dn"].as_object().unwrap() {
            self.gene_of_dn.insert(dn.clone(), v.as_str().unwrap().to_string());
        }
        for (dn, v) in rec["strand"].as_object().unwrap() {
            self.strand.insert(dn.clone(), v.as_str().unwrap().to_string());
        }
        for s in rec["r_skel"].as_array().unwrap() {
            let key = (
                s["chrom"].as_str().unwrap().to_string(),
                s["start"].as_i64().unwrap(),
                s["end"].as_i64().unwrap(),
            );
            let exons: Vec<(i64, i64)> = s["exons"]
                .as_array()
                .unwrap()
                .iter()
                .map(|p| {
                    let a = p.as_array().unwrap();
                    (a[0].as_i64().unwrap(), a[1].as_i64().unwrap())
                })
                .collect();
            self.r_skel.insert(key, exons);
        }
        for (dn, v) in rec["meta"].as_object().unwrap() {
            let a = v.as_array().unwrap();
            self.meta.insert(
                dn.clone(),
                (a[0].as_str().unwrap().to_string(), a[1].as_i64().unwrap(), a[2].as_i64().unwrap()),
            );
        }
        for s in rec["vskel"].as_array().unwrap() {
            let key = (
                s["chrom"].as_str().unwrap().to_string(),
                s["start"].as_i64().unwrap(),
                s["end"].as_i64().unwrap(),
            );
            self.vskel.insert(key, s["introns"].as_str().unwrap().to_string());
        }
        for (code, v) in rec["node_mult"].as_object().unwrap() {
            let c: u64 = code.parse().unwrap();
            let a = v.as_array().unwrap();
            self.mult.insert(c, a[0].as_u64().unwrap() as usize);
            self.cyclic.insert(c, a[1].as_u64().unwrap() as usize);
        }
        for sl in rec["slices"].as_array().unwrap() {
            let key = (
                sl["chrom"].as_str().unwrap().to_string(),
                sl["start0"].as_i64().unwrap(),
                sl["end0"].as_i64().unwrap(),
            );
            self.slices.insert(key, sl["bytes"].as_str().unwrap().as_bytes().to_vec());
        }
    }

    fn fasta(&self) -> MockFasta {
        MockFasta { slices: self.slices.clone() }
    }

    fn stage<'a>(&'a self, fa: &'a MockFasta) -> StageLoaders<'a, MockFasta> {
        StageLoaders {
            r_skel: &self.r_skel,
            strand: &self.strand,
            vskel: &self.vskel,
            meta: &self.meta,
            fa,
            mult: &self.mult,
            cyclic: &self.cyclic,
        }
    }
}

fn block_of(rec: &Value) -> Vec<String> {
    rec["block"].as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect()
}

fn parts_of(v: &Value) -> Vec<Vec<String>> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|p| p.as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect())
        .collect()
}

fn str_list(v: &Value) -> Vec<String> {
    v.as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect()
}

/// Assert the Rust `characterize` plan == the fixture plan for a labelled record.
fn assert_plan_eq(got: &Option<Plan>, want: &Value, label: &str) {
    if want.is_null() {
        assert!(got.is_none(), "{label}: expected None plan (n<2), got Some");
        return;
    }
    let g = got.as_ref().unwrap_or_else(|| panic!("{label}: expected Some plan, got None"));
    let skipped = want["skipped"].as_bool().unwrap();
    assert_eq!(g.skipped, skipped, "{label}: skipped");
    assert_eq!(g.n_members, want["n_members"].as_u64().unwrap() as usize, "{label}: n_members");
    assert_eq!(
        g.n_distinct_genes,
        want["n_distinct_genes"].as_u64().unwrap() as usize,
        "{label}: n_distinct_genes"
    );
    assert_eq!(
        g.same_gene_family,
        want["same_gene_family"].as_bool().unwrap(),
        "{label}: same_gene_family"
    );
    if skipped {
        return; // skip plan: remaining fields are Default (match the fixture's skip zeros)
    }
    let u = |k: &str| want[k].as_u64().unwrap() as usize;
    let b = |k: &str| want[k].as_bool().unwrap();
    assert_eq!(g.n_comp, u("n_comp"), "{label}: n_comp");
    assert_eq!(g.connected, b("connected"), "{label}: connected");
    assert_eq!(g.shares_full_exon, b("shares_full_exon"), "{label}: shares_full_exon");
    match want["xcomp_bits"].as_u64() {
        Some(bits) => {
            let x = g.xcomp_best_exon_id.unwrap_or_else(|| panic!("{label}: xcomp None, want Some"));
            assert_eq!(x.to_bits(), bits, "{label}: xcomp_best_exon_id bits ({x})");
        }
        None => assert!(
            g.xcomp_best_exon_id.is_none(),
            "{label}: xcomp Some({:?}), want None",
            g.xcomp_best_exon_id
        ),
    }
    assert_eq!(g.no_full_shared_exon, b("no_full_shared_exon"), "{label}: no_full_shared_exon");
    assert_eq!(g.n_cross_pairs, u("n_cross_pairs"), "{label}: n_cross_pairs");
    assert_eq!(
        g.n_cross_pairs_with_node,
        u("n_cross_pairs_with_node"),
        "{label}: n_cross_pairs_with_node"
    );
    assert_eq!(g.n_cross_shared_nodes, u("n_cross_shared_nodes"), "{label}: n_cross_shared_nodes");
    assert_eq!(g.max_cross_mult, u("max_cross_mult"), "{label}: max_cross_mult");
    assert_eq!(g.med_cross_mult, u("med_cross_mult"), "{label}: med_cross_mult");
    assert_eq!(g.n_cross_cyclic, u("n_cross_cyclic"), "{label}: n_cross_cyclic");
    // rep_bridges: fixture ships [[t, count], ...]
    let rb_want: Vec<(usize, usize)> = want["rep_bridges"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| {
            let a = p.as_array().unwrap();
            (a[0].as_u64().unwrap() as usize, a[1].as_u64().unwrap() as usize)
        })
        .collect();
    let rb_got: Vec<(usize, usize)> = g.rep_bridges.iter().map(|(&t, &c)| (t, c)).collect();
    assert_eq!(rb_got, rb_want, "{label}: rep_bridges");
    assert_eq!(g.n_internal_shared_nodes, u("n_internal_shared_nodes"), "{label}: n_internal_shared");
    assert_eq!(g.max_internal_mult, u("max_internal_mult"), "{label}: max_internal_mult");
    assert_eq!(g.n_internal_repeat_m8, u("n_internal_repeat_m8"), "{label}: n_internal_repeat_m8");
    assert_eq!(g.min_comp_size, u("min_comp_size"), "{label}: min_comp_size");
    assert_eq!(g.separates_same_gene, b("separates_same_gene"), "{label}: separates_same_gene");
    assert_eq!(g.guard_ok, b("guard_ok"), "{label}: guard_ok");
    // comps_dn (sorted DN lists, in comp order)
    let comps_want: Vec<Vec<String>> = want["comps_dn"].as_array().unwrap().iter().map(parts_row).collect();
    assert_eq!(g.comps_dn, comps_want, "{label}: comps_dn");
    assert_eq!(g.all_dn, str_list(&want["all_dn"]), "{label}: all_dn");
}

fn parts_row(v: &Value) -> Vec<String> {
    v.as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_string()).collect()
}

fn assert_split_info_eq(got: &[SplitInfo], want: &Value, label: &str) {
    let arr = want.as_array().unwrap();
    assert_eq!(got.len(), arr.len(), "{label}: split_info length ({} vs {})", got.len(), arr.len());
    for (i, (g, w)) in got.iter().zip(arr.iter()).enumerate() {
        assert_eq!(g.dominant, w["dominant"].as_str().unwrap(), "{label}: split_info[{i}].dominant");
        assert_eq!(g.genes, str_list(&w["genes"]), "{label}: split_info[{i}].genes");
        assert_eq!(g.name, w["name"].as_str().unwrap(), "{label}: split_info[{i}].name");
        assert_eq!(g.n_loci, w["n_loci"].as_u64().unwrap() as usize, "{label}: split_info[{i}].n_loci");
        assert_eq!(g.n_parts, w["n_parts"].as_u64().unwrap() as usize, "{label}: split_info[{i}].n_parts");
        assert_eq!(
            g.subfam_genes,
            str_list(&w["subfam_genes"]),
            "{label}: split_info[{i}].subfam_genes"
        );
    }
}

/// Per-record byte-parity (characterize plan + gate_cut + split_family parts, plus the
/// spared-property assertion for GSTM2/MAGE domain-share blocks), over the records for
/// which `keep(rec)` is true. SINGLE recompute per block. Returns
/// (n_checked, n_cut, n_gstm2_spared, n_mage_spared).
fn run_perblock<Keep: Fn(&Value) -> bool>(fx: &Value, keep: Keep) -> (usize, usize, usize, usize) {
    let t = fx["WIRED_MULT_MIN"].as_u64().unwrap() as usize;
    let c = fx["WIRED_COUNT_MIN"].as_u64().unwrap() as usize;
    assert_eq!(t, WIRED_MULT_MIN);
    assert_eq!(c, WIRED_COUNT_MIN);
    assert_eq!(fx["MAX_MEMBERS"].as_u64().unwrap() as usize, MAX_MEMBERS);

    let (mut n_checked, mut n_cut, mut n_g2, mut n_mg) = (0usize, 0usize, 0usize, 0usize);
    for rec in fx["records"].as_array().unwrap() {
        if !keep(rec) {
            continue;
        }
        let mut lo = Loaders::default();
        lo.add(rec);
        let fa = lo.fasta();
        let res = lo.stage(&fa);
        let block = block_of(rec);
        let group = rec["group"].as_str().unwrap();
        let label = format!("block {} (group {group})", block[0]);
        let members = block_members(&block, &lo.genes, &lo.gene_of_dn);

        let plan = characterize(
            &members, &lo.r_skel, &lo.strand, &fa, &lo.meta, &lo.vskel, &fa, &lo.mult, &lo.cyclic,
        );
        assert_plan_eq(&plan, &rec["plan"], &label);

        let (parts, _) = split_family_repeat_bridge(&block, &lo.genes, &lo.gene_of_dn, t, c, &res);
        assert_eq!(parts, parts_of(&rec["parts"]), "{label}: split_family parts");

        let cut = rec["cut"].as_bool().unwrap();
        assert_eq!(parts.len() > 1, cut, "{label}: cut flag");
        if let Some(pl) = &plan {
            assert_eq!(!pl.skipped && gate_cut(pl, t, c), cut, "{label}: gate_cut vs cut flag");
        }

        // GSTM2/MAGE domain-share SPARED (load-bearing no-full-shared-exon conjunct):
        // a single full-exon component -> gate STRUCTURALLY cannot fire.
        if group == "spared_gstm2" || group == "spared_mage" {
            let pl = plan.as_ref().expect("spared family has a plan");
            assert!(pl.connected, "{label}: spared must be one full-exon component");
            assert!(!pl.no_full_shared_exon, "{label}: spared shares a full exon");
            assert!(!gate_cut(pl, t, c), "{label}: spared must NOT be gate-cut");
            assert!(!cut && parts.len() == 1, "{label}: spared must NOT be split");
            if group == "spared_gstm2" {
                n_g2 += 1;
            } else {
                n_mg += 1;
            }
        }
        if cut {
            n_cut += 1;
        }
        n_checked += 1;
    }
    (n_checked, n_cut, n_g2, n_mg)
}

/// Run the wired `split_families_repeat_bridge` over the kept blocks (in fixture order),
/// asserting the (new_refined, split_info) == the fixture aggregate `{nr_key, si_key}`.
fn run_aggregate<Keep: Fn(&Value) -> bool>(fx: &Value, keep: Keep, nr_key: &str, si_key: &str) -> usize {
    let t = WIRED_MULT_MIN;
    let c = WIRED_COUNT_MIN;
    let mut merged = Loaders::default();
    let mut blocks: Vec<Vec<String>> = Vec::new();
    let mut n_cut = 0usize;
    for rec in fx["records"].as_array().unwrap() {
        if !keep(rec) {
            continue;
        }
        merged.add(rec);
        blocks.push(block_of(rec));
        if rec["cut"].as_bool().unwrap() {
            n_cut += 1;
        }
    }
    let fa = merged.fasta();
    let res = merged.stage(&fa);
    let (new_refined, split_info) =
        split_families_repeat_bridge(&blocks, &merged.genes, &merged.gene_of_dn, t, c, &res);
    assert_eq!(new_refined, parts_of(&fx[nr_key]), "aggregate new_refined ({nr_key})");
    assert_split_info_eq(&split_info, &fx[si_key], nr_key);
    n_cut
}

/// DEFAULT parity: per-block characterize plan + gate_cut + split_family parts (single
/// recompute) over the cost-budgeted `default` subset -- covers every required behaviour
/// (PDIA3/PRKAB2 cut, GSTM2/MAGE spared, >MAX_MEMBERS skip, guard-blocked, non-cut) and
/// asserts the default cut count. Snappy (~120 M cell-ops).
#[test]
fn parity_default() {
    let fx = load_fixture();
    let (n, n_cut, n_g2, n_mg) = run_perblock(&fx, |r| r["default"].as_bool().unwrap());
    assert_eq!(n_cut, fx["n_cut_default"].as_u64().unwrap() as usize, "default cut count");
    assert!(n_g2 >= 1, "default must exercise a GSTM2-spared family");
    assert!(n_mg >= 1, "default must exercise a MAGE-spared family");

    let recs = fx["records"].as_array().unwrap();
    let has_group = |g: &str| recs.iter().any(|r| r["default"].as_bool().unwrap() && r["group"] == g);
    assert!(has_group("guard"), "default must include a same-gene-guard-blocked family");
    assert!(has_group("skip"), "default must include a >MAX_MEMBERS skip family");
    assert!(has_group("noncut"), "default must include a non-cut family");
    let named = recs.iter().any(|r| {
        r["default"].as_bool().unwrap()
            && r["cut"].as_bool().unwrap()
            && r["gene_of_dn"].as_object().unwrap().values().any(|g| {
                matches!(g.as_str().unwrap(), "PDIA3" | "PRKAB2")
            })
    });
    assert!(named, "default must include the PDIA3/PRKAB2 cut family");
    eprintln!(
        "parity_default: {n} blocks byte-identical ({n_cut} cut, {n_g2} GSTM2-spared + {n_mg} MAGE-spared)"
    );
}

/// DEFAULT aggregate parity: the wired `split_families_repeat_bridge` (partition +
/// split_info bookkeeping: dominant / genes / name / n_loci / n_parts / subfam_genes) over
/// the CHEAP `agg` subset (multi-gene cuts + guard + skip + non-cut + MAGE-spared).
#[test]
fn aggregate_default() {
    let fx = load_fixture();
    let n_cut = run_aggregate(&fx, |r| r["agg"].as_bool().unwrap(), "agg_new_refined", "agg_split_info");
    assert_eq!(n_cut, fx["n_cut_agg"].as_u64().unwrap() as usize, "agg cut count");
    assert!(n_cut >= 1, "agg subset must contain at least one cut (split_info coverage)");
    eprintln!("aggregate_default: split_families_repeat_bridge partition + split_info byte-identical");
}

/// EXHAUSTIVE parity over ALL selected blocks incl. the expensive families: per-block
/// parity + the FULL aggregate, reproducing exactly 61 cut families and sparing the big
/// mult-426 GSTM2 + MAGEA cardinality families. Heavy HW-DP (~27 G cell-ops) ->
/// `#[ignore]`; run: `cargo test --release -- --ignored parity_full_61`.
#[test]
#[ignore = "heavy HW-DP (~27 G cell-ops); run with --release -- --ignored"]
fn parity_full_61() {
    let fx = load_fixture();
    let (n, n_cut, n_g2, n_mg) = run_perblock(&fx, |_| true);
    assert_eq!(n, fx["records"].as_array().unwrap().len(), "all records checked");
    assert_eq!(n_cut, 61, "expected exactly 61 cut families");
    assert_eq!(n_cut, fx["n_cut_full"].as_u64().unwrap() as usize, "cut count vs fixture");
    assert!(n_g2 >= 2 && n_mg >= 2, "full set must exercise the big + small GSTM2/MAGE spared");
    // FULL aggregate parity (split_families over every selected block).
    let agg_cut = run_aggregate(&fx, |_| true, "full_new_refined", "full_split_info");
    assert_eq!(agg_cut, 61, "full aggregate cut count");
    eprintln!("parity_full_61: {n} blocks byte-identical, {n_cut} cut families reproduced");
}
