//! O2 VG-materialization step 3: the LOADERS + copy-dedup that
//! `bench/o2_vg_visualization.py::materialize_family` runs BEFORE it aligns copies
//! and threads reads.
//!
//! This module will grow to hold the full `materialize_family`; it starts with the
//! four pieces that run first, ported byte-faithfully from the Python ground truth:
//!
//!   * [`dedup_copies`] — collapse de-novo loci that are the same genomic copy
//!     (isoforms) into one copy-region (Python `psv_graph_genomewide.dedup_copies`,
//!     ~line 62);
//!   * [`load_families`] / [`load_families_str`] — parse the validated-families TSV
//!     into `fam_id -> [(lid, chrom, start, end, nreads)]` (Python
//!     `o2_vg_visualization.load_families`, ~line 84);
//!   * [`load_gene_labels`] / [`load_gene_labels_str`] — parse the SUN identifiability
//!     TSV into `(chrom, start) -> gene` (Python `o2_vg_visualization.load_gene_labels`,
//!     ~line 71);
//!   * [`FLAGSHIP`] — the flagship-family roster constant (Python
//!     `o2_vg_visualization.FLAGSHIP`, ~line 63).
//!   * [`fetch_reads`] — the multimapper read-fetch: per copy-region, `.bai`-indexed
//!     query of the genome BAM for the best-mapping (lowest-`de`) copy per read plus
//!     the insertion-ordered per-read sequence pool that is then re-aligned (Python
//!     `o2_vg_visualization.materialize_family` read-fetch block, ~lines 139-161).
//!
//! Byte-parity is enforced against golden fixtures
//! (`testdata/o2_materialize_fixture.json` / `testdata/o2_readfetch_fixture.json`,
//! generated by `bench/gen_o2_materialize_fixture.py` /
//! `bench/gen_o2_readfetch_fixture.py`, PYTHONHASHSEED=0) by the `#[test]`s below.

use std::collections::BTreeMap;
use std::collections::HashMap;
use std::collections::HashSet;
use std::path::Path;

use anyhow::Result;
use noodles_sam::alignment::record::data::field::Tag;
use noodles_sam::alignment::record::Cigar as _;
use noodles_sam::alignment::record_buf::data::field::Value as BufValue;
use noodles_sam::alignment::RecordBuf;

/// De-novo loci with reciprocal overlap STRICTLY GREATER than this fraction of the
/// shorter locus are the same genomic copy (isoforms) and get merged; distinct tandem
/// copies (overlap `<=` this) stay separate. Hard-coded from the Python constant
/// `bench/psv_graph_genomewide.py:37  OVERLAP_MERGE = 0.5`.
pub const OVERLAP_MERGE: f64 = 0.5;

/// Default path of the validated-families TSV, the `dedup_copies`/`load_families`
/// input. Python `bench/psv_graph_genomewide.py:32`:
/// `FAM_TSV = os.environ.get("FAM_TSV", "/home/juanfra/winloci_scratch/validated_families.tsv")`
/// — the default; the env override is honored by [`fam_tsv_path`].
pub const FAM_TSV_DEFAULT: &str = "/home/juanfra/winloci_scratch/validated_families.tsv";

/// Basename of the SUN identifiability TSV that supplies gene labels. Python
/// `bench/o2_vg_visualization.py:60`:
/// `SUN_TSV = os.path.join(HERE, "sun_identifiability.tsv")` where `HERE` is the
/// `bench/` directory (`os.path.dirname(os.path.abspath(__file__))`).
pub const SUN_TSV_BASENAME: &str = "sun_identifiability.tsv";

/// Flagship-family roster: `fam_id -> (gene, role)`. Verbatim port of the Python
/// constant `bench/o2_vg_visualization.py:63`:
/// ```python
/// FLAGSHIP = {
///     39: ("RABL2", "RESOLVABLE"),   # 5 copies, all Tier-1 SUN, cross-chrom
///     1:  ("RGPD8", "FLOOR"),        # 7 copies, 0 PSV bubbles, all reads tied
///     22: ("ANKRD18", "MID"),        # 6 copies, K=4/6, some collapse
/// }
/// ```
pub const FLAGSHIP: [(i64, &str, &str); 3] = [
    (39, "RABL2", "RESOLVABLE"),
    (1, "RGPD8", "FLOOR"),
    (22, "ANKRD18", "MID"),
];

/// The default `FAM_TSV` path, honoring the `FAM_TSV` env override exactly like the
/// Python `os.environ.get("FAM_TSV", <default>)`.
pub fn fam_tsv_path() -> String {
    std::env::var("FAM_TSV").unwrap_or_else(|_| FAM_TSV_DEFAULT.to_string())
}

// ===========================================================================
// dedup_copies  (bench/psv_graph_genomewide.py:62)
// ===========================================================================

/// Collapse de-novo loci that are the same genomic copy (isoforms) into one
/// copy-region — same chrom + reciprocal overlap `>` [`OVERLAP_MERGE`] of the shorter
/// locus. Distinct tandem copies stay separate. Faithful port of
/// `bench/psv_graph_genomewide.py::dedup_copies`.
///
/// Input `loci` is a slice of `(lid, chrom, start, end, nreads)` (the `lid` is unused
/// by the algorithm, exactly as in Python where only `(c, s, e, nr)` are read).
/// Output is `(chrom, start, end, nreads)` per merged region.
///
/// ## Order fidelity (load-bearing — see the module note)
/// The Python groups by chrom with a `collections.defaultdict(list)`, whose iteration
/// is INSERTION order (first-seen chrom order across `loci`). The returned `regions`
/// list is emitted chrom-group by chrom-group in that first-seen order, and within a
/// group in sweep order (which follows the `items.sort()` ascending `(s, e, nr)`
/// order). We reproduce this EXACTLY with a first-seen `Vec<chrom>` + a `HashMap`
/// index (NOT a `BTreeMap`, which would reorder chroms alphabetically). The downstream
/// `materialize_family` re-sorts the regions by length-desc, but reproducing this
/// return order verbatim keeps the port byte-faithful for every consumer.
///
/// ## The merge test (reproduced verbatim, incl. the strict `>` and the min-of-lengths)
/// Sweeping the sorted items with a running `cur = (start, end, nreads)`: the next
/// item `(s, e, nr)` merges into `cur` iff `s < cur.end` AND
/// `ov > OVERLAP_MERGE * min(cur.end - cur.start, e - s)` where
/// `ov = min(cur.end, e) - s`. On a merge, `cur = (cur.start, max(cur.end, e),
/// cur.nreads + nr)` (note the `max` end and the `nreads` accumulation) and the next
/// item is consumed WITHOUT flushing (`continue`). Otherwise `cur` is flushed to
/// `regions` and a fresh `cur` starts at `(s, e, nr)`. The comparison is done in `f64`
/// (an `int` `ov` against the `float` `OVERLAP_MERGE * int`), matching Python; with
/// `OVERLAP_MERGE == 0.5` the products are exact for these coordinate magnitudes.
pub fn dedup_copies(loci: &[(String, String, i64, i64, i64)]) -> Vec<(String, i64, i64, i64)> {
    // Group by chrom preserving FIRST-SEEN chrom order (Python defaultdict(list)).
    let mut chrom_order: Vec<String> = Vec::new();
    let mut idx: HashMap<&str, usize> = HashMap::new();
    let mut groups: Vec<Vec<(i64, i64, i64)>> = Vec::new();
    for (_lid, c, s, e, nr) in loci {
        let gi = match idx.get(c.as_str()) {
            Some(&i) => i,
            None => {
                let i = groups.len();
                idx.insert(c.as_str(), i);
                chrom_order.push(c.clone());
                groups.push(Vec::new());
                i
            }
        };
        groups[gi].push((*s, *e, *nr));
    }

    let mut regions: Vec<(String, i64, i64, i64)> = Vec::new();
    for (gi, c) in chrom_order.iter().enumerate() {
        let mut items = std::mem::take(&mut groups[gi]);
        // Python items.sort() -> lexicographic ascending (s, e, nr).
        items.sort();
        let mut cur: Option<(i64, i64, i64)> = None;
        for (s, e, nr) in items {
            if let Some((cs, ce, cnr)) = cur {
                if s < ce {
                    let ov = ce.min(e) - s;
                    let minlen = (ce - cs).min(e - s);
                    if (ov as f64) > OVERLAP_MERGE * (minlen as f64) {
                        // merge (grow end via max, accumulate nreads) and continue
                        cur = Some((cs, ce.max(e), cnr + nr));
                        continue;
                    }
                }
                // no merge: flush the running region before starting a fresh one
                regions.push((c.clone(), cs, ce, cnr));
            }
            cur = Some((s, e, nr));
        }
        if let Some((cs, ce, cnr)) = cur {
            regions.push((c.clone(), cs, ce, cnr));
        }
    }
    regions
}

// ===========================================================================
// load_families  (bench/o2_vg_visualization.py:84)
// ===========================================================================

/// One family's loci as parsed from the validated-families TSV.
pub type FamLocus = (String, String, i64, i64, i64);

/// Parse the validated-families TSV text into `fam_id -> [(lid, chrom, start, end,
/// nreads)]`. Faithful port of `bench/o2_vg_visualization.py::load_families` operating
/// on the raw text (`load_families` reads the file and delegates here).
///
/// Header line skipped. Columns (Python `fi, lid, c, s, e, nr = line.split("\t")`):
/// `f[0]=family  f[1]=locus  f[2]=chrom  f[3]=start  f[4]=end  f[5]=nreads`. The
/// per-family `Vec` preserves FILE order (Python `defaultdict(list).append`), which is
/// what feeds [`dedup_copies`]' first-seen-chrom ordering — so the order must be kept.
/// The `BTreeMap` key order is irrelevant to callers (they index `fams[fam_id]`) but is
/// deterministic.
pub fn load_families_str(text: &str) -> BTreeMap<i64, Vec<FamLocus>> {
    let mut fams: BTreeMap<i64, Vec<FamLocus>> = BTreeMap::new();
    for line in text.lines().skip(1) {
        let f: Vec<&str> = line.split('\t').collect();
        let fi: i64 = f[0].parse().expect("family int");
        let s: i64 = f[3].parse().expect("start int");
        let e: i64 = f[4].parse().expect("end int");
        let nr: i64 = f[5].parse().expect("nreads int");
        fams.entry(fi)
            .or_default()
            .push((f[1].to_string(), f[2].to_string(), s, e, nr));
    }
    fams
}

/// Read the validated-families TSV file and parse it (see [`load_families_str`]).
pub fn load_families<P: AsRef<Path>>(path: P) -> std::io::Result<BTreeMap<i64, Vec<FamLocus>>> {
    Ok(load_families_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// load_gene_labels  (bench/o2_vg_visualization.py:71)
// ===========================================================================

/// Parse the SUN identifiability TSV text into `(chrom, start) -> gene`. Faithful port
/// of `bench/o2_vg_visualization.py::load_gene_labels` operating on the raw text.
///
/// Header line skipped. Columns (Python `p = line.split("\t"); g[(p[2], int(p[3]))] =
/// p[5]`): `p[2]=chrom  p[3]=start  p[5]=gene`. A repeated `(chrom, start)` key keeps
/// the LAST value (dict assignment / `BTreeMap::insert` both overwrite).
pub fn load_gene_labels_str(text: &str) -> BTreeMap<(String, i64), String> {
    let mut g: BTreeMap<(String, i64), String> = BTreeMap::new();
    for line in text.lines().skip(1) {
        let p: Vec<&str> = line.split('\t').collect();
        let start: i64 = p[3].parse().expect("gene-label start int");
        g.insert((p[2].to_string(), start), p[5].to_string());
    }
    g
}

/// Read the SUN identifiability TSV and parse it (see [`load_gene_labels_str`]). A
/// MISSING file yields an empty map, matching the Python
/// `if os.path.exists(SUN_TSV): ... else return {}`.
pub fn load_gene_labels<P: AsRef<Path>>(path: P) -> std::io::Result<BTreeMap<(String, i64), String>> {
    let path = path.as_ref();
    if !path.exists() {
        return Ok(BTreeMap::new());
    }
    Ok(load_gene_labels_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// fetch_reads  (bench/o2_vg_visualization.py::materialize_family, ~lines 139-161)
// ===========================================================================

/// Per-copy-region fetch pad, in bp, added to BOTH ends of every copy region before
/// the indexed BAM query. Hard-coded from the Python constant
/// `bench/psv_graph_genomewide.py:35  PAD = 2000`.
pub const PAD: i64 = 2000;

/// Cap on the per-family read-sequence pool: if the insertion-ordered `seqs` exceeds
/// this it is truncated to the first `READ_CAP` (Python
/// `if len(seqs) > pg.READ_CAP: seqs = dict(list(seqs.items())[:pg.READ_CAP])`).
/// Hard-coded from `bench/psv_graph_genomewide.py:38  READ_CAP = 6000`.
pub const READ_CAP: usize = 6000;

/// Default genome BAM, the read-fetch input. Python `bench/psv_graph_genomewide.py:31`:
/// `BAM = "/home/juanfra/winloci_scratch/GGO.bam"` (a symlink to the indexed
/// `GGO_mm.bam`; the sibling `GGO.bam.bai` index is required by [`fetch_reads`]).
pub const BAM_DEFAULT: &str = "/home/juanfra/winloci_scratch/GGO.bam";

/// Read the minimap2 `de` (gap-compressed per-base divergence) aux tag as an `f64`.
///
/// The BAM stores `de` as a 4-byte IEEE-754 single (`Value::Float`); pysam widens it
/// to a Python `float` (a C double) losslessly, so `f32 as f64` reproduces pysam's
/// value bit-for-bit — the comparison `de < best[qname][1]` and the emitted raw f64
/// bits therefore match Python exactly. A missing (or non-float) `de` yields `None`,
/// matching Python's `dict(r.get_tags()).get("de")` returning `None`.
fn read_de_tag(rb: &RecordBuf) -> Option<f64> {
    match rb.data().get(&Tag::new(b'd', b'e'))? {
        BufValue::Float(f) => Some(*f as f64),
        _ => None,
    }
}

/// The multimapper read-fetch of `materialize_family` (Python ~lines 139-161): sweep the
/// copy `regions` IN THE GIVEN ORDER (already sorted by `-length` upstream), and for each
/// region `.bai`-indexed-query the genome BAM over `[max(0, s-pad),
/// min(contig_len[c], e+pad))` on contig `c`, building two structures:
///
///  * `best`: `qname -> (region_index, de)` keeping the LOWEST `de` for each read, with
///    the FIRST-SEEN region winning ties (Python's strict `de < best[qname][1]`). This is
///    the "best-mapping copy" (lowest minimap2 divergence) per read — the multimapper
///    evidence pool.
///  * `seqs`: `[(qname, query_sequence)]` in INSERTION ORDER (fetch order across regions),
///    added for a read the FIRST time it is seen as a NON-secondary alignment with a
///    non-empty SEQ. Insertion order is load-bearing: it drives the [`READ_CAP`]
///    truncation (keep the first `read_cap`). Returned as a `Vec` (NOT a map) precisely to
///    preserve that order.
///
/// ## Filter (verbatim pysam semantics, Python lines 145-151)
///  1. skip `is_unmapped` (0x4) or `is_supplementary` (0x800);
///  2. skip if `reference_end is None` OR `reference_end < s` OR `reference_start > e`
///     — where `s`/`e` are the ORIGINAL (un-padded) region bounds, `reference_start` is
///     the 0-based leftmost aligned position (`alignment_start-1`) and `reference_end` is
///     the 0-based exclusive end (`reference_start + cigar reference-span`, i.e. the same
///     `reference_start + sum(M/D/N/=/X)` pysam reports; `None` when the read has no
///     reference-consuming alignment);
///  3. skip if the `de` tag is absent (so a seq-bearing read WITHOUT `de` never enters
///     `seqs` either — the `de` gate precedes the `seqs` update, exactly as in Python).
///
/// ## Query ↔ pysam intersection equivalence
/// pysam `fetch(c, s2, stop)` (0-based half-open) returns a read iff
/// `reference_start < stop AND reference_end > s2`. The noodles indexed query filters on
/// the 1-based-inclusive interval `[s2+1, stop]` (built via the crate's established
/// `"{chrom}:{a}-{b}"` region string) intersecting the read's 1-based `[start, end]`,
/// which reduces to the SAME predicate. Both return records in coordinate (BGZF file)
/// order, so re-applying the exact Python post-filter yields an identical set AND the
/// identical insertion order for `seqs`.
///
/// Requires a `{bam_path}.bai` index; errors (rather than scanning) if it is missing, so
/// the byte-parity test can skip cleanly when the multi-GB BAM is unavailable.
pub fn fetch_reads<P: AsRef<Path>>(
    bam_path: P,
    regions: &[(String, i64, i64, i64)],
    contig_len: &BTreeMap<String, i64>,
    pad: i64,
    read_cap: usize,
) -> Result<(BTreeMap<String, (usize, f64)>, Vec<(String, String)>)> {
    let bam_path = bam_path.as_ref();
    let bai_path = {
        let mut s = bam_path.as_os_str().to_os_string();
        s.push(".bai");
        std::path::PathBuf::from(s)
    };
    anyhow::ensure!(
        bai_path.exists(),
        "fetch_reads needs a .bai index next to {} (expected {})",
        bam_path.display(),
        bai_path.display()
    );

    let mut reader = noodles_bam::io::reader::Builder::default().build_from_path(bam_path)?;
    let header = reader.read_header()?;
    let index = noodles_bam::bai::read(&bai_path)?;

    // `best` is a MAP (qname -> (region_idx, de)); BTreeMap gives deterministic ascending
    // key order (Python later does `for r in sorted(best)`). `seqs`/`seen` preserve the
    // load-bearing first-seen INSERTION order for the cap.
    let mut best: BTreeMap<String, (usize, f64)> = BTreeMap::new();
    let mut seqs: Vec<(String, String)> = Vec::new();
    let mut seen: HashSet<String> = HashSet::new();

    for (i, (c, s, e, _)) in regions.iter().enumerate() {
        // s2, e2 = max(0, s - PAD), e + PAD ; stop = min(contig_len.get(c, e2), e2)
        let s2 = (s - pad).max(0);
        let e2 = e + pad;
        let stop = contig_len.get(c).copied().unwrap_or(e2).min(e2);
        if stop <= s2 {
            continue; // degenerate/empty region -> pysam.fetch returns nothing
        }
        // 1-based inclusive [s2+1, stop] == pysam 0-based half-open [s2, stop).
        let region: noodles_core::Region = format!("{c}:{}-{}", s2 + 1, stop).parse()?;
        let query = reader.query(&header, &index, &region)?;

        for result in query {
            let record = result?;
            let rb = RecordBuf::try_from_alignment_record(&header, &record)?;

            let flags = rb.flags();
            if flags.is_unmapped() || flags.is_supplementary() {
                continue;
            }

            // reference_start (0-based) and reference_end (0-based exclusive).
            // `reference_end is None` <=> no reference-consuming alignment.
            let Some(start) = rb.alignment_start() else {
                continue;
            };
            let ref_start_0 = start.get() as i64 - 1;
            let span = rb.cigar().alignment_span() as i64;
            if span == 0 {
                continue; // pysam reference_end is None here
            }
            let ref_end_0_excl = ref_start_0 + span;
            if ref_end_0_excl < *s || ref_start_0 > *e {
                continue;
            }

            let Some(de) = read_de_tag(&rb) else {
                continue;
            };

            let name = match rb.name() {
                Some(n) => n.to_string(),
                None => continue,
            };

            // best[qname] = (i, de) if new OR strictly-lower de (first-seen wins ties).
            match best.get(&name) {
                None => {
                    best.insert(name.clone(), (i, de));
                }
                Some(&(_, cur_de)) => {
                    if de < cur_de {
                        best.insert(name.clone(), (i, de));
                    }
                }
            }

            // seqs[qname] = query_sequence, first non-secondary seq-bearing sighting.
            if !flags.is_secondary() && !seen.contains(&name) {
                let seq_bytes: &[u8] = rb.sequence().as_ref();
                if !seq_bytes.is_empty() {
                    let seq: String = seq_bytes.iter().map(|&b| b as char).collect();
                    seen.insert(name.clone());
                    seqs.push((name, seq));
                }
            }
        }
    }

    if seqs.len() > read_cap {
        seqs.truncate(read_cap);
    }
    Ok((best, seqs))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/o2_materialize_fixture.json");
        serde_json::from_str(raw).expect("parse o2_materialize fixture json")
    }

    /// dedup_copies == Python EXACTLY (incl. RETURN ORDER) on every case.
    #[test]
    fn dedup_copies_byte_parity() {
        let fx = load_fixture();

        // OVERLAP_MERGE value agreement.
        assert_eq!(
            OVERLAP_MERGE,
            fx["overlap_merge"].as_f64().unwrap(),
            "OVERLAP_MERGE constant disagrees with Python"
        );

        let cases = fx["dedup_cases"].as_array().expect("dedup_cases array");
        assert!(
            cases.len() >= 100,
            "expected >=100 dedup cases, got {}",
            cases.len()
        );

        let mut n_merge = 0usize;
        let mut n_multichrom = 0usize;
        let mut n_single = 0usize;
        let mut n_tandem_sep = 0usize;

        for case in cases {
            let id = case["id"].as_str().unwrap();
            let loci: Vec<FamLocus> = case["loci"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    let a = r.as_array().unwrap();
                    (
                        a[0].as_str().unwrap().to_string(),
                        a[1].as_str().unwrap().to_string(),
                        a[2].as_i64().unwrap(),
                        a[3].as_i64().unwrap(),
                        a[4].as_i64().unwrap(),
                    )
                })
                .collect();
            let expect: Vec<(String, i64, i64, i64)> = case["expect"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    let a = r.as_array().unwrap();
                    (
                        a[0].as_str().unwrap().to_string(),
                        a[1].as_i64().unwrap(),
                        a[2].as_i64().unwrap(),
                        a[3].as_i64().unwrap(),
                    )
                })
                .collect();

            let got = dedup_copies(&loci);

            // First-mismatch localization (position + field), then whole-vec equality.
            let n = got.len().max(expect.len());
            for i in 0..n {
                match (got.get(i), expect.get(i)) {
                    (Some(g), Some(e)) if g == e => {}
                    (g, e) => panic!(
                        "dedup case {id}: region[{i}] rust={:?} python={:?}\n  \
                         rust n_regions={}, python n_regions={}",
                        g,
                        e,
                        got.len(),
                        expect.len()
                    ),
                }
            }
            assert_eq!(got, expect, "dedup case {id}: whole-vec inequality");

            // Class accounting (for the fixture-composition sanity checks below).
            let n_loci = loci.len();
            let n_chrom = {
                let mut cs: Vec<&str> = loci.iter().map(|l| l.1.as_str()).collect();
                cs.sort();
                cs.dedup();
                cs.len()
            };
            if n_loci == 1 {
                n_single += 1;
            }
            if n_chrom >= 2 {
                n_multichrom += 1;
            }
            if got.len() < n_loci {
                n_merge += 1;
            }
            // same-chrom loci that stayed as multiple regions => a tandem separation
            if n_chrom == 1 && got.len() >= 2 {
                n_tandem_sep += 1;
            }
        }

        assert!(n_merge >= 1, "no case exercised an isoform merge");
        assert!(n_single >= 1, "no single-locus case");
        assert!(n_multichrom >= 1, "no multi-chrom case");
        assert!(n_tandem_sep >= 1, "no tandem-stays-separate case");

        eprintln!(
            "o2_materialize dedup_copies byte-parity: {} cases all match incl order \
             ({} with merges, {} single-locus, {} multi-chrom, {} tandem-separate)",
            cases.len(),
            n_merge,
            n_single,
            n_multichrom,
            n_tandem_sep
        );
    }

    /// load_families == Python (full dict, per-family Vec order included).
    #[test]
    fn load_families_byte_parity() {
        let fx = load_fixture();
        let node = &fx["load_families"];
        let tsv = node["tsv"].as_str().expect("load_families.tsv");

        let got = load_families_str(tsv);

        let expect_obj = node["expect"].as_object().expect("load_families.expect obj");
        let mut expect: BTreeMap<i64, Vec<FamLocus>> = BTreeMap::new();
        for (k, v) in expect_obj {
            let fi: i64 = k.parse().unwrap();
            let rows: Vec<FamLocus> = v
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    let a = r.as_array().unwrap();
                    (
                        a[0].as_str().unwrap().to_string(),
                        a[1].as_str().unwrap().to_string(),
                        a[2].as_i64().unwrap(),
                        a[3].as_i64().unwrap(),
                        a[4].as_i64().unwrap(),
                    )
                })
                .collect();
            expect.insert(fi, rows);
        }

        // Localize the first family / row that diverges (order included).
        let mut fams: Vec<i64> = got.keys().chain(expect.keys()).copied().collect();
        fams.sort_unstable();
        fams.dedup();
        for fi in &fams {
            let g = got.get(fi);
            let e = expect.get(fi);
            match (g, e) {
                (Some(gr), Some(er)) => {
                    let n = gr.len().max(er.len());
                    for i in 0..n {
                        assert_eq!(
                            gr.get(i),
                            er.get(i),
                            "load_families fam {fi} row[{i}] mismatch (rust vs python)"
                        );
                    }
                }
                (g, e) => panic!("load_families fam {fi}: rust present={:?} python present={:?}", g.is_some(), e.is_some()),
            }
        }
        assert_eq!(got, expect, "load_families whole-dict inequality");
        assert!(got.len() >= 100, "expected >=100 families parsed, got {}", got.len());
        eprintln!("o2_materialize load_families byte-parity: {} families all match", got.len());
    }

    /// load_gene_labels == Python.
    #[test]
    fn load_gene_labels_byte_parity() {
        let fx = load_fixture();
        let node = &fx["load_gene_labels"];
        let tsv = node["tsv"].as_str().expect("load_gene_labels.tsv");

        let got = load_gene_labels_str(tsv);

        let mut expect: BTreeMap<(String, i64), String> = BTreeMap::new();
        for entry in node["expect"].as_array().expect("load_gene_labels.expect array") {
            let a = entry.as_array().unwrap();
            let chrom = a[0].as_str().unwrap().to_string();
            let start = a[1].as_i64().unwrap();
            let gene = a[2].as_str().unwrap().to_string();
            expect.insert((chrom, start), gene);
        }

        for (k, v) in &expect {
            assert_eq!(
                got.get(k),
                Some(v),
                "load_gene_labels key {:?}: rust={:?} python={:?}",
                k,
                got.get(k),
                v
            );
        }
        assert_eq!(got, expect, "load_gene_labels whole-map inequality");
        assert!(!got.is_empty(), "expected a non-empty gene-label map");
        eprintln!("o2_materialize load_gene_labels byte-parity: {} labels all match", got.len());
    }

    /// load_gene_labels on a missing file -> empty map (Python `os.path.exists` guard).
    #[test]
    fn load_gene_labels_missing_file_is_empty() {
        let g = load_gene_labels("/nonexistent/definitely/not/here/sun.tsv").unwrap();
        assert!(g.is_empty());
    }

    /// FLAGSHIP roster matches Python verbatim (id, gene, role, and order).
    #[test]
    fn flagship_matches_python() {
        let fx = load_fixture();
        let expect = fx["flagship"].as_array().expect("flagship array");
        assert_eq!(FLAGSHIP.len(), expect.len(), "FLAGSHIP length");
        for (i, (id, gene, role)) in FLAGSHIP.iter().enumerate() {
            let a = expect[i].as_array().unwrap();
            assert_eq!(*id, a[0].as_i64().unwrap(), "FLAGSHIP[{i}] id");
            assert_eq!(*gene, a[1].as_str().unwrap(), "FLAGSHIP[{i}] gene");
            assert_eq!(*role, a[2].as_str().unwrap(), "FLAGSHIP[{i}] role");
        }
    }

    fn load_readfetch_fixture() -> Value {
        let raw = include_str!("testdata/o2_readfetch_fixture.json");
        serde_json::from_str(raw).expect("parse o2_readfetch fixture json")
    }

    fn parse_regions(v: &Value) -> Vec<(String, i64, i64, i64)> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|r| {
                let a = r.as_array().unwrap();
                (
                    a[0].as_str().unwrap().to_string(),
                    a[1].as_i64().unwrap(),
                    a[2].as_i64().unwrap(),
                    a[3].as_i64().unwrap(),
                )
            })
            .collect()
    }

    fn qname_list(v: &Value) -> Vec<String> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|q| q.as_str().unwrap().to_string())
            .collect()
    }

    /// fetch_reads == the Python read-fetch EXACTLY on every fixture family:
    ///   * `best` map: qname -> (region_idx, de) with de compared as raw f64 BITS;
    ///   * `seqs` qname ORDER (insertion order, drives the cap);
    ///   * the READ_CAP truncation (via lowered-cap cases, since no family hits 6000).
    /// Skips-with-message (does NOT fail) if the multi-GB genome BAM / its `.bai` is
    /// absent, so CI without the BAM is green; it IS present in dev so this runs+passes.
    #[test]
    fn fetch_reads_byte_parity() {
        let fx = load_readfetch_fixture();
        let bam_path = fx["bam_path"].as_str().expect("bam_path");
        let bai = format!("{bam_path}.bai");
        if !Path::new(bam_path).exists() || !Path::new(&bai).exists() {
            eprintln!(
                "o2_materialize fetch_reads byte-parity SKIPPED: genome BAM or .bai absent \
                 ({bam_path} / {bai}). Present in dev; run there to exercise this test."
            );
            return;
        }

        // Constant agreement with the Python (pg.PAD / pg.READ_CAP).
        let pad = fx["pad"].as_i64().expect("pad");
        let read_cap = fx["read_cap"].as_u64().expect("read_cap") as usize;
        assert_eq!(PAD, pad, "PAD constant disagrees with Python pg.PAD");
        assert_eq!(READ_CAP, read_cap, "READ_CAP disagrees with Python pg.READ_CAP");

        // contig_len (all genome contigs, as the Python passed).
        let mut contig_len: BTreeMap<String, i64> = BTreeMap::new();
        for (k, v) in fx["contig_len"].as_object().expect("contig_len obj") {
            contig_len.insert(k.clone(), v.as_i64().unwrap());
        }

        // Keep each family's regions for the lowered-cap truncation cases below.
        let mut regions_by_fam: BTreeMap<i64, Vec<(String, i64, i64, i64)>> = BTreeMap::new();
        let mut total_best = 0usize;
        let mut total_seqs = 0usize;

        let families = fx["families"].as_array().expect("families array");
        assert!(families.len() >= 4, "expected >=4 fixture families");

        for fam in families {
            let fam_id = fam["fam_id"].as_i64().unwrap();
            let regions = parse_regions(&fam["regions"]);
            regions_by_fam.insert(fam_id, regions.clone());

            let (best, seqs) = fetch_reads(bam_path, &regions, &contig_len, pad, read_cap)
                .unwrap_or_else(|e| panic!("fetch_reads(fam {fam_id}) failed: {e}"));

            // ---- best map: qname -> (region_idx, de-as-f64-bits) ----
            let exp_best = fam["best"].as_object().expect("best obj");
            // localize first divergence over the union of keys (ascending).
            let mut names: Vec<&String> = best.keys().collect();
            for k in exp_best.keys() {
                if !best.contains_key(k) {
                    names.push(k);
                }
            }
            names.sort();
            names.dedup();
            for name in names {
                let got = best.get(name);
                let exp = exp_best.get(name);
                match (got, exp) {
                    (Some(&(gi, gde)), Some(ev)) => {
                        let ea = ev.as_array().unwrap();
                        let ei = ea[0].as_i64().unwrap() as usize;
                        let ebits: u64 = ea[1].as_str().unwrap().parse().unwrap();
                        assert_eq!(
                            gi, ei,
                            "fam {fam_id} best[{name}] region_idx rust={gi} python={ei}"
                        );
                        assert_eq!(
                            gde.to_bits(),
                            ebits,
                            "fam {fam_id} best[{name}] de-bits rust={} python={} (rust de={gde})",
                            gde.to_bits(),
                            ebits
                        );
                    }
                    (Some(g), None) => {
                        panic!("fam {fam_id} best[{name}] present in rust ({g:?}), MISSING in python")
                    }
                    (None, Some(e)) => {
                        panic!("fam {fam_id} best[{name}] MISSING in rust, python={e:?}")
                    }
                    (None, None) => unreachable!(),
                }
            }
            assert_eq!(
                best.len(),
                exp_best.len(),
                "fam {fam_id} best cardinality rust={} python={}",
                best.len(),
                exp_best.len()
            );
            assert_eq!(
                best.len(),
                fam["n_best"].as_u64().unwrap() as usize,
                "fam {fam_id} n_best disagrees"
            );

            // ---- seqs qname ORDER (no family hits READ_CAP, so precap == postcap) ----
            let got_order: Vec<String> = seqs.iter().map(|(n, _)| n.clone()).collect();
            let exp_precap = qname_list(&fam["seqs_order_precap"]);
            let exp_postcap = qname_list(&fam["seqs_order_postcap"]);
            assert!(
                !fam["hit_read_cap"].as_bool().unwrap(),
                "fixture fam {fam_id} unexpectedly hit READ_CAP; test assumes precap==postcap here"
            );
            assert_eq!(exp_precap, exp_postcap, "fam {fam_id} fixture precap!=postcap");
            // first-divergence localization on the ordered qname list.
            let n = got_order.len().max(exp_precap.len());
            for k in 0..n {
                assert_eq!(
                    got_order.get(k),
                    exp_precap.get(k),
                    "fam {fam_id} seqs order[{k}] rust={:?} python={:?} (rust len={}, python len={})",
                    got_order.get(k),
                    exp_precap.get(k),
                    got_order.len(),
                    exp_precap.len()
                );
            }
            assert_eq!(
                got_order.len(),
                fam["n_seqs_precap"].as_u64().unwrap() as usize,
                "fam {fam_id} n_seqs disagrees"
            );

            total_best += best.len();
            total_seqs += got_order.len();
        }

        // ---- lowered-cap cases: exercise the READ_CAP truncation path ----
        let lowered = fx["lowered_cap"].as_array().expect("lowered_cap array");
        assert!(!lowered.is_empty(), "expected lowered-cap truncation cases");
        let mut n_truncated = 0usize;
        for lc in lowered {
            let fam_id = lc["fam_id"].as_i64().unwrap();
            let cap = lc["read_cap"].as_u64().unwrap() as usize;
            let regions = regions_by_fam
                .get(&fam_id)
                .unwrap_or_else(|| panic!("lowered-cap fam {fam_id} not among fixture families"));
            let (_best, seqs) = fetch_reads(bam_path, regions, &contig_len, pad, cap)
                .unwrap_or_else(|e| panic!("fetch_reads(fam {fam_id}, cap {cap}) failed: {e}"));
            let got_order: Vec<String> = seqs.iter().map(|(n, _)| n.clone()).collect();
            let exp_postcap = qname_list(&lc["seqs_order_postcap"]);
            assert!(
                lc["truncated"].as_bool().unwrap(),
                "lowered fam {fam_id} cap {cap} should truncate"
            );
            assert_eq!(
                got_order.len(),
                cap,
                "lowered fam {fam_id}: truncated len rust={} expected cap={cap}",
                got_order.len()
            );
            for k in 0..got_order.len().max(exp_postcap.len()) {
                assert_eq!(
                    got_order.get(k),
                    exp_postcap.get(k),
                    "lowered fam {fam_id} cap {cap} postcap order[{k}] rust={:?} python={:?}",
                    got_order.get(k),
                    exp_postcap.get(k)
                );
            }
            n_truncated += 1;
        }

        eprintln!(
            "o2_materialize fetch_reads byte-parity: {} families ({} best entries, {} seqs) \
             all match python incl de-bits + seqs order; {} lowered-cap truncation cases match",
            families.len(),
            total_best,
            total_seqs,
            n_truncated
        );
    }
}
