//! O2 VG-materialization step 3: the LOADERS + copy-dedup that
//! `bench/o2_vg_visualization.py::materialize_family` runs BEFORE it aligns copies
//! and threads reads.
//!
//! This module will grow to hold the full `materialize_family`; it starts with the
//! four pieces that run first, ported byte-faithfully from the Python ground truth:
//!
//!   * [`dedup_copies`] — collapse de-novo loci that are the same genomic copy
//!     (isoforms) into one copy-region (Python `psv_graph_genomewide.dedup_copies`,
//!     ~line 62);
//!   * [`load_families`] / [`load_families_str`] — parse the validated-families TSV
//!     into `fam_id -> [(lid, chrom, start, end, nreads)]` (Python
//!     `o2_vg_visualization.load_families`, ~line 84);
//!   * [`load_gene_labels`] / [`load_gene_labels_str`] — parse the SUN identifiability
//!     TSV into `(chrom, start) -> gene` (Python `o2_vg_visualization.load_gene_labels`,
//!     ~line 71);
//!   * [`FLAGSHIP`] — the flagship-family roster constant (Python
//!     `o2_vg_visualization.FLAGSHIP`, ~line 63).
//!   * [`fetch_reads`] — the multimapper read-fetch: per copy-region, `.bai`-indexed
//!     query of the genome BAM for the best-mapping (lowest-`de`) copy per read plus
//!     the insertion-ordered per-read sequence pool that is then re-aligned (Python
//!     `o2_vg_visualization.materialize_family` read-fetch block, ~lines 139-161).
//!
//! Byte-parity is enforced against golden fixtures
//! (`testdata/o2_materialize_fixture.json` / `testdata/o2_readfetch_fixture.json`,
//! generated by `bench/gen_o2_materialize_fixture.py` /
//! `bench/gen_o2_readfetch_fixture.py`, PYTHONHASHSEED=0) by the `#[test]`s below.
//!
//! **STATUS:** TEST-ONLY  (docs/MODULE_STATUS.md; assigned by reachability, not by this header)

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::collections::HashMap;
use std::collections::HashSet;
use std::io::Write as _;
use std::path::Path;
use std::process::{Command, Stdio};

use anyhow::Result;
use noodles_sam::alignment::record::data::field::Tag;
use noodles_sam::alignment::record::Cigar as _;
use noodles_sam::alignment::record_buf::data::field::Value as BufValue;
use noodles_sam::alignment::RecordBuf;
use serde_json::{json, Map, Value};

use super::o2_columns::column_alleles;
use super::o2_margin_gate::{assign_read_margin, BTOL, ERR, JW, MARGIN};
use super::recombinant_abstain::{apply_abstain_to_vg, FamilyVg, VgBubble, VgCopy, VgRead};
use super::repeat_catalog::IndexedFasta;

/// De-novo loci with reciprocal overlap STRICTLY GREATER than this fraction of the
/// shorter locus are the same genomic copy (isoforms) and get merged; distinct tandem
/// copies (overlap `<=` this) stay separate. Hard-coded from the Python constant
/// `bench/psv_graph_genomewide.py:37  OVERLAP_MERGE = 0.5`.
pub const OVERLAP_MERGE: f64 = 0.5;

/// Default path of the validated-families TSV, the `dedup_copies`/`load_families`
/// input. Python `bench/psv_graph_genomewide.py:32`:
/// `FAM_TSV = os.environ.get("FAM_TSV", "/home/juanfra/winloci_scratch/validated_families.tsv")`
/// — the default; the env override is honored by [`fam_tsv_path`].
// test-only; not a shipped default — [`fam_tsv_path`] is only called from
// `MaterializeConfig::defaults`, which in turn is only constructed inside this module's
// `#[cfg(test)]` block (the `#[ignore]`d `materialize_family_e2e`). No `src/bin/*.rs`
// binary imports `o2_materialize`, so no shipped run can reach this constant.
pub const FAM_TSV_DEFAULT: &str = "/home/juanfra/winloci_scratch/validated_families.tsv"; // test-only; not a shipped default

/// Basename of the SUN identifiability TSV that supplies gene labels. Python
/// `bench/o2_vg_visualization.py:60`:
/// `SUN_TSV = os.path.join(HERE, "sun_identifiability.tsv")` where `HERE` is the
/// `bench/` directory (`os.path.dirname(os.path.abspath(__file__))`).
pub const SUN_TSV_BASENAME: &str = "sun_identifiability.tsv";

/// Flagship-family roster: `fam_id -> (gene, role)`. Verbatim port of the Python
/// constant `bench/o2_vg_visualization.py:63`:
/// ```python
/// FLAGSHIP = {
///     39: ("RABL2", "RESOLVABLE"),   # 5 copies, all Tier-1 SUN, cross-chrom
///     1:  ("RGPD8", "FLOOR"),        # 7 copies, 0 PSV bubbles, all reads tied
///     22: ("ANKRD18", "MID"),        # 6 copies, K=4/6, some collapse
/// }
/// ```
pub const FLAGSHIP: [(i64, &str, &str); 3] = [
    (39, "RABL2", "RESOLVABLE"),
    (1, "RGPD8", "FLOOR"),
    (22, "ANKRD18", "MID"),
];

/// The default `FAM_TSV` path, honoring the `FAM_TSV` env override exactly like the
/// Python `os.environ.get("FAM_TSV", <default>)`.
pub fn fam_tsv_path() -> String {
    std::env::var("FAM_TSV").unwrap_or_else(|_| FAM_TSV_DEFAULT.to_string())
}

// ===========================================================================
// dedup_copies  (bench/psv_graph_genomewide.py:62)
// ===========================================================================

/// Collapse de-novo loci that are the same genomic copy (isoforms) into one
/// copy-region — same chrom + reciprocal overlap `>` [`OVERLAP_MERGE`] of the shorter
/// locus. Distinct tandem copies stay separate. Faithful port of
/// `bench/psv_graph_genomewide.py::dedup_copies`.
///
/// Input `loci` is a slice of `(lid, chrom, start, end, nreads)` (the `lid` is unused
/// by the algorithm, exactly as in Python where only `(c, s, e, nr)` are read).
/// Output is `(chrom, start, end, nreads)` per merged region.
///
/// ## Order fidelity (load-bearing — see the module note)
/// The Python groups by chrom with a `collections.defaultdict(list)`, whose iteration
/// is INSERTION order (first-seen chrom order across `loci`). The returned `regions`
/// list is emitted chrom-group by chrom-group in that first-seen order, and within a
/// group in sweep order (which follows the `items.sort()` ascending `(s, e, nr)`
/// order). We reproduce this EXACTLY with a first-seen `Vec<chrom>` + a `HashMap`
/// index (NOT a `BTreeMap`, which would reorder chroms alphabetically). The downstream
/// `materialize_family` re-sorts the regions by length-desc, but reproducing this
/// return order verbatim keeps the port byte-faithful for every consumer.
///
/// ## The merge test (reproduced verbatim, incl. the strict `>` and the min-of-lengths)
/// Sweeping the sorted items with a running `cur = (start, end, nreads)`: the next
/// item `(s, e, nr)` merges into `cur` iff `s < cur.end` AND
/// `ov > OVERLAP_MERGE * min(cur.end - cur.start, e - s)` where
/// `ov = min(cur.end, e) - s`. On a merge, `cur = (cur.start, max(cur.end, e),
/// cur.nreads + nr)` (note the `max` end and the `nreads` accumulation) and the next
/// item is consumed WITHOUT flushing (`continue`). Otherwise `cur` is flushed to
/// `regions` and a fresh `cur` starts at `(s, e, nr)`. The comparison is done in `f64`
/// (an `int` `ov` against the `float` `OVERLAP_MERGE * int`), matching Python; with
/// `OVERLAP_MERGE == 0.5` the products are exact for these coordinate magnitudes.
pub fn dedup_copies(loci: &[(String, String, i64, i64, i64)]) -> Vec<(String, i64, i64, i64)> {
    // Group by chrom preserving FIRST-SEEN chrom order (Python defaultdict(list)).
    let mut chrom_order: Vec<String> = Vec::new();
    let mut idx: HashMap<&str, usize> = HashMap::new();
    let mut groups: Vec<Vec<(i64, i64, i64)>> = Vec::new();
    for (_lid, c, s, e, nr) in loci {
        let gi = match idx.get(c.as_str()) {
            Some(&i) => i,
            None => {
                let i = groups.len();
                idx.insert(c.as_str(), i);
                chrom_order.push(c.clone());
                groups.push(Vec::new());
                i
            }
        };
        groups[gi].push((*s, *e, *nr));
    }

    let mut regions: Vec<(String, i64, i64, i64)> = Vec::new();
    for (gi, c) in chrom_order.iter().enumerate() {
        let mut items = std::mem::take(&mut groups[gi]);
        // Python items.sort() -> lexicographic ascending (s, e, nr).
        items.sort();
        let mut cur: Option<(i64, i64, i64)> = None;
        for (s, e, nr) in items {
            if let Some((cs, ce, cnr)) = cur {
                if s < ce {
                    let ov = ce.min(e) - s;
                    let minlen = (ce - cs).min(e - s);
                    if (ov as f64) > OVERLAP_MERGE * (minlen as f64) {
                        // merge (grow end via max, accumulate nreads) and continue
                        cur = Some((cs, ce.max(e), cnr + nr));
                        continue;
                    }
                }
                // no merge: flush the running region before starting a fresh one
                regions.push((c.clone(), cs, ce, cnr));
            }
            cur = Some((s, e, nr));
        }
        if let Some((cs, ce, cnr)) = cur {
            regions.push((c.clone(), cs, ce, cnr));
        }
    }
    regions
}

// ===========================================================================
// load_families  (bench/o2_vg_visualization.py:84)
// ===========================================================================

/// One family's loci as parsed from the validated-families TSV.
pub type FamLocus = (String, String, i64, i64, i64);

/// Parse the validated-families TSV text into `fam_id -> [(lid, chrom, start, end,
/// nreads)]`. Faithful port of `bench/o2_vg_visualization.py::load_families` operating
/// on the raw text (`load_families` reads the file and delegates here).
///
/// Header line skipped. Columns (Python `fi, lid, c, s, e, nr = line.split("\t")`):
/// `f[0]=family  f[1]=locus  f[2]=chrom  f[3]=start  f[4]=end  f[5]=nreads`. The
/// per-family `Vec` preserves FILE order (Python `defaultdict(list).append`), which is
/// what feeds [`dedup_copies`]' first-seen-chrom ordering — so the order must be kept.
/// The `BTreeMap` key order is irrelevant to callers (they index `fams[fam_id]`) but is
/// deterministic.
pub fn load_families_str(text: &str) -> BTreeMap<i64, Vec<FamLocus>> {
    let mut fams: BTreeMap<i64, Vec<FamLocus>> = BTreeMap::new();
    for line in text.lines().skip(1) {
        let f: Vec<&str> = line.split('\t').collect();
        let fi: i64 = f[0].parse().expect("family int");
        let s: i64 = f[3].parse().expect("start int");
        let e: i64 = f[4].parse().expect("end int");
        let nr: i64 = f[5].parse().expect("nreads int");
        fams.entry(fi)
            .or_default()
            .push((f[1].to_string(), f[2].to_string(), s, e, nr));
    }
    fams
}

/// Read the validated-families TSV file and parse it (see [`load_families_str`]).
pub fn load_families<P: AsRef<Path>>(path: P) -> std::io::Result<BTreeMap<i64, Vec<FamLocus>>> {
    Ok(load_families_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// load_gene_labels  (bench/o2_vg_visualization.py:71)
// ===========================================================================

/// Parse the SUN identifiability TSV text into `(chrom, start) -> gene`. Faithful port
/// of `bench/o2_vg_visualization.py::load_gene_labels` operating on the raw text.
///
/// Header line skipped. Columns (Python `p = line.split("\t"); g[(p[2], int(p[3]))] =
/// p[5]`): `p[2]=chrom  p[3]=start  p[5]=gene`. A repeated `(chrom, start)` key keeps
/// the LAST value (dict assignment / `BTreeMap::insert` both overwrite).
pub fn load_gene_labels_str(text: &str) -> BTreeMap<(String, i64), String> {
    let mut g: BTreeMap<(String, i64), String> = BTreeMap::new();
    for line in text.lines().skip(1) {
        let p: Vec<&str> = line.split('\t').collect();
        let start: i64 = p[3].parse().expect("gene-label start int");
        g.insert((p[2].to_string(), start), p[5].to_string());
    }
    g
}

/// Read the SUN identifiability TSV and parse it (see [`load_gene_labels_str`]). A
/// MISSING file yields an empty map, matching the Python
/// `if os.path.exists(SUN_TSV): ... else return {}`.
pub fn load_gene_labels<P: AsRef<Path>>(path: P) -> std::io::Result<BTreeMap<(String, i64), String>> {
    let path = path.as_ref();
    if !path.exists() {
        return Ok(BTreeMap::new());
    }
    Ok(load_gene_labels_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// fetch_reads  (bench/o2_vg_visualization.py::materialize_family, ~lines 139-161)
// ===========================================================================

/// Per-copy-region fetch pad, in bp, added to BOTH ends of every copy region before
/// the indexed BAM query. Hard-coded from the Python constant
/// `bench/psv_graph_genomewide.py:35  PAD = 2000`.
pub const PAD: i64 = 2000;

/// Cap on the per-family read-sequence pool: if the insertion-ordered `seqs` exceeds
/// this it is truncated to the first `READ_CAP` (Python
/// `if len(seqs) > pg.READ_CAP: seqs = dict(list(seqs.items())[:pg.READ_CAP])`).
/// Hard-coded from `bench/psv_graph_genomewide.py:38  READ_CAP = 6000`.
///
/// `copy_assign --read-cap` exposes this value for auditability but does not consume it: as noted below, no
/// `src/bin/*.rs` binary imports this module, so there is no live call site for a CLI-supplied override to
/// reach.
pub const READ_CAP: usize = 6000;

/// Default genome BAM, the read-fetch input. Python `bench/psv_graph_genomewide.py:31`:
/// `BAM = "/home/juanfra/winloci_scratch/GGO.bam"` (a symlink to the indexed
/// `GGO_mm.bam`; the sibling `GGO.bam.bai` index is required by [`fetch_reads`]).
// test-only; not a shipped default — only consumed by `MaterializeConfig::defaults`,
// which is only constructed inside this module's `#[cfg(test)]` block. No `src/bin/*.rs`
// binary imports `o2_materialize`, so no shipped run can reach this constant.
pub const BAM_DEFAULT: &str = "/home/juanfra/winloci_scratch/GGO.bam"; // test-only; not a shipped default

/// Read the minimap2 `de` (gap-compressed per-base divergence) aux tag as an `f64`.
///
/// The BAM stores `de` as a 4-byte IEEE-754 single (`Value::Float`); pysam widens it
/// to a Python `float` (a C double) losslessly, so `f32 as f64` reproduces pysam's
/// value bit-for-bit — the comparison `de < best[qname][1]` and the emitted raw f64
/// bits therefore match Python exactly. A missing (or non-float) `de` yields `None`,
/// matching Python's `dict(r.get_tags()).get("de")` returning `None`.
fn read_de_tag(rb: &RecordBuf) -> Option<f64> {
    match rb.data().get(&Tag::new(b'd', b'e'))? {
        BufValue::Float(f) => Some(*f as f64),
        _ => None,
    }
}

/// The multimapper read-fetch of `materialize_family` (Python ~lines 139-161): sweep the
/// copy `regions` IN THE GIVEN ORDER (already sorted by `-length` upstream), and for each
/// region `.bai`-indexed-query the genome BAM over `[max(0, s-pad),
/// min(contig_len[c], e+pad))` on contig `c`, building two structures:
///
///  * `best`: `qname -> (region_index, de)` keeping the LOWEST `de` for each read, with
///    the FIRST-SEEN region winning ties (Python's strict `de < best[qname][1]`). This is
///    the "best-mapping copy" (lowest minimap2 divergence) per read — the multimapper
///    evidence pool.
///  * `seqs`: `[(qname, query_sequence)]` in INSERTION ORDER (fetch order across regions),
///    added for a read the FIRST time it is seen as a NON-secondary alignment with a
///    non-empty SEQ. Insertion order is load-bearing: it drives the [`READ_CAP`]
///    truncation (keep the first `read_cap`). Returned as a `Vec` (NOT a map) precisely to
///    preserve that order.
///
/// ## Filter (verbatim pysam semantics, Python lines 145-151)
///  1. skip `is_unmapped` (0x4) or `is_supplementary` (0x800);
///  2. skip if `reference_end is None` OR `reference_end < s` OR `reference_start > e`
///     — where `s`/`e` are the ORIGINAL (un-padded) region bounds, `reference_start` is
///     the 0-based leftmost aligned position (`alignment_start-1`) and `reference_end` is
///     the 0-based exclusive end (`reference_start + cigar reference-span`, i.e. the same
///     `reference_start + sum(M/D/N/=/X)` pysam reports; `None` when the read has no
///     reference-consuming alignment);
///  3. skip if the `de` tag is absent (so a seq-bearing read WITHOUT `de` never enters
///     `seqs` either — the `de` gate precedes the `seqs` update, exactly as in Python).
///
/// ## Query ↔ pysam intersection equivalence
/// pysam `fetch(c, s2, stop)` (0-based half-open) returns a read iff
/// `reference_start < stop AND reference_end > s2`. The noodles indexed query filters on
/// the 1-based-inclusive interval `[s2+1, stop]` (built via the crate's established
/// `"{chrom}:{a}-{b}"` region string) intersecting the read's 1-based `[start, end]`,
/// which reduces to the SAME predicate. Both return records in coordinate (BGZF file)
/// order, so re-applying the exact Python post-filter yields an identical set AND the
/// identical insertion order for `seqs`.
///
/// Requires a `{bam_path}.bai` index; errors (rather than scanning) if it is missing, so
/// the byte-parity test can skip cleanly when the multi-GB BAM is unavailable.
pub fn fetch_reads<P: AsRef<Path>>(
    bam_path: P,
    regions: &[(String, i64, i64, i64)],
    contig_len: &BTreeMap<String, i64>,
    pad: i64,
    read_cap: usize,
) -> Result<(BTreeMap<String, (usize, f64)>, Vec<(String, String)>)> {
    let bam_path = bam_path.as_ref();
    let bai_path = {
        let mut s = bam_path.as_os_str().to_os_string();
        s.push(".bai");
        std::path::PathBuf::from(s)
    };
    anyhow::ensure!(
        bai_path.exists(),
        "fetch_reads needs a .bai index next to {} (expected {})",
        bam_path.display(),
        bai_path.display()
    );

    let mut reader = noodles_bam::io::reader::Builder::default().build_from_path(bam_path)?;
    let header = reader.read_header()?;
    let index = noodles_bam::bai::read(&bai_path)?;

    // `best` is a MAP (qname -> (region_idx, de)); BTreeMap gives deterministic ascending
    // key order (Python later does `for r in sorted(best)`). `seqs`/`seen` preserve the
    // load-bearing first-seen INSERTION order for the cap.
    let mut best: BTreeMap<String, (usize, f64)> = BTreeMap::new();
    let mut seqs: Vec<(String, String)> = Vec::new();
    let mut seen: HashSet<String> = HashSet::new();

    for (i, (c, s, e, _)) in regions.iter().enumerate() {
        // s2, e2 = max(0, s - PAD), e + PAD ; stop = min(contig_len.get(c, e2), e2)
        let s2 = (s - pad).max(0);
        let e2 = e + pad;
        let stop = contig_len.get(c).copied().unwrap_or(e2).min(e2);
        if stop <= s2 {
            continue; // degenerate/empty region -> pysam.fetch returns nothing
        }
        // 1-based inclusive [s2+1, stop] == pysam 0-based half-open [s2, stop).
        let region: noodles_core::Region = format!("{c}:{}-{}", s2 + 1, stop).parse()?;
        let query = reader.query(&header, &index, &region)?;

        for result in query {
            let record = result?;
            let rb = RecordBuf::try_from_alignment_record(&header, &record)?;

            let flags = rb.flags();
            if flags.is_unmapped() || flags.is_supplementary() {
                continue;
            }

            // reference_start (0-based) and reference_end (0-based exclusive).
            // `reference_end is None` <=> no reference-consuming alignment.
            let Some(start) = rb.alignment_start() else {
                continue;
            };
            let ref_start_0 = start.get() as i64 - 1;
            let span = rb.cigar().alignment_span() as i64;
            if span == 0 {
                continue; // pysam reference_end is None here
            }
            let ref_end_0_excl = ref_start_0 + span;
            if ref_end_0_excl < *s || ref_start_0 > *e {
                continue;
            }

            let Some(de) = read_de_tag(&rb) else {
                continue;
            };

            let name = match rb.name() {
                Some(n) => n.to_string(),
                None => continue,
            };

            // best[qname] = (i, de) if new OR strictly-lower de (first-seen wins ties).
            match best.get(&name) {
                None => {
                    best.insert(name.clone(), (i, de));
                }
                Some(&(_, cur_de)) => {
                    if de < cur_de {
                        best.insert(name.clone(), (i, de));
                    }
                }
            }

            // seqs[qname] = query_sequence, first non-secondary seq-bearing sighting.
            if !flags.is_secondary() && !seen.contains(&name) {
                let seq_bytes: &[u8] = rb.sequence().as_ref();
                if !seq_bytes.is_empty() {
                    let seq: String = seq_bytes.iter().map(|&b| b as char).collect();
                    seen.insert(name.clone());
                    seqs.push((name, seq));
                }
            }
        }
    }

    if seqs.len() > read_cap {
        seqs.truncate(read_cap);
    }
    Ok((best, seqs))
}

// ===========================================================================
// assemble_vg  (the deterministic assembly core of
// bench/o2_vg_visualization.py::materialize_family, lines ~168-284)
// ===========================================================================

/// Default genome FASTA, the `materialize_family` copy-extraction input. Python
/// `bench/psv_graph_genomewide.py:30  GENOME = "/home/juanfra/winloci_scratch/GGO.fasta"`.
// test-only; not a shipped default — only consumed by `MaterializeConfig::defaults`,
// which is only constructed inside this module's `#[cfg(test)]` block. No `src/bin/*.rs`
// binary imports `o2_materialize`, so no shipped run can reach this constant.
pub const GENOME_DEFAULT: &str = "/home/juanfra/winloci_scratch/GGO.fasta"; // test-only; not a shipped default

/// A PSV bubble must recur across at least this many reads (not a one-read error).
/// Python `bench/psv_graph_genomewide.py:34  MIN_READS_PSV = 3`.
pub const MIN_READS_PSV: usize = 3;

/// Default VG cache directory. Python `bench/o2_vg_visualization.py:59
/// CACHE = "/home/juanfra/winloci_scratch/o2vg"`.
pub const CACHE_DIR_DEFAULT: &str = "/home/juanfra/winloci_scratch/o2vg"; // test-only; not a shipped default

/// The pre- and post-abstain materialized-VG JSON objects: `pre_abstain` is what the
/// Python dumps to the cache (`json.dump(vg, ...)` BEFORE the abstain leg);
/// `post_abstain` is what `materialize_family` RETURNS (after
/// `ra.apply_abstain_to_vg(vg)`). They differ only by the recombinant-abstain flips
/// (identical when no read flips, e.g. `< 2` bubbles or the leg opted out).
#[derive(Clone, Debug)]
pub struct VgPair {
    /// The pre-abstain VG (Python cache dump).
    pub pre_abstain: Value,
    /// The post-abstain VG (Python `materialize_family` return value).
    pub post_abstain: Value,
}

/// Python `round(float(x), 2)`, bit-for-bit.
///
/// CPython's `float.__round__(ndigits=2)` produces the correctly-rounded (round-half-to-
/// even) 2-decimal string via David Gay's dtoa, then converts it back to the nearest
/// `double`. `format!("{:.2}", x)` in Rust is likewise correctly-rounded round-half-to-
/// even on the exact binary value, and `parse::<f64>()` is a correct `strtod`, so the
/// composition yields the identical `f64`. `x` is always finite and non-negative here
/// (`margin = logL[best] - logL[runner-up] >= 0`; the `+inf` single-copy case never
/// reaches a read row because a lone copy admits no `>= 2`-allele bubble).
fn round2(x: f64) -> f64 {
    if !x.is_finite() {
        return x;
    }
    format!("{x:.2}").parse::<f64>().expect("round2 reparse")
}

/// A finite `f64` as a JSON number (mirrors `json.dump(float)` -> a JSON float that
/// serde parses back to the same `Float`). Non-finite -> `null` (never hit here).
fn f64_num(x: f64) -> Value {
    serde_json::Number::from_f64(x).map(Value::Number).unwrap_or(Value::Null)
}

/// `dict(counter)` as a JSON object `{key: count}` (order-independent; the Python
/// Counter/`dict` order is irrelevant to the semantic-map comparison).
fn counter_to_value(c: &BTreeMap<String, i64>) -> Value {
    let mut m = Map::new();
    for (k, v) in c {
        m.insert(k.clone(), json!(v));
    }
    Value::Object(m)
}

/// One kept PSV bubble: the parallel state (`pos`, `hap`) the downstream assembly needs
/// plus the emitted JSON object.
struct KeptBubble {
    pos: i64,
    hap: BTreeMap<String, char>, // name -> allele, EVERY copy present (kept-bubble invariant)
    json: Value,
}

/// Assemble the per-family variation-graph object from already-extracted columns — the
/// deterministic core of `bench/o2_vg_visualization.py::materialize_family` (lines
/// ~168-284), FACTORED OUT so it is fixture-testable WITHOUT running minimap2/samtools.
///
/// Inputs are exactly what the recompute path computes before the assembly:
///  * `regions` — dedup'd copy regions, ALREADY sorted by `-(end-start)` (Python
///    `sorted(..., key=lambda r: -(r[2]-r[1]))`); `regions[i]` is copy `i`.
///  * `backbone` — `(chrom, start, end)` of `regions[0]` after clamping (`backbone_*`).
///  * `refseq` — the UPPERCASED backbone bytes (`genome.fetch(bc,bs,be).upper()`).
///  * `names` — `["copy0", .., "copyN"]`.
///  * `copy_cols` / `read_cols` — [`column_alleles`] over the copies / reads BAM on
///    `copy0`.
///  * `best_names` — the read names in `sorted(best)` order (`n_reads == best_names.len`).
///  * `gene_lbl` — `(chrom, start) -> gene`.
///
/// Returns both the pre-abstain VG (Python cache dump) and the post-abstain VG (return
/// value): the recombinant-abstain leg [`apply_abstain_to_vg`] is applied to a
/// [`FamilyVg`] view and merged back (flipped reads get `status="recombinant"`,
/// `best_copy=null`, and the `gate_status_pre_abstain` / `recombinant_kind` keys; the
/// top-level `assignment` / `per_copy` counters move; `copies[*].n_assigned_reads` stays
/// the PRE-abstain quant, exactly as the Python `copies_out` captured it before the leg).
#[allow(clippy::too_many_arguments)]
pub fn assemble_vg(
    fam_id: i64,
    regions: &[(String, i64, i64, i64)],
    backbone: (&str, i64, i64),
    refseq: &[u8],
    names: &[String],
    copy_cols: &BTreeMap<i64, BTreeMap<String, char>>,
    read_cols: &BTreeMap<i64, BTreeMap<String, char>>,
    best_names: &[String],
    gene_lbl: &BTreeMap<(String, i64), String>,
) -> VgPair {
    let nnames = names.len();

    // ---- PSV bubbles: all copies defined, >=2 distinct alleles, read-supported ----
    let mut bubbles: Vec<KeptBubble> = Vec::new();
    let mut n_sun_bubbles = 0usize;
    for p in 0..refseq.len() {
        let mut hap: BTreeMap<String, char> = BTreeMap::new();
        hap.insert(names[0].clone(), refseq[p] as char);
        let cc = copy_cols.get(&(p as i64));
        for nm in &names[1..] {
            if let Some(m) = cc {
                if let Some(&b) = m.get(nm) {
                    hap.insert(nm.clone(), b);
                }
            }
        }
        if hap.len() != nnames {
            continue; // not every copy is defined at this column
        }
        let distinct: BTreeSet<char> = hap.values().copied().collect();
        if distinct.len() < 2 {
            continue; // no variation -> not a PSV
        }
        let n_read_support = read_cols.get(&(p as i64)).map(|m| m.len()).unwrap_or(0);
        if n_read_support < MIN_READS_PSV {
            continue; // one-read error, not a recurrent PSV
        }

        // allele -> [copies], in names order (list order is load-bearing); allele KEY
        // order is irrelevant (JSON object).
        let mut alleles: Vec<(char, Vec<String>)> = Vec::new();
        // char -> count for the SUN (private-allele) test.
        let mut count: BTreeMap<char, usize> = BTreeMap::new();
        for nm in names {
            let a = hap[nm];
            *count.entry(a).or_insert(0) += 1;
            if let Some(e) = alleles.iter_mut().find(|(k, _)| *k == a) {
                e.1.push(nm.clone());
            } else {
                alleles.push((a, vec![nm.clone()]));
            }
        }
        // sun_copy = FIRST copy (names order) whose allele is unique among the copies.
        let mut sun_copy: Option<String> = None;
        for nm in names {
            if count[&hap[nm]] == 1 {
                sun_copy = Some(nm.clone());
                break;
            }
        }
        if sun_copy.is_some() {
            n_sun_bubbles += 1;
        }

        let col = bubbles.len();
        let mut hap_json = Map::new();
        for nm in names {
            hap_json.insert(nm.clone(), Value::String(hap[nm].to_string()));
        }
        let mut alleles_json = Map::new();
        for (a, mem) in &alleles {
            alleles_json.insert(
                a.to_string(),
                Value::Array(mem.iter().map(|m| Value::String(m.clone())).collect()),
            );
        }
        let bjson = json!({
            "col": col,
            "pos": p,
            "hap": Value::Object(hap_json),
            "alleles": Value::Object(alleles_json),
            "is_sun": sun_copy.is_some(),
            "sun_copy": sun_copy.clone().map(Value::String).unwrap_or(Value::Null),
            "n_read_support": n_read_support,
        });
        bubbles.push(KeptBubble { pos: p as i64, hap, json: bjson });
    }

    // ---- hap-rows -> groups (first-seen order) -> group_id (stable sort by -size) ----
    let hap_rows: Vec<Vec<char>> = names
        .iter()
        .map(|nm| bubbles.iter().map(|b| b.hap[nm]).collect())
        .collect();
    let mut group_order: Vec<(Vec<char>, Vec<usize>)> = Vec::new();
    for ni in 0..nnames {
        let hr = &hap_rows[ni];
        if let Some(g) = group_order.iter_mut().find(|(k, _)| k == hr) {
            g.1.push(ni);
        } else {
            group_order.push((hr.clone(), vec![ni]));
        }
    }
    let k_groups = group_order.len();
    let mut group_sizes: Vec<usize> = group_order.iter().map(|(_, m)| m.len()).collect();
    group_sizes.sort_by(|a, b| b.cmp(a)); // descending
    // group_id: enumerate groups sorted by -len (STABLE -> ties keep first-seen order).
    let mut order_idx: Vec<usize> = (0..group_order.len()).collect();
    order_idx.sort_by_key(|&i| std::cmp::Reverse(group_order[i].1.len()));
    let mut group_id = vec![0usize; nnames];
    let mut group_size_of = vec![0usize; nnames];
    for (gi, &oi) in order_idx.iter().enumerate() {
        for &ni in &group_order[oi].1 {
            group_id[ni] = gi;
        }
    }
    for (_, mem) in &group_order {
        for &ni in mem {
            group_size_of[ni] = mem.len();
        }
    }

    // ---- per-copy SUN columns + tier ----
    let mut sun_cols: Vec<Vec<usize>> = vec![Vec::new(); nnames];
    for (j, b) in bubbles.iter().enumerate() {
        let mut count: BTreeMap<char, usize> = BTreeMap::new();
        for nm in names {
            *count.entry(b.hap[nm]).or_insert(0) += 1;
        }
        for (ni, nm) in names.iter().enumerate() {
            if count[&b.hap[nm]] == 1 {
                sun_cols[ni].push(j);
            }
        }
    }
    let mut tier = vec![0i64; nnames];
    for ni in 0..nnames {
        tier[ni] = if group_size_of[ni] > 1 {
            3 // hap-row collapses with another copy -> K-frontier
        } else if !sun_cols[ni].is_empty() {
            1 // >=1 private column -> single-read SUN-identifiable
        } else {
            2 // unique hap-row but no SUN -> needs PSV linkage
        };
    }

    // ---- copy allele vectors in COLUMN space (names order) for the real gate ----
    let copy_vecs: Vec<(String, BTreeMap<usize, char>)> = names
        .iter()
        .map(|nm| {
            let m: BTreeMap<usize, char> =
                bubbles.iter().enumerate().map(|(j, b)| (j, b.hap[nm])).collect();
            (nm.clone(), m)
        })
        .collect();

    // ---- thread every read through the graph via the REAL gate ----
    let mut reads_pre: Vec<Map<String, Value>> = Vec::with_capacity(best_names.len());
    let mut fvg_reads: Vec<VgRead> = Vec::with_capacity(best_names.len());
    let mut cats: BTreeMap<String, i64> = BTreeMap::new();
    let mut per_copy: BTreeMap<String, i64> = BTreeMap::new();
    for r in best_names {
        let mut obs: BTreeMap<usize, char> = BTreeMap::new();
        for (j, b) in bubbles.iter().enumerate() {
            if let Some(m) = read_cols.get(&b.pos) {
                if let Some(&base) = m.get(r) {
                    obs.insert(j, base);
                }
            }
        }
        if obs.is_empty() {
            *cats.entry("no_cover".to_string()).or_insert(0) += 1;
            let mut rm = Map::new();
            rm.insert("name".to_string(), Value::String(r.clone()));
            rm.insert("best_copy".to_string(), Value::Null);
            rm.insert("status".to_string(), Value::String("no_cover".to_string()));
            rm.insert("margin".to_string(), json!(0.0));
            rm.insert("n_span".to_string(), json!(0));
            rm.insert("n_decisive".to_string(), json!(0));
            rm.insert("span_cols".to_string(), Value::Null);
            rm.insert("obs".to_string(), Value::Object(Map::new()));
            reads_pre.push(rm);
            fvg_reads.push(VgRead {
                name: r.clone(),
                obs: BTreeMap::new(),
                status: "no_cover".to_string(),
                best_copy: None,
                gate_status_pre_abstain: None,
                recombinant_kind: None,
            });
            continue;
        }
        let obs_opt: BTreeMap<usize, Option<char>> =
            obs.iter().map(|(&k, &v)| (k, Some(v))).collect();
        let res = assign_read_margin(&obs_opt, &copy_vecs, None, None, ERR, JW, BTOL);
        let spanned: Vec<usize> = obs.keys().copied().collect(); // ascending (BTreeMap)
        let span0 = spanned[0];
        let span1 = spanned[spanned.len() - 1];
        let (status, best_copy): (&str, Option<String>) =
            if res.n_decisive >= 1 && res.margin >= MARGIN {
                ("assigned", Some(res.best.clone()))
            } else if res.n_decisive >= 1 {
                ("ambiguous", None)
            } else {
                ("tied", None)
            };
        match status {
            "assigned" => {
                *cats.entry("assigned".to_string()).or_insert(0) += 1;
                *per_copy.entry(res.best.clone()).or_insert(0) += 1;
            }
            "ambiguous" => {
                *cats.entry("ambiguous".to_string()).or_insert(0) += 1;
            }
            _ => {
                *cats.entry("tied".to_string()).or_insert(0) += 1;
            }
        }
        let mut obs_json = Map::new();
        for (&k, &v) in &obs {
            obs_json.insert(k.to_string(), Value::String(v.to_string()));
        }
        let mut rm = Map::new();
        rm.insert("name".to_string(), Value::String(r.clone()));
        rm.insert(
            "best_copy".to_string(),
            best_copy.clone().map(Value::String).unwrap_or(Value::Null),
        );
        rm.insert("status".to_string(), Value::String(status.to_string()));
        rm.insert("margin".to_string(), f64_num(round2(res.margin)));
        rm.insert("n_span".to_string(), json!(res.n_span));
        rm.insert("n_decisive".to_string(), json!(res.n_decisive));
        rm.insert("span_cols".to_string(), json!([span0, span1]));
        rm.insert("obs".to_string(), Value::Object(obs_json));
        reads_pre.push(rm);
        fvg_reads.push(VgRead {
            name: r.clone(),
            obs,
            status: status.to_string(),
            best_copy,
            gate_status_pre_abstain: None,
            recombinant_kind: None,
        });
    }

    // ---- classification ----
    let cls = if bubbles.is_empty() {
        "no_psv (K-FRONTIER floor)"
    } else if k_groups == 1 {
        "collapsed (K-FRONTIER floor)" // unreachable in practice (a bubble forces K>=2)
    } else if k_groups == nnames {
        "fully_resolvable"
    } else {
        "partial (mixed resolvable / collapsed)"
    };

    // ---- copies (n_assigned_reads is the PRE-abstain quant, captured now) ----
    let mut copies_json: Vec<Value> = Vec::with_capacity(nnames);
    for (i, (c, s, e, _nr)) in regions.iter().enumerate() {
        let nm = &names[i];
        let gene = gene_lbl
            .get(&(c.clone(), *s))
            .cloned()
            .unwrap_or_else(|| "?".to_string());
        let n_assigned = *per_copy.get(nm).unwrap_or(&0);
        let mut cm = Map::new();
        cm.insert("name".to_string(), Value::String(nm.clone()));
        cm.insert("chrom".to_string(), Value::String(c.clone()));
        cm.insert("start".to_string(), json!(s));
        cm.insert("end".to_string(), json!(e));
        cm.insert("length".to_string(), json!(e - s));
        cm.insert("gene".to_string(), Value::String(gene));
        cm.insert("hap_group".to_string(), json!(group_id[i]));
        cm.insert("tier".to_string(), json!(tier[i]));
        cm.insert("n_sun".to_string(), json!(sun_cols[i].len()));
        cm.insert("sun_cols".to_string(), json!(sun_cols[i]));
        cm.insert("n_assigned_reads".to_string(), json!(n_assigned));
        copies_json.push(Value::Object(cm));
    }

    // ---- tiers Counter ----
    let mut tiers_count: BTreeMap<i64, i64> = BTreeMap::new();
    for &t in &tier {
        *tiers_count.entry(t).or_insert(0) += 1;
    }
    let mut tiers_json = Map::new();
    for (t, cnt) in &tiers_count {
        tiers_json.insert(t.to_string(), json!(cnt));
    }

    // ---- top-level scalar fields (shared by pre + post) ----
    let (gene_flag, role_flag) = FLAGSHIP
        .iter()
        .find(|(id, _, _)| *id == fam_id)
        .map(|(_, g, r)| (*g, *r))
        .unwrap_or(("?", "?"));
    let chroms: BTreeSet<String> = regions.iter().map(|r| r.0.clone()).collect();
    let cross_chrom = chroms.len() >= 2;
    let chroms_vec: Vec<String> = chroms.into_iter().collect();

    let mut base = Map::new();
    base.insert("family".to_string(), json!(fam_id));
    base.insert("gene".to_string(), Value::String(gene_flag.to_string()));
    base.insert("role".to_string(), Value::String(role_flag.to_string()));
    base.insert("n_copies".to_string(), json!(nnames));
    base.insert("backbone_len".to_string(), json!(refseq.len()));
    base.insert("backbone_chrom".to_string(), Value::String(backbone.0.to_string()));
    base.insert("backbone_start".to_string(), json!(backbone.1));
    base.insert("backbone_end".to_string(), json!(backbone.2));
    base.insert("cross_chrom".to_string(), json!(cross_chrom));
    base.insert("chroms".to_string(), json!(chroms_vec));
    base.insert("n_bubbles".to_string(), json!(bubbles.len()));
    base.insert("n_sun_bubbles".to_string(), json!(n_sun_bubbles));
    base.insert("K".to_string(), json!(k_groups));
    base.insert("cls".to_string(), Value::String(cls.to_string()));
    base.insert("group_sizes".to_string(), json!(group_sizes));
    base.insert("tiers".to_string(), Value::Object(tiers_json));
    base.insert("copies".to_string(), Value::Array(copies_json));
    base.insert(
        "bubbles".to_string(),
        Value::Array(bubbles.iter().map(|b| b.json.clone()).collect()),
    );
    base.insert("n_reads".to_string(), json!(best_names.len()));

    // ---- pre-abstain VG (the cache dump) ----
    let mut pre = base.clone();
    pre.insert(
        "reads".to_string(),
        Value::Array(reads_pre.iter().map(|m| Value::Object(m.clone())).collect()),
    );
    pre.insert("assignment".to_string(), counter_to_value(&cats));
    pre.insert("per_copy".to_string(), counter_to_value(&per_copy));
    let pre_abstain = Value::Object(pre);

    // ---- recombinant-abstain leg over a FamilyVg view, then merge back ----
    let mut fvg = FamilyVg {
        family: fam_id,
        copies: names.iter().map(|nm| VgCopy { name: nm.clone() }).collect(),
        bubbles: bubbles
            .iter()
            .map(|b| VgBubble { hap: b.hap.clone() })
            .collect(),
        reads: fvg_reads,
        assignment: cats.clone(),
        per_copy: per_copy.clone(),
    };
    let _flipped = apply_abstain_to_vg(&mut fvg);

    let mut reads_post: Vec<Value> = Vec::with_capacity(reads_pre.len());
    for (i, rm) in reads_pre.iter().enumerate() {
        let fr = &fvg.reads[i];
        if fr.gate_status_pre_abstain.is_some() {
            // flipped: status -> recombinant, drop best_copy, add the two abstain keys.
            let mut m = rm.clone();
            m.insert("status".to_string(), Value::String(fr.status.clone()));
            m.insert("best_copy".to_string(), Value::Null);
            m.insert(
                "gate_status_pre_abstain".to_string(),
                Value::String(fr.gate_status_pre_abstain.clone().unwrap()),
            );
            m.insert(
                "recombinant_kind".to_string(),
                Value::String(fr.recombinant_kind.clone().unwrap()),
            );
            reads_post.push(Value::Object(m));
        } else {
            reads_post.push(Value::Object(rm.clone()));
        }
    }

    let mut post = base;
    post.insert("reads".to_string(), Value::Array(reads_post));
    post.insert("assignment".to_string(), counter_to_value(&fvg.assignment));
    post.insert("per_copy".to_string(), counter_to_value(&fvg.per_copy));
    let post_abstain = Value::Object(post);

    VgPair { pre_abstain, post_abstain }
}

// ===========================================================================
// materialize_family  (the full recompute path, use_cache=False)
// ===========================================================================

/// Paths + tunables the recompute path needs. [`MaterializeConfig::defaults`] fills the
/// Python constants (`pg.GENOME`, `pg.BAM`, `pg.FAM_TSV`, `SUN_TSV`, `CACHE`, `pg.PAD`,
/// `pg.READ_CAP`); tests override `cache_dir` / `tmp_dir` / `write_cache` to avoid
/// touching the real cache.
#[derive(Clone, Debug)]
pub struct MaterializeConfig {
    /// Genome FASTA (`.fai` sidecar required), `genome.fetch` + contig lengths.
    pub genome: String,
    /// Genome BAM (`.bai` required), the multimapper read pool.
    pub bam: String,
    /// Validated-families TSV.
    pub fam_tsv: String,
    /// SUN-identifiability TSV (gene labels).
    pub sun_tsv: String,
    /// VG cache directory (the `fam{id}.json` pre-abstain dump destination).
    pub cache_dir: String,
    /// Working directory for the per-family FASTAs/BAMs; `None` -> `{cache_dir}/tmp_fam{id}_rs`.
    pub tmp_dir: Option<String>,
    /// `minimap2` executable.
    pub minimap2: String,
    /// `samtools` executable.
    pub samtools: String,
    /// Fetch pad (`pg.PAD`).
    pub pad: i64,
    /// Read-sequence pool cap (`pg.READ_CAP`).
    pub read_cap: usize,
    /// Write the pre-abstain VG to `{cache_dir}/fam{id}.json` (Python `json.dump`).
    pub write_cache: bool,
}

impl MaterializeConfig {
    /// The shipped defaults (Python constants). `sun_tsv` must point at the `bench/`
    /// copy (the caller supplies the absolute path, as Python's `HERE`-relative join).
    pub fn defaults(sun_tsv: impl Into<String>) -> Self {
        MaterializeConfig {
            genome: GENOME_DEFAULT.to_string(),
            bam: BAM_DEFAULT.to_string(),
            fam_tsv: fam_tsv_path(),
            sun_tsv: sun_tsv.into(),
            cache_dir: CACHE_DIR_DEFAULT.to_string(),
            tmp_dir: None,
            minimap2: "minimap2".to_string(),
            samtools: "samtools".to_string(),
            pad: PAD,
            read_cap: READ_CAP,
            write_cache: true,
        }
    }
}

/// Read `name -> length` from a `.fai` sidecar (`contig_len` in Python:
/// `dict(zip(genome.references, genome.lengths))`).
fn read_contig_lengths(fai_path: &str) -> Result<BTreeMap<String, i64>> {
    let text = std::fs::read_to_string(fai_path)?;
    let mut out = BTreeMap::new();
    for line in text.lines() {
        let f: Vec<&str> = line.split('\t').collect();
        if f.len() < 2 {
            continue;
        }
        let len: i64 = f[1].parse().unwrap_or(0);
        out.insert(f[0].to_string(), len);
    }
    Ok(out)
}

/// Write a multi-record FASTA (`>{name}\n{seq}\n` per record; `seq` bytes verbatim).
fn write_fasta_records(path: &str, records: &[(String, &[u8])]) -> Result<()> {
    let mut f = std::io::BufWriter::new(std::fs::File::create(path)?);
    for (name, seq) in records {
        f.write_all(b">")?;
        f.write_all(name.as_bytes())?;
        f.write_all(b"\n")?;
        f.write_all(seq)?;
        f.write_all(b"\n")?;
    }
    f.flush()?;
    Ok(())
}

/// `samtools faidx {fa}` (stdout/stderr silenced, like `pg.sh`).
fn run_samtools_faidx(cfg: &MaterializeConfig, fa: &str) -> Result<()> {
    let status = Command::new(&cfg.samtools)
        .args(["faidx", fa])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()?;
    anyhow::ensure!(status.success(), "samtools faidx {fa} failed: {status}");
    Ok(())
}

/// `minimap2 -ax {preset} {ref} {query} 2>/dev/null | samtools sort -o {out_bam} - &&
/// samtools index {out_bam}` — the exact Python pipeline, wired via a direct OS pipe
/// (minimap2 stdout -> samtools sort stdin) rather than a shell string.
fn run_minimap2_sort(
    cfg: &MaterializeConfig,
    preset: &str,
    ref_fa: &str,
    query_fa: &str,
    out_bam: &str,
) -> Result<()> {
    let mut mm = Command::new(&cfg.minimap2)
        .args(["-ax", preset, ref_fa, query_fa])
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()?;
    let mm_stdout = mm.stdout.take().expect("minimap2 stdout piped");
    let sort_status = Command::new(&cfg.samtools)
        .args(["sort", "-o", out_bam, "-"])
        .stdin(Stdio::from(mm_stdout))
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()?;
    let mm_status = mm.wait()?;
    anyhow::ensure!(mm_status.success(), "minimap2 -ax {preset} failed: {mm_status}");
    anyhow::ensure!(sort_status.success(), "samtools sort -> {out_bam} failed: {sort_status}");
    let idx = Command::new(&cfg.samtools)
        .args(["index", out_bam])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()?;
    anyhow::ensure!(idx.success(), "samtools index {out_bam} failed: {idx}");
    Ok(())
}

/// The FULL `materialize_family` recompute path (`use_cache=False`): copy extraction +
/// minimap2/samtools orchestration + [`fetch_reads`] + [`column_alleles`] + [`assemble_vg`].
///
/// Byte-faithful port of `bench/o2_vg_visualization.py::materialize_family` lines
/// ~116-284. Returns the [`VgPair`] (pre-abstain cache dump + post-abstain return); when
/// `cfg.write_cache` the pre-abstain VG is written to `{cache_dir}/fam{id}.json` exactly
/// as the Python `json.dump`.
pub fn materialize_family(fam_id: i64, cfg: &MaterializeConfig) -> Result<VgPair> {
    std::fs::create_dir_all(&cfg.cache_dir)?;
    let tmp = cfg
        .tmp_dir
        .clone()
        .unwrap_or_else(|| format!("{}/tmp_fam{}_rs", cfg.cache_dir, fam_id));
    std::fs::create_dir_all(&tmp)?;

    let genome = IndexedFasta::open(&cfg.genome)
        .map_err(|e| anyhow::anyhow!("open genome {}: {e}", cfg.genome))?;
    let contig_len = read_contig_lengths(&format!("{}.fai", cfg.genome))?;
    let gene_lbl = load_gene_labels(&cfg.sun_tsv)?;
    let fams = load_families(&cfg.fam_tsv)?;
    let fam_loci = fams.get(&fam_id).cloned().unwrap_or_default();

    // regions = dedup_copies sorted by -(e-s)  (STABLE sort keeps dedup return order on ties)
    let mut regions = dedup_copies(&fam_loci);
    regions.sort_by(|a, b| (b.2 - b.1).cmp(&(a.2 - a.1)));
    anyhow::ensure!(!regions.is_empty(), "family {fam_id} has no regions");
    let names: Vec<String> = (0..regions.len()).map(|i| format!("copy{i}")).collect();

    let (bc, s0, e0, _) = regions[0].clone();
    let bs = s0.max(0);
    let be = contig_len.get(&bc).copied().unwrap_or(e0).min(e0);
    let refseq: Vec<u8> = genome
        .fetch(&bc, bs, be)
        .ok_or_else(|| anyhow::anyhow!("fetch backbone {bc}:{bs}-{be}"))?
        .iter()
        .map(|b| b.to_ascii_uppercase())
        .collect();

    // ref.fa (>copy0) + faidx
    write_fasta_records(&format!("{tmp}/ref.fa"), &[(names[0].clone(), &refseq)])?;
    run_samtools_faidx(cfg, &format!("{tmp}/ref.fa"))?;

    // copies.fa (>copyN for each region[1:])
    let mut copy_seqs: Vec<(String, Vec<u8>)> = Vec::new();
    for (i, nm) in names.iter().enumerate().skip(1) {
        let (c, s, e, _) = &regions[i];
        let s2 = (*s).max(0);
        let e2 = contig_len.get(c).copied().unwrap_or(*e).min(*e);
        let seq: Vec<u8> = genome
            .fetch(c, s2, e2)
            .unwrap_or_default()
            .iter()
            .map(|b| b.to_ascii_uppercase())
            .collect();
        copy_seqs.push((nm.clone(), seq));
    }
    let copy_recs: Vec<(String, &[u8])> =
        copy_seqs.iter().map(|(n, s)| (n.clone(), s.as_slice())).collect();
    write_fasta_records(&format!("{tmp}/copies.fa"), &copy_recs)?;
    run_minimap2_sort(
        cfg,
        "asm20",
        &format!("{tmp}/ref.fa"),
        &format!("{tmp}/copies.fa"),
        &format!("{tmp}/copies.bam"),
    )?;

    // reads from all copy loci -> best-mapping copy; reads.fa (insertion order)
    let (best, seqs) = fetch_reads(&cfg.bam, &regions, &contig_len, cfg.pad, cfg.read_cap)?;
    let read_recs: Vec<(String, &[u8])> =
        seqs.iter().map(|(n, s)| (n.clone(), s.as_bytes())).collect();
    write_fasta_records(&format!("{tmp}/reads.fa"), &read_recs)?;
    run_minimap2_sort(
        cfg,
        "splice:hq",
        &format!("{tmp}/ref.fa"),
        &format!("{tmp}/reads.fa"),
        &format!("{tmp}/reads.bam"),
    )?;

    let copy_cols = column_alleles(format!("{tmp}/copies.bam"), &names[0])?;
    let read_cols = column_alleles(format!("{tmp}/reads.bam"), &names[0])?;
    let best_names: Vec<String> = best.keys().cloned().collect(); // sorted(best)

    let pair = assemble_vg(
        fam_id,
        &regions,
        (&bc, bs, be),
        &refseq,
        &names,
        &copy_cols,
        &read_cols,
        &best_names,
        &gene_lbl,
    );

    if cfg.write_cache {
        std::fs::write(
            format!("{}/fam{}.json", cfg.cache_dir, fam_id),
            serde_json::to_string(&pair.pre_abstain)?,
        )?;
    }
    Ok(pair)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/o2_materialize_fixture.json");
        serde_json::from_str(raw).expect("parse o2_materialize fixture json")
    }

    /// dedup_copies == Python EXACTLY (incl. RETURN ORDER) on every case.
    #[test]
    fn dedup_copies_byte_parity() {
        let fx = load_fixture();

        // OVERLAP_MERGE value agreement.
        assert_eq!(
            OVERLAP_MERGE,
            fx["overlap_merge"].as_f64().unwrap(),
            "OVERLAP_MERGE constant disagrees with Python"
        );

        let cases = fx["dedup_cases"].as_array().expect("dedup_cases array");
        assert!(
            cases.len() >= 100,
            "expected >=100 dedup cases, got {}",
            cases.len()
        );

        let mut n_merge = 0usize;
        let mut n_multichrom = 0usize;
        let mut n_single = 0usize;
        let mut n_tandem_sep = 0usize;

        for case in cases {
            let id = case["id"].as_str().unwrap();
            let loci: Vec<FamLocus> = case["loci"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    let a = r.as_array().unwrap();
                    (
                        a[0].as_str().unwrap().to_string(),
                        a[1].as_str().unwrap().to_string(),
                        a[2].as_i64().unwrap(),
                        a[3].as_i64().unwrap(),
                        a[4].as_i64().unwrap(),
                    )
                })
                .collect();
            let expect: Vec<(String, i64, i64, i64)> = case["expect"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    let a = r.as_array().unwrap();
                    (
                        a[0].as_str().unwrap().to_string(),
                        a[1].as_i64().unwrap(),
                        a[2].as_i64().unwrap(),
                        a[3].as_i64().unwrap(),
                    )
                })
                .collect();

            let got = dedup_copies(&loci);

            // First-mismatch localization (position + field), then whole-vec equality.
            let n = got.len().max(expect.len());
            for i in 0..n {
                match (got.get(i), expect.get(i)) {
                    (Some(g), Some(e)) if g == e => {}
                    (g, e) => panic!(
                        "dedup case {id}: region[{i}] rust={:?} python={:?}\n  \
                         rust n_regions={}, python n_regions={}",
                        g,
                        e,
                        got.len(),
                        expect.len()
                    ),
                }
            }
            assert_eq!(got, expect, "dedup case {id}: whole-vec inequality");

            // Class accounting (for the fixture-composition sanity checks below).
            let n_loci = loci.len();
            let n_chrom = {
                let mut cs: Vec<&str> = loci.iter().map(|l| l.1.as_str()).collect();
                cs.sort();
                cs.dedup();
                cs.len()
            };
            if n_loci == 1 {
                n_single += 1;
            }
            if n_chrom >= 2 {
                n_multichrom += 1;
            }
            if got.len() < n_loci {
                n_merge += 1;
            }
            // same-chrom loci that stayed as multiple regions => a tandem separation
            if n_chrom == 1 && got.len() >= 2 {
                n_tandem_sep += 1;
            }
        }

        assert!(n_merge >= 1, "no case exercised an isoform merge");
        assert!(n_single >= 1, "no single-locus case");
        assert!(n_multichrom >= 1, "no multi-chrom case");
        assert!(n_tandem_sep >= 1, "no tandem-stays-separate case");

        eprintln!(
            "o2_materialize dedup_copies byte-parity: {} cases all match incl order \
             ({} with merges, {} single-locus, {} multi-chrom, {} tandem-separate)",
            cases.len(),
            n_merge,
            n_single,
            n_multichrom,
            n_tandem_sep
        );
    }

    /// load_families == Python (full dict, per-family Vec order included).
    #[test]
    fn load_families_byte_parity() {
        let fx = load_fixture();
        let node = &fx["load_families"];
        let tsv = node["tsv"].as_str().expect("load_families.tsv");

        let got = load_families_str(tsv);

        let expect_obj = node["expect"].as_object().expect("load_families.expect obj");
        let mut expect: BTreeMap<i64, Vec<FamLocus>> = BTreeMap::new();
        for (k, v) in expect_obj {
            let fi: i64 = k.parse().unwrap();
            let rows: Vec<FamLocus> = v
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    let a = r.as_array().unwrap();
                    (
                        a[0].as_str().unwrap().to_string(),
                        a[1].as_str().unwrap().to_string(),
                        a[2].as_i64().unwrap(),
                        a[3].as_i64().unwrap(),
                        a[4].as_i64().unwrap(),
                    )
                })
                .collect();
            expect.insert(fi, rows);
        }

        // Localize the first family / row that diverges (order included).
        let mut fams: Vec<i64> = got.keys().chain(expect.keys()).copied().collect();
        fams.sort_unstable();
        fams.dedup();
        for fi in &fams {
            let g = got.get(fi);
            let e = expect.get(fi);
            match (g, e) {
                (Some(gr), Some(er)) => {
                    let n = gr.len().max(er.len());
                    for i in 0..n {
                        assert_eq!(
                            gr.get(i),
                            er.get(i),
                            "load_families fam {fi} row[{i}] mismatch (rust vs python)"
                        );
                    }
                }
                (g, e) => panic!("load_families fam {fi}: rust present={:?} python present={:?}", g.is_some(), e.is_some()),
            }
        }
        assert_eq!(got, expect, "load_families whole-dict inequality");
        assert!(got.len() >= 100, "expected >=100 families parsed, got {}", got.len());
        eprintln!("o2_materialize load_families byte-parity: {} families all match", got.len());
    }

    /// load_gene_labels == Python.
    #[test]
    fn load_gene_labels_byte_parity() {
        let fx = load_fixture();
        let node = &fx["load_gene_labels"];
        let tsv = node["tsv"].as_str().expect("load_gene_labels.tsv");

        let got = load_gene_labels_str(tsv);

        let mut expect: BTreeMap<(String, i64), String> = BTreeMap::new();
        for entry in node["expect"].as_array().expect("load_gene_labels.expect array") {
            let a = entry.as_array().unwrap();
            let chrom = a[0].as_str().unwrap().to_string();
            let start = a[1].as_i64().unwrap();
            let gene = a[2].as_str().unwrap().to_string();
            expect.insert((chrom, start), gene);
        }

        for (k, v) in &expect {
            assert_eq!(
                got.get(k),
                Some(v),
                "load_gene_labels key {:?}: rust={:?} python={:?}",
                k,
                got.get(k),
                v
            );
        }
        assert_eq!(got, expect, "load_gene_labels whole-map inequality");
        assert!(!got.is_empty(), "expected a non-empty gene-label map");
        eprintln!("o2_materialize load_gene_labels byte-parity: {} labels all match", got.len());
    }

    /// load_gene_labels on a missing file -> empty map (Python `os.path.exists` guard).
    #[test]
    fn load_gene_labels_missing_file_is_empty() {
        let g = load_gene_labels("/nonexistent/definitely/not/here/sun.tsv").unwrap();
        assert!(g.is_empty());
    }

    /// FLAGSHIP roster matches Python verbatim (id, gene, role, and order).
    #[test]
    fn flagship_matches_python() {
        let fx = load_fixture();
        let expect = fx["flagship"].as_array().expect("flagship array");
        assert_eq!(FLAGSHIP.len(), expect.len(), "FLAGSHIP length");
        for (i, (id, gene, role)) in FLAGSHIP.iter().enumerate() {
            let a = expect[i].as_array().unwrap();
            assert_eq!(*id, a[0].as_i64().unwrap(), "FLAGSHIP[{i}] id");
            assert_eq!(*gene, a[1].as_str().unwrap(), "FLAGSHIP[{i}] gene");
            assert_eq!(*role, a[2].as_str().unwrap(), "FLAGSHIP[{i}] role");
        }
    }

    fn load_readfetch_fixture() -> Value {
        let raw = include_str!("testdata/o2_readfetch_fixture.json");
        serde_json::from_str(raw).expect("parse o2_readfetch fixture json")
    }

    fn parse_regions(v: &Value) -> Vec<(String, i64, i64, i64)> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|r| {
                let a = r.as_array().unwrap();
                (
                    a[0].as_str().unwrap().to_string(),
                    a[1].as_i64().unwrap(),
                    a[2].as_i64().unwrap(),
                    a[3].as_i64().unwrap(),
                )
            })
            .collect()
    }

    fn qname_list(v: &Value) -> Vec<String> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|q| q.as_str().unwrap().to_string())
            .collect()
    }

    /// fetch_reads == the Python read-fetch EXACTLY on every fixture family:
    ///   * `best` map: qname -> (region_idx, de) with de compared as raw f64 BITS;
    ///   * `seqs` qname ORDER (insertion order, drives the cap);
    ///   * the READ_CAP truncation (via lowered-cap cases, since no family hits 6000).
    /// Skips-with-message (does NOT fail) if the multi-GB genome BAM / its `.bai` is
    /// absent, so CI without the BAM is green; it IS present in dev so this runs+passes.
    #[test]
    fn fetch_reads_byte_parity() {
        let fx = load_readfetch_fixture();
        let bam_path = fx["bam_path"].as_str().expect("bam_path");
        let bai = format!("{bam_path}.bai");
        if !Path::new(bam_path).exists() || !Path::new(&bai).exists() {
            eprintln!(
                "o2_materialize fetch_reads byte-parity SKIPPED: genome BAM or .bai absent \
                 ({bam_path} / {bai}). Present in dev; run there to exercise this test."
            );
            return;
        }

        // Constant agreement with the Python (pg.PAD / pg.READ_CAP).
        let pad = fx["pad"].as_i64().expect("pad");
        let read_cap = fx["read_cap"].as_u64().expect("read_cap") as usize;
        assert_eq!(PAD, pad, "PAD constant disagrees with Python pg.PAD");
        assert_eq!(READ_CAP, read_cap, "READ_CAP disagrees with Python pg.READ_CAP");

        // contig_len (all genome contigs, as the Python passed).
        let mut contig_len: BTreeMap<String, i64> = BTreeMap::new();
        for (k, v) in fx["contig_len"].as_object().expect("contig_len obj") {
            contig_len.insert(k.clone(), v.as_i64().unwrap());
        }

        // Keep each family's regions for the lowered-cap truncation cases below.
        let mut regions_by_fam: BTreeMap<i64, Vec<(String, i64, i64, i64)>> = BTreeMap::new();
        let mut total_best = 0usize;
        let mut total_seqs = 0usize;

        let families = fx["families"].as_array().expect("families array");
        assert!(families.len() >= 4, "expected >=4 fixture families");

        for fam in families {
            let fam_id = fam["fam_id"].as_i64().unwrap();
            let regions = parse_regions(&fam["regions"]);
            regions_by_fam.insert(fam_id, regions.clone());

            let (best, seqs) = fetch_reads(bam_path, &regions, &contig_len, pad, read_cap)
                .unwrap_or_else(|e| panic!("fetch_reads(fam {fam_id}) failed: {e}"));

            // ---- best map: qname -> (region_idx, de-as-f64-bits) ----
            let exp_best = fam["best"].as_object().expect("best obj");
            // localize first divergence over the union of keys (ascending).
            let mut names: Vec<&String> = best.keys().collect();
            for k in exp_best.keys() {
                if !best.contains_key(k) {
                    names.push(k);
                }
            }
            names.sort();
            names.dedup();
            for name in names {
                let got = best.get(name);
                let exp = exp_best.get(name);
                match (got, exp) {
                    (Some(&(gi, gde)), Some(ev)) => {
                        let ea = ev.as_array().unwrap();
                        let ei = ea[0].as_i64().unwrap() as usize;
                        let ebits: u64 = ea[1].as_str().unwrap().parse().unwrap();
                        assert_eq!(
                            gi, ei,
                            "fam {fam_id} best[{name}] region_idx rust={gi} python={ei}"
                        );
                        assert_eq!(
                            gde.to_bits(),
                            ebits,
                            "fam {fam_id} best[{name}] de-bits rust={} python={} (rust de={gde})",
                            gde.to_bits(),
                            ebits
                        );
                    }
                    (Some(g), None) => {
                        panic!("fam {fam_id} best[{name}] present in rust ({g:?}), MISSING in python")
                    }
                    (None, Some(e)) => {
                        panic!("fam {fam_id} best[{name}] MISSING in rust, python={e:?}")
                    }
                    (None, None) => unreachable!(),
                }
            }
            assert_eq!(
                best.len(),
                exp_best.len(),
                "fam {fam_id} best cardinality rust={} python={}",
                best.len(),
                exp_best.len()
            );
            assert_eq!(
                best.len(),
                fam["n_best"].as_u64().unwrap() as usize,
                "fam {fam_id} n_best disagrees"
            );

            // ---- seqs qname ORDER (no family hits READ_CAP, so precap == postcap) ----
            let got_order: Vec<String> = seqs.iter().map(|(n, _)| n.clone()).collect();
            let exp_precap = qname_list(&fam["seqs_order_precap"]);
            let exp_postcap = qname_list(&fam["seqs_order_postcap"]);
            assert!(
                !fam["hit_read_cap"].as_bool().unwrap(),
                "fixture fam {fam_id} unexpectedly hit READ_CAP; test assumes precap==postcap here"
            );
            assert_eq!(exp_precap, exp_postcap, "fam {fam_id} fixture precap!=postcap");
            // first-divergence localization on the ordered qname list.
            let n = got_order.len().max(exp_precap.len());
            for k in 0..n {
                assert_eq!(
                    got_order.get(k),
                    exp_precap.get(k),
                    "fam {fam_id} seqs order[{k}] rust={:?} python={:?} (rust len={}, python len={})",
                    got_order.get(k),
                    exp_precap.get(k),
                    got_order.len(),
                    exp_precap.len()
                );
            }
            assert_eq!(
                got_order.len(),
                fam["n_seqs_precap"].as_u64().unwrap() as usize,
                "fam {fam_id} n_seqs disagrees"
            );

            total_best += best.len();
            total_seqs += got_order.len();
        }

        // ---- lowered-cap cases: exercise the READ_CAP truncation path ----
        let lowered = fx["lowered_cap"].as_array().expect("lowered_cap array");
        assert!(!lowered.is_empty(), "expected lowered-cap truncation cases");
        let mut n_truncated = 0usize;
        for lc in lowered {
            let fam_id = lc["fam_id"].as_i64().unwrap();
            let cap = lc["read_cap"].as_u64().unwrap() as usize;
            let regions = regions_by_fam
                .get(&fam_id)
                .unwrap_or_else(|| panic!("lowered-cap fam {fam_id} not among fixture families"));
            let (_best, seqs) = fetch_reads(bam_path, regions, &contig_len, pad, cap)
                .unwrap_or_else(|e| panic!("fetch_reads(fam {fam_id}, cap {cap}) failed: {e}"));
            let got_order: Vec<String> = seqs.iter().map(|(n, _)| n.clone()).collect();
            let exp_postcap = qname_list(&lc["seqs_order_postcap"]);
            assert!(
                lc["truncated"].as_bool().unwrap(),
                "lowered fam {fam_id} cap {cap} should truncate"
            );
            assert_eq!(
                got_order.len(),
                cap,
                "lowered fam {fam_id}: truncated len rust={} expected cap={cap}",
                got_order.len()
            );
            for k in 0..got_order.len().max(exp_postcap.len()) {
                assert_eq!(
                    got_order.get(k),
                    exp_postcap.get(k),
                    "lowered fam {fam_id} cap {cap} postcap order[{k}] rust={:?} python={:?}",
                    got_order.get(k),
                    exp_postcap.get(k)
                );
            }
            n_truncated += 1;
        }

        eprintln!(
            "o2_materialize fetch_reads byte-parity: {} families ({} best entries, {} seqs) \
             all match python incl de-bits + seqs order; {} lowered-cap truncation cases match",
            families.len(),
            total_best,
            total_seqs,
            n_truncated
        );
    }

    // =====================================================================
    // assemble_vg + materialize_family parity
    // =====================================================================

    fn load_assemble_fixture() -> Value {
        let raw = include_str!("testdata/o2_assemble_fixture.json");
        serde_json::from_str(raw).expect("parse o2_assemble fixture json")
    }

    fn parse_regions4(v: &Value) -> Vec<(String, i64, i64, i64)> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|r| {
                let a = r.as_array().unwrap();
                (
                    a[0].as_str().unwrap().to_string(),
                    a[1].as_i64().unwrap(),
                    a[2].as_i64().unwrap(),
                    a[3].as_i64().unwrap(),
                )
            })
            .collect()
    }

    fn parse_str_vec(v: &Value) -> Vec<String> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|s| s.as_str().unwrap().to_string())
            .collect()
    }

    fn parse_cols(v: &Value) -> BTreeMap<i64, BTreeMap<String, char>> {
        v.as_object()
            .unwrap()
            .iter()
            .map(|(p, inner)| {
                let pos = p.parse::<i64>().unwrap();
                let m: BTreeMap<String, char> = inner
                    .as_object()
                    .unwrap()
                    .iter()
                    .map(|(nm, b)| (nm.clone(), b.as_str().unwrap().chars().next().unwrap()))
                    .collect();
                (pos, m)
            })
            .collect()
    }

    /// fixture gene_lbl keys are `"chrom\tstart"` -> gene.
    fn parse_gene_lbl(v: &Value) -> BTreeMap<(String, i64), String> {
        v.as_object()
            .unwrap()
            .iter()
            .map(|(k, gene)| {
                let mut it = k.splitn(2, '\t');
                let chrom = it.next().unwrap().to_string();
                let start: i64 = it.next().unwrap().parse().unwrap();
                ((chrom, start), gene.as_str().unwrap().to_string())
            })
            .collect()
    }

    /// Semantic JSON comparison localizing the FIRST divergence (key-order-independent;
    /// numbers compared by `as_f64`, so `PosInt(5)` == `Float(5.0)`). Returns a
    /// human-readable path on divergence, else `None`.
    fn first_json_diff(a: &Value, b: &Value, path: &str) -> Option<String> {
        match (a, b) {
            (Value::Object(am), Value::Object(bm)) => {
                let mut keys: Vec<&String> = am.keys().chain(bm.keys()).collect();
                keys.sort();
                keys.dedup();
                for k in keys {
                    match (am.get(k), bm.get(k)) {
                        (Some(x), Some(y)) => {
                            if let Some(d) = first_json_diff(x, y, &format!("{path}.{k}")) {
                                return Some(d);
                            }
                        }
                        (Some(x), None) => {
                            return Some(format!("{path}.{k}: present in RUST ({x}), missing in PYTHON"))
                        }
                        (None, Some(y)) => {
                            return Some(format!("{path}.{k}: missing in RUST, present in PYTHON ({y})"))
                        }
                        (None, None) => {}
                    }
                }
                None
            }
            (Value::Array(ax), Value::Array(bx)) => {
                if ax.len() != bx.len() {
                    return Some(format!(
                        "{path}: array len rust={} python={}",
                        ax.len(),
                        bx.len()
                    ));
                }
                for (i, (x, y)) in ax.iter().zip(bx).enumerate() {
                    if let Some(d) = first_json_diff(x, y, &format!("{path}[{i}]")) {
                        return Some(d);
                    }
                }
                None
            }
            (Value::Number(_), Value::Number(_)) => {
                if a.as_f64() != b.as_f64() {
                    Some(format!("{path}: number rust={a} python={b}"))
                } else {
                    None
                }
            }
            _ => {
                if a != b {
                    Some(format!("{path}: rust={a} python={b}"))
                } else {
                    None
                }
            }
        }
    }

    /// FAST: `assemble_vg` == the Python assembly EXACTLY on every fixture family, for
    /// BOTH the pre-abstain VG (cache dump) and the post-abstain VG (return) — bubbles /
    /// tiers / groups / gate loop / round2 margins / obs str-keys / first-seen orders /
    /// copies / counters / the recombinant-abstain flip merge. No minimap2/BAM/genome
    /// needed (columns are baked into the fixture).
    #[test]
    fn assemble_vg_parity() {
        // DEFAULT-ON abstain (matches the Python fixture generation). Mirrors the
        // established pattern in recombinant_abstain's env-sensitive tests.
        std::env::remove_var(super::super::recombinant_abstain::OPTOUT_ENV);

        let fx = load_assemble_fixture();
        let fams = fx["families"].as_array().expect("families array");
        assert!(fams.len() >= 3, "expected >=3 fixture families, got {}", fams.len());

        let (mut tot_bubbles, mut tot_reads, mut tot_flips) = (0usize, 0usize, 0usize);
        let (mut n_no_psv, mut n_partial, mut n_full) = (0usize, 0usize, 0usize);
        let mut tiers_seen: BTreeSet<i64> = BTreeSet::new();

        for fam in fams {
            let fam_id = fam["fam_id"].as_i64().unwrap();
            let regions = parse_regions4(&fam["regions"]);
            let bb = fam["backbone"].as_array().unwrap();
            let bc = bb[0].as_str().unwrap();
            let bs = bb[1].as_i64().unwrap();
            let be = bb[2].as_i64().unwrap();
            let refseq = fam["refseq"].as_str().unwrap().as_bytes().to_vec();
            let names = parse_str_vec(&fam["names"]);
            let copy_cols = parse_cols(&fam["copy_cols"]);
            let read_cols = parse_cols(&fam["read_cols"]);
            let best_names = parse_str_vec(&fam["best_names"]);
            let gene_lbl = parse_gene_lbl(&fam["gene_lbl"]);

            let got = assemble_vg(
                fam_id,
                &regions,
                (bc, bs, be),
                &refseq,
                &names,
                &copy_cols,
                &read_cols,
                &best_names,
                &gene_lbl,
            );

            if let Some(loc) = first_json_diff(&got.pre_abstain, &fam["vg_pre"], "vg_pre") {
                panic!("fam {fam_id}: PRE-abstain VG diverges from Python at {loc}");
            }
            if let Some(loc) = first_json_diff(&got.post_abstain, &fam["vg_post"], "vg_post") {
                panic!("fam {fam_id}: POST-abstain VG diverges from Python at {loc}");
            }

            // fixture-composition accounting
            let nb = fam["vg_pre"]["n_bubbles"].as_u64().unwrap() as usize;
            tot_bubbles += nb;
            tot_reads += best_names.len();
            tot_flips += fam["n_flipped"].as_u64().unwrap() as usize;
            match got.pre_abstain["cls"].as_str().unwrap() {
                s if s.starts_with("no_psv") => n_no_psv += 1,
                s if s.starts_with("fully_resolvable") => n_full += 1,
                s if s.starts_with("partial") => n_partial += 1,
                _ => {}
            }
            for t in fam["vg_pre"]["tiers"].as_object().unwrap().keys() {
                tiers_seen.insert(t.parse().unwrap());
            }
        }

        assert!(n_no_psv >= 1, "no no_psv (0-bubble floor) family in fixture");
        assert!(n_full >= 1, "no fully_resolvable family in fixture");
        assert!(n_partial >= 1, "no partial (mixed) family in fixture");
        assert!(tot_flips >= 1, "no recombinant-abstain flip exercised");
        assert!(
            tiers_seen.contains(&1) && tiers_seen.contains(&3),
            "expected tier-1 and tier-3 coverage, saw {tiers_seen:?}"
        );
        eprintln!(
            "o2_materialize assemble_vg parity: {} families identical (pre+post) — \
             {tot_bubbles} bubbles, {tot_reads} reads, {tot_flips} abstain-flips; \
             cls {{no_psv={n_no_psv}, full={n_full}, partial={n_partial}}}, tiers {tiers_seen:?}",
            fams.len()
        );
    }

    /// SLOW e2e (`--ignored`): the FULL Rust `materialize_family` (live minimap2 +
    /// samtools + genome BAM) == a FRESH Python `materialize_family(use_cache=False)` on
    /// the same current alignments, for a few families, for BOTH the pre-abstain and
    /// post-abstain VG. Also discloses any minimap2 drift (fresh Python pre vs the
    /// shipped cache). Skips-with-message if minimap2/samtools/genome/BAM are absent.
    #[test]
    #[ignore = "needs minimap2/samtools + the multi-GB genome BAM; run with --ignored"]
    fn materialize_family_e2e() {
        use std::process::Command;

        const E2E_FAMS: &[i64] = &[39, 96, 90];
        let manifest = env!("CARGO_MANIFEST_DIR");
        let py = "/home/juanfra/miniforge3/bin/python";
        let mm2 = "/home/juanfra/miniforge3/bin/minimap2";
        let sam = "/home/juanfra/miniforge3/bin/samtools";
        let emit = format!("{manifest}/bench/o2_emit_materialize.py");
        let sun = format!("{manifest}/bench/sun_identifiability.tsv");

        let required: Vec<String> = vec![
            GENOME_DEFAULT.to_string(),
            format!("{GENOME_DEFAULT}.fai"),
            BAM_DEFAULT.to_string(),
            format!("{BAM_DEFAULT}.bai"),
            mm2.to_string(),
            sam.to_string(),
            py.to_string(),
            emit.clone(),
            sun.clone(),
        ];
        let missing: Vec<&String> = required.iter().filter(|p| !Path::new(p).exists()).collect();
        if !missing.is_empty() {
            eprintln!("materialize_family_e2e SKIPPED: missing {missing:?}");
            return;
        }

        // private scratch cache/tmp so the shipped o2vg cache is untouched.
        let scratch = std::env::temp_dir().join(format!("rustle_o2vg_e2e_{}", std::process::id()));
        std::fs::create_dir_all(&scratch).unwrap();
        std::env::remove_var(super::super::recombinant_abstain::OPTOUT_ENV); // default-ON

        let mut cfg = MaterializeConfig::defaults(sun.clone());
        cfg.minimap2 = mm2.to_string();
        cfg.samtools = sam.to_string();
        cfg.cache_dir = scratch.to_string_lossy().to_string();
        cfg.write_cache = true;

        for &fam in E2E_FAMS {
            let rust = materialize_family(fam, &cfg)
                .unwrap_or_else(|e| panic!("Rust materialize_family(fam {fam}) failed: {e}"));

            let out = Command::new(py)
                .env("PYTHONHASHSEED", "0")
                .arg(&emit)
                .arg(fam.to_string())
                .output()
                .unwrap_or_else(|e| panic!("python emit(fam {fam}) spawn failed: {e}"));
            assert!(
                out.status.success(),
                "python emit(fam {fam}) failed: {}",
                String::from_utf8_lossy(&out.stderr)
            );
            let pyj: Value = serde_json::from_slice(&out.stdout)
                .unwrap_or_else(|e| panic!("parse python emit(fam {fam}) json failed: {e}"));

            // post-abstain: Rust == fresh Python
            if let Some(loc) = first_json_diff(&rust.post_abstain, &pyj["post"], "post") {
                panic!("fam {fam}: Rust POST-abstain != fresh Python at {loc}");
            }
            // pre-abstain: Rust == fresh Python (both pre-abstain, same minimap2)
            if let Some(loc) = first_json_diff(&rust.pre_abstain, &pyj["pre_fresh"], "pre") {
                panic!("fam {fam}: Rust PRE-abstain != fresh Python at {loc}");
            }
            // minimap2 drift disclosure (informational): fresh Python pre vs shipped cache.
            let drift = if pyj["cached_stale"].is_null() {
                "no shipped cache".to_string()
            } else {
                match first_json_diff(&pyj["pre_fresh"], &pyj["cached_stale"], "cache") {
                    None => "IDENTICAL (no minimap2 drift)".to_string(),
                    Some(loc) => format!("DRIFT at {loc}"),
                }
            };
            let post = &rust.post_abstain;
            eprintln!(
                "fam {fam}: Rust materialize == fresh Python (pre+post) — copies={} bubbles={} \
                 K={} cls={:?} reads={} assign={:?}; cache-vs-fresh: {drift}",
                post["n_copies"], post["n_bubbles"], post["K"], post["cls"].as_str().unwrap(),
                post["n_reads"], post["assignment"]
            );
        }

        let _ = std::fs::remove_dir_all(&scratch);
    }
}
