//! O2 VG-materialization step 3: the LOADERS + copy-dedup that
//! `bench/o2_vg_visualization.py::materialize_family` runs BEFORE it aligns copies
//! and threads reads.
//!
//! This module will grow to hold the full `materialize_family`; it starts with the
//! four pieces that run first, ported byte-faithfully from the Python ground truth:
//!
//!   * [`dedup_copies`] — collapse de-novo loci that are the same genomic copy
//!     (isoforms) into one copy-region (Python `psv_graph_genomewide.dedup_copies`,
//!     ~line 62);
//!   * [`load_families`] / [`load_families_str`] — parse the validated-families TSV
//!     into `fam_id -> [(lid, chrom, start, end, nreads)]` (Python
//!     `o2_vg_visualization.load_families`, ~line 84);
//!   * [`load_gene_labels`] / [`load_gene_labels_str`] — parse the SUN identifiability
//!     TSV into `(chrom, start) -> gene` (Python `o2_vg_visualization.load_gene_labels`,
//!     ~line 71);
//!   * [`FLAGSHIP`] — the flagship-family roster constant (Python
//!     `o2_vg_visualization.FLAGSHIP`, ~line 63).
//!
//! Byte-parity is enforced against a golden fixture
//! (`testdata/o2_materialize_fixture.json`, generated by
//! `bench/gen_o2_materialize_fixture.py`, PYTHONHASHSEED=0) by the `#[test]`s below.

use std::collections::BTreeMap;
use std::collections::HashMap;
use std::path::Path;

/// De-novo loci with reciprocal overlap STRICTLY GREATER than this fraction of the
/// shorter locus are the same genomic copy (isoforms) and get merged; distinct tandem
/// copies (overlap `<=` this) stay separate. Hard-coded from the Python constant
/// `bench/psv_graph_genomewide.py:37  OVERLAP_MERGE = 0.5`.
pub const OVERLAP_MERGE: f64 = 0.5;

/// Default path of the validated-families TSV, the `dedup_copies`/`load_families`
/// input. Python `bench/psv_graph_genomewide.py:32`:
/// `FAM_TSV = os.environ.get("FAM_TSV", "/home/juanfra/winloci_scratch/validated_families.tsv")`
/// — the default; the env override is honored by [`fam_tsv_path`].
pub const FAM_TSV_DEFAULT: &str = "/home/juanfra/winloci_scratch/validated_families.tsv";

/// Basename of the SUN identifiability TSV that supplies gene labels. Python
/// `bench/o2_vg_visualization.py:60`:
/// `SUN_TSV = os.path.join(HERE, "sun_identifiability.tsv")` where `HERE` is the
/// `bench/` directory (`os.path.dirname(os.path.abspath(__file__))`).
pub const SUN_TSV_BASENAME: &str = "sun_identifiability.tsv";

/// Flagship-family roster: `fam_id -> (gene, role)`. Verbatim port of the Python
/// constant `bench/o2_vg_visualization.py:63`:
/// ```python
/// FLAGSHIP = {
///     39: ("RABL2", "RESOLVABLE"),   # 5 copies, all Tier-1 SUN, cross-chrom
///     1:  ("RGPD8", "FLOOR"),        # 7 copies, 0 PSV bubbles, all reads tied
///     22: ("ANKRD18", "MID"),        # 6 copies, K=4/6, some collapse
/// }
/// ```
pub const FLAGSHIP: [(i64, &str, &str); 3] = [
    (39, "RABL2", "RESOLVABLE"),
    (1, "RGPD8", "FLOOR"),
    (22, "ANKRD18", "MID"),
];

/// The default `FAM_TSV` path, honoring the `FAM_TSV` env override exactly like the
/// Python `os.environ.get("FAM_TSV", <default>)`.
pub fn fam_tsv_path() -> String {
    std::env::var("FAM_TSV").unwrap_or_else(|_| FAM_TSV_DEFAULT.to_string())
}

// ===========================================================================
// dedup_copies  (bench/psv_graph_genomewide.py:62)
// ===========================================================================

/// Collapse de-novo loci that are the same genomic copy (isoforms) into one
/// copy-region — same chrom + reciprocal overlap `>` [`OVERLAP_MERGE`] of the shorter
/// locus. Distinct tandem copies stay separate. Faithful port of
/// `bench/psv_graph_genomewide.py::dedup_copies`.
///
/// Input `loci` is a slice of `(lid, chrom, start, end, nreads)` (the `lid` is unused
/// by the algorithm, exactly as in Python where only `(c, s, e, nr)` are read).
/// Output is `(chrom, start, end, nreads)` per merged region.
///
/// ## Order fidelity (load-bearing — see the module note)
/// The Python groups by chrom with a `collections.defaultdict(list)`, whose iteration
/// is INSERTION order (first-seen chrom order across `loci`). The returned `regions`
/// list is emitted chrom-group by chrom-group in that first-seen order, and within a
/// group in sweep order (which follows the `items.sort()` ascending `(s, e, nr)`
/// order). We reproduce this EXACTLY with a first-seen `Vec<chrom>` + a `HashMap`
/// index (NOT a `BTreeMap`, which would reorder chroms alphabetically). The downstream
/// `materialize_family` re-sorts the regions by length-desc, but reproducing this
/// return order verbatim keeps the port byte-faithful for every consumer.
///
/// ## The merge test (reproduced verbatim, incl. the strict `>` and the min-of-lengths)
/// Sweeping the sorted items with a running `cur = (start, end, nreads)`: the next
/// item `(s, e, nr)` merges into `cur` iff `s < cur.end` AND
/// `ov > OVERLAP_MERGE * min(cur.end - cur.start, e - s)` where
/// `ov = min(cur.end, e) - s`. On a merge, `cur = (cur.start, max(cur.end, e),
/// cur.nreads + nr)` (note the `max` end and the `nreads` accumulation) and the next
/// item is consumed WITHOUT flushing (`continue`). Otherwise `cur` is flushed to
/// `regions` and a fresh `cur` starts at `(s, e, nr)`. The comparison is done in `f64`
/// (an `int` `ov` against the `float` `OVERLAP_MERGE * int`), matching Python; with
/// `OVERLAP_MERGE == 0.5` the products are exact for these coordinate magnitudes.
pub fn dedup_copies(loci: &[(String, String, i64, i64, i64)]) -> Vec<(String, i64, i64, i64)> {
    // Group by chrom preserving FIRST-SEEN chrom order (Python defaultdict(list)).
    let mut chrom_order: Vec<String> = Vec::new();
    let mut idx: HashMap<&str, usize> = HashMap::new();
    let mut groups: Vec<Vec<(i64, i64, i64)>> = Vec::new();
    for (_lid, c, s, e, nr) in loci {
        let gi = match idx.get(c.as_str()) {
            Some(&i) => i,
            None => {
                let i = groups.len();
                idx.insert(c.as_str(), i);
                chrom_order.push(c.clone());
                groups.push(Vec::new());
                i
            }
        };
        groups[gi].push((*s, *e, *nr));
    }

    let mut regions: Vec<(String, i64, i64, i64)> = Vec::new();
    for (gi, c) in chrom_order.iter().enumerate() {
        let mut items = std::mem::take(&mut groups[gi]);
        // Python items.sort() -> lexicographic ascending (s, e, nr).
        items.sort();
        let mut cur: Option<(i64, i64, i64)> = None;
        for (s, e, nr) in items {
            if let Some((cs, ce, cnr)) = cur {
                if s < ce {
                    let ov = ce.min(e) - s;
                    let minlen = (ce - cs).min(e - s);
                    if (ov as f64) > OVERLAP_MERGE * (minlen as f64) {
                        // merge (grow end via max, accumulate nreads) and continue
                        cur = Some((cs, ce.max(e), cnr + nr));
                        continue;
                    }
                }
                // no merge: flush the running region before starting a fresh one
                regions.push((c.clone(), cs, ce, cnr));
            }
            cur = Some((s, e, nr));
        }
        if let Some((cs, ce, cnr)) = cur {
            regions.push((c.clone(), cs, ce, cnr));
        }
    }
    regions
}

// ===========================================================================
// load_families  (bench/o2_vg_visualization.py:84)
// ===========================================================================

/// One family's loci as parsed from the validated-families TSV.
pub type FamLocus = (String, String, i64, i64, i64);

/// Parse the validated-families TSV text into `fam_id -> [(lid, chrom, start, end,
/// nreads)]`. Faithful port of `bench/o2_vg_visualization.py::load_families` operating
/// on the raw text (`load_families` reads the file and delegates here).
///
/// Header line skipped. Columns (Python `fi, lid, c, s, e, nr = line.split("\t")`):
/// `f[0]=family  f[1]=locus  f[2]=chrom  f[3]=start  f[4]=end  f[5]=nreads`. The
/// per-family `Vec` preserves FILE order (Python `defaultdict(list).append`), which is
/// what feeds [`dedup_copies`]' first-seen-chrom ordering — so the order must be kept.
/// The `BTreeMap` key order is irrelevant to callers (they index `fams[fam_id]`) but is
/// deterministic.
pub fn load_families_str(text: &str) -> BTreeMap<i64, Vec<FamLocus>> {
    let mut fams: BTreeMap<i64, Vec<FamLocus>> = BTreeMap::new();
    for line in text.lines().skip(1) {
        let f: Vec<&str> = line.split('\t').collect();
        let fi: i64 = f[0].parse().expect("family int");
        let s: i64 = f[3].parse().expect("start int");
        let e: i64 = f[4].parse().expect("end int");
        let nr: i64 = f[5].parse().expect("nreads int");
        fams.entry(fi)
            .or_default()
            .push((f[1].to_string(), f[2].to_string(), s, e, nr));
    }
    fams
}

/// Read the validated-families TSV file and parse it (see [`load_families_str`]).
pub fn load_families<P: AsRef<Path>>(path: P) -> std::io::Result<BTreeMap<i64, Vec<FamLocus>>> {
    Ok(load_families_str(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// load_gene_labels  (bench/o2_vg_visualization.py:71)
// ===========================================================================

/// Parse the SUN identifiability TSV text into `(chrom, start) -> gene`. Faithful port
/// of `bench/o2_vg_visualization.py::load_gene_labels` operating on the raw text.
///
/// Header line skipped. Columns (Python `p = line.split("\t"); g[(p[2], int(p[3]))] =
/// p[5]`): `p[2]=chrom  p[3]=start  p[5]=gene`. A repeated `(chrom, start)` key keeps
/// the LAST value (dict assignment / `BTreeMap::insert` both overwrite).
pub fn load_gene_labels_str(text: &str) -> BTreeMap<(String, i64), String> {
    let mut g: BTreeMap<(String, i64), String> = BTreeMap::new();
    for line in text.lines().skip(1) {
        let p: Vec<&str> = line.split('\t').collect();
        let start: i64 = p[3].parse().expect("gene-label start int");
        g.insert((p[2].to_string(), start), p[5].to_string());
    }
    g
}

/// Read the SUN identifiability TSV and parse it (see [`load_gene_labels_str`]). A
/// MISSING file yields an empty map, matching the Python
/// `if os.path.exists(SUN_TSV): ... else return {}`.
pub fn load_gene_labels<P: AsRef<Path>>(path: P) -> std::io::Result<BTreeMap<(String, i64), String>> {
    let path = path.as_ref();
    if !path.exists() {
        return Ok(BTreeMap::new());
    }
    Ok(load_gene_labels_str(&std::fs::read_to_string(path)?))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/o2_materialize_fixture.json");
        serde_json::from_str(raw).expect("parse o2_materialize fixture json")
    }

    /// dedup_copies == Python EXACTLY (incl. RETURN ORDER) on every case.
    #[test]
    fn dedup_copies_byte_parity() {
        let fx = load_fixture();

        // OVERLAP_MERGE value agreement.
        assert_eq!(
            OVERLAP_MERGE,
            fx["overlap_merge"].as_f64().unwrap(),
            "OVERLAP_MERGE constant disagrees with Python"
        );

        let cases = fx["dedup_cases"].as_array().expect("dedup_cases array");
        assert!(
            cases.len() >= 100,
            "expected >=100 dedup cases, got {}",
            cases.len()
        );

        let mut n_merge = 0usize;
        let mut n_multichrom = 0usize;
        let mut n_single = 0usize;
        let mut n_tandem_sep = 0usize;

        for case in cases {
            let id = case["id"].as_str().unwrap();
            let loci: Vec<FamLocus> = case["loci"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    let a = r.as_array().unwrap();
                    (
                        a[0].as_str().unwrap().to_string(),
                        a[1].as_str().unwrap().to_string(),
                        a[2].as_i64().unwrap(),
                        a[3].as_i64().unwrap(),
                        a[4].as_i64().unwrap(),
                    )
                })
                .collect();
            let expect: Vec<(String, i64, i64, i64)> = case["expect"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    let a = r.as_array().unwrap();
                    (
                        a[0].as_str().unwrap().to_string(),
                        a[1].as_i64().unwrap(),
                        a[2].as_i64().unwrap(),
                        a[3].as_i64().unwrap(),
                    )
                })
                .collect();

            let got = dedup_copies(&loci);

            // First-mismatch localization (position + field), then whole-vec equality.
            let n = got.len().max(expect.len());
            for i in 0..n {
                match (got.get(i), expect.get(i)) {
                    (Some(g), Some(e)) if g == e => {}
                    (g, e) => panic!(
                        "dedup case {id}: region[{i}] rust={:?} python={:?}\n  \
                         rust n_regions={}, python n_regions={}",
                        g,
                        e,
                        got.len(),
                        expect.len()
                    ),
                }
            }
            assert_eq!(got, expect, "dedup case {id}: whole-vec inequality");

            // Class accounting (for the fixture-composition sanity checks below).
            let n_loci = loci.len();
            let n_chrom = {
                let mut cs: Vec<&str> = loci.iter().map(|l| l.1.as_str()).collect();
                cs.sort();
                cs.dedup();
                cs.len()
            };
            if n_loci == 1 {
                n_single += 1;
            }
            if n_chrom >= 2 {
                n_multichrom += 1;
            }
            if got.len() < n_loci {
                n_merge += 1;
            }
            // same-chrom loci that stayed as multiple regions => a tandem separation
            if n_chrom == 1 && got.len() >= 2 {
                n_tandem_sep += 1;
            }
        }

        assert!(n_merge >= 1, "no case exercised an isoform merge");
        assert!(n_single >= 1, "no single-locus case");
        assert!(n_multichrom >= 1, "no multi-chrom case");
        assert!(n_tandem_sep >= 1, "no tandem-stays-separate case");

        eprintln!(
            "o2_materialize dedup_copies byte-parity: {} cases all match incl order \
             ({} with merges, {} single-locus, {} multi-chrom, {} tandem-separate)",
            cases.len(),
            n_merge,
            n_single,
            n_multichrom,
            n_tandem_sep
        );
    }

    /// load_families == Python (full dict, per-family Vec order included).
    #[test]
    fn load_families_byte_parity() {
        let fx = load_fixture();
        let node = &fx["load_families"];
        let tsv = node["tsv"].as_str().expect("load_families.tsv");

        let got = load_families_str(tsv);

        let expect_obj = node["expect"].as_object().expect("load_families.expect obj");
        let mut expect: BTreeMap<i64, Vec<FamLocus>> = BTreeMap::new();
        for (k, v) in expect_obj {
            let fi: i64 = k.parse().unwrap();
            let rows: Vec<FamLocus> = v
                .as_array()
                .unwrap()
                .iter()
                .map(|r| {
                    let a = r.as_array().unwrap();
                    (
                        a[0].as_str().unwrap().to_string(),
                        a[1].as_str().unwrap().to_string(),
                        a[2].as_i64().unwrap(),
                        a[3].as_i64().unwrap(),
                        a[4].as_i64().unwrap(),
                    )
                })
                .collect();
            expect.insert(fi, rows);
        }

        // Localize the first family / row that diverges (order included).
        let mut fams: Vec<i64> = got.keys().chain(expect.keys()).copied().collect();
        fams.sort_unstable();
        fams.dedup();
        for fi in &fams {
            let g = got.get(fi);
            let e = expect.get(fi);
            match (g, e) {
                (Some(gr), Some(er)) => {
                    let n = gr.len().max(er.len());
                    for i in 0..n {
                        assert_eq!(
                            gr.get(i),
                            er.get(i),
                            "load_families fam {fi} row[{i}] mismatch (rust vs python)"
                        );
                    }
                }
                (g, e) => panic!("load_families fam {fi}: rust present={:?} python present={:?}", g.is_some(), e.is_some()),
            }
        }
        assert_eq!(got, expect, "load_families whole-dict inequality");
        assert!(got.len() >= 100, "expected >=100 families parsed, got {}", got.len());
        eprintln!("o2_materialize load_families byte-parity: {} families all match", got.len());
    }

    /// load_gene_labels == Python.
    #[test]
    fn load_gene_labels_byte_parity() {
        let fx = load_fixture();
        let node = &fx["load_gene_labels"];
        let tsv = node["tsv"].as_str().expect("load_gene_labels.tsv");

        let got = load_gene_labels_str(tsv);

        let mut expect: BTreeMap<(String, i64), String> = BTreeMap::new();
        for entry in node["expect"].as_array().expect("load_gene_labels.expect array") {
            let a = entry.as_array().unwrap();
            let chrom = a[0].as_str().unwrap().to_string();
            let start = a[1].as_i64().unwrap();
            let gene = a[2].as_str().unwrap().to_string();
            expect.insert((chrom, start), gene);
        }

        for (k, v) in &expect {
            assert_eq!(
                got.get(k),
                Some(v),
                "load_gene_labels key {:?}: rust={:?} python={:?}",
                k,
                got.get(k),
                v
            );
        }
        assert_eq!(got, expect, "load_gene_labels whole-map inequality");
        assert!(!got.is_empty(), "expected a non-empty gene-label map");
        eprintln!("o2_materialize load_gene_labels byte-parity: {} labels all match", got.len());
    }

    /// load_gene_labels on a missing file -> empty map (Python `os.path.exists` guard).
    #[test]
    fn load_gene_labels_missing_file_is_empty() {
        let g = load_gene_labels("/nonexistent/definitely/not/here/sun.tsv").unwrap();
        assert!(g.is_empty());
    }

    /// FLAGSHIP roster matches Python verbatim (id, gene, role, and order).
    #[test]
    fn flagship_matches_python() {
        let fx = load_fixture();
        let expect = fx["flagship"].as_array().expect("flagship array");
        assert_eq!(FLAGSHIP.len(), expect.len(), "FLAGSHIP length");
        for (i, (id, gene, role)) in FLAGSHIP.iter().enumerate() {
            let a = expect[i].as_array().unwrap();
            assert_eq!(*id, a[0].as_i64().unwrap(), "FLAGSHIP[{i}] id");
            assert_eq!(*gene, a[1].as_str().unwrap(), "FLAGSHIP[{i}] gene");
            assert_eq!(*role, a[2].as_str().unwrap(), "FLAGSHIP[{i}] role");
        }
    }
}
