//! O2 **MARGIN** gate: assign a read to a specific paralog COPY by a PSV (+ optional
//! copy-specific junction) log-likelihood, calling ASSIGNED only when the best copy
//! clears a fixed log-likelihood-ratio MARGIN over the runner-up.
//!
//! Faithful Rust port of `bench/copy_assign.py::assign_read` -- the gate that
//! `bench/o2_vg_visualization.py::materialize_family` (the O2 VG-materialization
//! pipeline) actually calls.
//!
//! ⚠ This is a *different* function from [`super::copy_assign::assign_read`], which is
//! the newer min_p / Poisson-binomial *significance* gate. The two must not be
//! conflated: this one is the log-likelihood + fixed-margin gate.
//!
//! Semantics reproduced EXACTLY from the Python source (see that file's docstring):
//!   * `names = list(copy_vecs)` -- dict INSERTION order; here the caller passes an
//!     order-preserving `Vec<(name, vec)>` so the order is deterministic and matches.
//!   * PSV term: for each spanned column, every copy that has a base at that column
//!     accrues `ln(1-e)` on a match else `ln(e/3)`; a column where >=2 distinct copy
//!     alleles occur is DECISIVE.
//!   * junction term (only when both `read_bounds` and `copy_bounds` are non-empty):
//!     each read boundary within `btol` of a copy's boundary set is `+jw` for that
//!     copy else `-jw`; a boundary some-but-not-all copies carry is DECISIVE.
//!   * `best` = the max-`logL` name; ties broken by the ORIGINAL names order (Python
//!     `sorted(..., reverse=True)` is stable and keeps equal-key elements in input
//!     order). `margin` = `logL[best] - logL[runner-up]` (`+inf` if a single copy).
//!
//! Float fidelity: the `logL` sums are accumulated in the SAME operation order as
//! Python (spanned columns iterated in ascending index; names iterated in `copy_vecs`
//! order), and `f64::ln` is bit-identical to CPython `math.log` on this target, so the
//! per-copy `logL` and the `margin` match Python bit-for-bit. Verified against a golden
//! fixture (`testdata/o2_margin_gate_fixture.json`, generated by
//! `bench/gen_o2_margin_gate_fixture.py`, PYTHONHASHSEED=0) by the `#[test]`s below,
//! which compare every `logL` and the `margin` as raw IEEE-754 bits.
//!
//! **STATUS:** TEST-ONLY  (docs/MODULE_STATUS.md; assigned by reachability, not by this header)

use std::cmp::Ordering;
use std::collections::{BTreeMap, BTreeSet};

/// Per-base error assumed in the likelihood (HiFi). Python `copy_assign.ERR`.
pub const ERR: f64 = 0.003;
/// Min log-likelihood-ratio over the runner-up to call ASSIGNED (else AMBIGUOUS).
/// Python `copy_assign.MARGIN`.
pub const MARGIN: f64 = 2.0;
/// Default junction weight `jw` in `assign_read`.
pub const JW: f64 = 5.0;
/// Default boundary tolerance `btol` (bp) in `assign_read`.
pub const BTOL: i64 = 4;

/// Result of [`assign_read_margin`]: mirrors the Python
/// `(best, margin, n_span, n_decisive, logL)` tuple.
#[derive(Debug, Clone, PartialEq)]
pub struct MarginAssignment {
    /// Argmax copy name (ties broken by `copy_vecs` order).
    pub best: String,
    /// `logL[best] - logL[runner-up]`; `+inf` when there is a single copy.
    pub margin: f64,
    /// Number of spanned (non-`None`) observed columns (Python `len(spanned)`).
    pub n_span: usize,
    /// Count of DECISIVE features (PSV columns + junction boundaries where copies differ).
    pub n_decisive: usize,
    /// Per-copy log-likelihood, in `copy_vecs` (names) order.
    pub logl: Vec<(String, f64)>,
}

/// Assign a read to a copy by the MARGIN gate. Faithful port of
/// `bench/copy_assign.py::assign_read`.
///
/// * `obs` — observed seq-space base per PSV column; `None` values are unspanned
///   (Python's `obs[c] is None`) and contribute nothing. Iterated in ascending column
///   index (BTreeMap order) to match the fixture generator's operation order.
/// * `copy_vecs` — ORDER-PRESERVING list of `(copy_name, {column -> base})`; the list
///   order IS the Python `list(copy_vecs)` names order (do not pass a HashMap).
/// * `read_bounds` / `copy_bounds` — optional junction evidence (`None`/empty ⇒ the
///   junction term is skipped, matching Python truthiness).
/// * `e`, `jw`, `btol` — the likelihood error, junction weight and boundary tolerance
///   (defaults [`ERR`], [`JW`], [`BTOL`]).
pub fn assign_read_margin(
    obs: &BTreeMap<usize, Option<char>>,
    copy_vecs: &[(String, BTreeMap<usize, char>)],
    read_bounds: Option<&BTreeSet<i64>>,
    copy_bounds: Option<&[(String, BTreeSet<i64>)]>,
    e: f64,
    jw: f64,
    btol: i64,
) -> MarginAssignment {
    let n = copy_vecs.len();
    // lp_match, lp_mis = math.log(1 - e), math.log(e / 3)
    let lp_match = (1.0 - e).ln();
    let lp_mis = (e / 3.0).ln();
    // spanned = [c for c in obs if obs[c] is not None]  (BTreeMap => ascending column)
    let spanned: Vec<(usize, char)> = obs
        .iter()
        .filter_map(|(&c, v)| v.map(|b| (c, b)))
        .collect();
    let mut n_decisive = 0usize;
    // logL = {n: 0.0 for n in names}
    let mut logl = vec![0.0f64; n];

    // --- PSV term ---
    for &(c, ob) in &spanned {
        // alleles = { copy_vecs[nm].get(c) for nm in names if not None }
        let mut alleles: BTreeSet<char> = BTreeSet::new();
        for (_, cv) in copy_vecs {
            if let Some(&a) = cv.get(&c) {
                alleles.insert(a);
            }
        }
        if alleles.len() > 1 {
            n_decisive += 1;
        }
        for (i, (_, cv)) in copy_vecs.iter().enumerate() {
            if let Some(&a) = cv.get(&c) {
                logl[i] += if ob == a { lp_match } else { lp_mis };
            }
        }
    }

    // --- junction (copy-specific splicing) term ---  Python: if read_bounds and copy_bounds
    if let (Some(rb), Some(cb)) = (read_bounds, copy_bounds) {
        if !rb.is_empty() && !cb.is_empty() {
            // copy_bounds.get(nm, ()) lookup (keys may be a subset of names)
            let bounds_of = |name: &str| -> Option<&BTreeSet<i64>> {
                cb.iter().find(|(k, _)| k == name).map(|(_, s)| s)
            };
            // has(b, s) = any(abs(b - x) <= btol for x in s)
            let has = |b: i64, s: Option<&BTreeSet<i64>>| -> bool {
                match s {
                    Some(set) => set.iter().any(|&x| (b - x).abs() <= btol),
                    None => false,
                }
            };
            for &b in rb {
                let present = copy_vecs
                    .iter()
                    .filter(|(nm, _)| has(b, bounds_of(nm)))
                    .count();
                if 0 < present && present < n {
                    n_decisive += 1;
                }
                for (i, (nm, _)) in copy_vecs.iter().enumerate() {
                    logl[i] += if has(b, bounds_of(nm)) { jw } else { -jw };
                }
            }
        }
    }

    // order = sorted(names, key=lambda n: logL[n], reverse=True)
    // Python's reverse=True sort is STABLE: equal keys retain the original names order.
    // Rust's sort_by is stable, so returning Equal on equal logL preserves that order.
    let mut order: Vec<usize> = (0..n).collect();
    order.sort_by(|&i, &j| logl[j].partial_cmp(&logl[i]).unwrap_or(Ordering::Equal));
    let best_idx = order[0];
    let margin = if n > 1 {
        logl[order[0]] - logl[order[1]]
    } else {
        f64::INFINITY
    };

    MarginAssignment {
        best: copy_vecs[best_idx].0.clone(),
        margin,
        n_span: spanned.len(),
        n_decisive,
        logl: copy_vecs
            .iter()
            .map(|(nm, _)| nm.clone())
            .zip(logl)
            .collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/o2_margin_gate_fixture.json");
        serde_json::from_str(raw).expect("parse o2_margin_gate fixture json")
    }

    fn char_of(v: &Value) -> char {
        v.as_str().unwrap().chars().next().unwrap()
    }

    /// obs: {str(col) -> base|null} -> BTreeMap<usize, Option<char>>
    fn parse_obs(v: &Value) -> BTreeMap<usize, Option<char>> {
        v.as_object()
            .unwrap()
            .iter()
            .map(|(k, val)| {
                let col = k.parse::<usize>().unwrap();
                let base = if val.is_null() { None } else { Some(char_of(val)) };
                (col, base)
            })
            .collect()
    }

    /// copy_vecs: [[name, {str(col) -> base}], ...] -> Vec<(String, BTreeMap<usize,char>)>
    fn parse_copy_vecs(v: &Value) -> Vec<(String, BTreeMap<usize, char>)> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|pair| {
                let name = pair[0].as_str().unwrap().to_string();
                let cols: BTreeMap<usize, char> = pair[1]
                    .as_object()
                    .unwrap()
                    .iter()
                    .map(|(k, b)| (k.parse::<usize>().unwrap(), char_of(b)))
                    .collect();
                (name, cols)
            })
            .collect()
    }

    fn parse_read_bounds(v: &Value) -> Option<BTreeSet<i64>> {
        if v.is_null() {
            None
        } else {
            Some(v.as_array().unwrap().iter().map(|x| x.as_i64().unwrap()).collect())
        }
    }

    fn parse_copy_bounds(v: &Value) -> Option<Vec<(String, BTreeSet<i64>)>> {
        if v.is_null() {
            None
        } else {
            Some(
                v.as_array()
                    .unwrap()
                    .iter()
                    .map(|pair| {
                        let name = pair[0].as_str().unwrap().to_string();
                        let s: BTreeSet<i64> =
                            pair[1].as_array().unwrap().iter().map(|x| x.as_i64().unwrap()).collect();
                        (name, s)
                    })
                    .collect(),
            )
        }
    }

    #[test]
    fn constants_match_python() {
        let fx = load_fixture();
        let c = &fx["constants"];
        assert_eq!(ERR.to_bits(), c["ERR_bits"].as_u64().unwrap(), "ERR");
        assert_eq!(MARGIN.to_bits(), c["MARGIN_bits"].as_u64().unwrap(), "MARGIN");
        assert_eq!(JW.to_bits(), c["JW_bits"].as_u64().unwrap(), "JW");
        assert_eq!(BTOL, c["BTOL"].as_i64().unwrap(), "BTOL");
    }

    #[test]
    fn byte_parity_all_cases() {
        let fx = load_fixture();
        let cases = fx["cases"].as_array().expect("cases array");
        assert!(cases.len() >= 200, "expected >=200 cases, got {}", cases.len());

        let mut n_real = 0usize;
        let mut n_synth = 0usize;
        let mut n_junction = 0usize;

        for case in cases {
            let id = case["id"].as_str().unwrap();
            match case["kind"].as_str().unwrap() {
                "real" => n_real += 1,
                _ => n_synth += 1,
            }
            let obs = parse_obs(&case["obs"]);
            let copy_vecs = parse_copy_vecs(&case["copy_vecs"]);
            let read_bounds = parse_read_bounds(&case["read_bounds"]);
            let copy_bounds = parse_copy_bounds(&case["copy_bounds"]);
            if read_bounds.is_some() {
                n_junction += 1;
            }
            let e = f64::from_bits(case["e_bits"].as_u64().unwrap());
            let jw = f64::from_bits(case["jw_bits"].as_u64().unwrap());
            let btol = case["btol"].as_i64().unwrap();

            let got = assign_read_margin(
                &obs,
                &copy_vecs,
                read_bounds.as_ref(),
                copy_bounds.as_deref(),
                e,
                jw,
                btol,
            );

            let exp = &case["expect"];
            // best (exact name)
            let exp_best = exp["best"].as_str().unwrap();
            assert_eq!(
                got.best, exp_best,
                "case {id}: best {} != {}",
                got.best, exp_best
            );
            // margin: raw IEEE-754 bits
            let exp_margin_bits = exp["margin_bits"].as_u64().unwrap();
            assert_eq!(
                got.margin.to_bits(),
                exp_margin_bits,
                "case {id}: margin bits {:#018x} != {:#018x} (got {:?}, exp {:?})",
                got.margin.to_bits(),
                exp_margin_bits,
                got.margin,
                f64::from_bits(exp_margin_bits),
            );
            // n_span, n_decisive
            assert_eq!(
                got.n_span as u64,
                exp["n_span"].as_u64().unwrap(),
                "case {id}: n_span"
            );
            assert_eq!(
                got.n_decisive as u64,
                exp["n_decisive"].as_u64().unwrap(),
                "case {id}: n_decisive"
            );
            // logL: name + raw bits, in order
            let exp_logl = exp["logl"].as_array().unwrap();
            assert_eq!(
                got.logl.len(),
                exp_logl.len(),
                "case {id}: logl length {} != {}",
                got.logl.len(),
                exp_logl.len()
            );
            for (k, (gname, gval)) in got.logl.iter().enumerate() {
                let ename = exp_logl[k][0].as_str().unwrap();
                let ebits = exp_logl[k][1].as_u64().unwrap();
                assert_eq!(gname, ename, "case {id}: logl[{k}] name {gname} != {ename}");
                assert_eq!(
                    gval.to_bits(),
                    ebits,
                    "case {id}: logl[{k}] ({gname}) bits {:#018x} != {:#018x} (got {:?}, exp {:?})",
                    gval.to_bits(),
                    ebits,
                    gval,
                    f64::from_bits(ebits),
                );
            }
        }

        // sanity on the fixture composition (also reported by the generator)
        assert!(n_real >= 200, "expected >=200 real reads, got {n_real}");
        assert!(n_junction >= 20, "expected >=20 junction cases, got {n_junction}");
        eprintln!(
            "o2_margin_gate byte-parity: {} cases ({} real, {} synthetic, {} junction) all match",
            cases.len(),
            n_real,
            n_synth,
            n_junction
        );
    }
}
