//! O1 recombinant-SPLIT gate -- faithful Rust port of `bench/recombinant_split.py`
//! (the O1 over-merge-gate migration, `docs/RETIREMENT_AND_MIGRATION.md` Tier-2 #6,
//! full byte-parity path).
//!
//! A RECOMBINANT bridge is a locus whose exon-chain splits COLINEARLY into >=2
//! DIFFERENT sub-families' exons AND is an articulation point whose best single-
//! neighbour colinear coverage `< COLINEAR_COV`. The shipped pairwise-edge family
//! definition transitively merges `G1-G3-G2` through such a bridge (a density-2/3
//! barbell survives the gamma-quasi-clique); this gate SPLITS the family along the
//! bridge into its colinear sub-families. The HIGH-confidence DISTRIBUTED-MOSAIC
//! subset only (both bridged sub-families annotated, minor block >= 2 exons, NOT
//! genomically colocated) is recall-safe to split (flagship: fid 210
//! `LOC115935264` bridging `LOC101126070 | GALNT17`).
//!
//! REUSES the already-ported shared exon-graph LIBRARY in `super::bridge_detector`
//! (`family_exons` / `exon_match_tensor` / `build_graph` / `colinear_cov` /
//! `subfams_colocated` / `subfam_dom_gene` + `ID_THRESH` / `COLINEAR_COV`) and the
//! `GeneMeta` shape from `super::family_loaders` -- nothing re-derived. Only the
//! SPLIT-gate driver (`_members`, `_recombinant_bridges`, `split_block`) + the two
//! deterministic graph algorithms it needs (`articulation_points`,
//! `components_excluding`) are ported here.
//!
//! PORTED (the Python is ground truth; line refs are `bench/recombinant_split.py`):
//!   * constants `COLINEAR_COV=0.60` (:39, reused from bridge_detector),
//!     `ID_THRESH=0.70` (:40, reused), `MAX_LOCI=60` (:41);
//!   * `_members` (:72), `_recombinant_bridges` (:83), `split_block` (:132).
//!
//! NEW graph algorithms (deterministic):
//!   * `articulation_points` -- iterative Tarjan cut-vertices. The Python does
//!     `sorted(nx.articulation_points(G))`; networkx 3.6.1 `articulation_points`
//!     DEDUPLICATES its DFS generator (`seen` set), so the yielded value is exactly
//!     the graph-invariant cut-vertex SET -- which a standard Tarjan implementation
//!     reproduces regardless of neighbour order. Verified SET-equal to networkx on
//!     the `articulation_graphs` fixture (chains, cycles, trees, star, shared-vertex
//!     triangles, barbell, K4, multi-component, single node, bridges).
//!   * `components_excluding` -- connected components over the nodes NOT in a removed
//!     set (matching `nx.connected_components(G.copy(); remove_nodes_from(...))`,
//!     INCLUDING singleton components for now-isolated nodes), each sorted, sorted by
//!     first element (the Python `sorted((sorted(c) ...), key=lambda c: c[0])`).
//!
//! Verified byte-identical to the shipped Python against a golden fixture
//! (`testdata/recombinant_split_fixture.json`, generated by
//! `bench/gen_recombinant_split_fixture.py`, PYTHONHASHSEED=0); see the `#[test]`s.
//!
//! **STATUS:** OTHER-BINARY — family_define only; DEFAULT-ON there, opt out with --no-split-recombinants or RUSTLE_NO_SPLIT_RECOMBINANTS=1 (src/bin/family_define.rs:44-46 clap arg   (docs/MODULE_STATUS.md; assigned by reachability, not by this header)

use std::collections::{BTreeSet, HashMap};

use super::bridge_detector::{
    build_graph, colinear_cov, exon_match_tensor, family_exons, subfam_dom_gene, subfams_colocated,
    ExonFetcher, LocusGraph, Member, Rec, Tensor, COLINEAR_COV, ID_THRESH,
};
use super::family_loaders::GeneMeta;

/// Skip giant families (repeat hubs, already repeat-gated; never mosaics).
/// `bench/recombinant_split.py:41  MAX_LOCI = 60`.
pub const MAX_LOCI: usize = 60;

// ===========================================================================
// articulation_points  -- iterative Tarjan cut-vertices (== nx.articulation_points SET)
// ===========================================================================

/// The set of articulation points (cut vertices) of the undirected graph given by
/// `adj` (node `u`'s neighbours = `adj[u]`, symmetric, no self-loops). Node universe
/// is `0..adj.len()`.
///
/// Standard iterative (non-recursive) Tarjan DFS: a non-root node `u` is a cut vertex
/// iff it has a child `v` in the DFS tree with `low[v] >= disc[u]`; the DFS root is a
/// cut vertex iff it has `> 1` tree children. The cut-vertex SET is a graph invariant
/// (independent of neighbour iteration order), so this equals
/// `set(nx.articulation_points(G))` exactly (networkx 3.6.1 deduplicates its own DFS
/// generator via a `seen` set). Multi-component graphs = union over the DFS forest;
/// a single node / edgeless graph has none.
pub fn articulation_points(adj: &[BTreeSet<usize>]) -> BTreeSet<usize> {
    let n = adj.len();
    // Indexed neighbour snapshots (sorted order from the BTreeSet; order is irrelevant
    // to the resulting SET -- see the doc).
    let neigh: Vec<Vec<usize>> = adj.iter().map(|s| s.iter().copied().collect()).collect();
    let mut disc = vec![0usize; n];
    let mut low = vec![0usize; n];
    let mut visited = vec![false; n];
    let mut ap: BTreeSet<usize> = BTreeSet::new();
    let mut timer = 0usize;

    for s in 0..n {
        if visited[s] {
            continue;
        }
        timer += 1;
        disc[s] = timer;
        low[s] = timer;
        visited[s] = true;
        let mut root_children = 0usize;
        // Frame: (node, parent(-1 for root), next-neighbour index).
        let mut stack: Vec<(usize, isize, usize)> = vec![(s, -1, 0)];
        while !stack.is_empty() {
            let top = stack.len() - 1;
            let (u, parent) = (stack[top].0, stack[top].1);
            if stack[top].2 < neigh[u].len() {
                let v = neigh[u][stack[top].2];
                stack[top].2 += 1;
                if v as isize == parent {
                    continue; // skip the single tree edge back to the DFS parent
                }
                if visited[v] {
                    if disc[v] < low[u] {
                        low[u] = disc[v]; // back edge
                    }
                } else {
                    visited[v] = true;
                    timer += 1;
                    disc[v] = timer;
                    low[v] = timer;
                    if parent == -1 {
                        root_children += 1;
                    }
                    stack.push((v, u as isize, 0));
                }
            } else {
                // u fully explored: propagate low to the DFS parent + test cut-vertex.
                stack.pop();
                if let Some(&(pu, pp, _)) = stack.last() {
                    if low[u] < low[pu] {
                        low[pu] = low[u];
                    }
                    if pp != -1 && low[u] >= disc[pu] {
                        ap.insert(pu);
                    }
                }
            }
        }
        if root_children > 1 {
            ap.insert(s);
        }
    }
    ap
}

// ===========================================================================
// components_excluding  -- connected components with a node set removed
// ===========================================================================

/// Connected components of the graph `adj` over the nodes NOT in `removed`, each
/// component sorted ascending, the list sorted by first element. Matches the Python
/// `sorted((sorted(c) for c in nx.connected_components(Gb)), key=lambda c: c[0])`
/// where `Gb` is `G` with `removed` deleted -- INCLUDING singleton components for
/// nodes whose only edges went to removed nodes. Deterministic DFS in ascending order.
pub fn components_excluding(adj: &[BTreeSet<usize>], removed: &BTreeSet<usize>) -> Vec<Vec<usize>> {
    let n = adj.len();
    let mut seen = vec![false; n];
    for &r in removed {
        if r < n {
            seen[r] = true; // treat removed nodes as already-visited => skipped
        }
    }
    let mut comps: Vec<Vec<usize>> = Vec::new();
    for s in 0..n {
        if seen[s] {
            continue;
        }
        let mut stack = vec![s];
        seen[s] = true;
        let mut comp = Vec::new();
        while let Some(u) = stack.pop() {
            comp.push(u);
            for &v in &adj[u] {
                if !seen[v] {
                    seen[v] = true;
                    stack.push(v);
                }
            }
        }
        comp.sort_unstable();
        comps.push(comp);
    }
    comps.sort_by(|a, b| a[0].cmp(&b[0]));
    comps
}

// ===========================================================================
// _members  (recombinant_split.py:72)
// ===========================================================================

/// Sorted-DN member records for a block. Faithful port of `_members` (:72): iterate
/// `sorted(block)`, skip any `dn` absent from `genes`, else build a member with
/// `gene = gene_of_dn.get(dn, "NA")` and `chrom/start/end` from `genes[dn]`.
fn members_of(
    block: &[String],
    genes: &HashMap<String, GeneMeta>,
    gene_of_dn: &HashMap<String, String>,
) -> Vec<Member> {
    let mut sb: Vec<String> = block.to_vec();
    sb.sort();
    let mut ms = Vec::new();
    for dn in &sb {
        let g = match genes.get(dn) {
            None => continue,
            Some(g) => g,
        };
        ms.push(Member {
            dn: dn.clone(),
            gene: gene_of_dn.get(dn).cloned().unwrap_or_else(|| "NA".to_string()),
            chrom: g.chrom.clone(),
            start: g.start,
            end: g.end,
        });
    }
    ms
}

/// `sorted(block)` (lexicographic, matches Python `sorted` on the ASCII DN ids).
fn sorted_block(block: &[String]) -> Vec<String> {
    let mut b: Vec<String> = block.to_vec();
    b.sort();
    b
}

// ===========================================================================
// _recombinant_bridges  (recombinant_split.py:83)
// ===========================================================================

/// Indices of vg-split RECOMBINANT articulation bridges. Faithful port of
/// `_recombinant_bridges` (:83): for each articulation point `b` (ascending), the
/// components of `G\b` that touch `b`'s neighbours (sorted by min-member) are the
/// bridged sub-families; require `>= 2`. For each exon `i` of `b`, the sub-families it
/// SOLELY hits (`idv >= ID_THRESH`, single component) are counted; require `>= 2`
/// singly-hit sub-families (different exons -> different sub-families). Skip if any
/// neighbour colinearly covers `>= COLINEAR_COV` (a shared domain, not a mosaic); skip
/// if the sub-families are genomically colocated (readthrough chimera); require BOTH
/// involved sub-families annotated AND the minor block `>= 2` exons. Emit `b`.
fn recombinant_bridges(recs: &[Rec], best: &Tensor, graph: &LocusGraph) -> Vec<usize> {
    if graph.num_edges() == 0 {
        return Vec::new();
    }
    let adj = &graph.adj;
    let mut out: Vec<usize> = Vec::new();
    // sorted(nx.articulation_points(G)): BTreeSet iterates ascending == sorted.
    for b in articulation_points(adj) {
        let nbrs = &adj[b];
        let removed: BTreeSet<usize> = std::iter::once(b).collect();
        // components of G\b that intersect b's neighbours, sorted by min-member.
        let bridged: Vec<Vec<usize>> = components_excluding(adj, &removed)
            .into_iter()
            .filter(|c| c.iter().any(|m| nbrs.contains(m)))
            .collect();
        if bridged.len() < 2 {
            continue;
        }
        // comp id of each member
        let mut cid_of: HashMap<usize, usize> = HashMap::new();
        for (ci, comp) in bridged.iter().enumerate() {
            for &m in comp {
                cid_of.insert(m, ci);
            }
        }
        // per exon of b: which single sub-family it solely hits
        let mut single: HashMap<usize, usize> = HashMap::new();
        for i in 0..recs[b].exons.len() {
            let mut hit: BTreeSet<usize> = BTreeSet::new();
            for &m in nbrs {
                let (idv, _) = best.get(b, i, m);
                if idv >= ID_THRESH {
                    if let Some(&c) = cid_of.get(&m) {
                        hit.insert(c);
                    }
                }
            }
            if hit.len() == 1 {
                let c = *hit.iter().next().expect("hit has exactly one element");
                *single.entry(c).or_insert(0) += 1;
            }
        }
        if single.len() < 2 {
            continue; // NOT recombinant (needs different exons -> different subfams)
        }
        // best single-neighbour colinear cover (default 0.0; all covers are >= 0).
        let best_single = nbrs
            .iter()
            .map(|&m| colinear_cov(recs, best, b, m))
            .fold(0.0f64, f64::max);
        if best_single >= COLINEAR_COV {
            continue; // a neighbour colinearly covers the bridge -> not a mosaic
        }
        if subfams_colocated(recs, &bridged) {
            continue; // readthrough chimera (assembly artifact), not distributed
        }
        // HIGH-confidence: BOTH involved sub-families annotated + minor block >= 2 exons.
        let mut involved: Vec<usize> = single.keys().copied().collect();
        involved.sort_unstable();
        let minor = involved
            .iter()
            .map(|c| single[c])
            .min()
            .expect("involved is non-empty (single.len() >= 2)");
        let both_annotated = involved.iter().all(|&c| {
            let g = subfam_dom_gene(recs, &bridged[c]);
            g != "NA" && !g.is_empty()
        });
        if !(both_annotated && minor >= 2) {
            continue; // LOW confidence (NA-dominant sub-family / 1-exon minor block)
        }
        out.push(b);
    }
    out
}

// ===========================================================================
// split_block  (recombinant_split.py:132)
// ===========================================================================

/// Return a PARTITION of `block` (list of sorted DN-blocks): split along vg-split
/// recombinant bridges, or `[sorted(block)]` unchanged if none. Never loses a locus;
/// deterministic. Faithful port of `split_block` (:132) -- see the inline comments for
/// the bridge-assignment, skeleton-less attachment, and same-gene recall-safety guard.
pub fn split_block<F: ExonFetcher>(
    block: &[String],
    genes: &HashMap<String, GeneMeta>,
    gene_of_dn: &HashMap<String, String>,
    skel: &HashMap<(String, i64, i64), Vec<(i64, i64)>>,
    strand: &HashMap<String, String>,
    fa: &F,
) -> Vec<Vec<String>> {
    if block.len() < 3 {
        return vec![sorted_block(block)];
    }
    let members = members_of(block, genes, gene_of_dn);
    if members.len() < 3 || members.len() > MAX_LOCI {
        return vec![sorted_block(block)];
    }
    let recs = family_exons(&members, skel, strand, fa);
    if recs.len() < 3 {
        return vec![sorted_block(block)];
    }
    let best = exon_match_tensor(&recs);
    let graph = build_graph(&recs, &best);
    let bridge_idx = recombinant_bridges(&recs, &best, &graph);
    if bridge_idx.is_empty() {
        return vec![sorted_block(block)];
    }

    let dn_of: Vec<String> = recs.iter().map(|r| r.dn.clone()).collect();
    let bset: BTreeSet<usize> = bridge_idx.iter().copied().collect();
    // sub-families = connected components after removing ALL vg-split bridges.
    let subfams = components_excluding(&graph.adj, &bset);
    let mut subfam_dns: Vec<BTreeSet<String>> = subfams
        .iter()
        .map(|sf| sf.iter().map(|&i| dn_of[i].clone()).collect())
        .collect();

    // assign each bridge to its best-colinear sub-family (>= COLINEAR_COV to a member)
    // else its own singleton.
    for &b in &bridge_idx {
        let mut bestc = 0.0f64;
        let mut bestsf: isize = -1;
        for (si, sf) in subfams.iter().enumerate() {
            let c = sf
                .iter()
                .map(|&m| colinear_cov(&recs, &best, b, m))
                .fold(0.0f64, f64::max);
            if c > bestc {
                bestc = c;
                bestsf = si as isize;
            }
        }
        if bestsf >= 0 && bestc >= COLINEAR_COV {
            subfam_dns[bestsf as usize].insert(dn_of[b].clone());
        } else {
            subfam_dns.push(std::iter::once(dn_of[b].clone()).collect());
        }
    }

    // skeleton-less DNs (not in recs): attach to the FIRST sub-family sharing a
    // chromosome, else own singleton.
    let mut placed: BTreeSet<String> = BTreeSet::new();
    for s in &subfam_dns {
        for x in s {
            placed.insert(x.clone());
        }
    }
    for dn in sorted_block(block) {
        if placed.contains(&dn) {
            continue;
        }
        let mut tgt: isize = -1;
        if let Some(g) = genes.get(&dn) {
            let gchrom = g.chrom.as_str();
            for si in 0..subfam_dns.len() {
                let found = subfam_dns[si].iter().any(|x| {
                    genes.get(x).map(|gx| gx.chrom.as_str()) == Some(gchrom)
                });
                if found {
                    tgt = si as isize;
                    break;
                }
            }
        }
        if tgt >= 0 {
            subfam_dns[tgt as usize].insert(dn.clone());
        } else {
            subfam_dns.push(std::iter::once(dn.clone()).collect());
        }
        placed.insert(dn);
    }

    // result = sorted((sorted(s) for s in subfam_dns if s), key=first)
    let mut result: Vec<Vec<String>> = subfam_dns
        .iter()
        .filter(|s| !s.is_empty())
        .map(|s| s.iter().cloned().collect::<Vec<String>>())
        .collect();
    result.sort_by(|a, b| a[0].cmp(&b[0]));

    // RECALL-SAFETY GUARD: if the partition separates loci of the SAME gene into
    // different sub-families, REJECT the whole split (keep merged).
    if result.len() > 1 {
        let mut gene_parts: HashMap<String, BTreeSet<usize>> = HashMap::new();
        for (pi, part) in result.iter().enumerate() {
            for dn in part {
                if let Some(g) = gene_of_dn.get(dn) {
                    if g != "NA" {
                        gene_parts.entry(g.clone()).or_default().insert(pi);
                    }
                }
            }
        }
        if gene_parts.values().any(|pis| pis.len() >= 2) {
            return vec![sorted_block(block)];
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/recombinant_split_fixture.json");
        serde_json::from_str(raw).expect("parse recombinant_split fixture json")
    }

    // ----------------------------------------------------------------- unit corners

    #[test]
    fn constants_match_python() {
        let fx = load_fixture();
        assert_eq!(fx["MAX_LOCI"].as_u64().unwrap() as usize, MAX_LOCI);
        assert_eq!(fx["COLINEAR_COV"].as_f64().unwrap(), COLINEAR_COV);
        assert_eq!(fx["ID_THRESH"].as_f64().unwrap(), ID_THRESH);
        assert_eq!(MAX_LOCI, 60);
    }

    fn adj_from_edges(n: usize, edges: &[(usize, usize)]) -> Vec<BTreeSet<usize>> {
        let mut adj: Vec<BTreeSet<usize>> = vec![BTreeSet::new(); n];
        for &(u, v) in edges {
            adj[u].insert(v);
            adj[v].insert(u);
        }
        adj
    }

    #[test]
    fn articulation_points_unit() {
        // path 0-1-2-3-4 -> internal nodes are cut vertices
        let adj = adj_from_edges(5, &[(0, 1), (1, 2), (2, 3), (3, 4)]);
        assert_eq!(articulation_points(&adj), [1, 2, 3].into_iter().collect());
        // cycle -> none
        let adj = adj_from_edges(4, &[(0, 1), (1, 2), (2, 3), (3, 0)]);
        assert!(articulation_points(&adj).is_empty());
        // single node / edgeless -> none
        assert!(articulation_points(&adj_from_edges(1, &[])).is_empty());
        assert!(articulation_points(&adj_from_edges(3, &[])).is_empty());
        // star center is a cut vertex
        let adj = adj_from_edges(4, &[(0, 1), (0, 2), (0, 3)]);
        assert_eq!(articulation_points(&adj), [0].into_iter().collect());
    }

    #[test]
    fn components_excluding_unit() {
        // 0-1-2-3, remove 1 -> {0} and {2,3}
        let adj = adj_from_edges(4, &[(0, 1), (1, 2), (2, 3)]);
        let comps = components_excluding(&adj, &[1].into_iter().collect());
        assert_eq!(comps, vec![vec![0], vec![2, 3]]);
        // remove nothing -> one component
        let comps = components_excluding(&adj, &BTreeSet::new());
        assert_eq!(comps, vec![vec![0, 1, 2, 3]]);
        // isolated node becomes its own singleton component
        let adj = adj_from_edges(3, &[(0, 1)]);
        let comps = components_excluding(&adj, &BTreeSet::new());
        assert_eq!(comps, vec![vec![0, 1], vec![2]]);
    }

    // ----------------------------------------------------------------- (a) articulation parity

    /// PROVES the Rust Tarjan cut-vertex SET == `nx.articulation_points` on >= 20
    /// graphs (chains, cycles, trees, star, shared-vertex triangles, barbell, K4,
    /// multi-component, single node, bridges). Reports the first mismatch.
    #[test]
    fn articulation_points_parity_vs_networkx() {
        let fx = load_fixture();
        let graphs = fx["articulation_graphs"].as_array().expect("articulation_graphs array");
        assert!(graphs.len() >= 20, "need >= 20 articulation graphs, got {}", graphs.len());
        let mut n_with_ap = 0;
        let mut n_no_ap = 0;
        let mut n_multi_component = 0;
        let mut seen_single_node = false;
        for g in graphs {
            let label = g["label"].as_str().unwrap();
            let n = g["n"].as_u64().unwrap() as usize;
            let edges: Vec<(usize, usize)> = g["edges"]
                .as_array()
                .unwrap()
                .iter()
                .map(|e| {
                    let a = e.as_array().unwrap();
                    (a[0].as_u64().unwrap() as usize, a[1].as_u64().unwrap() as usize)
                })
                .collect();
            let want: BTreeSet<usize> = g["art"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_u64().unwrap() as usize)
                .collect();
            let adj = adj_from_edges(n, &edges);
            let got = articulation_points(&adj);
            assert_eq!(got, want, "articulation SET mismatch for graph '{label}': rust {got:?} != nx {want:?}");
            if want.is_empty() {
                n_no_ap += 1;
            } else {
                n_with_ap += 1;
            }
            if n == 1 && edges.is_empty() {
                seen_single_node = true;
            }
            if components_excluding(&adj, &BTreeSet::new()).len() >= 2 {
                n_multi_component += 1;
            }
        }
        assert!(n_with_ap >= 8, "need >= 8 graphs WITH articulation points, got {n_with_ap}");
        assert!(n_no_ap >= 5, "need >= 5 biconnected/AP-free graphs, got {n_no_ap}");
        assert!(n_multi_component >= 2, "need >= 2 multi-component graphs, got {n_multi_component}");
        assert!(seen_single_node, "need a single-node graph");
        eprintln!(
            "articulation parity: {} graphs SET-identical to networkx (with-AP={n_with_ap}, AP-free={n_no_ap}, multi-component={n_multi_component})",
            graphs.len()
        );
    }

    // ----------------------------------------------------------------- (b) split_block parity

    /// Mock fetcher backed by the fixture's captured raw (case-carrying) genome slices,
    /// keyed on `(chrom, start0, end0)` = the exact `fetch(chrom, s-1, e)` args.
    struct MockFasta {
        slices: HashMap<(String, i64, i64), Vec<u8>>,
    }
    impl ExonFetcher for MockFasta {
        fn fetch(&self, chrom: &str, start: i64, end: i64) -> Option<Vec<u8>> {
            self.slices.get(&(chrom.to_string(), start, end)).cloned()
        }
    }

    fn block_inputs(
        b: &Value,
    ) -> (
        Vec<String>,
        HashMap<String, GeneMeta>,
        HashMap<String, String>,
        HashMap<(String, i64, i64), Vec<(i64, i64)>>,
        HashMap<String, String>,
        MockFasta,
    ) {
        let block: Vec<String> =
            b["block"].as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();
        // genes: {dn:[chrom,start,end]} -> GeneMeta (name/biotype/ov unused by split_block)
        let mut genes: HashMap<String, GeneMeta> = HashMap::new();
        for (dn, v) in b["genes"].as_object().unwrap() {
            let a = v.as_array().unwrap();
            genes.insert(
                dn.clone(),
                GeneMeta {
                    chrom: a[0].as_str().unwrap().to_string(),
                    start: a[1].as_i64().unwrap(),
                    end: a[2].as_i64().unwrap(),
                    name: dn.clone(),
                    biotype: "NA".to_string(),
                    ov: 0.0,
                },
            );
        }
        let mut gene_of_dn: HashMap<String, String> = HashMap::new();
        for (dn, v) in b["gene_of_dn"].as_object().unwrap() {
            gene_of_dn.insert(dn.clone(), v.as_str().unwrap().to_string());
        }
        let mut strand: HashMap<String, String> = HashMap::new();
        for (dn, v) in b["strand"].as_object().unwrap() {
            strand.insert(dn.clone(), v.as_str().unwrap().to_string());
        }
        let mut skel: HashMap<(String, i64, i64), Vec<(i64, i64)>> = HashMap::new();
        for s in b["skel"].as_array().unwrap() {
            let chrom = s["chrom"].as_str().unwrap().to_string();
            let st = s["start"].as_i64().unwrap();
            let en = s["end"].as_i64().unwrap();
            let exons: Vec<(i64, i64)> = s["exons"]
                .as_array()
                .unwrap()
                .iter()
                .map(|p| {
                    let a = p.as_array().unwrap();
                    (a[0].as_i64().unwrap(), a[1].as_i64().unwrap())
                })
                .collect();
            skel.insert((chrom, st, en), exons);
        }
        let mut slices: HashMap<(String, i64, i64), Vec<u8>> = HashMap::new();
        for sl in b["slices"].as_array().unwrap() {
            let chrom = sl["chrom"].as_str().unwrap().to_string();
            let s0 = sl["start0"].as_i64().unwrap();
            let e0 = sl["end0"].as_i64().unwrap();
            let bytes = sl["bytes"].as_str().unwrap().as_bytes().to_vec();
            slices.insert((chrom, s0, e0), bytes);
        }
        (block, genes, gene_of_dn, skel, strand, MockFasta { slices })
    }

    fn as_set(parts: &[Vec<String>]) -> BTreeSet<Vec<String>> {
        parts.iter().cloned().collect()
    }

    /// PROVES `split_block` == the shipped Python EXACTLY (as sets of sorted DN-blocks)
    /// for every fixture block. Reports the first mismatch + root-cause hints.
    #[test]
    fn split_block_parity() {
        let fx = load_fixture();
        let blocks = fx["blocks"].as_array().expect("blocks array");
        assert!(blocks.len() >= 20, "need >= 20 blocks, got {}", blocks.len());

        let mut n_split = 0;
        let mut n_unchanged = 0;
        let mut seen_flagship = false;
        let mut seen_colocated = false;
        let mut seen_na = false;
        let mut seen_multi_art = false;
        let mut seen_gt_maxloci = false;
        let mut seen_lt3 = false;
        let mut seen_graph = false;

        for b in blocks {
            let label = b["label"].as_str().unwrap();
            let cls = b["cls"].as_str().unwrap();
            let n_art = b["n_art"].as_u64().unwrap();
            let (block, genes, gene_of_dn, skel, strand, fa) = block_inputs(b);

            let want: Vec<Vec<String>> = b["result"]
                .as_array()
                .unwrap()
                .iter()
                .map(|p| p.as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect())
                .collect();
            let got = split_block(&block, &genes, &gene_of_dn, &skel, &strand, &fa);

            assert_eq!(
                as_set(&got),
                as_set(&want),
                "split_block MISMATCH block '{label}' (cls={cls}): rust {} parts {:?} != python {} parts {:?}",
                got.len(),
                got,
                want.len(),
                want
            );

            if want.len() > 1 {
                n_split += 1;
            } else {
                n_unchanged += 1;
            }
            match cls {
                "split" => {
                    if label == "flagship_210" {
                        seen_flagship = true;
                        // fid 210: LOC115935264 bridges LOC101126070 | GALNT17 -> 3 singleton parts;
                        // GALNT17 + LOC101126070 must NOT be co-membered after the split.
                        assert!(got.len() >= 2, "flagship 210 did not split");
                        let galnt17: Vec<&String> =
                            gene_of_dn.iter().filter(|(_, g)| g.as_str() == "GALNT17").map(|(d, _)| d).collect();
                        let loc: Vec<&String> = gene_of_dn
                            .iter()
                            .filter(|(_, g)| g.as_str() == "LOC101126070")
                            .map(|(d, _)| d)
                            .collect();
                        assert!(!galnt17.is_empty() && !loc.is_empty(), "flagship missing GALNT17/LOC101126070");
                        for part in &got {
                            let has_g = galnt17.iter().any(|d| part.contains(d));
                            let has_l = loc.iter().any(|d| part.contains(d));
                            assert!(!(has_g && has_l), "flagship 210: GALNT17 + LOC101126070 still co-membered");
                        }
                    }
                }
                "colocated_skip" => seen_colocated = true,
                "na_dominant_skip" => seen_na = true,
                "multi_articulation" => seen_multi_art = true,
                "skip_gt_maxloci" => seen_gt_maxloci = true,
                "skip_block_lt3" => seen_lt3 = true,
                "nonsplit_graph" => seen_graph = true,
                _ => {}
            }
            if n_art >= 2 {
                seen_multi_art = true;
            }
        }

        assert!(n_split >= 1, "fixture must exercise >= 1 SPLIT block");
        assert!(seen_flagship, "fixture must include the flagship fid-210 GALNT17|LOC101126070 split");
        assert!(seen_colocated, "fixture must include a colocated-chimera skip");
        assert!(seen_na, "fixture must include an NA-dominant skip");
        assert!(seen_multi_art, "fixture must include a multi-articulation-point family");
        assert!(seen_gt_maxloci, "fixture must include a >MAX_LOCI skip");
        assert!(seen_lt3, "fixture must include a <3-loci skip");
        assert!(seen_graph, "fixture must include non-split blocks that reach the exon graph");
        eprintln!(
            "split_block parity: {} blocks byte-identical to Python ({n_split} split, {n_unchanged} unchanged)",
            blocks.len()
        );
    }
}
