//! O2 recombinant-read ABSTAIN gate -- faithful Rust port of
//! `bench/recombinant_abstain.py` (the recombinant-read abstain leg of the O2
//! copy-assignment gate). Continues the family-def migration: the O1 pipeline is
//! already fully ported to `super::*`; this is the O2 leg.
//!
//! WHY (`bench/VG_READ_PATH_RECOMBINATION.md`, commit 7e3be89): the per-read
//! significance gate (`super::copy_assign`) FORCE-ASSIGNS recombinant reads to a
//! single copy. A recombinant read carries copy A's private SUN in one
//! bubble-bounded arm and copy B's in another arm; it satisfies TWO
//! Strong-Separation witnesses at once, so it belongs to NO single copy = a
//! read-level K-frontier (THEORY.md K>=3 recombination obstruction). Such a read
//! must ABSTAIN rather than be force-assigned to whichever copy has more SUNs.
//!
//! WHAT THIS MODULE IS. The SINGLE SOURCE of the recombinant-detection logic. It
//! hosts (verbatim) the bubble-bounded copy-switch test
//! [`detect_read_recombination`] + [`full_pattern_switches`] + their thresholds,
//! plus [`build_supported`] (read-supported-allele pileup), [`is_recombinant`]
//! (the reusable predicate) and [`apply_abstain_to_vg`] (the DEFAULT-ON gate leg
//! over a materialized family VG, `bench/o2_vg_visualization.py`).
//!
//! DETERMINISTIC + PURE: no BAM/genome/pysam/RNG. Iteration is over `BTreeMap`
//! keys / `names` slice order, mirroring Python's `sorted(obs)` and
//! `itertools.combinations(names, 2)` (which preserves list order). The
//! pair-selection tie-break key `(switches, -len(seq), imp, A, B)` (with the copy
//! NAME strings as the final tie-break, byte-compared like Python str) and the
//! crossover-vs-conversion boundary arithmetic + `clean_full` are reproduced
//! EXACTLY.
//!
//! OPT-OUT: DEFAULT-ON. Disable with env `RUSTLE_NO_RECOMBINANT_ABSTAIN=1`
//! (accepted truthy values `1`/`true`/`True`/`TRUE`); [`apply_abstain_to_vg`] is
//! then a no-op returning `[]` and the assignment output is byte-identical to the
//! prior gate.
//!
//! Verified byte-identical to the shipped Python against a golden fixture
//! (`testdata/recombinant_abstain_fixture.json`, generated by
//! `bench/gen_recombinant_abstain_fixture.py`, PYTHONHASHSEED=0); see the
//! `#[test]`s (detection parity, `build_supported` parity, apply-abstain flip-list
//! + counters parity, and the opt-out no-op check).

use std::collections::{BTreeMap, BTreeSet};

// ---------------------------------------------------------------------------
// detection thresholds (documented; conservative for a HiFi ERR~0.003 single
// molecule). MOVED verbatim from `bench/recombinant_abstain.py:57-70`.
// ---------------------------------------------------------------------------

/// Read must span >= this many pair-discriminating bubbles matched to A or B.
/// `bench/recombinant_abstain.py:57  MIN_INFO = 4`.
pub const MIN_INFO: usize = 4;
/// Crossover: each side of the switch >= this many discriminating bubbles.
/// `bench/recombinant_abstain.py:58  MIN_ARM = 2`.
pub const MIN_ARM: usize = 2;
/// Conversion: each flank (the outer A blocks) >= this many bubbles.
/// `bench/recombinant_abstain.py:59  MIN_FLANK = 2`.
pub const MIN_FLANK: usize = 2;
/// Conversion: tract (inner B block) >= this many bubbles (a 1-bubble "tract" is a
/// point event, not a recombination tract). `bench/recombinant_abstain.py:60  MIN_TRACT = 2`.
pub const MIN_TRACT: usize = 2;
/// NO single copy may explain the read within `(MIN_SINGLE_MM - 1)` mismatches.
/// `bench/recombinant_abstain.py:63  MIN_SINGLE_MM = 2`.
pub const MIN_SINGLE_MM: usize = 2;
/// Allow <= this many read bases matching NEITHER paired allele (dropped from split).
/// `bench/recombinant_abstain.py:64  IMPURITY_MAX = 1`.
pub const IMPURITY_MAX: usize = 1;
/// Supported(base) = read-count >= max(ALLELE_SUPPORT_ABS, ALLELE_SUPPORT_FRAC*cov).
/// `bench/recombinant_abstain.py:69  ALLELE_SUPPORT_ABS = 3`.
pub const ALLELE_SUPPORT_ABS: u32 = 3;
/// `bench/recombinant_abstain.py:70  ALLELE_SUPPORT_FRAC = 0.02`.
pub const ALLELE_SUPPORT_FRAC: f64 = 0.02;

/// Opt-out env (default-ON). `bench/recombinant_abstain.py:73`.
pub const OPTOUT_ENV: &str = "RUSTLE_NO_RECOMBINANT_ABSTAIN";
/// The abstain label (distinct from assigned/ambiguous/tied/no_cover).
/// `bench/recombinant_abstain.py:218  ABSTAIN_STATUS = "recombinant"`.
pub const ABSTAIN_STATUS: &str = "recombinant";

/// The recombinant-abstain leg is DEFAULT-ON; `RUSTLE_NO_RECOMBINANT_ABSTAIN=1`
/// disables it. Mirrors `bench/recombinant_abstain.py:76 abstain_enabled`:
/// `os.environ.get(OPTOUT_ENV, "0") not in ("1", "true", "True", "TRUE")`.
pub fn abstain_enabled() -> bool {
    match std::env::var(OPTOUT_ENV) {
        Ok(v) => !matches!(v.as_str(), "1" | "true" | "True" | "TRUE"),
        Err(_) => true, // unset -> "0" -> enabled
    }
}

// ---------------------------------------------------------------------------
// data representation of the materialized family VG the gate operates on
// (a subset of `bench/o2_vg_visualization.materialize_family`'s dict -- only the
// fields the abstain leg reads/writes).
// ---------------------------------------------------------------------------

/// A copy allele vector in COLUMN space: `col -> that copy's allele` (or `None`
/// when the copy has no allele at that bubble, mirroring `dict.get`). Built by
/// `copy_vecs[nm] = {j: bubbles[j]["hap"].get(nm) for j in range(len(bubbles))}`.
pub type CopyVec = BTreeMap<usize, Option<char>>;

/// Read-supported alleles per bubble: `col -> set(supported bases)`.
pub type Supported = BTreeMap<usize, BTreeSet<char>>;

/// Recombination kind (the copy-switch pattern class).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RecombKind {
    /// A single ordered switch `A..A|B..B` (1 switch).
    Crossover,
    /// A bounded reverting tract `A..A|B..B|A..A` (2 switches, `syms[0]==syms[-1]`).
    Conversion,
}

impl RecombKind {
    /// The Python `cand["type"]` string.
    pub fn as_str(&self) -> &'static str {
        match self {
            RecombKind::Crossover => "crossover",
            RecombKind::Conversion => "conversion",
        }
    }
}

/// The best recombinant split for one read (`detect_read_recombination`'s `cand`).
#[derive(Clone, Debug)]
pub struct Recombination {
    pub kind: RecombKind,
    pub a: String,
    pub b: String,
    /// `[(col, 'A'|'B')]` over bubbles where A,B differ and the read matches one.
    pub seq: Vec<(usize, char)>,
    pub imp: usize,
    pub switches: usize,
    pub bnd_idx: Vec<usize>,
    /// `[i1, i2-1]` for a conversion, `None` for a crossover.
    pub tract_idx: Option<(usize, usize)>,
    pub full_switches: usize,
    pub n_full_ab: usize,
    /// `int(full_switches == switches)` -- 1 iff no extra switch is hidden by
    /// dropping the copy-unsupported columns.
    pub clean_full: u8,
}

/// One copy node of the VG (only the name is needed by the abstain leg).
#[derive(Clone, Debug)]
pub struct VgCopy {
    pub name: String,
}

/// One PSV bubble (only the `hap` map `copy -> allele` is needed).
#[derive(Clone, Debug)]
pub struct VgBubble {
    pub hap: BTreeMap<String, char>,
}

/// One threaded read. `obs` is the RAW observed alleles `col -> base` (the ACGT
/// filter of `apply_abstain_to_vg` is applied by the leg, not stored here).
#[derive(Clone, Debug)]
pub struct VgRead {
    pub name: String,
    pub obs: BTreeMap<usize, char>,
    pub status: String,
    pub best_copy: Option<String>,
    /// Set to the pre-abstain status ONLY on a flipped read (else `None`).
    pub gate_status_pre_abstain: Option<String>,
    /// Set to the switch kind ONLY on a flipped read (else `None`).
    pub recombinant_kind: Option<String>,
}

/// The materialized family VG (subset the abstain leg reads/writes).
#[derive(Clone, Debug)]
pub struct FamilyVg {
    pub family: i64,
    pub copies: Vec<VgCopy>,
    pub bubbles: Vec<VgBubble>,
    pub reads: Vec<VgRead>,
    pub assignment: BTreeMap<String, i64>,
    pub per_copy: BTreeMap<String, i64>,
}

/// One flipped-read report record (an element of `apply_abstain_to_vg`'s return).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FlipRecord {
    pub family: i64,
    pub read: String,
    pub kind: String,
    pub copy_a: String,
    pub copy_b: String,
    pub switches: usize,
    pub clean_full: u8,
    pub prev_best: Option<String>,
}

// ===========================================================================
// per-read detection
// ===========================================================================

/// HONESTY LEG: switch count over ALL read-supported discriminating columns for
/// the chosen pair -- NOT just the both-copy-read-supported subset the split is
/// fit on. `spanned` is already restricted to columns where the READ base is
/// read-supported. Keeps every column where the two copies differ (`cvA != cvB`)
/// regardless of whether the copy allele is itself read-supported, classifies the
/// read A/B/neither, and counts switches on the A/B subsequence. Returns
/// `(full_switch_count, n_full_AB_cols)`.
/// Port of `bench/recombinant_abstain.py:82 full_pattern_switches`.
pub fn full_pattern_switches(
    spanned: &[usize],
    obs: &BTreeMap<usize, char>,
    cva: &CopyVec,
    cvb: &CopyVec,
) -> (usize, usize) {
    let mut syms: Vec<char> = Vec::new();
    for &c in spanned {
        let a = cva.get(&c).copied().flatten();
        let b = cvb.get(&c).copied().flatten();
        match (a, b) {
            (Some(a), Some(b)) if a != b => {
                let r = obs[&c];
                if r == a && r != b {
                    syms.push('A');
                } else if r == b && r != a {
                    syms.push('B');
                }
                // matches neither paired allele -> skip
            }
            _ => {}
        }
    }
    let sw = (1..syms.len()).filter(|&i| syms[i] != syms[i - 1]).count();
    (sw, syms.len())
}

/// The best recombinant split for one read, or `None`.
///
/// `obs[col] -> read base`; `supported[col] -> set of READ-supported alleles at
/// that bubble`; `copy_vecs[copy][col] -> that copy's allele`. Only bubbles whose
/// read base is a supported allele are used (`spanned`); a pair (A,B) may only
/// switch at cols where BOTH copies' alleles are read-supported. A recombinant =
/// NO single copy explains it (min single-copy mismatch >= `MIN_SINGLE_MM`) AND
/// some pair admits a PURE ordered A|B (or A|B|A) split with 1 or 2 switches.
///
/// Port of `bench/recombinant_abstain.py:106 detect_read_recombination`.
pub fn detect_read_recombination(
    obs: &BTreeMap<usize, char>,
    supported: &Supported,
    copy_vecs: &BTreeMap<String, CopyVec>,
    names: &[String],
) -> Option<Recombination> {
    let empty: BTreeSet<char> = BTreeSet::new();
    let sup_at = |c: usize| supported.get(&c).unwrap_or(&empty);

    // spanned = [c for c in sorted(obs) if obs[c] in supported.get(c, ())]
    // (obs is a BTreeMap -> iterated in sorted-key order == Python `sorted(obs)`).
    let spanned: Vec<usize> = obs
        .iter()
        .filter(|(c, b)| sup_at(**c).contains(*b))
        .map(|(c, _)| *c)
        .collect();
    if spanned.len() < MIN_INFO {
        return None;
    }

    // single-copy mismatch, counted only where the copy's own allele is
    // read-supported (fair comparison). If any single copy explains the read
    // within (MIN_SINGLE_MM - 1) mismatches -> not recombinant.
    let mut min_mm: usize = usize::MAX;
    for nm in names {
        let cv = &copy_vecs[nm];
        let mut mm = 0usize;
        for &c in &spanned {
            if let Some(base) = cv.get(&c).copied().flatten() {
                if sup_at(c).contains(&base) && obs[&c] != base {
                    mm += 1;
                }
            }
        }
        if mm < min_mm {
            min_mm = mm;
        }
    }
    if min_mm < MIN_SINGLE_MM {
        return None;
    }

    let mut best: Option<Recombination> = None;
    let mut best_key: Option<(usize, isize, usize, String, String)> = None;

    // itertools.combinations(names, 2) preserves list order: (i, j) with i < j.
    for i in 0..names.len() {
        for j in (i + 1)..names.len() {
            let a_name = &names[i];
            let b_name = &names[j];
            let cva = &copy_vecs[a_name];
            let cvb = &copy_vecs[b_name];

            let mut seq: Vec<(usize, char)> = Vec::new();
            let mut imp = 0usize;
            for &c in &spanned {
                let a = cva.get(&c).copied().flatten();
                let b = cvb.get(&c).copied().flatten();
                let sup = sup_at(c);
                match (a, b) {
                    (Some(a), Some(b)) if a != b && sup.contains(&a) && sup.contains(&b) => {
                        let r = obs[&c];
                        if r == a && r != b {
                            seq.push((c, 'A'));
                        } else if r == b && r != a {
                            seq.push((c, 'B'));
                        } else {
                            imp += 1; // matches neither paired allele
                        }
                    }
                    _ => {} // not a discriminating, read-supported bubble
                }
            }
            if imp > IMPURITY_MAX || seq.len() < MIN_INFO {
                continue;
            }
            let syms: Vec<char> = seq.iter().map(|&(_, s)| s).collect();
            let sw: Vec<usize> = (1..syms.len())
                .filter(|&k| syms[k] != syms[k - 1])
                .collect();

            let cand: Recombination = if sw.len() == 1 {
                let ii = sw[0];
                if ii.min(syms.len() - ii) < MIN_ARM {
                    continue;
                }
                Recombination {
                    kind: RecombKind::Crossover,
                    a: a_name.clone(),
                    b: b_name.clone(),
                    seq: seq.clone(),
                    imp,
                    switches: 1,
                    bnd_idx: vec![ii],
                    tract_idx: None,
                    full_switches: 0,
                    n_full_ab: 0,
                    clean_full: 0,
                }
            } else if sw.len() == 2 {
                let (i1, i2) = (sw[0], sw[1]);
                if syms[0] != syms[syms.len() - 1] {
                    continue; // must revert (X Y X)
                }
                let flank1 = i1;
                let tract = i2 - i1;
                let flank2 = syms.len() - i2;
                if flank1 < MIN_FLANK || flank2 < MIN_FLANK || tract < MIN_TRACT {
                    continue;
                }
                Recombination {
                    kind: RecombKind::Conversion,
                    a: a_name.clone(),
                    b: b_name.clone(),
                    seq: seq.clone(),
                    imp,
                    switches: 2,
                    bnd_idx: vec![i1, i2],
                    tract_idx: Some((i1, i2 - 1)),
                    full_switches: 0,
                    n_full_ab: 0,
                    clean_full: 0,
                }
            } else {
                continue;
            };

            // prefer fewer switches, then more informative bubbles, then less
            // impurity, then copy order (A, B copy-name strings byte-compared).
            let key = (cand.switches, -(seq.len() as isize), imp, a_name.clone(), b_name.clone());
            if best_key.as_ref().map_or(true, |bk| key.lt(bk)) {
                best = Some(cand);
                best_key = Some(key);
            }
        }
    }

    if let Some(mut b) = best {
        let cva = &copy_vecs[&b.a];
        let cvb = &copy_vecs[&b.b];
        let (full_sw, n_full) = full_pattern_switches(&spanned, obs, cva, cvb);
        b.full_switches = full_sw;
        b.n_full_ab = n_full;
        b.clean_full = u8::from(full_sw == b.switches);
        Some(b)
    } else {
        None
    }
}

// ===========================================================================
// reusable predicate
// ===========================================================================

/// Read-supported alleles per bubble (factored verbatim from `process_family`).
/// A base is supported iff its read-count >=
/// `max(ALLELE_SUPPORT_ABS, ALLELE_SUPPORT_FRAC * coverage)`. Drops asm20
/// copy-vector miscalls (a copy allele with ~0 read support) + singleton errors.
/// Port of `bench/recombinant_abstain.py:183 build_supported`.
pub fn build_supported(reads: &[VgRead], n_bubbles: usize) -> Supported {
    // pile[col][base] += 1 over ACGT read bases.
    let mut pile: BTreeMap<usize, BTreeMap<char, u64>> = BTreeMap::new();
    for r in reads {
        for (&k, &v) in &r.obs {
            if matches!(v, 'A' | 'C' | 'G' | 'T') {
                *pile.entry(k).or_default().entry(v).or_insert(0) += 1;
            }
        }
    }
    let mut supported: Supported = BTreeMap::new();
    for j in 0..n_bubbles {
        let counts = pile.get(&j);
        let cov: u64 = counts.map(|m| m.values().sum()).unwrap_or(0);
        // thr = max(3, 0.02 * cov). Comparing an integer count `n` to this f64 is
        // exact for `n < 2^53`, so `n as f64 >= thr` matches Python's `n >= thr`
        // whether `thr` is the int 3 or the float 0.02*cov.
        let thr = (ALLELE_SUPPORT_FRAC * cov as f64).max(ALLELE_SUPPORT_ABS as f64);
        let mut s: BTreeSet<char> = BTreeSet::new();
        if let Some(m) = counts {
            for (&b, &n) in m {
                if n as f64 >= thr {
                    s.insert(b);
                }
            }
        }
        supported.insert(j, s);
    }
    supported
}

/// The reusable recombinant predicate. `None` == Python `(False, None, None)`;
/// `Some(rec)` == `(True, rec.kind, arms)` where `arms` = the copy pair + the
/// colinear arms (`a`, `b`, `switches`, `clean_full`, `seq`). A thin wrapper over
/// [`detect_read_recombination`] -- the SAME test the diagnostic detector uses.
/// Port of `bench/recombinant_abstain.py:201 is_recombinant`.
pub fn is_recombinant(
    obs: &BTreeMap<usize, char>,
    supported: &Supported,
    copy_vecs: &BTreeMap<String, CopyVec>,
    names: &[String],
) -> Option<Recombination> {
    detect_read_recombination(obs, supported, copy_vecs, names)
}

// ===========================================================================
// the gate leg
// ===========================================================================

/// DEFAULT-ON recombinant-abstain leg over a materialized family VG.
///
/// For every read the significance gate currently ASSIGNS (`status == "assigned"`)
/// that [`is_recombinant`], relabel `status -> "recombinant"` (abstain), record the
/// pre-abstain gate call in `gate_status_pre_abstain` and the switch kind in
/// `recombinant_kind`, and drop `best_copy`. A PURE MONOTONE ADDITION OF
/// ABSTENTIONS: non-recombinant reads and already-abstaining reads are left
/// bit-for-bit unchanged; only force-assigned recombinant reads change. The
/// `assignment` and `per_copy` summary counters are kept consistent (each flipped
/// read is moved out of `assigned` and out of its copy's quant into `recombinant`).
///
/// Returns one [`FlipRecord`] per flipped read (empty when disabled or no leaks).
/// No-op (returns `[]`) when `RUSTLE_NO_RECOMBINANT_ABSTAIN=1`, or when the VG has
/// `< 2` copies or `< 2` bubbles.
/// Port of `bench/recombinant_abstain.py:221 apply_abstain_to_vg`.
pub fn apply_abstain_to_vg(vg: &mut FamilyVg) -> Vec<FlipRecord> {
    if !abstain_enabled() {
        return Vec::new();
    }
    let names: Vec<String> = vg.copies.iter().map(|c| c.name.clone()).collect();
    let n_bubbles = vg.bubbles.len();
    if names.len() < 2 || n_bubbles < 2 {
        return Vec::new();
    }

    // copy_vecs[nm] = {j: bubbles[j]["hap"].get(nm) for j in range(len(bubbles))}
    let mut copy_vecs: BTreeMap<String, CopyVec> = BTreeMap::new();
    for nm in &names {
        let mut cv: CopyVec = BTreeMap::new();
        for j in 0..n_bubbles {
            cv.insert(j, vg.bubbles[j].hap.get(nm).copied());
        }
        copy_vecs.insert(nm.clone(), cv);
    }
    let supported = build_supported(&vg.reads, n_bubbles);

    // Split the borrow of the distinct VG fields so the read loop can mutate the
    // reads AND the summary counters simultaneously.
    let family = vg.family;
    let reads = &mut vg.reads;
    let assignment = &mut vg.assignment;
    let per_copy = &mut vg.per_copy;

    let mut flipped: Vec<FlipRecord> = Vec::new();
    for r in reads.iter_mut() {
        if r.status != "assigned" {
            continue; // only ADD abstentions on force-assigned reads
        }
        // obs = {int(k): v for k, v in r["obs"].items() if v in "ACGT"}
        let mut obs: BTreeMap<usize, char> = BTreeMap::new();
        for (&k, &v) in &r.obs {
            if matches!(v, 'A' | 'C' | 'G' | 'T') {
                obs.insert(k, v);
            }
        }
        if obs.len() < MIN_INFO {
            continue;
        }
        let cand = match is_recombinant(&obs, &supported, &copy_vecs, &names) {
            Some(c) => c,
            None => continue,
        };
        let prev_best = r.best_copy.clone();
        flipped.push(FlipRecord {
            family,
            read: r.name.clone(),
            kind: cand.kind.as_str().to_string(),
            copy_a: cand.a.clone(),
            copy_b: cand.b.clone(),
            switches: cand.switches,
            clean_full: cand.clean_full,
            prev_best: prev_best.clone(),
        });
        r.gate_status_pre_abstain = Some(r.status.clone());
        r.recombinant_kind = Some(cand.kind.as_str().to_string());
        r.status = ABSTAIN_STATUS.to_string();
        r.best_copy = None;
        // keep the summary counters consistent (get-with-default 0, like Python).
        *assignment.entry("assigned".to_string()).or_insert(0) -= 1;
        *assignment.entry(ABSTAIN_STATUS.to_string()).or_insert(0) += 1;
        if let Some(pb) = &prev_best {
            if let Some(v) = per_copy.get_mut(pb) {
                *v -= 1;
            }
        }
    }
    flipped
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;
    use std::sync::Mutex;

    // Only the two env-touching tests below read/mutate OPTOUT_ENV; serialize them so
    // one never runs while the other has the env in the opposite state. No other test
    // reads this env.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    fn load_fixture() -> Value {
        let raw = include_str!("testdata/recombinant_abstain_fixture.json");
        serde_json::from_str(raw).expect("parse recombinant_abstain fixture json")
    }

    // ------------------------------------------------------------- json -> types
    fn base_of(v: &Value) -> char {
        v.as_str().unwrap().chars().next().unwrap()
    }
    fn parse_obs(v: &Value) -> BTreeMap<usize, char> {
        v.as_object()
            .unwrap()
            .iter()
            .map(|(k, b)| (k.parse::<usize>().unwrap(), base_of(b)))
            .collect()
    }
    fn parse_supported(v: &Value) -> Supported {
        v.as_object()
            .unwrap()
            .iter()
            .map(|(k, arr)| {
                let set: BTreeSet<char> = arr.as_array().unwrap().iter().map(base_of).collect();
                (k.parse::<usize>().unwrap(), set)
            })
            .collect()
    }
    fn parse_copy_vecs(v: &Value) -> BTreeMap<String, CopyVec> {
        v.as_object()
            .unwrap()
            .iter()
            .map(|(nm, cols)| {
                let cv: CopyVec = cols
                    .as_object()
                    .unwrap()
                    .iter()
                    .map(|(c, b)| {
                        let base = if b.is_null() { None } else { Some(base_of(b)) };
                        (c.parse::<usize>().unwrap(), base)
                    })
                    .collect();
                (nm.clone(), cv)
            })
            .collect()
    }
    fn parse_names(v: &Value) -> Vec<String> {
        v.as_array()
            .unwrap()
            .iter()
            .map(|s| s.as_str().unwrap().to_string())
            .collect()
    }
    fn parse_counter(v: &Value) -> BTreeMap<String, i64> {
        v.as_object()
            .unwrap()
            .iter()
            .map(|(k, n)| (k.clone(), n.as_i64().unwrap()))
            .collect()
    }
    fn parse_vg(v: &Value) -> FamilyVg {
        let copies = v["copies"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| VgCopy { name: c["name"].as_str().unwrap().to_string() })
            .collect();
        let bubbles = v["bubbles"]
            .as_array()
            .unwrap()
            .iter()
            .map(|b| {
                let hap = b["hap"]
                    .as_object()
                    .unwrap()
                    .iter()
                    .map(|(n, base)| (n.clone(), base_of(base)))
                    .collect();
                VgBubble { hap }
            })
            .collect();
        let reads = v["reads"]
            .as_array()
            .unwrap()
            .iter()
            .map(|r| VgRead {
                name: r["name"].as_str().unwrap().to_string(),
                obs: parse_obs(&r["obs"]),
                status: r["status"].as_str().unwrap().to_string(),
                best_copy: r["best_copy"].as_str().map(|s| s.to_string()),
                gate_status_pre_abstain: None,
                recombinant_kind: None,
            })
            .collect();
        FamilyVg {
            family: v["family"].as_i64().unwrap(),
            copies,
            bubbles,
            reads,
            assignment: parse_counter(&v["assignment"]),
            per_copy: parse_counter(&v["per_copy"]),
        }
    }

    /// Compare a `detect_read_recombination` result to the fixture `expect` (null or
    /// the load-bearing output fields). Returns Err(reason) on the first mismatch.
    fn check_detect(got: &Option<Recombination>, expect: &Value) -> Result<(), String> {
        if expect.is_null() {
            return match got {
                None => Ok(()),
                Some(r) => Err(format!("expected None, got {:?}", r.kind)),
            };
        }
        let r = match got {
            Some(r) => r,
            None => return Err("expected a recombination, got None".to_string()),
        };
        if r.kind.as_str() != expect["type"].as_str().unwrap() {
            return Err(format!("type {} != {}", r.kind.as_str(), expect["type"]));
        }
        if r.a != expect["A"].as_str().unwrap() {
            return Err(format!("A {} != {}", r.a, expect["A"]));
        }
        if r.b != expect["B"].as_str().unwrap() {
            return Err(format!("B {} != {}", r.b, expect["B"]));
        }
        if r.switches as u64 != expect["switches"].as_u64().unwrap() {
            return Err(format!("switches {} != {}", r.switches, expect["switches"]));
        }
        if r.clean_full as u64 != expect["clean_full"].as_u64().unwrap() {
            return Err(format!("clean_full {} != {}", r.clean_full, expect["clean_full"]));
        }
        if r.full_switches as u64 != expect["full_switches"].as_u64().unwrap() {
            return Err(format!("full_switches {} != {}", r.full_switches, expect["full_switches"]));
        }
        if r.n_full_ab as u64 != expect["n_full_ab"].as_u64().unwrap() {
            return Err(format!("n_full_ab {} != {}", r.n_full_ab, expect["n_full_ab"]));
        }
        if r.imp as u64 != expect["imp"].as_u64().unwrap() {
            return Err(format!("imp {} != {}", r.imp, expect["imp"]));
        }
        let eseq = expect["seq"].as_array().unwrap();
        if r.seq.len() != eseq.len() {
            return Err(format!("seq len {} != {}", r.seq.len(), eseq.len()));
        }
        for (i, (got_pair, want)) in r.seq.iter().zip(eseq).enumerate() {
            let wcol = want[0].as_u64().unwrap() as usize;
            let wsym = base_of(&want[1]);
            if got_pair.0 != wcol || got_pair.1 != wsym {
                return Err(format!("seq[{i}] ({},{}) != ({wcol},{wsym})", got_pair.0, got_pair.1));
            }
        }
        Ok(())
    }

    // ----------------------------------------------------------------- constants

    #[test]
    fn constants_match_python() {
        let fx = load_fixture();
        let t = &fx["thresholds"];
        assert_eq!(t["MIN_INFO"].as_u64().unwrap() as usize, MIN_INFO);
        assert_eq!(t["MIN_ARM"].as_u64().unwrap() as usize, MIN_ARM);
        assert_eq!(t["MIN_FLANK"].as_u64().unwrap() as usize, MIN_FLANK);
        assert_eq!(t["MIN_TRACT"].as_u64().unwrap() as usize, MIN_TRACT);
        assert_eq!(t["MIN_SINGLE_MM"].as_u64().unwrap() as usize, MIN_SINGLE_MM);
        assert_eq!(t["IMPURITY_MAX"].as_u64().unwrap() as usize, IMPURITY_MAX);
        assert_eq!(t["ALLELE_SUPPORT_ABS"].as_u64().unwrap() as u32, ALLELE_SUPPORT_ABS);
        assert_eq!(t["ALLELE_SUPPORT_FRAC"].as_f64().unwrap(), ALLELE_SUPPORT_FRAC);
        assert_eq!(t["OPTOUT_ENV"].as_str().unwrap(), OPTOUT_ENV);
        assert_eq!(t["ABSTAIN_STATUS"].as_str().unwrap(), ABSTAIN_STATUS);
        assert_eq!((MIN_INFO, MIN_ARM, MIN_FLANK, MIN_TRACT, MIN_SINGLE_MM, IMPURITY_MAX), (4, 2, 2, 2, 2, 1));
    }

    // ----------------------------------------------------------------- detect parity

    /// `detect_read_recombination` == Python EXACTLY on every detection case
    /// (type/A/B/switches/clean_full/full_switches/n_full_ab/imp/seq). Reports the
    /// first mismatch. Covers crossover, conversion, clean_full 0/1, the non-recombinant
    /// branches, and the >=2-pair tie-break.
    #[test]
    fn detect_read_recombination_parity() {
        let fx = load_fixture();
        let cases = fx["detection_cases"].as_array().expect("detection_cases");
        assert!(cases.len() >= 200, "want >= 200 detection cases, got {}", cases.len());
        let (mut n_cross, mut n_conv, mut n_none, mut n_c0, mut n_c1, mut n_syn) = (0, 0, 0, 0, 0, 0);
        for case in cases {
            let label = case["label"].as_str().unwrap();
            let names = parse_names(&case["names"]);
            let obs = parse_obs(&case["obs"]);
            let supported = parse_supported(&case["supported"]);
            let copy_vecs = parse_copy_vecs(&case["copy_vecs"]);
            let got = detect_read_recombination(&obs, &supported, &copy_vecs, &names);
            if let Err(why) = check_detect(&got, &case["expect"]) {
                panic!("detect mismatch on case '{label}': {why}");
            }
            // is_recombinant is the same predicate -> must agree case-by-case
            let ir = is_recombinant(&obs, &supported, &copy_vecs, &names);
            assert_eq!(ir.is_some(), got.is_some(), "is_recombinant disagrees on '{label}'");
            if case["expect"].is_null() {
                n_none += 1;
            } else {
                match case["expect"]["type"].as_str().unwrap() {
                    "crossover" => n_cross += 1,
                    "conversion" => n_conv += 1,
                    _ => {}
                }
                match case["expect"]["clean_full"].as_u64().unwrap() {
                    0 => n_c0 += 1,
                    _ => n_c1 += 1,
                }
            }
            if label.starts_with("syn_") {
                n_syn += 1;
            }
        }
        assert!(n_cross >= 5, "want crossover cases, got {n_cross}");
        assert!(n_conv >= 5, "want conversion cases, got {n_conv}");
        assert!(n_none >= 10, "want None cases, got {n_none}");
        assert!(n_c0 >= 5 && n_c1 >= 5, "want clean_full 0 and 1 cases, got {n_c0}/{n_c1}");
        assert!(n_syn >= 10, "want synthetic boundary cases, got {n_syn}");
        eprintln!(
            "detect parity: {} cases identical (crossover={n_cross} conversion={n_conv} none={n_none} clean_full0={n_c0} clean_full1={n_c1} synthetic={n_syn})",
            cases.len()
        );
    }

    // ----------------------------------------------------------------- build_supported parity

    #[test]
    fn build_supported_parity() {
        let fx = load_fixture();
        // (a) dedicated synthetic cases (frac-vs-abs threshold boundary)
        let cases = fx["build_supported_cases"].as_array().expect("build_supported_cases");
        assert!(!cases.is_empty());
        for case in cases {
            let label = case["label"].as_str().unwrap();
            let n_bubbles = case["n_bubbles"].as_u64().unwrap() as usize;
            let reads: Vec<VgRead> = case["reads"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| VgRead {
                    name: String::new(),
                    obs: parse_obs(&r["obs"]),
                    status: String::new(),
                    best_copy: None,
                    gate_status_pre_abstain: None,
                    recombinant_kind: None,
                })
                .collect();
            let got = build_supported(&reads, n_bubbles);
            let want = parse_supported(&case["expected"]);
            assert_eq!(got, want, "build_supported mismatch on synthetic case '{label}'");
        }
        // (b) the whole-VG read piles: build_supported(vg.reads) == the stored supported
        let mut n_real = 0;
        for vgv in fx["vgs"].as_array().unwrap() {
            let vg = parse_vg(vgv);
            if vg.bubbles.len() < 2 {
                continue;
            }
            let got = build_supported(&vg.reads, vg.bubbles.len());
            let want = parse_supported(&vgv["expect_supported"]);
            assert_eq!(got, want, "build_supported mismatch on VG fam {}", vg.family);
            n_real += 1;
        }
        eprintln!("build_supported parity: {} synthetic + {} real family piles identical", cases.len(), n_real);
    }

    // ----------------------------------------------------------------- apply_abstain parity

    /// `apply_abstain_to_vg` == Python on every whole VG: the flipped list (order +
    /// every field), the post-abstain per-read status/best_copy/gate_status_pre_abstain/
    /// recombinant_kind, and the post assignment/per_copy counters. Also asserts the
    /// MONOTONE property: only 'assigned'->'recombinant' reads change; everything else
    /// is bit-for-bit unchanged. Reports the first mismatch.
    #[test]
    fn apply_abstain_parity() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::remove_var(OPTOUT_ENV); // DEFAULT-ON
        assert!(abstain_enabled());

        let fx = load_fixture();
        let vgs = fx["vgs"].as_array().expect("vgs");
        let (mut n_flip_vgs, mut n_noflip_vgs, mut total_flips) = (0usize, 0usize, 0usize);
        for vgv in vgs {
            let mut vg = parse_vg(vgv);
            let pre = vg.clone(); // to verify the MONOTONE property
            let flipped = apply_abstain_to_vg(&mut vg);

            // (1) flipped list == expect_flipped (order + fields)
            let want_flipped = vgv["expect_flipped"].as_array().unwrap();
            assert_eq!(
                flipped.len(),
                want_flipped.len(),
                "fam {}: flip count {} != {}",
                vg.family,
                flipped.len(),
                want_flipped.len()
            );
            for (i, (g, w)) in flipped.iter().zip(want_flipped).enumerate() {
                assert_eq!(g.family, w["family"].as_i64().unwrap(), "fam {} flip[{i}] family", vg.family);
                assert_eq!(g.read, w["read"].as_str().unwrap(), "fam {} flip[{i}] read", vg.family);
                assert_eq!(g.kind, w["kind"].as_str().unwrap(), "fam {} flip[{i}] kind ({})", vg.family, g.read);
                assert_eq!(g.copy_a, w["copyA"].as_str().unwrap(), "fam {} flip[{i}] copyA ({})", vg.family, g.read);
                assert_eq!(g.copy_b, w["copyB"].as_str().unwrap(), "fam {} flip[{i}] copyB ({})", vg.family, g.read);
                assert_eq!(g.switches as u64, w["switches"].as_u64().unwrap(), "fam {} flip[{i}] switches ({})", vg.family, g.read);
                assert_eq!(g.clean_full as u64, w["clean_full"].as_u64().unwrap(), "fam {} flip[{i}] clean_full ({})", vg.family, g.read);
                assert_eq!(g.prev_best.as_deref(), w["prev_best"].as_str(), "fam {} flip[{i}] prev_best ({})", vg.family, g.read);
            }

            // (2) post-abstain per-read fields == expect_reads
            let want_reads = vgv["expect_reads"].as_array().unwrap();
            assert_eq!(vg.reads.len(), want_reads.len(), "fam {}: read count", vg.family);
            let mut changed = 0;
            for (i, (r, w)) in vg.reads.iter().zip(want_reads).enumerate() {
                assert_eq!(r.name, w["name"].as_str().unwrap(), "fam {} read[{i}] name", vg.family);
                assert_eq!(r.status, w["status"].as_str().unwrap(), "fam {} read[{i}] status ({})", vg.family, r.name);
                assert_eq!(r.best_copy.as_deref(), w["best_copy"].as_str(), "fam {} read[{i}] best_copy ({})", vg.family, r.name);
                assert_eq!(
                    r.gate_status_pre_abstain.as_deref(),
                    w["gate_status_pre_abstain"].as_str(),
                    "fam {} read[{i}] gate_status_pre_abstain ({})",
                    vg.family,
                    r.name
                );
                assert_eq!(
                    r.recombinant_kind.as_deref(),
                    w["recombinant_kind"].as_str(),
                    "fam {} read[{i}] recombinant_kind ({})",
                    vg.family,
                    r.name
                );
                // MONOTONE: a read changed status iff it was flipped assigned->recombinant.
                let pr = &pre.reads[i];
                if r.status != pr.status {
                    assert_eq!(pr.status, "assigned", "fam {}: only assigned reads may flip ({})", vg.family, r.name);
                    assert_eq!(r.status, ABSTAIN_STATUS, "fam {}: flipped read must be recombinant ({})", vg.family, r.name);
                    changed += 1;
                } else {
                    // unchanged status => the read is bit-for-bit unchanged
                    assert_eq!(r.best_copy, pr.best_copy, "fam {}: non-flipped best_copy changed ({})", vg.family, r.name);
                    assert!(r.gate_status_pre_abstain.is_none() && r.recombinant_kind.is_none(),
                        "fam {}: non-flipped read got abstain fields ({})", vg.family, r.name);
                }
            }
            assert_eq!(changed, flipped.len(), "fam {}: #status-changed != #flipped", vg.family);

            // (3) post assignment / per_copy counters
            assert_eq!(vg.assignment, parse_counter(&vgv["expect_assignment"]), "fam {}: assignment", vg.family);
            assert_eq!(vg.per_copy, parse_counter(&vgv["expect_per_copy"]), "fam {}: per_copy", vg.family);

            total_flips += flipped.len();
            if flipped.is_empty() {
                n_noflip_vgs += 1;
            } else {
                n_flip_vgs += 1;
            }
        }
        assert!(n_flip_vgs >= 3, "want >= 3 flipping VGs, got {n_flip_vgs}");
        assert!(n_noflip_vgs >= 2, "want >= 2 non-flipping VGs, got {n_noflip_vgs}");
        eprintln!(
            "apply_abstain parity: {} VGs identical ({n_flip_vgs} flip, {n_noflip_vgs} no-flip; {total_flips} total reads abstained)",
            vgs.len()
        );
    }

    // ----------------------------------------------------------------- opt-out no-op

    #[test]
    fn optout_is_a_noop() {
        let _guard = ENV_LOCK.lock().unwrap();
        // enabled/disabled recognition
        std::env::remove_var(OPTOUT_ENV);
        assert!(abstain_enabled(), "unset env -> enabled");
        for v in ["1", "true", "True", "TRUE"] {
            std::env::set_var(OPTOUT_ENV, v);
            assert!(!abstain_enabled(), "env={v} -> disabled");
        }
        for v in ["0", "no", "2", ""] {
            std::env::set_var(OPTOUT_ENV, v);
            assert!(abstain_enabled(), "env={v:?} -> enabled");
        }

        // pick a VG that flips reads when enabled; disabled -> [] and VG unchanged.
        let fx = load_fixture();
        let flipper = fx["vgs"]
            .as_array()
            .unwrap()
            .iter()
            .find(|v| !v["expect_flipped"].as_array().unwrap().is_empty())
            .expect("a flipping VG in the fixture");
        let before = parse_vg(flipper);

        std::env::set_var(OPTOUT_ENV, "1");
        let mut vg = parse_vg(flipper);
        let flipped = apply_abstain_to_vg(&mut vg);
        assert!(flipped.is_empty(), "disabled leg must return []");
        // bit-for-bit unchanged: statuses, best_copy, counters
        for (r, b) in vg.reads.iter().zip(&before.reads) {
            assert_eq!(r.status, b.status);
            assert_eq!(r.best_copy, b.best_copy);
            assert!(r.gate_status_pre_abstain.is_none() && r.recombinant_kind.is_none());
        }
        assert_eq!(vg.assignment, before.assignment);
        assert_eq!(vg.per_copy, before.per_copy);

        std::env::remove_var(OPTOUT_ENV); // restore default-ON for other tests
        eprintln!("opt-out no-op verified: RUSTLE_NO_RECOMBINANT_ABSTAIN=1 -> [] and byte-identical VG");
    }
}
