//! Node-multiplicity REPEAT CATALOG -- faithful Rust port of the catalog-production
//! core of `bench/vg_repeat_catalog.py` (the O1 over-merge-gate migration,
//! `docs/RETIREMENT_AND_MIGRATION.md` Tier-2 #7, full-port path).
//!
//! This is the piece the repeat-bridge GATE consumes at runtime: per canonical
//! (k,w)-minimizer NODE it produces `multiplicity` (# distinct genes carrying the
//! node), the `cyclic`/`is_repeat` flags, `n_transcripts`, and `softmask_frac`.
//! The gate's keep/cut decision uses the fixed `M_OP = 5` threshold on the node
//! multiplicities (a family edge is CUT iff every shared node has multiplicity
//! `>= M_OP`); this module builds exactly those multiplicities.
//!
//! PORTED (the Python is ground truth; line refs are `bench/vg_repeat_catalog.py`):
//!   * `load_skeletons`  (:80)  -> `parse_skeletons` / `load_skeletons`;
//!   * `dn_exons`        (:90)  -> `dn_exons` (intron -> exon COMPLEMENT + coord convention);
//!   * the VG build loop (:245-289) + node-section output (:598-604) -> `NodeCatalog`.
//!   * `minimizers` is REUSED from `super::minimizers` (already byte-exact, commit 18adb6e).
//!
//! DEFERRED (NOT gate-runtime -- calibration/evaluation, see the report):
//!   * the `M_GRID` masking-oracle sweep (:397), the `KFOLDS` component CV (:431-478),
//!     and the "# SECTION edges (eval population)" block (:605-618). Those select /
//!     report `M_OP` and compute AUC / tp_recall / genuine_cut_rate against the DNA
//!     truth population; the gate consumes the FIXED `M_OP = 5` + these node
//!     multiplicities, not the CV.
//!
//! GENOME ACCESS: `GenomeIndex` (`genome.rs`) UPPERCASES bases, which would destroy
//! the soft-mask (lowercase) that `minimizers` reads for `softmask_frac`; so this
//! module carries a minimal CASE-CARRYING indexed-FASTA reader (`IndexedFasta`) that
//! returns the reference bytes verbatim, exactly like `pysam.FastaFile.fetch`.
//!
//! Verified byte-identical to the shipped Python against a golden fixture
//! (`testdata/repeat_catalog_fixture.json`, generated by
//! `bench/gen_repeat_catalog_fixture.py`, PYTHONHASHSEED=0); see the `#[test]`s.

use std::collections::{HashMap, HashSet};
use std::fs::File;
use std::io;
use std::os::unix::fs::FileExt;

use super::minimizers::{minimizers, MINIMIZER_K, MINIMIZER_W};

/// Headline operating multiplicity threshold. `bench/vg_repeat_catalog.py:72  M_OP = 5`.
/// A node is a library-free REPEAT iff `multiplicity >= M_OP` OR it is `cyclic`; the
/// repeat-bridge gate CUTS a family edge iff every shared node is a repeat at `M_OP`.
pub const M_OP: usize = 5;

// ===========================================================================
// load_skeletons  (bench/vg_repeat_catalog.py:80)
// ===========================================================================

/// Parse the denovo-skeletons TSV text into `{(chrom, start, end) -> introns_string}`.
///
/// Faithful port of `load_skeletons`: skips the header row (`next(fh)`), keys on the
/// first three tab fields `(f[0], int(f[1]), int(f[2]))`, value = the `introns` field
/// `f[5]` (empty string for single-exon skeletons). Columns:
/// `chrom  start  end  n_exon  n_reads  introns`.
pub fn parse_skeletons(text: &str) -> HashMap<(String, i64, i64), String> {
    let mut skel = HashMap::new();
    let mut lines = text.lines();
    lines.next(); // header
    for ln in lines {
        // Python: f = ln.rstrip("\n").split("\t"); skel[(f0,int f1,int f2)] = f5
        let f: Vec<&str> = ln.split('\t').collect();
        if f.len() < 6 {
            continue; // well-formed rows always carry 6 cols (introns may be empty)
        }
        let start: i64 = match f[1].parse() {
            Ok(v) => v,
            Err(_) => continue,
        };
        let end: i64 = match f[2].parse() {
            Ok(v) => v,
            Err(_) => continue,
        };
        skel.insert((f[0].to_string(), start, end), f[5].to_string());
    }
    skel
}

/// Read + parse the denovo-skeletons TSV file (see `parse_skeletons`).
pub fn load_skeletons(path: &str) -> io::Result<HashMap<(String, i64, i64), String>> {
    Ok(parse_skeletons(&std::fs::read_to_string(path)?))
}

// ===========================================================================
// dn_exons  (bench/vg_repeat_catalog.py:90)
// ===========================================================================

/// Reconstruct a de-novo locus's `(chrom, exons)` from its meta coords + skeleton
/// introns (exons = the COMPLEMENT of the introns within `[start, end)`).
///
/// Faithful port of `dn_exons`:
///   * `meta.get(dn)` miss  -> `None` (Python `(None, None)`);
///   * skeleton key absent  -> `Some((chrom, [(start, end)]))` (single exon);
///   * else parse `"a-b;c-d;..."` into intervals, SORT them, and walk the complement:
///     `cur = start`; for each `(a, b)` push `(cur, a)` iff `a > cur`, then `cur = b`;
///     finally push `(cur, end)` iff `end > cur`.
///
/// The blank-introns skeleton (`introns == ""`) and the missing-skeleton case both
/// yield a single `[(start, end)]` exon but via the two distinct Python branches.
pub fn dn_exons(
    dn: &str,
    meta: &HashMap<String, (String, i64, i64)>,
    skel: &HashMap<(String, i64, i64), String>,
) -> Option<(String, Vec<(i64, i64)>)> {
    let (chrom, start, end) = match meta.get(dn) {
        None => return None,
        Some(t) => (t.0.clone(), t.1, t.2),
    };
    let introns = match skel.get(&(chrom.clone(), start, end)) {
        None => return Some((chrom, vec![(start, end)])),
        Some(s) => s,
    };
    let mut iv: Vec<(i64, i64)> = Vec::new();
    if !introns.trim().is_empty() {
        for tok in introns.split(';') {
            // Python: a, b = tok.split("-")
            let mut it = tok.split('-');
            let a: i64 = it
                .next()
                .expect("intron token has a left field")
                .parse()
                .expect("intron start parses");
            let b: i64 = it
                .next()
                .expect("intron token has a right field")
                .parse()
                .expect("intron end parses");
            iv.push((a, b));
        }
    }
    iv.sort();
    let mut exons: Vec<(i64, i64)> = Vec::new();
    let mut cur = start;
    for (a, b) in iv {
        if a > cur {
            exons.push((cur, a));
        }
        cur = b;
    }
    if end > cur {
        exons.push((cur, end));
    }
    Some((chrom, exons))
}

// ===========================================================================
// Case-carrying indexed FASTA (pysam.FastaFile.fetch equivalent)
// ===========================================================================

#[derive(Clone, Copy, Debug)]
struct FaiRecord {
    length: u64,
    offset: u64,
    linebases: u64,
    linewidth: u64,
}

/// Minimal `.fai`-indexed FASTA reader returning bytes VERBATIM (soft-mask lowercase
/// preserved), matching `pysam.FastaFile.fetch(chrom, start, end)` on 0-based
/// half-open coordinates. Needed because `genome.rs::GenomeIndex` upper-cases and so
/// cannot feed the `softmask_frac` computation.
pub struct IndexedFasta {
    file: File,
    index: HashMap<String, FaiRecord>,
}

impl IndexedFasta {
    /// Open `path` and read its `path.fai` sidecar
    /// (`name \t length \t offset \t linebases \t linewidth`).
    pub fn open(path: &str) -> io::Result<Self> {
        let fai_text = std::fs::read_to_string(format!("{}.fai", path))?;
        let mut index = HashMap::new();
        for line in fai_text.lines() {
            let f: Vec<&str> = line.split('\t').collect();
            if f.len() < 5 {
                continue;
            }
            let rec = FaiRecord {
                length: f[1].parse().unwrap_or(0),
                offset: f[2].parse().unwrap_or(0),
                linebases: f[3].parse().unwrap_or(0),
                linewidth: f[4].parse().unwrap_or(0),
            };
            if rec.linebases == 0 || rec.linewidth == 0 {
                continue;
            }
            index.insert(f[0].to_string(), rec);
        }
        let file = File::open(path)?;
        Ok(Self { file, index })
    }

    /// Fetch `[start, end)` (0-based half-open) verbatim, or `None` if the contig is
    /// unknown. An empty/degenerate interval yields `Some(vec![])` (pysam returns "").
    /// Bytes are read straight from the file at their `.fai`-computed offsets, skipping
    /// the per-line newline, so lowercase soft-mask is preserved exactly.
    pub fn fetch(&self, chrom: &str, start: i64, end: i64) -> Option<Vec<u8>> {
        let rec = self.index.get(chrom)?;
        let mut s = start.max(0) as u64;
        let mut e = end.max(0) as u64;
        if e > rec.length {
            e = rec.length;
        }
        if s > rec.length {
            s = rec.length;
        }
        if s >= e {
            return Some(Vec::new());
        }
        let mut out = Vec::with_capacity((e - s) as usize);
        let (lb, lw) = (rec.linebases, rec.linewidth);
        let mut p = s;
        while p < e {
            let line = p / lb;
            let col = p % lb;
            let byte_off = rec.offset + line * lw + col;
            let take = std::cmp::min(lb - col, e - p); // bases left on this line
            let mut buf = vec![0u8; take as usize];
            self.file.read_exact_at(&mut buf, byte_off).ok()?;
            out.extend_from_slice(&buf);
            p += take;
        }
        Some(out)
    }
}

/// Concatenate a locus's exon slices into its spliced, case-carrying sequence
/// (`"".join(fa.fetch(chrom, a, b) for a, b in exons)`). `None` iff any fetch fails
/// (Python's `try/except` around the join -> the locus is skipped).
pub fn locus_exon_sequence(
    fa: &IndexedFasta,
    chrom: &str,
    exons: &[(i64, i64)],
) -> Option<Vec<u8>> {
    let mut s = Vec::new();
    for &(a, b) in exons {
        let part = fa.fetch(chrom, a, b)?;
        s.extend_from_slice(&part);
    }
    Some(s)
}

// ===========================================================================
// Node-multiplicity catalog  (build loop :245-289 + node section :598-604)
// ===========================================================================

/// One "# SECTION nodes (mult>=2)" output row.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NodeRow {
    /// canonical (k,w)-minimizer value (`node_id`)
    pub node_id: u64,
    /// `multiplicity` = # DISTINCT GENES whose node set contains this node
    pub multiplicity: usize,
    /// `n_genes` -- the Python writes `mult[c]` a second time in this column
    pub n_genes: usize,
    /// `cyclic` -- the node recurs (>= 2 runs) within a single transcript
    pub cyclic: bool,
    /// `is_repeat_m{M_OP}` = `multiplicity >= M_OP` OR `cyclic`
    pub is_repeat: bool,
    /// `n_transcripts` = # transcripts (loci) carrying the node
    pub n_transcripts: usize,
    /// masked-run occurrences (numerator of `softmask_frac`)
    pub softmask_num: u64,
    /// total-run occurrences (denominator of `softmask_frac`)
    pub softmask_den: u64,
}

impl NodeRow {
    /// `softmask_frac` as the raw ratio (unrounded).
    pub fn softmask_frac(&self) -> f64 {
        if self.softmask_den == 0 {
            0.0
        } else {
            self.softmask_num as f64 / self.softmask_den as f64
        }
    }

    /// The exact TSV line Python writes (fields `\t`-joined, no trailing newline).
    pub fn to_tsv(&self) -> String {
        format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            self.node_id,
            self.multiplicity,
            self.n_genes,
            self.cyclic as u8,
            self.is_repeat as u8,
            self.n_transcripts,
            format_softmask(self.softmask_num, self.softmask_den),
        )
    }
}

/// `round(num/den, 4)` formatted exactly as Python `str(float)` (drops trailing
/// zeros, always keeps `".0"`). Rounds the actual `f64` (NOT the rational a/b): for
/// these dyadic doubles no exact 4-decimal tie exists, so Rust's correctly-rounded
/// `{:.4}` matches Python's `format(x, ".4f")`, which equals `str(round(x, 4))`
/// after stripping (verified over all num/den <= 1200). `den == 0` -> `"0.0"`
/// (Python `node_sm.get(c, 0.0)`).
fn format_softmask(num: u64, den: u64) -> String {
    if den == 0 {
        return "0.0".to_string();
    }
    let x = num as f64 / den as f64;
    let s = format!("{:.4}", x); // correctly-rounded 4-decimal, e.g. "0.0063","0.5000","1.0000"
    let trimmed = s.trim_end_matches('0');
    if trimmed.ends_with('.') {
        format!("{}0", trimmed)
    } else {
        trimmed.to_string()
    }
}

/// The canonical-minimizer node-multiplicity catalog over a universe of loci.
///
/// Faithful port of the VG build loop (`:245-289`): each locus contributes its GENE
/// label and its case-carrying spliced sequence; per node (canonical minimizer value)
/// we accumulate the DISTINCT gene set (=> `multiplicity`), the max within-transcript
/// run count (=> `cyclic`), the masked / total run occurrences (=> `softmask_frac`),
/// and the transcript count (=> `n_transcripts`). All accumulators are commutative,
/// so the catalog is independent of locus order.
#[derive(Default, Debug)]
pub struct NodeCatalog {
    /// node -> # distinct genes (multiplicity)
    mult: HashMap<u64, usize>,
    /// node -> max #runs within a single transcript (cyclic iff >= 2)
    cyc_max: HashMap<u64, usize>,
    /// node -> masked-run occurrences
    lc_occ: HashMap<u64, u64>,
    /// node -> total run occurrences
    tot_occ: HashMap<u64, u64>,
    /// node -> # transcripts carrying it
    n_tx: HashMap<u64, usize>,
}

impl NodeCatalog {
    /// Build the catalog from `(gene, case_carrying_sequence)` items -- one per
    /// gene-assigned family-universe locus. Loci with `seq.len() < k` are skipped
    /// (Python `if len(s) < K: continue`, redundant with `minimizers` but preserved).
    pub fn build<'a>(loci: impl IntoIterator<Item = (&'a str, &'a [u8])>) -> Self {
        let mut node_genes: HashMap<u64, HashSet<&'a str>> = HashMap::new();
        let mut cat = NodeCatalog::default();
        for (g, s) in loci {
            if s.len() < MINIMIZER_K {
                continue;
            }
            let runs = minimizers(s, MINIMIZER_K, MINIMIZER_W);
            // per-transcript run counts (for the cyclic flag) + the distinct-node set
            let mut loc_runcount: HashMap<u64, usize> = HashMap::new();
            let mut seen: HashSet<u64> = HashSet::new();
            for (val, mk) in &runs {
                node_genes.entry(*val).or_default().insert(g);
                seen.insert(*val);
                *loc_runcount.entry(*val).or_default() += 1;
                *cat.tot_occ.entry(*val).or_default() += 1;
                if *mk {
                    *cat.lc_occ.entry(*val).or_default() += 1;
                }
            }
            for val in &seen {
                *cat.n_tx.entry(*val).or_default() += 1;
                let rc = loc_runcount[val];
                let cm = cat.cyc_max.entry(*val).or_default();
                if rc > *cm {
                    *cm = rc;
                }
            }
        }
        // mult[c] = len(node_genes[c])
        cat.mult = node_genes.into_iter().map(|(c, gs)| (c, gs.len())).collect();
        cat
    }

    /// `multiplicity` of a node (# distinct genes), or 0 if absent. Gate input.
    pub fn multiplicity(&self, node_id: u64) -> usize {
        self.mult.get(&node_id).copied().unwrap_or(0)
    }

    /// Whether a node is a library-free REPEAT at `M_OP` (`multiplicity >= M_OP`
    /// OR cyclic). The gate CUTS a family edge iff every shared node is a repeat.
    pub fn is_repeat(&self, node_id: u64) -> bool {
        self.multiplicity(node_id) >= M_OP || self.cyclic(node_id)
    }

    /// Whether a node recurs (>= 2 runs) within a single transcript (tandem/cyclic).
    pub fn cyclic(&self, node_id: u64) -> bool {
        self.cyc_max.get(&node_id).copied().unwrap_or(0) >= 2
    }

    /// Total number of nodes in the catalog (all multiplicities).
    pub fn n_nodes(&self) -> usize {
        self.mult.len()
    }

    fn row(&self, c: u64) -> NodeRow {
        let m = self.mult[&c];
        let cyc = self.cyclic(c);
        NodeRow {
            node_id: c,
            multiplicity: m,
            n_genes: m,
            cyclic: cyc,
            is_repeat: m >= M_OP || cyc,
            n_transcripts: self.n_tx.get(&c).copied().unwrap_or(0),
            softmask_num: self.lc_occ.get(&c).copied().unwrap_or(0),
            softmask_den: self.tot_occ.get(&c).copied().unwrap_or(0),
        }
    }

    /// The "# SECTION nodes (mult>=2)" rows, sorted by `(-multiplicity, node_id)`
    /// (descending multiplicity, then ascending node id) exactly as the Python writer.
    pub fn node_rows(&self) -> Vec<NodeRow> {
        let mut codes: Vec<u64> = self
            .mult
            .iter()
            .filter(|(_, &m)| m >= 2)
            .map(|(&c, _)| c)
            .collect();
        codes.sort_by(|&a, &b| {
            let (ma, mb) = (self.mult[&a], self.mult[&b]);
            mb.cmp(&ma).then(a.cmp(&b))
        });
        codes.into_iter().map(|c| self.row(c)).collect()
    }

    /// The full "# SECTION nodes (mult>=2)" text (the two Python header lines + one
    /// line per `node_rows()` row, each terminated by `\n`) -- byte-identical to the
    /// section `bench/vg_repeat_catalog.py` writes at lines 599-604.
    pub fn node_section_text(&self) -> String {
        let mut out = String::new();
        out.push_str("# SECTION nodes (mult>=2)\n");
        out.push_str(&format!(
            "node_id\tmultiplicity\tn_genes\tcyclic\tis_repeat_m{}\tn_transcripts\tsoftmask_frac\n",
            M_OP
        ));
        for row in self.node_rows() {
            out.push_str(&row.to_tsv());
            out.push('\n');
        }
        out
    }
}

/// Runtime gate DRIVER: build the node catalog from the genome + loaders' outputs,
/// mirroring `bench/vg_repeat_catalog.py:243-289`. Iterates `sorted(gene_of_dn.keys())`,
/// projects each locus to `(chrom, exons)` via `dn_exons`, fetches the case-carrying
/// spliced sequence, and accumulates into a `NodeCatalog`. (Order-independent, so the
/// sort only mirrors Python; skipped loci: no gene, no exons, fetch failure, `len < k`.)
pub fn build_catalog_from_genome(
    fa: &IndexedFasta,
    meta: &HashMap<String, (String, i64, i64)>,
    skel: &HashMap<(String, i64, i64), String>,
    gene_of_dn: &HashMap<String, String>,
) -> NodeCatalog {
    let mut loci: Vec<&String> = gene_of_dn.keys().collect();
    loci.sort();
    let mut items: Vec<(String, Vec<u8>)> = Vec::new();
    for dn in loci {
        let g = match gene_of_dn.get(dn) {
            Some(g) if !g.is_empty() => g.clone(),
            _ => continue,
        };
        let (chrom, exons) = match dn_exons(dn, meta, skel) {
            Some(x) => x,
            None => continue,
        };
        let s = match locus_exon_sequence(fa, &chrom, &exons) {
            Some(s) => s,
            None => continue,
        };
        if s.len() < MINIMIZER_K {
            continue;
        }
        items.push((g, s));
    }
    NodeCatalog::build(items.iter().map(|(g, s)| (g.as_str(), s.as_slice())))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    // ------------------------------------------------------------ unit corners

    #[test]
    fn dn_exons_branches() {
        let mut meta: HashMap<String, (String, i64, i64)> = HashMap::new();
        let mut skel: HashMap<(String, i64, i64), String> = HashMap::new();
        meta.insert("m".into(), ("c".into(), 100, 300));

        // (1) meta miss -> None
        assert_eq!(dn_exons("absent", &meta, &skel), None);

        // (2) skel key absent -> single exon [(start,end)]
        assert_eq!(
            dn_exons("m", &meta, &skel),
            Some(("c".to_string(), vec![(100, 300)]))
        );

        // (3) blank introns -> single exon via the OTHER branch
        skel.insert(("c".into(), 100, 300), "".into());
        assert_eq!(
            dn_exons("m", &meta, &skel),
            Some(("c".to_string(), vec![(100, 300)]))
        );

        // (4) unsorted introns -> sorted complement
        skel.insert(("c".into(), 100, 300), "250-280;120-150".into());
        assert_eq!(
            dn_exons("m", &meta, &skel),
            Some(("c".to_string(), vec![(100, 120), (150, 250), (280, 300)]))
        );

        // (5) leading intron a == start (no leading exon)
        skel.insert(("c".into(), 100, 300), "100-150".into());
        assert_eq!(
            dn_exons("m", &meta, &skel),
            Some(("c".to_string(), vec![(150, 300)]))
        );

        // (6) whole span is intron -> empty exon list
        skel.insert(("c".into(), 100, 300), "100-300".into());
        assert_eq!(dn_exons("m", &meta, &skel), Some(("c".to_string(), vec![])));
    }

    #[test]
    fn softmask_formatting_tricky_cases() {
        // 1/160 = 0.00625: the DOUBLE is > the exact midpoint -> rounds UP (NOT
        // half-even on the rational) -> "0.0063".  Guards the format-the-f64 choice.
        assert_eq!(format_softmask(1, 160), "0.0063");
        assert_eq!(format_softmask(0, 5), "0.0");
        assert_eq!(format_softmask(5, 5), "1.0");
        assert_eq!(format_softmask(1, 2), "0.5");
        assert_eq!(format_softmask(1, 5), "0.2");
        assert_eq!(format_softmask(2, 3), "0.6667");
        assert_eq!(format_softmask(1, 3), "0.3333");
        assert_eq!(format_softmask(1, 1000), "0.001");
        assert_eq!(format_softmask(1, 10000), "0.0001");
        assert_eq!(format_softmask(1, 100000), "0.0"); // rounds below 4 decimals
        assert_eq!(format_softmask(0, 0), "0.0"); // den==0 default
    }

    #[test]
    fn catalog_accumulation_min_example() {
        // Two "genes" over tiny sequences: a shared homopolymer node (mult 2) and a
        // per-gene node. Homopolymer -> one collapsed run each -> cyclic=false.
        let a = vec![b'A'; 40];
        let b = vec![b'A'; 40];
        let cat = NodeCatalog::build(
            [("geneA", a.as_slice()), ("geneB", b.as_slice())].into_iter(),
        );
        // poly-A canon == 0; two distinct genes -> multiplicity 2
        assert_eq!(cat.multiplicity(0), 2);
        assert!(!cat.cyclic(0));
        assert_eq!(cat.node_rows().len(), 1);
        let r = &cat.node_rows()[0];
        assert_eq!(r.node_id, 0);
        assert_eq!(r.multiplicity, 2);
        assert_eq!(r.n_transcripts, 2);
    }

    // ------------------------------------------------------------ fixture parity

    fn load_fixture() -> serde_json::Value {
        let raw = include_str!("testdata/repeat_catalog_fixture.json");
        serde_json::from_str(raw).expect("parse repeat_catalog fixture json")
    }

    /// (a) `dn_exons` parity: reconstruct meta/skel from the fixture and assert every
    /// case's `(chrom, exons)` matches Python (multi-intron, single-exon, edge cases).
    #[test]
    fn dn_exons_parity() {
        let fx = load_fixture();
        assert_eq!(fx["K"].as_u64().unwrap() as usize, MINIMIZER_K, "K drift");
        assert_eq!(fx["M_OP"].as_u64().unwrap() as usize, M_OP, "M_OP drift");

        let cases = fx["dn_exons"].as_array().expect("dn_exons array");
        assert!(cases.len() >= 40, "need >= 40 dn_exons cases, got {}", cases.len());

        // Build meta + skel maps from the self-contained fixture rows.
        let mut meta: HashMap<String, (String, i64, i64)> = HashMap::new();
        let mut skel: HashMap<(String, i64, i64), String> = HashMap::new();
        for c in cases {
            let dn = c["dn"].as_str().unwrap();
            if let Some(m) = c["meta"].as_array() {
                let chrom = m[0].as_str().unwrap().to_string();
                let s = m[1].as_i64().unwrap();
                let e = m[2].as_i64().unwrap();
                meta.insert(dn.to_string(), (chrom.clone(), s, e));
                if let Some(intr) = c["introns"].as_str() {
                    skel.insert((chrom, s, e), intr.to_string());
                }
            }
        }

        let mut n_multi = 0usize;
        let mut n_single = 0usize;
        let mut n_none = 0usize;
        for c in cases {
            let dn = c["dn"].as_str().unwrap();
            let got = dn_exons(dn, &meta, &skel);
            if c["exons"].is_null() {
                assert_eq!(got, None, "case '{dn}': expected None (meta miss)");
                n_none += 1;
                continue;
            }
            let chrom = c["chrom"].as_str().unwrap().to_string();
            let exons: Vec<(i64, i64)> = c["exons"]
                .as_array()
                .unwrap()
                .iter()
                .map(|p| {
                    let a = p.as_array().unwrap();
                    (a[0].as_i64().unwrap(), a[1].as_i64().unwrap())
                })
                .collect();
            match exons.len() {
                0 | 1 => n_single += 1,
                _ => n_multi += 1,
            }
            assert_eq!(
                got,
                Some((chrom, exons)),
                "dn_exons MISMATCH case '{dn}'"
            );
        }
        assert!(n_multi > 0 && n_single > 0 && n_none > 0, "fixture must cover all branches");
        eprintln!(
            "dn_exons parity: {} cases OK (multi={n_multi} single={n_single} none={n_none})",
            cases.len()
        );
    }

    /// (b) per-locus NODE SET parity: `sorted(set(minimizers(exon_seq)))` on the
    /// shipped case-carrying exon bytes must equal Python -- proves dn_exons +
    /// extraction + minimizers compose (no genome needed; bytes are in the fixture).
    #[test]
    fn node_set_parity() {
        let fx = load_fixture();
        let loci = fx["loci"].as_array().expect("loci array");
        let mut n_checked = 0usize;
        for locus in loci {
            let node_set = match locus["node_set"].as_array() {
                Some(v) => v,
                None => continue, // only the part-(b) subset carries node_set
            };
            let dn = locus["dn"].as_str().unwrap();
            let seq = locus["seq"].as_str().unwrap().as_bytes();
            let golden: Vec<u64> = node_set.iter().map(|v| v.as_u64().unwrap()).collect();
            let got: BTreeSet<u64> = minimizers(seq, MINIMIZER_K, MINIMIZER_W)
                .into_iter()
                .map(|(v, _)| v)
                .collect();
            let got_sorted: Vec<u64> = got.into_iter().collect();
            assert_eq!(
                got_sorted, golden,
                "node-set MISMATCH locus '{dn}' ({} vs {} distinct nodes)",
                got_sorted.len(),
                golden.len()
            );
            n_checked += 1;
        }
        assert!(n_checked >= 30, "need >= 30 node-set cases, got {n_checked}");
        eprintln!("node-set parity: {n_checked} loci byte-identical to Python");
    }

    /// (c) node-section parity over a SELF-CONTAINED (closed-by-construction) universe:
    /// the fixture ships the exact set of loci as the universe and the exact Python
    /// "# SECTION nodes (mult>=2)" text produced FOR THAT UNIVERSE. Rust rebuilds the
    /// catalog from the same sequences and must reproduce the section byte-for-byte.
    #[test]
    fn node_section_parity() {
        let fx = load_fixture();
        let loci = fx["loci"].as_array().expect("loci array");
        // owned buffers so the (&str,&[u8]) borrows outlive the build call
        let owned: Vec<(String, Vec<u8>)> = loci
            .iter()
            .map(|l| {
                (
                    l["gene"].as_str().unwrap().to_string(),
                    l["seq"].as_str().unwrap().as_bytes().to_vec(),
                )
            })
            .collect();
        let cat = NodeCatalog::build(owned.iter().map(|(g, s)| (g.as_str(), s.as_slice())));
        let got = cat.node_section_text();
        let want = fx["node_section_text"].as_str().expect("node_section_text");

        if got != want {
            // report the FIRST differing line for a precise failure
            let (gl, wl): (Vec<&str>, Vec<&str>) = (got.lines().collect(), want.lines().collect());
            let mut first = None;
            for i in 0..gl.len().max(wl.len()) {
                let (a, b) = (gl.get(i), wl.get(i));
                if a != b {
                    first = Some((i, a.copied().unwrap_or("<none>"), b.copied().unwrap_or("<none>")));
                    break;
                }
            }
            let (i, a, b) = first.unwrap_or((0, "", ""));
            panic!(
                "node-section MISMATCH: {} rust lines vs {} python lines; first diff at line {i}:\n  rust  : {a}\n  python: {b}",
                gl.len(),
                wl.len()
            );
        }
        let n_rows = want.lines().count().saturating_sub(2); // minus 2 header lines
        eprintln!("node-section parity: {n_rows} rows byte-identical to Python (closed universe = fixture loci)");
    }

    /// Case-carrying FASTA reader sanity on a tiny synthetic multi-line FASTA + `.fai`
    /// (validates the fai offset math + soft-mask/lowercase preservation without the
    /// 3.4G genome). Also exercises clamping + empty-interval behaviour.
    #[test]
    fn indexed_fasta_case_carrying() {
        let dir = std::env::temp_dir();
        let base = dir.join(format!("rustle_faidx_{}.fa", std::process::id()));
        let fa_path = base.to_str().unwrap().to_string();
        // 26 bases across 3 lines of linebases=10 (linewidth=11 with '\n'); mixed case.
        let seq = "ACGTacgtNN"; // line 1 (10)
        let seq2 = "GGGGcccctt"; // line 2 (10)
        let seq3 = "AAAAaa"; //     line 3 (6)
        std::fs::write(&fa_path, format!(">c1\n{seq}\n{seq2}\n{seq3}\n")).unwrap();
        // .fai: name length offset linebases linewidth ; offset = len(">c1\n") = 4
        std::fs::write(format!("{fa_path}.fai"), "c1\t26\t4\t10\t11\n").unwrap();

        let fa = IndexedFasta::open(&fa_path).unwrap();
        let whole: Vec<u8> = format!("{seq}{seq2}{seq3}").into_bytes();
        // full sequence, verbatim case
        assert_eq!(fa.fetch("c1", 0, 26).unwrap(), whole);
        // an interior slice straddling two lines, preserving lowercase
        assert_eq!(fa.fetch("c1", 4, 14).unwrap(), b"acgtNNGGGG".to_vec());
        // clamped end
        assert_eq!(fa.fetch("c1", 20, 999).unwrap(), b"AAAAaa".to_vec());
        // empty / unknown
        assert_eq!(fa.fetch("c1", 5, 5).unwrap(), Vec::<u8>::new());
        assert_eq!(fa.fetch("nope", 0, 3), None);

        let _ = std::fs::remove_file(&fa_path);
        let _ = std::fs::remove_file(format!("{fa_path}.fai"));
    }

    /// If the real genome is present, prove the case-carrying reader matches pysam by
    /// re-fetching the fixture loci's exon sequences and comparing to the shipped
    /// pysam bytes. Skipped (passes) when the 3.4G genome is unavailable (e.g. CI).
    #[test]
    fn indexed_fasta_matches_pysam_on_real_genome() {
        let genome = "/home/juanfra/winloci_scratch/GGO.fasta";
        if !std::path::Path::new(&format!("{genome}.fai")).exists() {
            eprintln!("real genome absent -> skipping pysam cross-check");
            return;
        }
        let fx = load_fixture();
        let fa = match IndexedFasta::open(genome) {
            Ok(f) => f,
            Err(_) => return,
        };
        let mut n = 0usize;
        for locus in fx["loci"].as_array().unwrap() {
            let exons = match locus["exons"].as_array() {
                Some(e) => e,
                None => continue, // only present when the generator recorded coords
            };
            let chrom = locus["chrom"].as_str().unwrap();
            let want = locus["seq"].as_str().unwrap().as_bytes();
            let ex: Vec<(i64, i64)> = exons
                .iter()
                .map(|p| {
                    let a = p.as_array().unwrap();
                    (a[0].as_i64().unwrap(), a[1].as_i64().unwrap())
                })
                .collect();
            let got = locus_exon_sequence(&fa, chrom, &ex).unwrap();
            assert_eq!(got, want, "pysam vs IndexedFasta MISMATCH at {chrom}");
            n += 1;
        }
        eprintln!("IndexedFasta == pysam on {n} real loci (case-carrying)");
    }
}
