#!/usr/bin/env python3
"""Prereg Addendum P: P1 subfamilies as supported tree clades (MAFFT FFT-NS-2 -> gap-column trim -> IQ-TREE
ModelFinder + UFBoot + SH-aLRT) on Addendum O's exon-masked gene-body members; P2 hybrid width (transcript boundary
where a paralog has one, gene body otherwise) on Addendum O's G1 candidates.

usage: guided_tree_width.py <workdir> <refseq gff> <genes.gff.gz> <genome.fa> <iqtree3>
Reuses bench/guided_genebody.py's definitions (executed up to its G2 reference section) so members and candidates are
regenerated by the same code; member FASTAs are checked byte-for-byte against Addendum O's `g2/` files.
"""
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
IQTREE = sys.argv[5]
src = open(os.path.join(HERE, "guided_genebody.py")).read().split("# reference: all truth records of each family")[0]
sys_argv_saved = sys.argv
exec(compile(src, "guided_genebody.py(definitions)", "exec"))
sys.argv = sys_argv_saved

TD = f"{W}/tree"
os.makedirs(TD, exist_ok=True)
MODEL = ["-m", "MFP"]

# ---------------- literature groups ----------------
GROUPS = {
    "NPIP": {"L1 NPIPA|NPIPB": {t["name"] for t in truth if t["level1"] == "NPIPA"},
             "L2 A6-9": {t["name"] for t in truth if t["level2"] == "A6-9"},
             "L2 B3-5": {t["name"] for t in truth if t["level2"] == "B3-5"},
             "L2 B6-9": {t["name"] for t in truth if t["level2"] == "B6-9"},
             "L2 B12/13": {t["name"] for t in truth if t["level2"] == "B12/13"},
             "named B3,B4,B5,B11,B12,B13": {"NPIPB3", "NPIPB4", "NPIPB5", "NPIPB11", "NPIPB12", "NPIPB13"}},
    "TBC1D3": {"AE": {t["name"] for t in truth if t["level2"] == "AE"},
               "CDKL": {t["name"] for t in truth if t["level2"] == "CDKL"}},
}
POSITIONAL = {"TBC1D3": {t["name"] for t in truth if t["level1"] == "cluster1"}}
# Any other family: its level-1 and level-2 truth groups with >= 2 members (Addendum R).
for _fam in families:
    if _fam not in GROUPS:
        _g = {}
        for _lvl in ("level1", "level2"):
            for _v in sorted({t[_lvl] for t in truth if t["family"] == _fam}):
                _m = {t["name"] for t in truth if t["family"] == _fam and t[_lvl] == _v}
                if len(_m) >= 2 and f"L1 {_v}" not in _g:
                    _g[f"{'L1' if _lvl == 'level1' else 'L2'} {_v}"] = _m
        GROUPS[_fam] = _g


# ---------------- newick ----------------
def parse_newick(s):
    """Return (children, parent, length, label) dicts over integer node ids; leaves carry their name as label."""
    s = s.strip().rstrip(";")
    children, parent, length, label = {}, {}, {}, {}
    stack, cur, nid, i = [], None, 0, 0

    def new(p):
        nonlocal nid
        n = nid
        nid += 1
        children[n] = []
        parent[n] = p
        length[n] = 0.0
        label[n] = ""
        if p is not None:
            children[p].append(n)
        return n
    root = new(None)
    cur = root
    while i < len(s):
        c = s[i]
        if c == "(":
            child = new(cur)
            stack.append(cur)
            cur = child
            i += 1
        elif c == ",":
            p = stack[-1]
            cur = new(p)
            i += 1
        elif c == ")":
            cur = stack.pop()
            i += 1
        elif c == ":":
            j = i + 1
            while j < len(s) and s[j] not in ",()":
                j += 1
            length[cur] = float(s[i + 1:j])
            i = j
        else:
            j = i
            while j < len(s) and s[j] not in ",():":
                j += 1
            label[cur] = s[i:j]
            i = j
    return root, children, parent, length, label


def leaves_under(n, children, label, memo):
    if n in memo:
        return memo[n]
    out = {label[n]} if not children[n] else set().union(*(leaves_under(c, children, label, memo) for c in children[n]))
    memo[n] = out
    return out


def splits(tree):
    root, children, parent, length, label = tree
    memo = {}
    allleaves = leaves_under(root, children, label, memo)
    out = []
    for n in children:
        if not children[n] or parent[n] is None:
            continue
        sup = label[n].split("/")
        sh = float(sup[0]) if sup and sup[0] not in ("",) else float("nan")
        ufb = float(sup[1]) if len(sup) > 1 else float("nan")
        side = leaves_under(n, children, label, memo)
        if 1 < len(side) < len(allleaves) - 1:
            out.append((frozenset(side), sh, ufb))
    return out, allleaves


def midpoint_partition(tree):
    root, children, parent, length, label = tree
    adj = collections.defaultdict(list)
    for n, p in parent.items():
        if p is not None:
            adj[n].append((p, length[n]))
            adj[p].append((n, length[n]))
    leaves = [n for n in children if not children[n]]

    def farthest(src):
        dist, prev, stack = {src: 0.0}, {src: None}, [src]
        while stack:
            u = stack.pop()
            for v, w in adj[u]:
                if v not in dist:
                    dist[v], prev[v] = dist[u] + w, u
                    stack.append(v)
        far = max(leaves, key=lambda x: dist[x])
        return far, dist, prev
    a, _, _ = farthest(leaves[0])
    b, dist, prev = farthest(a)
    half = dist[b] / 2
    node = b
    while prev[node] is not None and dist[prev[node]] >= half:
        node = prev[node]
    u, v = node, prev[node]  # midpoint lies on edge (u, v) with dist[u] >= half > dist[v]
    # side containing u when edge (u, v) is cut
    seen, stack = {u}, [u]
    while stack:
        x = stack.pop()
        for y, _ in adj[x]:
            if y not in seen and not (x == u and y == v):
                seen.add(y)
                stack.append(y)
    side = {label[n] for n in seen if not children[n]}
    allleaves = {label[n] for n in leaves}
    return side, allleaves - side


def build_tree(tag, fasta):
    aln, trim = f"{TD}/{tag}.aln.fa", f"{TD}/{tag}.trim.fa"
    with open(aln, "w") as fh:
        subprocess.run(["mafft", "--retree", "2", "--thread", "4", fasta], stdout=fh, stderr=subprocess.DEVNULL, check=True)
    names, seqs, cur = [], [], None
    for line in open(aln):
        if line.startswith(">"):
            names.append(line[1:].strip())
            seqs.append([])
        else:
            seqs[-1].append(line.strip())
    seqs = ["".join(s).upper() for s in seqs]
    L = len(seqs[0])
    keep = [j for j in range(L) if sum(1 for s in seqs if s[j] == "-") <= 0.5 * len(seqs)]
    with open(trim, "w") as fh:
        for n, s in zip(names, seqs):
            fh.write(f">{n}\n{''.join(s[j] for j in keep)}\n")
    t0 = time.time()
    subprocess.run([IQTREE, "-s", trim, *MODEL, "-B", "1000", "-alrt", "1000", "-T", "4", "--seed", "1", "--prefix",
                    f"{TD}/{tag}", "-redo", "-quiet"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                   timeout=600)
    model = next((l.split(":", 1)[1].strip() for l in open(f"{TD}/{tag}.iqtree") if l.startswith("Best-fit model")),
                 MODEL[-1])
    return parse_newick(open(f"{TD}/{tag}.treefile").read()), L, len(keep), time.time() - t0, model


def tree_scores(tree, fam, label_of):
    sp, allleaves = splits(tree)
    truth_leaves = {m for m in allleaves if label_of.get(m)}
    res = {}
    for gname, G in GROUPS[fam].items():
        present = {label_of[m] for m in truth_leaves} & G
        if len(present) < 2:
            res[gname] = ("absent", None, None)
            continue
        best = None
        for side, sh, ufb in sp:
            ts = {label_of[m] for m in side if m in truth_leaves}
            tc = {label_of[m] for m in (allleaves - side) if m in truth_leaves}
            if ts == present or tc == present:
                best = (sh, ufb)
        if best is None:
            res[gname] = ("no split", None, None)
        else:
            res[gname] = ("RECOVERED" if best[0] > 75 else "unsupported", best[0], best[1])
    positional = None
    if fam in POSITIONAL:
        P = POSITIONAL[fam]
        positional = False
        for side, sh, ufb in sp:
            ts = {label_of[m] for m in side if m in truth_leaves}
            tc = {label_of[m] for m in (allleaves - side) if m in truth_leaves}
            present = {label_of[m] for m in truth_leaves}
            if sh > 75 and ((ts == P & present) or (tc == P & present)) and ts and tc:
                positional = True
    a, b = midpoint_partition(tree)
    lab = {m: 0 for m in a} | {m: 1 for m in b}
    items = [(m, label_of[m]) for m in allleaves if label_of.get(m)]
    pred = [lab[m] for m, _ in items]
    true = [rec[r]["level1"] for _, r in items]
    ps, pp = pairwise(pred, true)
    br, bp, ex, nt = bipartite(pred, true)
    mid = ([sorted(label_of.get(m, m) for m in a), sorted(label_of.get(m, m) for m in b)])
    return res, positional, (ps, pp, br, bp, ex, nt), mid


# ---------------- P1: reference + leave-out ----------------
runs = []  # (tag, family, label_of, fasta)
for fam in families:
    fa = f"{W}/g2/ref_{fam}.fa"
    seqs = {t["name"]: seq_minus(t["chrom"], t["start0"], t["end"], union_exons[t["name"]], t["strand"])
            for t in truth if t["family"] == fam}
    runs.append((f"ref_{fam}", fam, {k: k for k in seqs}, seqs))

width_rows = []
for level in ("half", "keep1"):
    for rep in range(REPS):
        seeds, hidden = set(), set()
        for fi, fam in enumerate(families):
            names = sorted(t["name"] for t in truth if t["family"] == fam)
            random.Random(1000 * rep + fi).shuffle(names)
            k = math.ceil(len(names) / 2) if level == "half" else 1
            seeds.update(names[:k])
            hidden.update(names[k:])
        m0 = candidates(M0_hits, seeds, "nm", lambda b: (b["s"], b["e"]))
        rp0 = classify(m0, hidden)
        g1 = candidates(G1_hits, seeds, "nm", lambda b: (b["xs"], b["xe"]))
        rp = classify(g1, hidden)
        # P2 widths
        for c in g1:
            th = [h for h in M0_hits if h["q"] in seeds and rec[h["q"]]["family"] == c["family"] and h["chrom"] == c["chrom"]
                  and ov(h["s"], h["e"], *c["clip"]) > 0
                  and not any(rec[s]["chrom"] == h["chrom"] and ov(rec[s]["start0"], rec[s]["end"], h["s"], h["e"]) > 0 for s in seeds)]
            if th:
                b = max(th, key=lambda h: (h["nm"], -h["s"]))
                c["H"], c["Hu"], c["tx"] = (b["s"], b["e"]), (min(h["s"] for h in th), max(h["e"] for h in th)), True
            else:
                c["H"] = c["Hu"] = c["clip"]
                c["tx"] = False
        for fam in families + ["ALL"]:
            H_ = [n for n in hidden if fam in ("ALL", rec[n]["family"])]
            C_ = [c for c in g1 if fam in ("ALL", c["family"])]
            for wname, getspan, rpx in (("M0", lambda c: (c["s"], c["e"]), rp0), ("G1-clip", lambda c: c["clip"], rp),
                                        ("H", lambda c: c["H"], rp), ("H-union", lambda c: c["Hu"], rp)):
                for scope in ("all", "like-for-like"):
                    wd = []
                    for n in H_:
                        c = rpx[n]
                        if not c or c["family"] != rec[n]["family"]:
                            continue
                        if scope == "like-for-like" and not (rp0[n] and rp0[n]["family"] == rec[n]["family"]):
                            continue
                        wd.append(width_stats(rec[n], *getspan(c)))
                    width_rows.append({"level": level, "rep": rep, "family": fam, "arm": wname, "scope": scope, "n": len(wd),
                                       "tx_frac": (sum(c["tx"] for c in C_) / len(C_) if C_ and wname.startswith("H") else float("nan")),
                                       "jaccard": statistics.median([w[0] for w in wd]) if wd else float("nan"),
                                       "off5": statistics.median([w[1] for w in wd]) if wd else float("nan"),
                                       "off3": statistics.median([w[2] for w in wd]) if wd else float("nan"),
                                       "truncated": sum(w[3] for w in wd), "overextended": sum(w[4] for w in wd)})
        for fam in families:
            members, label_of = {}, {}
            for s in sorted(seeds):
                if rec[s]["family"] == fam:
                    t = rec[s]
                    members[s] = seq_minus(t["chrom"], t["start0"], t["end"], union_exons[s], t["strand"])
                    label_of[s] = s
            for i, c in enumerate(g1):
                if c["family"] != fam:
                    continue
                members[f"cand{i}"] = seq_minus(c["chrom"], c["s"], c["e"], project_exons(c["best"]), c["best"]["strand"])
                if c["class"] == "hidden" and rec[c["match"]]["family"] == fam:
                    label_of[f"cand{i}"] = c["match"]
            runs.append((f"{level}_{rep}_{fam}", fam, label_of, members))

mismatch = 0
for tag, fam, label_of, members in runs:
    fa = f"{TD}/{tag}.fa"
    with open(fa, "w") as fh:
        for k, s in members.items():
            fh.write(f">{k}\n{s}\n")
    ofa = f"{W}/g2/{tag}.fa"
    if os.path.exists(ofa) and open(ofa).read() != open(fa).read():
        # O wrote members in dict insertion order; compare as sets of records
        def recs(p):
            out, cur = {}, None
            for line in open(p):
                if line.startswith(">"):
                    cur = line[1:].strip()
                else:
                    out[cur] = line.strip()
            return out
        if recs(ofa) != recs(fa):
            mismatch += 1
print(f"# member FASTAs differing from Addendum O's g2/ files: {mismatch} of {len(runs)}")

def all_trees():
    out = []
    for tag, fam, label_of, members in runs:
        if len(members) < 4:
            out.append((tag, fam, None))
            continue
        tree, L, kept, secs, model = build_tree(tag, f"{TD}/{tag}.fa")
        out.append((tag, fam, (tree_scores(tree, fam, label_of), L, kept, secs, model, len(members),
                               sum(1 for m in members if label_of.get(m)))))
        print(f"[tree] {tag}: {len(members)} leaves, alignment {L} -> {kept} columns, model {model}, {secs:.0f} s",
              file=sys.stderr, flush=True)
    return out


try:
    results = all_trees()
except subprocess.TimeoutExpired:
    print("# an IQ-TREE run exceeded 10 min with ModelFinder -> GTR+F+R4 fixed for ALL runs, all trees rebuilt (disclosed)")
    MODEL[:] = ["-m", "GTR+F+R4"]
    results = all_trees()


def ms(v):
    v = [x for x in v if not (isinstance(x, float) and math.isnan(x))]
    return "nan" if not v else (f"{statistics.mean(v):.3f}±{statistics.stdev(v):.3f}" if len(v) > 1 else f"{v[0]:.3f}")


print("\n## P1 — supported clades (SH-aLRT > 75; UFBoot shown)")
summary = collections.defaultdict(lambda: collections.Counter())
for tag, fam, r in results:
    if r is None:
        print(f"{tag}: too few members")
        continue
    (res, positional, part, mid), L, kept, secs, model, nleaves, ntruth = r
    ps, pp, br, bp, ex, nt = part
    groups = "; ".join(f"{g}: {v[0]}" + (f" (SH {v[1]:.1f}/UFB {v[2]:.0f})" if v[1] is not None else "") for g, v in res.items())
    extra = "" if positional is None else f" | positional cluster1|cluster2 supported: {positional} -> {'WRONG' if positional else 'CORRECT'}"
    print(f"{tag}: {nleaves} leaves ({ntruth} truth), {kept}/{L} columns, {model} | {groups}{extra}")
    print(f"      midpoint-root L1 partition: pairwise sens {ps:.3f} prec {pp:.3f} | bipartite R {br:.3f} P {bp:.3f} exact {ex}/{nt}")
    print(f"      root sides: {' '.join(mid[0])}  ||  {' '.join(mid[1])}")
    kind = "reference" if tag.startswith("ref") else "leave-out"
    for g, v in res.items():
        summary[(fam, kind, g)][v[0]] += 1
    if positional is not None:
        summary[(fam, kind, "positional split")]["WRONG" if positional else "CORRECT"] += 1
print("\n## P1 summary (counts over runs)")
for k in sorted(summary):
    print(f"{k[0]:6s} {k[1]:9s} {k[2]:28s} {dict(summary[k])}")

print("\n## P2 — width (median over replicates' medians; counts mean±SD)")
for level in ("half", "keep1"):
    for fam in families + ["ALL"]:
        for scope in ("all", "like-for-like"):
            for arm in ("M0", "G1-clip", "H", "H-union"):
                R = [r for r in width_rows if r["level"] == level and r["family"] == fam and r["arm"] == arm and r["scope"] == scope]
                g = lambda k: ms([r[k] for r in R])
                print(f"{level:5s} {fam:6s} {scope:13s} {arm:8s} n {g('n')} tx-boundary {g('tx_frac')} | J {g('jaccard')} "
                      f"5' {g('off5')} 3' {g('off3')} trunc {g('truncated')} overext {g('overextended')}")
