//! Synthetic ground-truth fixture test for VG-HMM novel-copy rescue.
//!
//! ## Fixture layout
//!
//!   test_data/vg_hmm/synthetic_family.fa   — two "gene copies":
//!       copy0        — 3000-bp deterministic reference
//!       copy1_novel  — copy0 + 50-bp copy-specific exon at pos 1000, 5% base perturbation
//!
//!   test_data/vg_hmm/synthetic_reads.bam   — 50 unmapped reads from copy1_novel,
//!       1% per-base noise, 1000-bp each.  Generated by tools/make_vg_hmm_fixture.py.
//!
//! ## What this test validates
//!
//! The synthetic BAM has only unmapped reads (no mapped alignments), so rustle
//! will find 0 bundles from the mapping pass and therefore 0 family groups.
//! Consequently HMM rescue does not fire.  The test goal is:
//!   (a) rustle exits 0 — no crash, no panic, plumbing works end-to-end.
//!   (b) a GTF output file is produced (may be empty or have 0 transcripts).
//!
//! Real ground-truth rescue testing (rescue_class attribute present in GTF,
//! ≥80% read rescue rate) requires a BAM that contains *mapped* reads to
//! seed family discovery — that is covered by Task 7.4 (full GGO.bam benchmark).
//!
//! ## Regenerating fixtures
//!
//!   python3 tools/make_vg_hmm_fixture.py

use std::process::Command;

const FIXTURE_FA: &str = "test_data/vg_hmm/synthetic_family.fa";
const FIXTURE_BAM: &str = "test_data/vg_hmm/synthetic_reads.bam";

#[test]
fn synthetic_fixture_runs_without_crash() {
    // Fixtures are committed; they should always be present.  If somehow
    // missing (e.g. a fresh checkout that skipped LFS / large-file storage),
    // skip gracefully.
    if !std::path::Path::new(FIXTURE_FA).exists() {
        eprintln!(
            "skipping: fixture {} missing — run `python3 tools/make_vg_hmm_fixture.py`",
            FIXTURE_FA
        );
        return;
    }
    if !std::path::Path::new(FIXTURE_BAM).exists() {
        eprintln!(
            "skipping: fixture {} missing — run `python3 tools/make_vg_hmm_fixture.py`",
            FIXTURE_BAM
        );
        return;
    }

    let out_gtf = std::env::temp_dir().join("rustle_synthetic_gt.gtf");

    let status = Command::new(env!("CARGO_BIN_EXE_rustle"))
        .args([
            "-L",
            "--vg",
            "--vg-discover-novel",
            "--vg-discover-novel-mode",
            "hmm",
            "--genome-fasta",
            FIXTURE_FA,
            "-o",
            out_gtf.to_str().unwrap(),
            FIXTURE_BAM,
        ])
        .status()
        .expect("rustle failed to spawn");

    assert!(
        status.success(),
        "rustle exited non-zero ({:?}) on synthetic fixture",
        status
    );

    // GTF file must be created (may be empty — 0 bundles from 0 mapped reads).
    assert!(
        out_gtf.exists(),
        "rustle did not produce output GTF at {:?}",
        out_gtf
    );
}

#[test]
fn synthetic_fixture_files_are_present_and_non_empty() {
    // Confirm the committed fixtures are both present and non-trivially sized.
    for path in &[FIXTURE_FA, FIXTURE_BAM] {
        if !std::path::Path::new(path).exists() {
            eprintln!("skipping: fixture {} missing", path);
            return;
        }
    }

    let fa_meta = std::fs::metadata(FIXTURE_FA).expect("stat FASTA");
    assert!(
        fa_meta.len() > 100,
        "synthetic FASTA too small: {} bytes",
        fa_meta.len()
    );

    let bam_meta = std::fs::metadata(FIXTURE_BAM).expect("stat BAM");
    assert!(
        bam_meta.len() > 100,
        "synthetic BAM too small: {} bytes",
        bam_meta.len()
    );
}
